CREATE TABLE [dbo].[ADT_EVENTS] (
    [ACCOMMODATION_CODE]                NVARCHAR (400)  NULL,
    [ACCOM_REASON_CODE]                 INT             NULL,
    [ACTION_SOURCE_CODE]                INT             NULL,
    [ADM_EVENT_ID]                      DECIMAL (18, 4) NULL,
    [ALT_EVENT_TYPE_CODE]               INT             NULL,
    [BASE_PAT_CLASS_CODE]               INT             NULL,
    [BED_ID]                            NVARCHAR (400)  NULL,
    [BED_STATUS_CODE]                   INT             NULL,
    [BED_STAY_ID]                       DECIMAL (18, 4) NULL,
    [CANCEL_REASON_CODE]                NVARCHAR (400)  NULL,
    [CANC_EVENT_ID]                     DECIMAL (18, 4) NULL,
    [CM_LOG_OWNER_ID]                   NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]                   NVARCHAR (400)  NULL,
    [COMMENTS]                          NVARCHAR (400)  NULL,
    [CONVERTED_TO_EVENT_ID]             DECIMAL (18, 4) NULL,
    [DELETE_TIME]                       DATETIME2 (7)   NULL,
    [DEPARTMENT_ID]                     DECIMAL (18, 4) NULL,
    [DIS_EVENT_ID]                      DECIMAL (18, 4) NULL,
    [EFFECTIVE_TIME]                    DATETIME2 (7)   NULL,
    [EFFECTIVE_UTC_DTTM]                DATETIME2 (7)   NULL,
    [ENCOUNTER_ID]                      DECIMAL (18, 4) NULL,
    [ENC_SERIES_FINANCIAL_CLASS_CODE]   NVARCHAR (400)  NULL,
    [ENC_SERIES_FROM_FIN_CLASS_CODE]    NVARCHAR (400)  NULL,
    [ENC_SERIES_FROM_PAYER_ID]          DECIMAL (18, 4) NULL,
    [ENC_SERIES_FROM_PLAN_ID]           DECIMAL (18, 4) NULL,
    [ENC_SERIES_HOSP_ACCOUNT_ID]        DECIMAL (18, 4) NULL,
    [ENC_SERIES_IN_FIN_CL_EV_TYP_CODE]  INT             NULL,
    [ENC_SERIES_IN_PAYER_EV_TYP_CODE]   INT             NULL,
    [ENC_SERIES_IN_PLAN_EV_TYP_CODE]    INT             NULL,
    [ENC_SERIES_OUT_FIN_CL_EV_TYP_CODE] INT             NULL,
    [ENC_SERIES_OUT_PAYER_EV_TYP_CODE]  INT             NULL,
    [ENC_SERIES_OUT_PLAN_EV_TYP_CODE]   INT             NULL,
    [ENC_SERIES_PRIMARY_PAYER_ID]       DECIMAL (18, 4) NULL,
    [ENC_SERIES_PRIMARY_PLAN_ID]        DECIMAL (18, 4) NULL,
    [ENC_SERIES_TO_FIN_CLASS_CODE]      NVARCHAR (400)  NULL,
    [ENC_SERIES_TO_PAYER_ID]            DECIMAL (18, 4) NULL,
    [ENC_SERIES_TO_PLAN_ID]             DECIMAL (18, 4) NULL,
    [EVENT_CONVERTED_FLAG_CODE]         INT             NULL,
    [EVENT_ID]                          DECIMAL (18, 4) NULL,
    [EVENT_SUBTYPE_CODE]                INT             NULL,
    [EVENT_TIME]                        DATETIME2 (7)   NULL,
    [EVENT_TYPE_CODE]                   INT             NULL,
    [EVNT_REVIEW_CODE]                  INT             NULL,
    [EVT_CANCEL_USER_ID]                NVARCHAR (400)  NULL,
    [FIRST_IP_IN_IP_FLAG]               NVARCHAR (400)  NULL,
    [FROM_BASE_CLASS_CODE]              INT             NULL,
    [IN_EVENT_TYPE_CODE]                INT             NULL,
    [IS_LOA_UPDATE_FLAG]                NVARCHAR (400)  NULL,
    [LABOR_STATUS_CODE]                 INT             NULL,
    [LAST_IN_EVENT_ID]                  DECIMAL (18, 4) NULL,
    [LOA_REASON_CODE]                   INT             NULL,
    [NEXT_OUT_EVENT_ID]                 DECIMAL (18, 4) NULL,
    [OFF_LEVEL_CARE_FLAG]               NVARCHAR (400)  NULL,
    [OFF_SERVICE_FLAG]                  NVARCHAR (400)  NULL,
    [ORDER_ID]                          DECIMAL (18, 4) NULL,
    [ORIGINAL_EVENT_ID]                 DECIMAL (18, 4) NULL,
    [ORIG_EFF_TIME]                     DATETIME2 (7)   NULL,
    [ORIG_EVENT_TIME]                   DATETIME2 (7)   NULL,
    [OUT_EVENT_TYPE_CODE]               INT             NULL,
    [PATIENT_CLASS_CODE]                NVARCHAR (400)  NULL,
    [PATIENT_ENC_DATE_REAL]             FLOAT (53)      NULL,
    [PATIENT_ID]                        NVARCHAR (400)  NULL,
    [PATIENT_LVL_OF_CARE_CODE]          NVARCHAR (400)  NULL,
    [PATIENT_SERVICE_CODE]              NVARCHAR (400)  NULL,
    [PREV_EVENT_ID]                     DECIMAL (18, 4) NULL,
    [PREV_UPD_EFF_TIME]                 DATETIME2 (7)   NULL,
    [PREV_UPD_EVNT_TIME]                DATETIME2 (7)   NULL,
    [REASON_CODE]                       NVARCHAR (400)  NULL,
    [REVIEW_DTTM]                       DATETIME2 (7)   NULL,
    [REVIEW_USER_ID]                    NVARCHAR (400)  NULL,
    [ROOM_ENC_ID]                       DECIMAL (18, 4) NULL,
    [ROOM_ID]                           NVARCHAR (400)  NULL,
    [SEQ_NUM_IN_BED_MIN]                DECIMAL (18, 4) NULL,
    [SEQ_NUM_IN_ENC]                    DECIMAL (18, 4) NULL,
    [SOURCE_LOC_EVNT_ID]                DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_FINANCIAL_CLASS_CODE]   NVARCHAR (400)  NULL,
    [SPLIT_ACCT_FROM_FIN_CLASS_CODE]    NVARCHAR (400)  NULL,
    [SPLIT_ACCT_FROM_PAYER_ID]          DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_FROM_PLAN_ID]           DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_HOSP_ACCOUNT_ID]        DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_IN_FIN_CL_EV_TYP_CODE]  INT             NULL,
    [SPLIT_ACCT_IN_PAYER_EV_TYP_CODE]   INT             NULL,
    [SPLIT_ACCT_IN_PLAN_EV_TYP_CODE]    INT             NULL,
    [SPLIT_ACCT_OUT_FIN_CL_EV_TYP_CODE] INT             NULL,
    [SPLIT_ACCT_OUT_PAYER_EV_TYP_CODE]  INT             NULL,
    [SPLIT_ACCT_OUT_PLAN_EV_TYP_CODE]   INT             NULL,
    [SPLIT_ACCT_PRIMARY_PAYER_ID]       DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_PRIMARY_PLAN_ID]        DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_TO_FIN_CLASS_CODE]      NVARCHAR (400)  NULL,
    [SPLIT_ACCT_TO_PAYER_ID]            DECIMAL (18, 4) NULL,
    [SPLIT_ACCT_TO_PLAN_ID]             DECIMAL (18, 4) NULL,
    [STATUS_OF_BED_CODE]                NVARCHAR (400)  NULL,
    [SWAP_EVENT_ID]                     DECIMAL (18, 4) NULL,
    [TO_BASE_CLASS_CODE]                INT             NULL,
    [USER_ID]                           NVARCHAR (400)  NULL,
    [XFER_EVENT_ID]                     DECIMAL (18, 4) NULL,
    [XFER_IN_EVENT_ID]                  DECIMAL (18, 4) NULL,
    [_SURROGATEKEY]                     BIGINT          NULL
);


GO

