CREATE TABLE [dbo].[ALERT_HISTORY] (
    [ALERT_ALLERGEN_ID]      DECIMAL (18, 4) NULL,
    [ALERT_ALLERGY_ID]       DECIMAL (18, 4) NULL,
    [ALERT_MED_CLASS_ID]     DECIMAL (18, 4) NULL,
    [ALERT_ROOT_ALLER_ID]    DECIMAL (18, 4) NULL,
    [ALERT_TYPE_OVTIME_CODE] INT             NULL,
    [ALLERGY_LEVEL_CODE]     INT             NULL,
    [ALLERGY_REPLACE_ID]     DECIMAL (18, 4) NULL,
    [ALT_ACTION_INST]        DATETIME2 (7)   NULL,
    [ALT_DATE_REAL]          FLOAT (53)      NULL,
    [ALT_ENCOUNTER_ID]       DECIMAL (18, 4) NULL,
    [ALT_GROUP_INFO]         NVARCHAR (400)  NULL,
    [ALT_ID]                 DECIMAL (18, 4) NULL,
    [ALT_STATUS_CODE]        INT             NULL,
    [BARCODE_ERX_ID]         DECIMAL (18, 4) NULL,
    [BARCODE_ORD_ID]         DECIMAL (18, 4) NULL,
    [BPA_ACK_APP_OPT_CODE]   INT             NULL,
    [BPA_ACK_LOCKOUT_TM]     INT             NULL,
    [BPA_ACK_SDE_CTXT_ID]    DECIMAL (18, 4) NULL,
    [BPA_ACK_SDE_ID]         DECIMAL (18, 4) NULL,
    [BPA_ACK_SDE_VALUE]      NVARCHAR (400)  NULL,
    [BPA_FUP_ASYNC_FRQ_CODE] INT             NULL,
    [BPA_FUP_IB_FREQ_CODE]   INT             NULL,
    [BPA_TRGR_ACTION_CODE]   INT             NULL,
    [BSA_CALC_DETAIL]        NVARCHAR (400)  NULL,
    [BSA_SOURCE_CODE]        INT             NULL,
    [CM_CT_OWNER_ID]         NVARCHAR (400)  NULL,
    [CONTACT_DATE]           DATETIME2 (7)   NULL,
    [CONTACT_NUM]            INT             NULL,
    [DEFAULT_GEST_AGE]       INT             NULL,
    [DM_ALERT_SIGN_CODE]     INT             NULL,
    [DOSING_BSA]             DECIMAL (18, 4) NULL,
    [DOSING_HEIGHT]          DECIMAL (18, 4) NULL,
    [DOSING_WEIGHT]          DECIMAL (18, 4) NULL,
    [DRUG_ALLERGY_GRP_CODE]  INT             NULL,
    [DRUG_DIS_SEV_NDDF_CODE] INT             NULL,
    [DRUG_INT_BASICLVL_CODE] INT             NULL,
    [DRUG_INT_BASIC_ID]      DECIMAL (18, 4) NULL,
    [DRUG_INT_FDDB_SVR_CODE] INT             NULL,
    [DRUG_INT_GS_PRES_FLAG]  NVARCHAR (400)  NULL,
    [DRUG_INT_GS_RXTX_FLAG]  NVARCHAR (400)  NULL,
    [DRUG_INT_GS_RX_FLAG]    NVARCHAR (400)  NULL,
    [DRUG_INT_GS_SVR_CODE]   INT             NULL,
    [DRUG_INT_GS_WFG_FLAG]   NVARCHAR (400)  NULL,
    [DRUG_INT_NDDF_SVR_CODE] NVARCHAR (400)  NULL,
    [DRUG_INT_SVRTY_CODE]    INT             NULL,
    [DUP_ALERT_ALLOW]        INT             NULL,
    [DUP_ALERT_CLS_CODE]     INT             NULL,
    [DUP_ALERT_SIGN_CODE]    INT             NULL,
    [GERI_ALRT_SEV_LVL_CODE] INT             NULL,
    [HT_RECORD_DATETIME]     DATETIME2 (7)   NULL,
    [HT_SOURCE_CODE]         INT             NULL,
    [IMMUNIZATION_LPL_ID]    DECIMAL (18, 4) NULL,
    [IMPORTANCE_LVL_CODE]    NVARCHAR (400)  NULL,
    [INACT_INGRED_IND_FLAG]  NVARCHAR (400)  NULL,
    [INACT_REVIEW_FLAG]      NVARCHAR (400)  NULL,
    [INT_DTMS_FDDB_ID]       DECIMAL (18, 4) NULL,
    [INT_MANAGE_CODE_CODE]   INT             NULL,
    [IS_NONFILTERED_FLAG]    NVARCHAR (400)  NULL,
    [IVCHEK_CSRATING_CODE]   INT             NULL,
    [IVCHEK_ENC]             DECIMAL (18, 4) NULL,
    [IVCHEK_SOLUTION_NUM]    INT             NULL,
    [IV_TEST_RESULT_CODE]    INT             NULL,
    [LACT_ALRT_SEV_LVL_CODE] INT             NULL,
    [LA_AAP_CODE]            INT             NULL,
    [LA_CODE_CODE]           INT             NULL,
    [LA_RATING_CODE]         INT             NULL,
    [NDC_ENC_ID]             NVARCHAR (400)  NULL,
    [ORDER_CONTEXT_CODE]     INT             NULL,
    [OVERALL_OVR_CMNT]       NVARCHAR (400)  NULL,
    [OVERALL_OVR_RSN_CODE]   INT             NULL,
    [OVERRIDDEN_INT_ID]      DECIMAL (18, 4) NULL,
    [PATIENT_DEP_ID]         DECIMAL (18, 4) NULL,
    [PA_BRIGGS_CODE]         INT             NULL,
    [PA_FDA_CODE]            INT             NULL,
    [PA_PTCODE_CODE]         INT             NULL,
    [PEDI_ALRT_SEV_LVL_CODE] INT             NULL,
    [PRC_MANAGE_LEVEL_CODE]  INT             NULL,
    [PREG_ALRT_SIG_LVL_CODE] INT             NULL,
    [PROVIDER_TYPE_CODE]     NVARCHAR (400)  NULL,
    [SCANNED_BARCODE]        NVARCHAR (400)  NULL,
    [SHOWN_PLACE_CODE]       INT             NULL,
    [SIGN_OFF_COMMENT]       NVARCHAR (400)  NULL,
    [SIGN_OFF_DATETIME]      DATETIME2 (7)   NULL,
    [SIGN_OFF_EMP_ID]        NVARCHAR (400)  NULL,
    [SPECIFIC_DEFR_RSN_CODE] INT             NULL,
    [SPEC_OVR_CMNT]          NVARCHAR (400)  NULL,
    [SPEC_OVR_RSN_CODE]      INT             NULL,
    [SYS_INTSET_ENC]         DECIMAL (18, 4) NULL,
    [TPN_COMPONENT_CODE]     INT             NULL,
    [TPN_COMPONENT_VAL]      DECIMAL (18, 4) NULL,
    [TPN_COMP_UNIT_CODE]     INT             NULL,
    [TPN_RANGE_MAX]          DECIMAL (18, 4) NULL,
    [TPN_RANGE_MIN]          DECIMAL (18, 4) NULL,
    [USER_ID]                NVARCHAR (400)  NULL,
    [USER_INTSET_ENC]        DECIMAL (18, 4) NULL,
    [VISIT_ID]               DECIMAL (18, 4) NULL,
    [WAS_SHOWN_CODE]         INT             NULL,
    [WT_COMMENTS]            NVARCHAR (400)  NULL,
    [WT_RECORD_DATETIME]     DATETIME2 (7)   NULL,
    [WT_SOURCE_CODE]         INT             NULL,
    [_SURROGATEKEY]          BIGINT          NULL
);


GO

