CREATE TABLE [dbo].[CALENDAR_DATES] (
    [BUS_DAY_CT]               INT             NULL,
    [CALENDAR_DT]              DATETIME2 (7)   NULL,
    [CALENDAR_DT_STR]          NVARCHAR (400)  NULL,
    [DAY_OF_MONTH]             INT             NULL,
    [DAY_OF_THE_WEEK_CODE]     INT             NULL,
    [DAY_OF_WEEK]              NVARCHAR (400)  NULL,
    [DAY_OF_WEEK_INDEX]        INT             NULL,
    [DAY_OF_YEAR]              INT             NULL,
    [HOLIDAY_FLAG]             NVARCHAR (400)  NULL,
    [INSTANT_AT_MIDNIGHT]      DECIMAL (18, 4) NULL,
    [INTERNAL_DAT]             INT             NULL,
    [INTERNAL_DTE]             INT             NULL,
    [LAST_FRIDAY_DT]           DATETIME2 (7)   NULL,
    [LEAP_YEAR_FLAG]           NVARCHAR (400)  NULL,
    [MONTHNAME_YEAR]           NVARCHAR (400)  NULL,
    [MONTH_BEGIN_DT]           DATETIME2 (7)   NULL,
    [MONTH_BEGIN_DT_STR]       NVARCHAR (400)  NULL,
    [MONTH_END_DT]             DATETIME2 (7)   NULL,
    [MONTH_END_FLAG]           NVARCHAR (400)  NULL,
    [MONTH_NAME]               NVARCHAR (400)  NULL,
    [MONTH_NUMBER]             INT             NULL,
    [OCCURRENCE_IN_MONTH]      INT             NULL,
    [PREV_DAY_DT]              DATETIME2 (7)   NULL,
    [QTR_BEGIN_DT_STR]         NVARCHAR (400)  NULL,
    [QUARTER_BEGIN_DT]         DATETIME2 (7)   NULL,
    [QUARTER_END_DT]           DATETIME2 (7)   NULL,
    [QUARTER_NUMBER]           INT             NULL,
    [QUARTER_STR]              NVARCHAR (400)  NULL,
    [SAME_DAY_YEAR_AGO]        DATETIME2 (7)   NULL,
    [TOMORROW_DT]              DATETIME2 (7)   NULL,
    [USA_FISCAL_YEAR_BEGIN_DT] DATETIME2 (7)   NULL,
    [USA_FISCAL_YEAR_END_DT]   DATETIME2 (7)   NULL,
    [WEEKDAY_CT]               INT             NULL,
    [WEEKEND_FLAG]             NVARCHAR (400)  NULL,
    [WEEK_BEGIN_DT]            DATETIME2 (7)   NULL,
    [WEEK_BEGIN_DT_STR]        NVARCHAR (400)  NULL,
    [WEEK_ENDING_DT]           DATETIME2 (7)   NULL,
    [WEEK_NUMBER]              INT             NULL,
    [WHICH_DAYS_CODE]          INT             NULL,
    [YEAR]                     INT             NULL,
    [YEAR_BEGIN_DT]            DATETIME2 (7)   NULL,
    [YEAR_BEGIN_DT_STR]        NVARCHAR (400)  NULL,
    [YEAR_END_DT]              DATETIME2 (7)   NULL,
    [YEAR_MONTH]               NVARCHAR (400)  NULL,
    [YEAR_MONTH_STR]           NVARCHAR (400)  NULL,
    [YEAR_OF_THE_WEEK]         INT             NULL,
    [YEAR_QUARTER]             NVARCHAR (400)  NULL
);


GO

