CREATE TABLE [dbo].[CLINICAL_ALERTS] (
    [ALERT_DESC]                      NVARCHAR (400)  NULL,
    [ALT_ID]                          DECIMAL (18, 4) NULL,
    [BLOOD_ALERT_BUCKET_CODE]         INT             NULL,
    [BPA_IS_PAT_FACING_FLAG]          NVARCHAR (400)  NULL,
    [BPA_LOCATOR_ID]                  DECIMAL (18, 4) NULL,
    [CM_LOG_OWNER_ID]                 NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]                 NVARCHAR (400)  NULL,
    [EXPECTED_WKFL_ACTVTIES_CODE]     INT             NULL,
    [GENERAL_ALT_TYPE_CODE]           INT             NULL,
    [HM_TOPIC_ID]                     DECIMAL (18, 4) NULL,
    [IMMUN_ID]                        DECIMAL (18, 4) NULL,
    [MAR_ACTION_CODE]                 NVARCHAR (400)  NULL,
    [MAR_DUPLICATE_FLAG]              NVARCHAR (400)  NULL,
    [MED_ADVISORY_RECORD_ID]          DECIMAL (18, 4) NULL,
    [MED_ADVISORY_TYPE_CODE]          INT             NULL,
    [MED_ADVISORY_USER_COMMENT]       NVARCHAR (400)  NULL,
    [MED_ADVISORY_USER_FEEDBACK_CODE] INT             NULL,
    [MED_ALERT_SUBTYPE_CODE]          INT             NULL,
    [MED_ALERT_TYPE_CODE]             INT             NULL,
    [MED_VENDOR_CODE]                 INT             NULL,
    [NBA_GUARANTOR_ACCT_ID]           DECIMAL (18, 4) NULL,
    [NBA_LOCATOR_ID]                  DECIMAL (18, 4) NULL,
    [NBA_PATIENT_ID]                  NVARCHAR (400)  NULL,
    [NBA_PROSPECT_RECORD_ID]          DECIMAL (18, 4) NULL,
    [NBA_PROV_ID]                     NVARCHAR (400)  NULL,
    [NBA_SUBMITTER_RECORD_ID]         DECIMAL (18, 4) NULL,
    [ORDER_GROUP_ID]                  DECIMAL (18, 4) NULL,
    [ORD_VALID_LPP_ID]                DECIMAL (18, 4) NULL,
    [PATIENT_ID]                      NVARCHAR (400)  NULL,
    [PROTOCOL_ID]                     DECIMAL (18, 4) NULL,
    [PUMP_ID]                         NVARCHAR (400)  NULL,
    [RECORD_STATUS_CODE]              INT             NULL,
    [REC_ARCHIVED_FLAG]               NVARCHAR (400)  NULL,
    [SVV_LEAF_LPP_ID]                 DECIMAL (18, 4) NULL,
    [SVV_PROFILE_LPP_ID]              DECIMAL (18, 4) NULL,
    [SVV_RULE_ID]                     NVARCHAR (400)  NULL,
    [UPDATE_DATE]                     DATETIME2 (7)   NULL,
    [VISIT_ID]                        DECIMAL (18, 4) NULL
);


GO

