CREATE TABLE [dbo].[CLINICAL_NOTES] (
    [ACCEPT_DATE]                  DATETIME2 (7)   NULL,
    [ACCT_NOTES_EXTRA_ID]          DECIMAL (18, 4) NULL,
    [ACTIVE_FROM_DT]               DATETIME2 (7)   NULL,
    [ACTIVE_TO_DT]                 DATETIME2 (7)   NULL,
    [ADDENDUM_PARENT_ENC]          DECIMAL (18, 4) NULL,
    [ADDR_VERIF_ACCT_ID]           DECIMAL (18, 4) NULL,
    [AMB_NOTE_FLAG]                NVARCHAR (400)  NULL,
    [AUTO_GENERATED_FLAG]          NVARCHAR (400)  NULL,
    [A_COPY_FLAG]                  NVARCHAR (400)  NULL,
    [BOOK_CONFRM_LOC_ID]           DECIMAL (18, 4) NULL,
    [BOOK_CONFRM_PROV_ID]          NVARCHAR (400)  NULL,
    [BOOK_CONFRM_TXT]              NVARCHAR (400)  NULL,
    [CLAIM_TEST_INS_DTTM]          DATETIME2 (7)   NULL,
    [CM_LOG_OWNER_ID]              NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]              NVARCHAR (400)  NULL,
    [COMMENT_EDIT_INST_DTTM]       DATETIME2 (7)   NULL,
    [COMMENT_USER_ID]              NVARCHAR (400)  NULL,
    [CONVERSATION_MSG_ID]          NVARCHAR (400)  NULL,
    [COSIGNED_NOTE_LINK]           DECIMAL (18, 4) NULL,
    [CREATE_INSTANT_DTTM]          DATETIME2 (7)   NULL,
    [CRT_INST_LOCAL_DTTM]          DATETIME2 (7)   NULL,
    [CURRENT_AUTHOR_ID]            NVARCHAR (400)  NULL,
    [DATE_OF_SERVIC_DTTM]          DATETIME2 (7)   NULL,
    [DELETED_CAT_CODE]             INT             NULL,
    [DELETE_INSTANT_DTTM]          DATETIME2 (7)   NULL,
    [DELETE_USER_ID]               NVARCHAR (400)  NULL,
    [DEL_INST_LOCAL_DTTM]          DATETIME2 (7)   NULL,
    [DEPT_MSG_DEPT_ID]             DECIMAL (18, 4) NULL,
    [DEPT_MSG_STATUS_CODE]         INT             NULL,
    [DEPT_MSG_TYPE_CODE]           INT             NULL,
    [DEPT_SPECIALTY_CODE]          NVARCHAR (400)  NULL,
    [DICT_IDENTIFIER]              NVARCHAR (400)  NULL,
    [DOWNTIME_ID]                  NVARCHAR (400)  NULL,
    [ECG_REPORT_TYPE]              NVARCHAR (400)  NULL,
    [ECG_REVIEWED_BY]              NVARCHAR (400)  NULL,
    [ECG_REV_INST_DTTM]            DATETIME2 (7)   NULL,
    [ECG_TECHNICIAN_ID]            NVARCHAR (400)  NULL,
    [ENCOUNTER_ID]                 DECIMAL (18, 4) NULL,
    [ENTRY_DATETIME]               DATETIME2 (7)   NULL,
    [ENTRY_USER_ID]                NVARCHAR (400)  NULL,
    [EXT_INTERF_ID]                DECIMAL (18, 4) NULL,
    [FASTNOTE_FLAG]                NVARCHAR (400)  NULL,
    [FROM_AUTOSAVE_FLAG]           NVARCHAR (400)  NULL,
    [IB_RESP_POOL_ID]              DECIMAL (18, 4) NULL,
    [IB_RESP_USER_ID]              NVARCHAR (400)  NULL,
    [INPATIENT_DATA_ID]            NVARCHAR (400)  NULL,
    [INTF_TRANS_CODE]              INT             NULL,
    [IP_NOTE_TYPE_CODE]            NVARCHAR (400)  NULL,
    [IS_POC_NOTE_FLAG]             NVARCHAR (400)  NULL,
    [LETTER_SUMMARY]               NVARCHAR (400)  NULL,
    [LETTER_TEMPLATE_SMARTTEXT_ID] NVARCHAR (400)  NULL,
    [LETTER_TYPE_CODE]             NVARCHAR (400)  NULL,
    [LET_PRNT_MTHD_CODE]           INT             NULL,
    [LST_FILED_INST_DTTM]          DATETIME2 (7)   NULL,
    [MMTA_USED_FLAG]               NVARCHAR (400)  NULL,
    [NOTEWRITER_TEMPLATE]          NVARCHAR (400)  NULL,
    [NOTE_ATTESTED_FLAG]           NVARCHAR (400)  NULL,
    [NOTE_DESC]                    NVARCHAR (400)  NULL,
    [NOTE_FORMAT_NOADD_CODE]       NVARCHAR (400)  NULL,
    [NOTE_ID]                      NVARCHAR (400)  NULL,
    [NOTE_LET_PRNT_DTTM]           DATETIME2 (7)   NULL,
    [NOTE_MOVE_SOURCE_ID]          NVARCHAR (400)  NULL,
    [NOTE_PURPOSE_CODE]            INT             NULL,
    [NOTE_SHARED_W_PAT_FLAG]       NVARCHAR (400)  NULL,
    [NOTE_SOURCE_CODE]             INT             NULL,
    [NOTE_TYPE_NOADD_CODE]         NVARCHAR (400)  NULL,
    [NOT_FOR_PRINTING_FLAG]        NVARCHAR (400)  NULL,
    [NUM_LETTER_PARTS]             INT             NULL,
    [NURS_NOTE_AUTH_NAM]           NVARCHAR (400)  NULL,
    [ORIGINAL_HP_ID]               NVARCHAR (400)  NULL,
    [ORIG_HP_DATE_REAL]            DECIMAL (18, 4) NULL,
    [PATIENT_ID]                   NVARCHAR (400)  NULL,
    [PATIENT_LINK_ID]              NVARCHAR (400)  NULL,
    [PATMSG_DISPLAY]               NVARCHAR (400)  NULL,
    [PATMSG_EXP_DT]                DATETIME2 (7)   NULL,
    [PATMSG_LED_DT]                DATETIME2 (7)   NULL,
    [PATMSG_LED_USER_ID]           NVARCHAR (400)  NULL,
    [PATMSG_PATIENT_ID]            NVARCHAR (400)  NULL,
    [PATMSG_PRIORITY_CODE]         NVARCHAR (400)  NULL,
    [PREV_DOC_TYPE_CODE]           NVARCHAR (400)  NULL,
    [PREV_NOTE_TYPE_CODE]          NVARCHAR (400)  NULL,
    [PRIORITY_FLAG]                NVARCHAR (400)  NULL,
    [REC_ARCHIVED_FLAG]            NVARCHAR (400)  NULL,
    [RTE_REVIEW_VER_ID]            DECIMAL (18, 4) NULL,
    [RTE_TRIGGER_USER_ID]          NVARCHAR (400)  NULL,
    [RTE_TRIGRD_PATIENT_ID]        NVARCHAR (400)  NULL,
    [SAVED_IN_NW_FLAG]             NVARCHAR (400)  NULL,
    [SCANNED_DOC_INFO]             NVARCHAR (400)  NULL,
    [SCANNED_NOTE_FLAG]            NVARCHAR (400)  NULL,
    [SENSITIVITY_STAT_CODE]        NVARCHAR (400)  NULL,
    [SIGNED_NOTE_ID]               NVARCHAR (400)  NULL,
    [SOURCE_HP_DATE_REAL]          DECIMAL (18, 4) NULL,
    [SOURCE_HP_ID]                 NVARCHAR (400)  NULL,
    [TREAT_SUM_RLS_TO_MYC_ENC]     DECIMAL (18, 4) NULL,
    [TREAT_SUM_RLS_TO_MYC_FLAG]    NVARCHAR (400)  NULL,
    [TRNSCRTN_MVD_DT]              DATETIME2 (7)   NULL,
    [TX_IB_FOLDER_CODE]            DECIMAL (18, 4) NULL,
    [UNSIGNED_FLAG]                NVARCHAR (400)  NULL,
    [UPDATE_DATE]                  DATETIME2 (7)   NULL,
    [VISIT_NUM]                    NVARCHAR (400)  NULL,
    [WORKING_COPY_FLAG]            NVARCHAR (400)  NULL,
    [_SURROGATEKEY]                BIGINT          NULL
);


GO

