CREATE TABLE [dbo].[DIAGNOSES] (
    [CC_FLG_FLAG]               NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]           NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]           NVARCHAR (400)  NULL,
    [CURRENT_ICD10_LIST]        NVARCHAR (400)  NULL,
    [CURRENT_ICD9_LIST]         NVARCHAR (400)  NULL,
    [CUR_MPD_ICDO3_DELIM]       NVARCHAR (400)  NULL,
    [CUR_MPD_ICPC_DELIM]        NVARCHAR (400)  NULL,
    [CUR_MPD_MONDO_DELIM]       NVARCHAR (400)  NULL,
    [CUR_MPD_THL_DISPLAY]       NVARCHAR (400)  NULL,
    [DIAGNOSIS_CODE]            NVARCHAR (400)  NULL,
    [DX_CHRONIC_FLAG_FLAG]      NVARCHAR (400)  NULL,
    [DX_CODE_TYPE]              INT             NULL,
    [DX_GROUP]                  NVARCHAR (400)  NULL,
    [DX_GROUP_ID]               NVARCHAR (400)  NULL,
    [DX_ICD9_IMO_ID]            NVARCHAR (400)  NULL,
    [DX_ID]                     DECIMAL (18, 4) NULL,
    [DX_IMO_ID]                 NVARCHAR (400)  NULL,
    [DX_LATERALITY_CODE]        INT             NULL,
    [DX_NAME]                   NVARCHAR (400)  NULL,
    [DX_OTHER_DESC]             NVARCHAR (400)  NULL,
    [DX_RISK_CHRONIC_CODE]      INT             NULL,
    [DX_RISK_DEGREE_CODE]       INT             NULL,
    [DX_RISK_TYPE_CODE]         INT             NULL,
    [DX_STATUS]                 NVARCHAR (400)  NULL,
    [EC_INACTIVE_FLAG]          NVARCHAR (400)  NULL,
    [EXTERNAL_ID]               NVARCHAR (400)  NULL,
    [FULLY_SPECIFIED_CODE_FLAG] NVARCHAR (400)  NULL,
    [GENERIC_DX_CODE]           INT             NULL,
    [HCC_COMM_FACT]             NVARCHAR (400)  NULL,
    [HCC_INST_FACT]             NVARCHAR (400)  NULL,
    [HCC_MODEL_CAT]             NVARCHAR (400)  NULL,
    [HISTORICAL_REF_CODE]       NVARCHAR (400)  NULL,
    [HL_TERM_ID]                NVARCHAR (400)  NULL,
    [HX_REF_CODE_NO_ADD]        NVARCHAR (400)  NULL,
    [ICD9_CODE]                 NVARCHAR (400)  NULL,
    [ICD9_CODE_NO_ADD]          NVARCHAR (400)  NULL,
    [IMO_TERM_ID]               NVARCHAR (400)  NULL,
    [INSTANT_OF_UPDATE_DTTM]    DATETIME2 (7)   NULL,
    [IS_STAGEABLE_CANCER_FLAG]  NVARCHAR (400)  NULL,
    [MCC_FLG_FLAG]              NVARCHAR (400)  NULL,
    [PARENT_DX_ID]              DECIMAL (18, 4) NULL,
    [PATIENT_FRIENDLY_ID]       DECIMAL (18, 4) NULL,
    [PATIENT_FRIENDLY_TEXT]     NVARCHAR (400)  NULL,
    [PREFERRED_TERM_ID]         DECIMAL (18, 4) NULL,
    [PREF_GEN_TERM_ID]          DECIMAL (18, 4) NULL,
    [PRIMARY_DX_ALLOWED_CODE]   INT             NULL,
    [RECORD_STATE_CODE]         INT             NULL,
    [RECORD_TYPE_CODE]          INT             NULL,
    [REFERENCE_CODE]            NVARCHAR (400)  NULL,
    [REF_BILL_CODE]             NVARCHAR (400)  NULL,
    [REF_BILL_CODE_SET_CODE]    INT             NULL,
    [RXHCC_DOL_COEFF]           NVARCHAR (400)  NULL,
    [RXHCC_MODEL_CAT]           NVARCHAR (400)  NULL,
    [RXHCC_REL_FACT]            NVARCHAR (400)  NULL,
    [SHOWN_IN_MYC_FLAG]         NVARCHAR (400)  NULL,
    [SPEC_BILLING_FLAG]         NVARCHAR (400)  NULL,
    [_SURROGATEKEY]             BIGINT          NULL
);


GO

