CREATE TABLE [dbo].[ED_EVENT_TEMPLATES] (
    [CASE_TRKING_EVENT_CODE] NVARCHAR (400) NULL,
    [CM_LOG_OWNER_ID]        NVARCHAR (400) NULL,
    [CM_PHY_OWNER_ID]        NVARCHAR (400) NULL,
    [DISPLAY_NAME]           NVARCHAR (400) NULL,
    [EVENT_NAME]             NVARCHAR (400) NULL,
    [FLOWSHEET_ROW_ID]       NVARCHAR (400) NULL,
    [FLWSHT_ADD_ROWS_FLAG]   NVARCHAR (400) NULL,
    [INP_NOTE_TYPE_CODE]     NVARCHAR (400) NULL,
    [ITEMS_EDITED_TIME]      DATETIME2 (7)  NULL,
    [LEV_LDAPLASSESS_FLAG]   NVARCHAR (400) NULL,
    [RECORD_ID]              NVARCHAR (400) NULL,
    [RECORD_NAME]            NVARCHAR (400) NULL,
    [RECORD_STATE_NAME]      NVARCHAR (400) NULL,
    [TEMP_NAME_EDIT]         NVARCHAR (400) NULL,
    [UPDATE_TIME]            DATETIME2 (7)  NULL
);


GO

