CREATE TABLE [dbo].[ED_ENCOUNTERS_FACT] (
    [ACUITY_LEVEL_CODE]                 NVARCHAR (400)  NULL,
    [ADMISSION_EVENT_ID]                DECIMAL (18, 4) NULL,
    [ADT_ARRIVAL_DATE]                  DATETIME2 (7)   NULL,
    [ADT_ARRIVAL_DTTM]                  DATETIME2 (7)   NULL,
    [ADT_SERVICE_AREA_ID]               DECIMAL (18, 4) NULL,
    [AGE_AT_ARRIVAL_MONTHS]             INT             NULL,
    [AGE_AT_ARRIVAL_YEARS]              INT             NULL,
    [AMBULANCE_CODE_CODE]               INT             NULL,
    [DISASTER_NUM]                      NVARCHAR (400)  NULL,
    [DISCHARGE_DESTINATION_CODE]        NVARCHAR (400)  NULL,
    [DISCHARGE_DISPOSITION_CODE]        NVARCHAR (400)  NULL,
    [DISCHARGE_EVENT_ID]                DECIMAL (18, 4) NULL,
    [ED_DEPARTURE_DTTM]                 DATETIME2 (7)   NULL,
    [ED_DISPOSITION_CODE]               NVARCHAR (400)  NULL,
    [ED_DISPOSITION_DTTM]               DATETIME2 (7)   NULL,
    [ED_DISPOSITION_PAT_CONDITION_CODE] INT             NULL,
    [ED_EPISODE_ID]                     DECIMAL (18, 4) NULL,
    [ED_PRIMARY_CARE_AREA_ID]           DECIMAL (18, 4) NULL,
    [EMERGENCY_ADMISSION_DTTM]          DATETIME2 (7)   NULL,
    [EMERGENCY_ADMISSION_EVENT_ID]      DECIMAL (18, 4) NULL,
    [ENCOUNTER_ID]                      DECIMAL (18, 4) NULL,
    [ENC_ADDRESS_LINE]                  INT             NULL,
    [FIRST_CHIEF_COMPLAINT_ID]          DECIMAL (18, 4) NULL,
    [FIRST_CHIEF_COMPLAINT_OTHER]       NVARCHAR (400)  NULL,
    [FIRST_ED_ATTEND_PROV_ID]           NVARCHAR (400)  NULL,
    [FIRST_EMERGENCY_DEPARTMENT_ID]     DECIMAL (18, 4) NULL,
    [HOSPITAL_ACCOUNT_ID]               DECIMAL (18, 4) NULL,
    [HOSPITAL_ADMISSION_DTTM]           DATETIME2 (7)   NULL,
    [HOSPITAL_DISCHARGE_DATE]           DATETIME2 (7)   NULL,
    [HOSPITAL_DISCHARGE_DTTM]           DATETIME2 (7)   NULL,
    [INPATIENT_ADMISSION_DTTM]          DATETIME2 (7)   NULL,
    [INPATIENT_ADMISSION_EVENT_ID]      DECIMAL (18, 4) NULL,
    [INPATIENT_ENCOUNTER_ID]            DECIMAL (18, 4) NULL,
    [LAST_DEPARTMENT_ID]                DECIMAL (18, 4) NULL,
    [LAST_ED_ATTEND_PROV_ID]            NVARCHAR (400)  NULL,
    [LAST_EMERGENCY_DEPARTMENT_ID]      DECIMAL (18, 4) NULL,
    [LOA_ENCOUNTER_ID]                  DECIMAL (18, 4) NULL,
    [LOA_LINE]                          INT             NULL,
    [LONGEST_ED_ATTEND_PROV_ID]         NVARCHAR (400)  NULL,
    [MEANS_OF_ARRIVAL_CODE]             NVARCHAR (400)  NULL,
    [NUM_CHIEF_COMPLAINTS_ENC]          INT             NULL,
    [NUM_DX_ENC]                        INT             NULL,
    [NUM_ED_DX_ENC]                     INT             NULL,
    [PATIENT_ID]                        NVARCHAR (400)  NULL,
    [PCP_AT_ENC_PROV_ID]                NVARCHAR (400)  NULL,
    [PREV_ED_ENCOUNTER_ID]              DECIMAL (18, 4) NULL,
    [PREV_ED_ENC_DATEDIFF]              INT             NULL,
    [PREV_ED_ENC_HOURDIFF]              INT             NULL,
    [PREV_HOSP_ENCOUNTER_ID]            DECIMAL (18, 4) NULL,
    [PREV_HOSP_ENC_DATEDIFF]            INT             NULL,
    [PREV_HOSP_ENC_ED_FLAG]             NVARCHAR (400)  NULL,
    [PREV_HOSP_ENC_HOURDIFF]            INT             NULL,
    [PREV_HOSP_ENC_INPATIENT_FLAG]      NVARCHAR (400)  NULL,
    [PRIMARY_DX_ED_FLAG]                NVARCHAR (400)  NULL,
    [PRIMARY_DX_ID]                     DECIMAL (18, 4) NULL,
    [PRIMARY_DX_LINE]                   INT             NULL,
    [PRIVATE_HOSPITAL_ENC_CODE]         INT             NULL,
    [UPDATE_DATE]                       DATETIME2 (7)   NULL
);


GO

