CREATE TABLE [dbo].[ED_ENCOUNTERS_DM] (
    [ABUSE_RECD_BEF_DEPART]          INT             NULL,
    [ACUITY]                         INT             NULL,
    [ADMIT_DECISION_DTTM]            DATETIME2 (7)   NULL,
    [ALLERGY_REVD_BEF_DEPART_FLAG]   NVARCHAR (400)  NULL,
    [ARRIVAL_DATE]                   DATETIME2 (7)   NULL,
    [ARRIVAL_DTTM]                   DATETIME2 (7)   NULL,
    [ASSESS_BEF_DEPART]              INT             NULL,
    [AVS_PRINTED_DTTM]               DATETIME2 (7)   NULL,
    [BALLOON_START_DTTM]             DATETIME2 (7)   NULL,
    [BED_ASSIGNED_DTTM]              DATETIME2 (7)   NULL,
    [BED_REQUESTED_DTTM]             DATETIME2 (7)   NULL,
    [CM_LOG_OWNER_ID]                NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]                NVARCHAR (400)  NULL,
    [DEPART_DATE]                    DATETIME2 (7)   NULL,
    [DEPART_DTTM]                    DATETIME2 (7)   NULL,
    [DISPOSITION_DTTM]               DATETIME2 (7)   NULL,
    [DM_DATE]                        DATETIME2 (7)   NULL,
    [ED_BOARD_CARE_START_DTTM]       DATETIME2 (7)   NULL,
    [ED_BP_RECD_BEF_DEPART]          INT             NULL,
    [ED_GENERIC_DISPO_CODE]          INT             NULL,
    [ED_HR_RECD_BEF_DEPART]          INT             NULL,
    [ED_INFSN_STOPPED_FLAG]          NVARCHAR (400)  NULL,
    [ED_LDA_REMOVAL_DOC_FLAG]        NVARCHAR (400)  NULL,
    [ED_NOTES_ON_TIME_FLAG]          NVARCHAR (400)  NULL,
    [ED_PAIN_REC_BEF_DEPART]         INT             NULL,
    [ED_RESP_REC_BEF_DEP]            INT             NULL,
    [ED_SPO2_BEF_DEP]                INT             NULL,
    [ENCOUNTER_ID]                   DECIMAL (18, 4) NULL,
    [FACILITY_CRIT_CARE_FLAG]        NVARCHAR (400)  NULL,
    [FACILITY_LOS]                   INT             NULL,
    [FIRST_ABX_GIVEN_DTTM]           DATETIME2 (7)   NULL,
    [FIRST_ASPIRIN_GIVEN_DTTM]       DATETIME2 (7)   NULL,
    [FIRST_BLOOD_GAS_ORDERED_DTTM]   DATETIME2 (7)   NULL,
    [FIRST_BLOOD_GAS_RESULTED_DTTM]  DATETIME2 (7)   NULL,
    [FIRST_BLOOD_GAS_SPEC_COLL_DTTM] DATETIME2 (7)   NULL,
    [FIRST_BLOOD_GAS_SPEC_RECV_DTTM] DATETIME2 (7)   NULL,
    [FIRST_CARD_LAB_ORDERED_DTTM]    DATETIME2 (7)   NULL,
    [FIRST_CARD_LAB_RESULTED_DTTM]   DATETIME2 (7)   NULL,
    [FIRST_CARD_LAB_SPEC_COLL_DTTM]  DATETIME2 (7)   NULL,
    [FIRST_CARD_LAB_SPEC_RECV_DTTM]  DATETIME2 (7)   NULL,
    [FIRST_CBC_ORDERED_DTTM]         DATETIME2 (7)   NULL,
    [FIRST_CBC_RESULTED_DTTM]        DATETIME2 (7)   NULL,
    [FIRST_CBC_SPEC_COLL_DTTM]       DATETIME2 (7)   NULL,
    [FIRST_CBC_SPEC_RECV_DTTM]       DATETIME2 (7)   NULL,
    [FIRST_CHEM_PROF_ORDERED_DTTM]   DATETIME2 (7)   NULL,
    [FIRST_CHEM_PROF_RESULTED_DTTM]  DATETIME2 (7)   NULL,
    [FIRST_CHEM_PROF_SPEC_COLL_DTTM] DATETIME2 (7)   NULL,
    [FIRST_CHEM_PROF_SPEC_RECV_DTTM] DATETIME2 (7)   NULL,
    [FIRST_CT_END_DTTM]              DATETIME2 (7)   NULL,
    [FIRST_CT_ORD_DTTM]              DATETIME2 (7)   NULL,
    [FIRST_CT_START_DTTM]            DATETIME2 (7)   NULL,
    [FIRST_ECG_START_DTTM]           DATETIME2 (7)   NULL,
    [FIRST_MRI_END_DTTM]             DATETIME2 (7)   NULL,
    [FIRST_MRI_ORD_DTTM]             DATETIME2 (7)   NULL,
    [FIRST_MRI_START_DTTM]           DATETIME2 (7)   NULL,
    [FIRST_PAIN_MED_GIVEN_DTTM]      DATETIME2 (7)   NULL,
    [FIRST_TPA_GIVEN_DTTM]           DATETIME2 (7)   NULL,
    [FIRST_UA_ORDERED_DTTM]          DATETIME2 (7)   NULL,
    [FIRST_UA_RESULTED_DTTM]         DATETIME2 (7)   NULL,
    [FIRST_UA_SPEC_COLL_DTTM]        DATETIME2 (7)   NULL,
    [FIRST_UA_SPEC_RECV_DTTM]        DATETIME2 (7)   NULL,
    [FIRST_US_END_DTTM]              DATETIME2 (7)   NULL,
    [FIRST_US_ORD_DTTM]              DATETIME2 (7)   NULL,
    [FIRST_US_START_DTTM]            DATETIME2 (7)   NULL,
    [FIRST_XRAY_END_DTTM]            DATETIME2 (7)   NULL,
    [FIRST_XRAY_ORD_DTTM]            DATETIME2 (7)   NULL,
    [FIRST_XRAY_START_DTTM]          DATETIME2 (7)   NULL,
    [HAS_PSYCH_DIAGNOSIS_FLAG]       NVARCHAR (400)  NULL,
    [KEY_ATND_PROV_ID]               NVARCHAR (400)  NULL,
    [KEY_MIDLEVEL_ID]                NVARCHAR (400)  NULL,
    [KEY_NURSE_ID]                   NVARCHAR (400)  NULL,
    [KEY_RESIDENT_ID]                NVARCHAR (400)  NULL,
    [MED_HX_REV_BEF_DEPART_FLAG]     NVARCHAR (400)  NULL,
    [NUM_ED_VIS_48_H_BEF_ENC]        INT             NULL,
    [NUM_ED_VIS_72_H_BEF_ENC]        INT             NULL,
    [NUM_IP_VIS_30_D_BEF_ENC]        INT             NULL,
    [OBSERVATION_END_DTTM]           DATETIME2 (7)   NULL,
    [OBSERVATION_START_DTTM]         DATETIME2 (7)   NULL,
    [PATIENT_ID]                     NVARCHAR (400)  NULL,
    [PATIENT_READY_TO_GO_DTTM]       DATETIME2 (7)   NULL,
    [PROFESSIONAL_LOS]               INT             NULL,
    [PROF_CRIT_CARE_FLAG]            NVARCHAR (400)  NULL,
    [PROV_ASSIGN_DTTM]               DATETIME2 (7)   NULL,
    [PROV_FIRST_SEEN_DTTM]           DATETIME2 (7)   NULL,
    [PTA_MED_REV_BEF_DEPART_FLAG]    NVARCHAR (400)  NULL,
    [RECORD_ID]                      DECIMAL (18, 4) NULL,
    [REGISTRY_STATUS_CODE]           INT             NULL,
    [ROOMED_DTTM]                    DATETIME2 (7)   NULL,
    [TRIAGE_END_DTTM]                DATETIME2 (7)   NULL,
    [TRIAGE_START_DTTM]              DATETIME2 (7)   NULL,
    [WAS_EVER_OBS_FLAG]              NVARCHAR (400)  NULL
);


GO

