CREATE TABLE [dbo].[ED_EVENT_INFO] (
    [ADT_EVENT_ID]                 DECIMAL (18, 4) NULL,
    [ALLOW_UPD_PROV_ON_TRANS_FLAG] NVARCHAR (400)  NULL,
    [AN_DX_ID]                     DECIMAL (18, 4) NULL,
    [AN_LINKED_EVENT_ID]           NVARCHAR (400)  NULL,
    [AN_LINKED_EVENT_LINE]         INT             NULL,
    [AN_PROBLEM_LIST_ID]           DECIMAL (18, 4) NULL,
    [CM_LOG_OWNER_ID]              NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]              NVARCHAR (400)  NULL,
    [CT_EVENT_FILED_BY_CODE]       NVARCHAR (400)  NULL,
    [DEPT_SCORE]                   DECIMAL (18, 4) NULL,
    [DISCHARGE_NAV_CONFIG_ID]      DECIMAL (18, 4) NULL,
    [ED_C_CLIENT_SRC_CODE]         INT             NULL,
    [EVENT_CMT]                    NVARCHAR (400)  NULL,
    [EVENT_CONTEXT]                NVARCHAR (400)  NULL,
    [EVENT_DEPT_ID]                DECIMAL (18, 4) NULL,
    [EVENT_DISPLAY_NAME]           NVARCHAR (400)  NULL,
    [EVENT_FINDING_ID]             DECIMAL (18, 4) NULL,
    [EVENT_ID]                     NVARCHAR (400)  NULL,
    [EVENT_IMPLANT_ID]             NVARCHAR (400)  NULL,
    [EVENT_INI_RECORD_ID]          NVARCHAR (400)  NULL,
    [EVENT_KEY]                    NVARCHAR (400)  NULL,
    [EVENT_LABEL]                  NVARCHAR (400)  NULL,
    [EVENT_LINE_DATA_ID]           NVARCHAR (400)  NULL,
    [EVENT_LOG_ID]                 NVARCHAR (400)  NULL,
    [EVENT_NOTE_ID]                NVARCHAR (400)  NULL,
    [EVENT_ORIGIN_CODE]            INT             NULL,
    [EVENT_OVRIDE_RSN_CODE]        INT             NULL,
    [EVENT_OWNER_ID]               NVARCHAR (400)  NULL,
    [EVENT_PROV_ID]                NVARCHAR (400)  NULL,
    [EVENT_RECORD_TIME]            DATETIME2 (7)   NULL,
    [EVENT_SIGN_OFF_ID]            DECIMAL (18, 4) NULL,
    [EVENT_SOURCE_CODE]            NVARCHAR (400)  NULL,
    [EVENT_SOURCE_ENC_ID]          DECIMAL (18, 4) NULL,
    [EVENT_STATUS_CODE]            INT             NULL,
    [EVENT_STATUS_NAME]            NVARCHAR (400)  NULL,
    [EVENT_SUPPLY_ID]              NVARCHAR (400)  NULL,
    [EVENT_TIME]                   DATETIME2 (7)   NULL,
    [EVENT_TYPE]                   NVARCHAR (400)  NULL,
    [EVENT_TYPE_VERSION]           DECIMAL (18, 4) NULL,
    [EVENT_USER_ID]                NVARCHAR (400)  NULL,
    [EVENT_VALUE]                  NVARCHAR (400)  NULL,
    [FULLY_STAFF_FLAG]             NVARCHAR (400)  NULL,
    [IP_REC_NOTE_ID]               NVARCHAR (400)  NULL,
    [LINE]                         INT             NULL,
    [LINKED_IEV_LINE]              INT             NULL,
    [LINKED_IEV_REC_ID]            NVARCHAR (400)  NULL,
    [LOCATION_ID]                  DECIMAL (18, 4) NULL,
    [MATCH_PX_ID]                  DECIMAL (18, 4) NULL,
    [MATCH_PX_INFO]                NVARCHAR (400)  NULL,
    [NOTIFY_PND_STATUS_CODE]       INT             NULL,
    [NOTIFY_STATUS_CODE]           INT             NULL,
    [OB_DEL_RECORD_ID]             DECIMAL (18, 4) NULL,
    [PEND_ACTIVE_CODE]             INT             NULL,
    [PEND_CHANGE_COUNT]            INT             NULL,
    [PEND_COMMENT]                 NVARCHAR (400)  NULL,
    [PEND_CREATE_TYPE_CODE]        INT             NULL,
    [PEND_DELETED_BY_ID]           NVARCHAR (400)  NULL,
    [PEND_DELETED_I_DTTM]          DATETIME2 (7)   NULL,
    [PEND_INSTANT_DTTM]            DATETIME2 (7)   NULL,
    [PEND_RESTORED_BY_ID]          NVARCHAR (400)  NULL,
    [PEND_RESTORED_DTTM]           DATETIME2 (7)   NULL,
    [PEND_STATUS_CODE]             INT             NULL,
    [REC_ADMIT_STATUS_CODE]        INT             NULL,
    [REC_IS_MED_HOSP_FLAG]         NVARCHAR (400)  NULL,
    [REC_IS_PROC_HOSP_FLAG]        NVARCHAR (400)  NULL,
    [REC_MED_AUTH_ADDR_IDENT]      NVARCHAR (400)  NULL,
    [REC_MED_AUTH_ID]              NVARCHAR (400)  NULL,
    [REC_MED_MSG_RCP_ID]           NVARCHAR (400)  NULL,
    [REC_ORD_PROV_ADDR_IDENT]      NVARCHAR (400)  NULL,
    [REC_ORD_PROV_ID]              NVARCHAR (400)  NULL,
    [REC_PAT_LOC_ID]               DECIMAL (18, 4) NULL,
    [REC_PROC_AUTH_ADDR_IDENT]     NVARCHAR (400)  NULL,
    [REC_PROC_AUTH_ID]             NVARCHAR (400)  NULL,
    [REC_PROC_MSG_RCP_ID]          NVARCHAR (400)  NULL,
    [REC_ROLE_ADMIT_STATUS_CODE]   INT             NULL,
    [REC_ROLE_ADMIT_USERROL_CODE]  INT             NULL,
    [REC_VERB_ORD_CMT]             NVARCHAR (400)  NULL,
    [REC_VERB_ORD_TYPE_CODE]       INT             NULL,
    [REC_VRB_ORD_COMM_ID]          NVARCHAR (400)  NULL,
    [REC_VRB_ORD_MODE_CODE]        INT             NULL,
    [REC_VRB_SIGNER_ID]            NVARCHAR (400)  NULL,
    [RX_REQUEST_PHARMACY_ID]       DECIMAL (18, 4) NULL,
    [RX_REQUEST_TYPE_CODE]         INT             NULL,
    [RX_REQUEST_VIEWED_FLAG]       NVARCHAR (400)  NULL,
    [SOURCE_PX_ID]                 DECIMAL (18, 4) NULL,
    [SOURCE_PX_INFO]               NVARCHAR (400)  NULL,
    [STAFFED_BEDS]                 DECIMAL (18, 4) NULL,
    [STAFF_IS_ATTN_FLAG]           NVARCHAR (400)  NULL,
    [STAFF_ROLE_CODE]              NVARCHAR (400)  NULL,
    [TRANSFER_DEST_DEPT_ID]        DECIMAL (18, 4) NULL,
    [TRANSPORT_ID]                 DECIMAL (18, 4) NULL,
    [TXPORT_HLR_ID]                DECIMAL (18, 4) NULL,
    [_SURROGATEKEY]                BIGINT          NULL
);


GO

