CREATE TABLE [dbo].[ED_PATIENT_INFO] (
    [ADT_TRANSFER_LINK]           INT             NULL,
    [AVS_COPY_FORWARD_DTTM]       DATETIME2 (7)   NULL,
    [AVS_COPY_FORWARD_USER_ID]    NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]             NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]             NVARCHAR (400)  NULL,
    [CONTACT_DATE]                DATETIME2 (7)   NULL,
    [CREATE_DTTM]                 DATETIME2 (7)   NULL,
    [CREATE_USER_ID]              NVARCHAR (400)  NULL,
    [DEPT_EVENT_DEP_ID]           DECIMAL (18, 4) NULL,
    [DTE_EXTERNAL]                DATETIME2 (7)   NULL,
    [ENCOUNTER_ID]                DECIMAL (18, 4) NULL,
    [EPT_DAT]                     FLOAT (53)      NULL,
    [EVENT_DATE]                  DATETIME2 (7)   NULL,
    [EVENT_ID]                    NVARCHAR (400)  NULL,
    [EVENT_LOCATION_EAF_ID]       DECIMAL (18, 4) NULL,
    [EVENT_YEAR]                  INT             NULL,
    [IP_ORDREC_SORT_DTTM]         DATETIME2 (7)   NULL,
    [ITEMS_EDITED_TIME]           DATETIME2 (7)   NULL,
    [ORD_REC_ADT_EVENT_ID]        DECIMAL (18, 4) NULL,
    [ORD_REC_DISCHARGE_DISP_CODE] NVARCHAR (400)  NULL,
    [ORD_REC_SUMMARY_UPDT_DTTM]   DATETIME2 (7)   NULL,
    [OR_ADMISSION_GROUP_CODE]     INT             NULL,
    [PATIENT_DATE_REAL]           FLOAT (53)      NULL,
    [PATIENT_ENC_DATE_REAL]       FLOAT (53)      NULL,
    [PATIENT_ID]                  NVARCHAR (400)  NULL,
    [RECORD_STATE_CODE]           INT             NULL,
    [RECORD_STATE_NAME]           NVARCHAR (400)  NULL,
    [REG_CLIP_COMMENTS]           NVARCHAR (400)  NULL,
    [REG_CLIP_FREETEXT]           NVARCHAR (400)  NULL,
    [REG_CLIP_LWS_ID]             NVARCHAR (400)  NULL,
    [REG_WAIT_ARRV_DTTM]          DATETIME2 (7)   NULL,
    [REG_WAIT_IS_PRI_FLAG]        NVARCHAR (400)  NULL,
    [REG_WAIT_PAGER_ID]           NVARCHAR (400)  NULL,
    [REG_WAIT_PAGER_NUM]          NVARCHAR (400)  NULL,
    [REG_WAIT_PAT_NAME]           NVARCHAR (400)  NULL,
    [REG_WAIT_STATE_CODE]         INT             NULL,
    [TRANSFER_STATUS_CODE]        INT             NULL,
    [TYPE_ID]                     NVARCHAR (400)  NULL,
    [UPDATE_DATE]                 DATETIME2 (7)   NULL,
    [VISIT_ID]                    DECIMAL (18, 4) NULL
);


GO

