CREATE TABLE [dbo].[FLOWSHEET_MEASUREMENTS] (
    [ABNORMAL_CODE]                 INT             NULL,
    [ABNORMAL_TYPE_CODE]            INT             NULL,
    [AUTOVALIDATE_FLAG]             NVARCHAR (400)  NULL,
    [CAPTURE_DEVICE_ID]             NVARCHAR (400)  NULL,
    [CHART_CORR_ID]                 DECIMAL (18, 4) NULL,
    [CLIENT_APP_TARGET_CODE]        INT             NULL,
    [CM_LOG_OWNER_ID]               NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]               NVARCHAR (400)  NULL,
    [DOCUMENTATION_SOURCE_CODE]     INT             NULL,
    [DOCUMENTING_INPATIENT_DATA_ID] NVARCHAR (400)  NULL,
    [DOC_METHOD_CODE]               INT             NULL,
    [EDITED_LINE]                   INT             NULL,
    [ENTRY_TIME]                    DATETIME2 (7)   NULL,
    [ENTRY_USER_ID]                 NVARCHAR (400)  NULL,
    [EXCLUDED_FLAG]                 NVARCHAR (400)  NULL,
    [FLO_CATEGORY_INI]              NVARCHAR (400)  NULL,
    [FLO_CATEGORY_ITEM]             NVARCHAR (400)  NULL,
    [FLO_CATEGORY_VALUE]            NVARCHAR (400)  NULL,
    [FLO_CNCT_DATE_REAL]            DECIMAL (18, 4) NULL,
    [FLO_DAT_USED]                  DECIMAL (18, 4) NULL,
    [FLO_MEAS_ID]                   NVARCHAR (400)  NULL,
    [FLO_NETWORKED_INI]             NVARCHAR (400)  NULL,
    [FLT_ID]                        NVARCHAR (400)  NULL,
    [FSD_ID]                        NVARCHAR (400)  NULL,
    [INSTANT_PENDED_DTTM]           DATETIME2 (7)   NULL,
    [IP_SIGNIFICANT_FLAG]           NVARCHAR (400)  NULL,
    [ISACCEPTED_FLAG]               NVARCHAR (400)  NULL,
    [IS_FROM_SPEECH_FLAG]           NVARCHAR (400)  NULL,
    [LINE]                          INT             NULL,
    [MACRO_RECORD_ID]               DECIMAL (18, 4) NULL,
    [MEAS_COMMENT]                  NVARCHAR (400)  NULL,
    [MEAS_LOCATION]                 NVARCHAR (400)  NULL,
    [MEAS_VALUE]                    NVARCHAR (400)  NULL,
    [MYPT_ID]                       NVARCHAR (400)  NULL,
    [NEEDS_COSIGN_CODE]             INT             NULL,
    [OCCURANCE]                     INT             NULL,
    [PATIENT_REPORTED_STATUS_CODE]  INT             NULL,
    [RECEIVED_INSTANT]              DATETIME2 (7)   NULL,
    [RECORDED_TIME]                 DATETIME2 (7)   NULL,
    [SPEECH_ENTERED_METHOD_CODE]    INT             NULL,
    [TAKEN_USER_ID]                 NVARCHAR (400)  NULL,
    [THRDPRTY_SRC_CODE]             INT             NULL,
    [UPDATE_DATE]                   DATETIME2 (7)   NULL,
    [USER_PENDED_BY_ID]             NVARCHAR (400)  NULL,
    [_SURROGATEKEY]                 BIGINT          NULL
);


GO

