CREATE TABLE [dbo].[FLOWSHEET_RECORDS] (
    [CM_LOG_OWNER_ID]      NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]      NVARCHAR (400)  NULL,
    [DAILY_NET]            DECIMAL (18, 4) NULL,
    [FSD_ID]               NVARCHAR (400)  NULL,
    [INPATIENT_DATA_ID]    NVARCHAR (400)  NULL,
    [PATIENT_ID]           NVARCHAR (400)  NULL,
    [RECORD_DATE]          DATETIME2 (7)   NULL,
    [REC_ARCHIVED_FLAG]    NVARCHAR (400)  NULL,
    [UNVERIFIED_DAILY_NET] DECIMAL (18, 4) NULL,
    [UPDATE_DATE]          DATETIME2 (7)   NULL
);


GO

