CREATE TABLE [dbo].[GROUPER_GROUPS] (
    [CM_LOG_OWNER_ID] NVARCHAR (400) NULL,
    [CM_PHY_OWNER_ID] NVARCHAR (400) NULL,
    [GROUPER_ID]      NVARCHAR (400) NULL,
    [GROUPER_LIST]    NVARCHAR (400) NULL,
    [LINE]            INT            NULL
);


GO

