CREATE TABLE [dbo].[GROUPER_TERMINOLOGY] (
    [CM_LOG_OWNER_ID]        NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]        NVARCHAR (400)  NULL,
    [CODE]                   NVARCHAR (400)  NULL,
    [CODE_SYSTEM_CODE]       INT             NULL,
    [GROUPER_ID]             NVARCHAR (400)  NULL,
    [HEDIS_MED_BRAND_NAME]   NVARCHAR (400)  NULL,
    [HEDIS_MED_DRUG_CLASS]   NVARCHAR (400)  NULL,
    [HEDIS_MED_GENERIC_NAME] NVARCHAR (400)  NULL,
    [HEDIS_MED_PACKAGE_SIZE] DECIMAL (18, 4) NULL,
    [HEDIS_MED_ROUTE]        NVARCHAR (400)  NULL,
    [HEDIS_MED_UNIT]         NVARCHAR (400)  NULL,
    [LINE]                   INT             NULL,
    [MED_STRENGTH]           DECIMAL (18, 4) NULL,
    [PQA_MED_ATTR_TYPE]      NVARCHAR (400)  NULL,
    [PQA_MED_ATTR_VALUE]     DECIMAL (18, 4) NULL,
    [_SURROGATEKEY]          BIGINT          NULL
);


GO

