CREATE TABLE [dbo].[HOSPITAL_TRANSACTIONS] (
    [ACCT_CLASS_HA_CODE]      NVARCHAR (400)  NULL,
    [ACTION_STRING]           NVARCHAR (400)  NULL,
    [ADDR_CITY]               NVARCHAR (400)  NULL,
    [ADDR_LINE1]              NVARCHAR (400)  NULL,
    [ADDR_LINE2]              NVARCHAR (400)  NULL,
    [ADDR_NAME]               NVARCHAR (400)  NULL,
    [ADDR_ZIP]                NVARCHAR (400)  NULL,
    [ALLOWANCE_ADJ_FLAG]      NVARCHAR (400)  NULL,
    [ALLOWED_AMOUNT]          DECIMAL (18, 4) NULL,
    [BAD_DEBT_FLAG_FLAG]      NVARCHAR (400)  NULL,
    [BEN_BKT_CVG_ID]          DECIMAL (18, 4) NULL,
    [BEN_BKT_INC_STR]         NVARCHAR (400)  NULL,
    [BILLED_AMOUNT]           DECIMAL (18, 4) NULL,
    [BILLING_PROV_ID]         NVARCHAR (400)  NULL,
    [BUCKET_ID]               DECIMAL (18, 4) NULL,
    [CASH_ID]                 DECIMAL (18, 4) NULL,
    [CE_FILED_TIME]           DATETIME2 (7)   NULL,
    [CE_HM_OFF_TXTYP_CODE]    INT             NULL,
    [CE_POST_DT]              DATETIME2 (7)   NULL,
    [CE_SRC_DEP_ID]           NVARCHAR (400)  NULL,
    [CE_SRC_HAR_ID]           DECIMAL (18, 4) NULL,
    [CE_SRC_HLB_ID]           DECIMAL (18, 4) NULL,
    [CE_SRC_HTR_ID]           DECIMAL (18, 4) NULL,
    [CHG_CRED_ORIG_ID]        DECIMAL (18, 4) NULL,
    [CHG_ROUTER_SRC_ID]       NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]         NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]         NVARCHAR (400)  NULL,
    [CM_SRC_HTR_DOT_ONE]      NVARCHAR (400)  NULL,
    [COINSURANCE_AMOUNT]      DECIMAL (18, 4) NULL,
    [COLLECTION_AGENCY]       DECIMAL (18, 4) NULL,
    [COMM_MOD_DISTB_H_FLAG]   NVARCHAR (400)  NULL,
    [COMM_MOD_HOME_AD_FLAG]   NVARCHAR (400)  NULL,
    [COPAY_AMOUNT]            DECIMAL (18, 4) NULL,
    [COST]                    DECIMAL (18, 4) NULL,
    [COST_CNTR_ID]            DECIMAL (18, 4) NULL,
    [CPT_CODE]                NVARCHAR (400)  NULL,
    [DEDUCTIBLE_AMOUNT]       DECIMAL (18, 4) NULL,
    [DEPARTMENT]              DECIMAL (18, 4) NULL,
    [DFLT_COST_CNTR_ID]       DECIMAL (18, 4) NULL,
    [DFLT_FEE_SCHED_ID]       DECIMAL (18, 4) NULL,
    [DFLT_PROC_DESC]          NVARCHAR (400)  NULL,
    [DFLT_UB_REV_CD_ID]       DECIMAL (18, 4) NULL,
    [DURATION_MINUTES]        INT             NULL,
    [EB_PMT_HAR_RES_FLAG]     NVARCHAR (400)  NULL,
    [EB_PMT_POST_TYPE_CODE]   INT             NULL,
    [EB_PMT_TOTAL_AMOUNT]     NVARCHAR (400)  NULL,
    [EB_PREPMT_POST_TP_CODE]  INT             NULL,
    [ELEC_PMT_APRVL_CODE]     NVARCHAR (400)  NULL,
    [ELEC_PMT_CRD_BRND_CODE]  NVARCHAR (400)  NULL,
    [ELEC_PMT_EVM_ID]         DECIMAL (18, 4) NULL,
    [ELEC_PMT_INST_TIME]      DATETIME2 (7)   NULL,
    [ENCOUNTER_ID]            DECIMAL (18, 4) NULL,
    [ERX_ID]                  DECIMAL (18, 4) NULL,
    [EXTERN_AR_FLAG_FLAG]     NVARCHAR (400)  NULL,
    [FACILITY_ID]             DECIMAL (18, 4) NULL,
    [FILER_NUMBER]            INT             NULL,
    [FIN_CLASS_CODE]          NVARCHAR (400)  NULL,
    [GL_CREDIT_NUM]           NVARCHAR (400)  NULL,
    [GL_DEBIT_NUM]            NVARCHAR (400)  NULL,
    [HCPCS_CODE]              NVARCHAR (400)  NULL,
    [HIPPS_CODE]              NVARCHAR (400)  NULL,
    [HIPPS_CODE_DESC]         NVARCHAR (400)  NULL,
    [HIPPS_CODE_TYPE_CODE]    INT             NULL,
    [HOM_RPT_FLG_YN]          NVARCHAR (400)  NULL,
    [HOSPITAL_ACCOUNT_ID]     DECIMAL (18, 4) NULL,
    [IMD_ID]                  NVARCHAR (400)  NULL,
    [IMPLANT_ID]              NVARCHAR (400)  NULL,
    [INI_FILE_ATTEMPT_DT]     DATETIME2 (7)   NULL,
    [INST_BILL_COMMENT]       NVARCHAR (400)  NULL,
    [INST_BILL_DOB]           DATETIME2 (7)   NULL,
    [INST_BILL_EMP_NUM]       NVARCHAR (400)  NULL,
    [INST_BILL_LNKPATIENT_ID] NVARCHAR (400)  NULL,
    [INST_BILL_PAT_NAME]      NVARCHAR (400)  NULL,
    [INST_BILL_SEX_CODE]      NVARCHAR (400)  NULL,
    [INST_BILL_SSN]           NVARCHAR (400)  NULL,
    [INT_CONTROL_NUMBER]      NVARCHAR (400)  NULL,
    [INVOICE_NUM]             NVARCHAR (400)  NULL,
    [IS_CONTESTED_FLAG]       NVARCHAR (400)  NULL,
    [IS_HOSPITALIST_FLAG]     NVARCHAR (400)  NULL,
    [IS_LATE_CHARGE_FLAG]     NVARCHAR (400)  NULL,
    [IS_RECOUPMENT_FLAG]      NVARCHAR (400)  NULL,
    [IS_REFUND_ADJ_FLAG]      NVARCHAR (400)  NULL,
    [IS_SYSTEM_ADJ_FLAG]      NVARCHAR (400)  NULL,
    [LATE_CRCTN_ORIG_ID]      DECIMAL (18, 4) NULL,
    [LINE_LEVEL_INFO_FLAG]    NVARCHAR (400)  NULL,
    [LINE_NUM_IN_HTT]         INT             NULL,
    [LINKED_HTR_ID]           DECIMAL (18, 4) NULL,
    [MEA_ID_CODE]             INT             NULL,
    [MODIFIERS]               NVARCHAR (400)  NULL,
    [NDC_ID]                  NVARCHAR (400)  NULL,
    [NON_COVERED_AMT]         DECIMAL (18, 4) NULL,
    [NON_COVERED_FLAG]        NVARCHAR (400)  NULL,
    [OLD_HOSP_ACCOUNT_ID]     DECIMAL (18, 4) NULL,
    [OPTIME_LOG_ID]           NVARCHAR (400)  NULL,
    [ORDER_ID]                DECIMAL (18, 4) NULL,
    [ORIG_ETR_ID]             DECIMAL (18, 4) NULL,
    [ORIG_PRICE]              DECIMAL (18, 4) NULL,
    [ORIG_REPOST_TX_ID]       DECIMAL (18, 4) NULL,
    [ORIG_REV_TX_ID]          DECIMAL (18, 4) NULL,
    [OVERRIDE_XOVER_FLAG]     NVARCHAR (400)  NULL,
    [PANEL_DAT]               FLOAT (53)      NULL,
    [PANEL_DT]                DATETIME2 (7)   NULL,
    [PANEL_ID]                DECIMAL (18, 4) NULL,
    [PATIENT_SERIAL_NUM]      DECIMAL (18, 4) NULL,
    [PAYMENT_FROM]            NVARCHAR (400)  NULL,
    [PAYMENT_NOT_ALLOWED]     DECIMAL (18, 4) NULL,
    [PAYMENT_SRC_HA_CODE]     INT             NULL,
    [PAYOR_ID]                DECIMAL (18, 4) NULL,
    [PERFORMING_PROV_ID]      NVARCHAR (400)  NULL,
    [PLACE_OF_SVC_ID]         DECIMAL (18, 4) NULL,
    [PMT_HAR_DIS_FROM_DT]     DATETIME2 (7)   NULL,
    [PMT_HAR_DIS_TO_DT]       DATETIME2 (7)   NULL,
    [PMT_RECEIPT_NO]          NVARCHAR (400)  NULL,
    [POST_BATCH_NUM]          INT             NULL,
    [POS_SESSIONID]           NVARCHAR (400)  NULL,
    [POS_TXID]                NVARCHAR (400)  NULL,
    [POS_TX_LINE]             DECIMAL (18, 4) NULL,
    [PREV_CREDITS_ACT]        DECIMAL (18, 4) NULL,
    [PRIMARY_PLAN_ID]         DECIMAL (18, 4) NULL,
    [PRIM_FEE_SCHED_ID]       DECIMAL (18, 4) NULL,
    [PROCEDURE_DESC]          NVARCHAR (400)  NULL,
    [PROC_ID]                 DECIMAL (18, 4) NULL,
    [PROC_MPI_ID]             NVARCHAR (400)  NULL,
    [QUANTITY]                DECIMAL (18, 4) NULL,
    [QUICK_PMT_TYPE_CODE]     INT             NULL,
    [RECONCILIATION_NUM]      NVARCHAR (400)  NULL,
    [REFERENCE_NUM]           NVARCHAR (400)  NULL,
    [REFUND_PLAN_ID]          DECIMAL (18, 4) NULL,
    [RELATED_HTR_ID]          DECIMAL (18, 4) NULL,
    [REMIT_CODES]             NVARCHAR (400)  NULL,
    [RESEARCH_STUDY_ID]       NVARCHAR (400)  NULL,
    [REVENUE_LOC_ID]          DECIMAL (18, 4) NULL,
    [RFND_AP_DATE]            DATETIME2 (7)   NULL,
    [RFND_AP_STATUS_CODE]     INT             NULL,
    [RFND_COVERAGE_ID]        DECIMAL (18, 4) NULL,
    [RFND_CUST_PAYEE_CODE]    NVARCHAR (400)  NULL,
    [RFND_GUAR_ID]            DECIMAL (18, 4) NULL,
    [RFND_PATIENT_ID]         NVARCHAR (400)  NULL,
    [RFND_SND_TO_CODE]        INT             NULL,
    [RSH_CHG_ORIG_HAR_ID]     DECIMAL (18, 4) NULL,
    [RVU]                     DECIMAL (18, 4) NULL,
    [RVU_MLPRACT]             DECIMAL (18, 4) NULL,
    [RVU_OVERHEAD]            DECIMAL (18, 4) NULL,
    [RVU_WORK]                DECIMAL (18, 4) NULL,
    [SERVICE_AREA_ID]         DECIMAL (18, 4) NULL,
    [SERVICE_DATE]            DATETIME2 (7)   NULL,
    [SESSION_NUMBER]          INT             NULL,
    [SHOW_HCPCS_ONUB_FLAG]    NVARCHAR (400)  NULL,
    [START_DATE_TIME]         DATETIME2 (7)   NULL,
    [STATE_CODE]              NVARCHAR (400)  NULL,
    [STOP_DATE_TIME]          DATETIME2 (7)   NULL,
    [SUP_ID]                  NVARCHAR (400)  NULL,
    [TEMP_TX_ID]              DECIMAL (18, 4) NULL,
    [TOTAL_CHARGES_ACT]       DECIMAL (18, 4) NULL,
    [TX_AMOUNT]               DECIMAL (18, 4) NULL,
    [TX_BATCH_NUM]            INT             NULL,
    [TX_COMMENT]              NVARCHAR (400)  NULL,
    [TX_FILED_TIME]           DATETIME2 (7)   NULL,
    [TX_ID]                   DECIMAL (18, 4) NULL,
    [TX_NUM_IN_HOSPACCT]      INT             NULL,
    [TX_POST_DATE]            DATETIME2 (7)   NULL,
    [TX_SOURCE_HA_CODE]       INT             NULL,
    [TX_TYPE_HA_CODE]         INT             NULL,
    [TYPE_OF_SVC_HA_CODE]     INT             NULL,
    [UB_REV_CODE_ID]          DECIMAL (18, 4) NULL,
    [USER_ID]                 NVARCHAR (400)  NULL,
    [WORKSTATION_ID]          NVARCHAR (400)  NULL,
    [XFER_LIAB_ADJ_FLAG]      NVARCHAR (400)  NULL,
    [_SURROGATEKEY]           BIGINT          NULL
);


GO

