CREATE TABLE [dbo].[HOSPITAL_ENCOUNTERS] (
    [ACCOMMODATION_CODE]       NVARCHAR (400)  NULL,
    [ACCOM_REASON_CODE]        INT             NULL,
    [ACTL_DELIVRY_METH_CODE]   NVARCHAR (400)  NULL,
    [ACUITY_LEVEL_CODE]        NVARCHAR (400)  NULL,
    [ADMISSION_PROV_ID]        NVARCHAR (400)  NULL,
    [ADMIT_ADDR_ID]            NVARCHAR (400)  NULL,
    [ADMIT_CATEGORY_CODE]      INT             NULL,
    [ADMIT_CONF_STAT_CODE]     INT             NULL,
    [ADMIT_PROV_TEXT]          NVARCHAR (400)  NULL,
    [ADMIT_SOURCE_CODE]        NVARCHAR (400)  NULL,
    [ADM_EVENT_ID]             DECIMAL (18, 4) NULL,
    [ADOPTION_CASE_FLAG]       NVARCHAR (400)  NULL,
    [ADT_ARRIVAL_STS_CODE]     INT             NULL,
    [ADT_ARRIVAL_TIME]         DATETIME2 (7)   NULL,
    [ADT_ATHCRT_STAT_CODE]     INT             NULL,
    [ADT_BILLING_TYPE_CODE]    INT             NULL,
    [ADT_CONTACT]              INT             NULL,
    [ADT_INITIAL]              NVARCHAR (400)  NULL,
    [ADT_LAST_RVW_DT]          DATETIME2 (7)   NULL,
    [ADT_NEXT_RVW_DT]          DATETIME2 (7)   NULL,
    [ADT_PATIENT_CLASS_CODE]   NVARCHAR (400)  NULL,
    [ADT_PATIENT_STAT_CODE]    INT             NULL,
    [ADT_SERVICE_AREA_ID]      DECIMAL (18, 4) NULL,
    [AMBULANCE_CODE_CODE]      INT             NULL,
    [ATTEND_PROV_TEXT]         NVARCHAR (400)  NULL,
    [BED_ID]                   NVARCHAR (400)  NULL,
    [BELONG_CLAIM_NO]          NVARCHAR (400)  NULL,
    [BELONG_LOCATION]          NVARCHAR (400)  NULL,
    [BELONG_RECV_PERS]         NVARCHAR (400)  NULL,
    [BELONG_RECV_TIME]         DATETIME2 (7)   NULL,
    [BELONG_REL_DATE]          DATETIME2 (7)   NULL,
    [BELONG_REL_PERS]          NVARCHAR (400)  NULL,
    [BELONG_STORE_LOC_CODE]    INT             NULL,
    [BILL_ATTEND_PROV_ID]      NVARCHAR (400)  NULL,
    [BILL_NUM]                 NVARCHAR (400)  NULL,
    [BILL_NUM_TYPE_CODE]       INT             NULL,
    [CANCEL_USER_ID]           NVARCHAR (400)  NULL,
    [CHIEF_COMPLAINT_CODE]     NVARCHAR (400)  NULL,
    [CM_CT_OWNER_ID]           NVARCHAR (400)  NULL,
    [CONTACT_DATE]             DATETIME2 (7)   NULL,
    [COPY_TO_PCP_FLAG]         NVARCHAR (400)  NULL,
    [DELIVERY_TYPE_CODE]       NVARCHAR (400)  NULL,
    [DEPARTMENT_ID]            DECIMAL (18, 4) NULL,
    [DISCHARGE_CAT_CODE]       INT             NULL,
    [DISCHARGE_PROV_ID]        NVARCHAR (400)  NULL,
    [DISCH_CODE_CODE]          NVARCHAR (400)  NULL,
    [DISCH_CONF_STAT_CODE]     INT             NULL,
    [DISCH_DEST_CODE]          NVARCHAR (400)  NULL,
    [DISCH_DISP_CODE]          NVARCHAR (400)  NULL,
    [DIS_EVENT_ID]             DECIMAL (18, 4) NULL,
    [EDDISP_EDIT_INST]         DATETIME2 (7)   NULL,
    [EDDISP_EDIT_USER_ID]      NVARCHAR (400)  NULL,
    [ED_AREA_OF_CARE_ID]       DECIMAL (18, 4) NULL,
    [ED_DEPARTURE_TIME]        DATETIME2 (7)   NULL,
    [ED_DISPOSITION_CODE]      NVARCHAR (400)  NULL,
    [ED_DISP_TIME]             DATETIME2 (7)   NULL,
    [ED_EPISODE_ID]            DECIMAL (18, 4) NULL,
    [ED_FU_EDIT_INST]          DATETIME2 (7)   NULL,
    [ED_FU_EDIT_USER_ID]       NVARCHAR (400)  NULL,
    [EMER_ADM_DATE]            DATETIME2 (7)   NULL,
    [EMER_ADM_EVENT_ID]        DECIMAL (18, 4) NULL,
    [ENCOUNTER_ID]             DECIMAL (18, 4) NULL,
    [ER_BADGE_NUMBER]          NVARCHAR (400)  NULL,
    [ER_INJURY]                NVARCHAR (400)  NULL,
    [EXP_ADMISSION_TIME]       DATETIME2 (7)   NULL,
    [EXP_DISCHARGE_DATE]       DATETIME2 (7)   NULL,
    [EXP_DISCHARGE_TIME]       DATETIME2 (7)   NULL,
    [EXP_LEN_OF_STAY]          INT             NULL,
    [FOLLOWUP_PROV_ID]         NVARCHAR (400)  NULL,
    [HOSPIST_NEEDED_FLAG]      NVARCHAR (400)  NULL,
    [HOSPITAL_ACCOUNT_ID]      DECIMAL (18, 4) NULL,
    [HOSPITAL_AREA_ID]         DECIMAL (18, 4) NULL,
    [HOSP_ADMSN_TIME]          DATETIME2 (7)   NULL,
    [HOSP_ADMSN_TYPE_CODE]     NVARCHAR (400)  NULL,
    [HOSP_DISCH_TIME]          DATETIME2 (7)   NULL,
    [HOSP_SERV_CODE]           NVARCHAR (400)  NULL,
    [HOV_CONF_STATUS_CODE]     INT             NULL,
    [INPATIENT_DATA_ID]        NVARCHAR (400)  NULL,
    [INP_ADM_DATE]             DATETIME2 (7)   NULL,
    [INP_ADM_EVENT_DATE]       DATETIME2 (7)   NULL,
    [INP_ADM_EVENT_ID]         DECIMAL (18, 4) NULL,
    [INP_DWNGRD_DATE]          DATETIME2 (7)   NULL,
    [INP_DWNGRD_EVNT_DT]       DATETIME2 (7)   NULL,
    [INP_DWNGRD_EVNT_ID]       DECIMAL (18, 4) NULL,
    [INSTANT_OF_ENTRY_TM]      DATETIME2 (7)   NULL,
    [IP_EPISODE_ID]            DECIMAL (18, 4) NULL,
    [LABOR_ACT_BIRTH_CODE]     INT             NULL,
    [LABOR_FEED_TYPE_CODE]     INT             NULL,
    [LABOR_STATUS_CODE]        INT             NULL,
    [LEVEL_OF_CARE_CODE]       NVARCHAR (400)  NULL,
    [MEANS_OF_ARRV_CODE]       NVARCHAR (400)  NULL,
    [MEANS_OF_DEPART_CODE]     INT             NULL,
    [MSE_DATE]                 DATETIME2 (7)   NULL,
    [MU_HOSP_ADMSN_TIME]       DATETIME2 (7)   NULL,
    [NEED_FIN_CLR_FLAG]        NVARCHAR (400)  NULL,
    [OB_LD_LABORING_FLAG]      NVARCHAR (400)  NULL,
    [OB_LD_LABOR_TM]           DATETIME2 (7)   NULL,
    [OP_ADM_DATE]              DATETIME2 (7)   NULL,
    [OP_ADM_EVENT_ID]          DECIMAL (18, 4) NULL,
    [OSHPD_ADMSN_SRC_CODE]     INT             NULL,
    [OSHPD_LICENSURE_CODE]     INT             NULL,
    [OSHPD_ROUTE_CODE]         INT             NULL,
    [PATIENT_CONTACT_MPI_NO]   NVARCHAR (400)  NULL,
    [PATIENT_ENC_DATE_REAL]    FLOAT (53)      NULL,
    [PATIENT_ESCORTED_BY_CODE] INT             NULL,
    [PATIENT_ID]               NVARCHAR (400)  NULL,
    [PENDING_DISCH_TIME]       DATETIME2 (7)   NULL,
    [PREADM_UNDO_RSN_CODE]     INT             NULL,
    [PRENATAL_CARE_CODE]       INT             NULL,
    [PREOP_PH_SCREEN_CODE]     INT             NULL,
    [PREOP_PRN_EVAL_CODE]      INT             NULL,
    [PREOP_TEACHING_CODE]      INT             NULL,
    [PREREG_SOURCE_CODE]       INT             NULL,
    [PROC_SERV_CODE]           INT             NULL,
    [PROV_CONT_INFO]           NVARCHAR (400)  NULL,
    [PROV_PRIM_TEXT]           NVARCHAR (400)  NULL,
    [PROV_PRIM_TEXT_PHON]      NVARCHAR (400)  NULL,
    [PVT_HOSP_ENC_CODE]        INT             NULL,
    [REFERRING_DEPT_ID]        DECIMAL (18, 4) NULL,
    [RELIG_AFFIL_FLAG]         NVARCHAR (400)  NULL,
    [RELIG_NEEDS_VISIT_CODE]   INT             NULL,
    [ROOM_ID]                  NVARCHAR (400)  NULL,
    [RSN_FOR_BED_CODE]         NVARCHAR (400)  NULL,
    [RSN_FOR_ROOM_CODE]        INT             NULL,
    [TPLNT_BILL_STAT_CODE]     INT             NULL,
    [TRANSFER_FROM_CODE]       INT             NULL,
    [TRIAGE_DATETIME]          DATETIME2 (7)   NULL,
    [TRIAGE_ID_TAG]            NVARCHAR (400)  NULL,
    [TRIAGE_ID_TAG_CMT]        NVARCHAR (400)  NULL,
    [TRIAGE_STATUS_CODE]       INT             NULL,
    [TYPE_OF_BED_CODE]         NVARCHAR (400)  NULL,
    [TYPE_OF_ROOM_CODE]        NVARCHAR (400)  NULL,
    [_SURROGATEKEY]            BIGINT          NULL
);


GO

