CREATE TABLE [dbo].[ICU_STAY_SUMMARY] (
    [ENCOUNTER_ID]      DECIMAL (18, 4) NULL,
    [ICU_STAY_END_DT]   DATETIME2 (7)   NULL,
    [ICU_STAY_START_DT] DATETIME2 (7)   NULL,
    [PATIENT_ID]        DECIMAL (18, 4) NULL
);


GO

