CREATE TABLE [dbo].[LAB_COMPONENTS] (
    [ABBREVIATION]                  NVARCHAR (400)  NULL,
    [ALLOW_DILUTION_FLAG]           NVARCHAR (400)  NULL,
    [ANTIBIOTIC_MED_ID]             DECIMAL (18, 4) NULL,
    [ANTIBIO_COST_CODE]             INT             NULL,
    [BASE_NAME]                     NVARCHAR (400)  NULL,
    [CALCULATED_LRR_FLAG]           NVARCHAR (400)  NULL,
    [CANONICAL_CONCEPT_INTERNAL_ID] DECIMAL (18, 4) NULL,
    [CM_LOG_OWNER_ID]               NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]               NVARCHAR (400)  NULL,
    [COMMON_NAME]                   NVARCHAR (400)  NULL,
    [COMPONENT_ID]                  DECIMAL (18, 4) NULL,
    [COMPONENT_SUBTYPE_CODE]        INT             NULL,
    [COMPONENT_TYPE_CODE]           INT             NULL,
    [COMP_PLATELET_ANTIGEN_CODE]    INT             NULL,
    [COMP_RBC_ANTIGEN_CODE]         INT             NULL,
    [DEFAULT_HIGH]                  NVARCHAR (400)  NULL,
    [DEFAULT_LNC_ID]                DECIMAL (18, 4) NULL,
    [DEFAULT_LOW]                   NVARCHAR (400)  NULL,
    [DFLT_HIGH_FEMALE]              NVARCHAR (400)  NULL,
    [DFLT_LOW_FEMALE]               NVARCHAR (400)  NULL,
    [DFLT_UNITS]                    NVARCHAR (400)  NULL,
    [DISPLAY_FLAG]                  NVARCHAR (400)  NULL,
    [EXCHG_COMPONENT_FLAG]          NVARCHAR (400)  NULL,
    [EXTERNAL_NAME]                 NVARCHAR (400)  NULL,
    [GRAPH_MAX]                     DECIMAL (18, 4) NULL,
    [GRAPH_MIN]                     DECIMAL (18, 4) NULL,
    [GROUP_TYPE_CODE]               INT             NULL,
    [LAB_ANTIBIOTIC_CODE]           INT             NULL,
    [LAB_CAT_DISCRIM]               NVARCHAR (400)  NULL,
    [LAB_CAT_DISPLY_CODE]           INT             NULL,
    [LAB_CAT_INI]                   NVARCHAR (400)  NULL,
    [LAB_CAT_ITEM]                  DECIMAL (18, 4) NULL,
    [LAB_DATA_TYPE_CODE]            INT             NULL,
    [LAB_DAYS_LOOKBACK]             DECIMAL (18, 4) NULL,
    [LAB_DEFINITIONS_FLAG]          NVARCHAR (400)  NULL,
    [LAB_LTGT_DISBLD_FLAG]          NVARCHAR (400)  NULL,
    [LAB_NUM_PRECISION]             DECIMAL (18, 4) NULL,
    [LAB_NUM_PRV_VALUES]            DECIMAL (18, 4) NULL,
    [LAB_OWC_USE_TYPE_CODE]         INT             NULL,
    [LAB_SUBTYPE_CODE]              INT             NULL,
    [LAB_TRUNCATE_FLAG]             NVARCHAR (400)  NULL,
    [LOINC_CODE]                    NVARCHAR (400)  NULL,
    [NAME]                          NVARCHAR (400)  NULL,
    [NHSN_CODE_ID]                  DECIMAL (18, 4) NULL,
    [QC_NUM_PRECISION]              DECIMAL (18, 4) NULL,
    [RECORD_STATE_CODE]             INT             NULL,
    [RECORD_TYPE_CODE]              INT             NULL,
    [RESULT_CHECKING_ID]            DECIMAL (18, 4) NULL,
    [STDRD_RSLT_RNG_MAX]            DECIMAL (18, 4) NULL,
    [STDRD_RSLT_RNG_MIN]            DECIMAL (18, 4) NULL,
    [STDRD_UNIT_TRG]                NVARCHAR (400)  NULL,
    [UNIT_CONCEPT_ID]               DECIMAL (18, 4) NULL,
    [_SURROGATEKEY]                 BIGINT          NULL
);


GO

