CREATE TABLE [dbo].[MED_ADMIN_RECORDS] (
    [AN_BCMA_MED_SCANCOMP_CODE]     INT             NULL,
    [BCMA_CUP_SCANCOMP_CODE]        INT             NULL,
    [BCMA_MED_SCANCOMP_CODE]        INT             NULL,
    [BCMA_PAT_SCANCOMP_CODE]        INT             NULL,
    [BCMA_PSP_SCANCOMP_CODE]        INT             NULL,
    [CHART_CORR_ID]                 DECIMAL (18, 4) NULL,
    [CLIENT_SRC_CODE]               INT             NULL,
    [CM_LOG_OWNER_ID]               NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]               NVARCHAR (400)  NULL,
    [COMMENTS]                      NVARCHAR (400)  NULL,
    [CONCENTRATION]                 NVARCHAR (400)  NULL,
    [CUP_IDENT]                     NVARCHAR (400)  NULL,
    [CUP_OVRIDE_ALERT_ID]           DECIMAL (18, 4) NULL,
    [CUP_SCANCOMP_CODE]             INT             NULL,
    [CUP_SCAN_STATUS_CODE]          INT             NULL,
    [CYCLIC_RATE_CHILD_LINE]        INT             NULL,
    [CYCLIC_RATE_PARENT_LINE]       INT             NULL,
    [DDD_VALUE]                     DECIMAL (18, 4) NULL,
    [DEVICE_ID]                     NVARCHAR (400)  NULL,
    [DEV_RECV_TIME]                 DATETIME2 (7)   NULL,
    [DOSE_UNIT_CODE]                INT             NULL,
    [DUE_ACTION_CODE]               NVARCHAR (400)  NULL,
    [DUR_BASED_CHILD_LINE]          INT             NULL,
    [DUR_BASED_PARENT_LINE]         INT             NULL,
    [DUR_BASED_PARENT_ORDER_ID]     DECIMAL (18, 4) NULL,
    [EDITED_LINE]                   INT             NULL,
    [FLO_DOC_MISSING_FLAG]          NVARCHAR (400)  NULL,
    [HOLD_DUR_DOSES]                INT             NULL,
    [HOLD_DUR_INST_DTTM]            DATETIME2 (7)   NULL,
    [HOLD_DUR_RETURN]               INT             NULL,
    [IDFY_DEV_DATA_CODE]            INT             NULL,
    [INFUSION_RATE]                 NVARCHAR (400)  NULL,
    [LINE]                          INT             NULL,
    [MAR_ACTION_CODE]               NVARCHAR (400)  NULL,
    [MAR_ADMIN_DEPT_ID]             DECIMAL (18, 4) NULL,
    [MAR_BILLING_PROV_ID]           NVARCHAR (400)  NULL,
    [MAR_BLOOD_INFO_LN]             INT             NULL,
    [MAR_COSIGN_COMPL_FLAG]         NVARCHAR (400)  NULL,
    [MAR_DOC_USER_ID]               NVARCHAR (400)  NULL,
    [MAR_DUAL_SIGN_SOURCE_CODE]     INT             NULL,
    [MAR_DURATION]                  NVARCHAR (400)  NULL,
    [MAR_DURATION_UNIT_CODE]        INT             NULL,
    [MAR_ENC_ENC]                   DECIMAL (18, 4) NULL,
    [MAR_IMM_LINK_ID]               DECIMAL (18, 4) NULL,
    [MAR_INF_RATE_UNIT_CODE]        INT             NULL,
    [MAR_ORD_CONTACT_DATE_REAL]     FLOAT (53)      NULL,
    [MAR_ORD_DAT]                   DECIMAL (18, 4) NULL,
    [MAR_ORIG_DUE_TM]               DATETIME2 (7)   NULL,
    [MAR_ORIG_DUE_UTC_DTTM]         DATETIME2 (7)   NULL,
    [MAR_OVRD_LNK_USR_ID]           NVARCHAR (400)  NULL,
    [MAR_PEND_SECOND_USER_ID]       NVARCHAR (400)  NULL,
    [MAR_PEND_USER_ID]              NVARCHAR (400)  NULL,
    [MAR_PSP_IDENT]                 NVARCHAR (400)  NULL,
    [MAR_SCHD_DTTM]                 DATETIME2 (7)   NULL,
    [MAR_TIME_SOURCE_CODE]          INT             NULL,
    [MAR_UNIT_NUM]                  NVARCHAR (400)  NULL,
    [MED_OVERRIDE_COUNT]            INT             NULL,
    [MED_OVRIDE_ALERT_ID]           DECIMAL (18, 4) NULL,
    [MED_SCANCOMP_CODE]             INT             NULL,
    [MORPHINE_EQUIV_MG_DOSE]        DECIMAL (18, 4) NULL,
    [MORPHINE_EQUIV_MG_PER_HR_RATE] DECIMAL (18, 4) NULL,
    [MULTILINE_SIG_PART]            NVARCHAR (400)  NULL,
    [MULTILINE_SIG_PERIOD]          NVARCHAR (400)  NULL,
    [ORDER_MED_ID]                  DECIMAL (18, 4) NULL,
    [ORIGINAL_AMOUNT]               NVARCHAR (400)  NULL,
    [ORIGINAL_UNIT_CODE]            INT             NULL,
    [OVRD_LINK_STATUS_CODE]         INT             NULL,
    [PATIENT_OVERRIDE_COUNT]        INT             NULL,
    [PATIENT_OVRIDE_ALERT_ID]       DECIMAL (18, 4) NULL,
    [PATIENT_SCANCOMP_CODE]         INT             NULL,
    [PATIENT_SUPPLIED_FLAG]         NVARCHAR (400)  NULL,
    [PENDED_DUE_ACTION_CODE]        NVARCHAR (400)  NULL,
    [PENDING_TYPE_CODE]             INT             NULL,
    [PSP_OVRIDE_ALERT_ID]           DECIMAL (18, 4) NULL,
    [PSP_SCANCOMP_CODE]             INT             NULL,
    [REASON_CODE]                   INT             NULL,
    [REQ_FLO_REASON_CODE]           INT             NULL,
    [ROUTE_CODE]                    INT             NULL,
    [SAVED_TIME]                    DATETIME2 (7)   NULL,
    [SAVED_UTC_DTTM]                DATETIME2 (7)   NULL,
    [SCAN_MODE_FLAG]                NVARCHAR (400)  NULL,
    [SCHEDULED_AMOUNT]              NVARCHAR (400)  NULL,
    [SCHEDULED_AMOUNT_UNIT_CODE]    INT             NULL,
    [SCHEDULED_DOSE]                NVARCHAR (400)  NULL,
    [SCHEDULED_DOSE_UNIT_CODE]      INT             NULL,
    [SCHEDULED_TIME]                DATETIME2 (7)   NULL,
    [SEC_USER_ID]                   NVARCHAR (400)  NULL,
    [SIG]                           NVARCHAR (400)  NULL,
    [SITE_CODE]                     NVARCHAR (400)  NULL,
    [SUBSEQUENT_CHILDREN]           INT             NULL,
    [SUBSEQUENT_INFO_DAT]           INT             NULL,
    [SUBSEQUENT_PARENT]             INT             NULL,
    [TAKEN_TIME]                    DATETIME2 (7)   NULL,
    [TAKEN_UTC_DTTM]                DATETIME2 (7)   NULL,
    [TCI_CONCENTRATION]             NVARCHAR (400)  NULL,
    [TCI_CONCENTRATION_UNIT_CODE]   INT             NULL,
    [TCI_MODEL_CODE]                INT             NULL,
    [TCI_TARGET_CODE]               INT             NULL,
    [USER_ID]                       NVARCHAR (400)  NULL,
    [WAS_TIMELY_ADMIN_CODE]         INT             NULL,
    [_SURROGATEKEY]                 BIGINT          NULL
);


GO

