CREATE TABLE [dbo].[ORDER_TRACKING_METRICS] (
    [ACKNOWLEDGE_DTTM]          DATETIME2 (7)   NULL,
    [ACTIVE_ORDER_CODE]         INT             NULL,
    [AUTH_PROV_ID]              NVARCHAR (400)  NULL,
    [CANC_DEPT_OVRIDE_FLAG]     NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]           NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]           NVARCHAR (400)  NULL,
    [CPOE_FLAG]                 NVARCHAR (400)  NULL,
    [CSGN_TURNAROUND_SEC]       INT             NULL,
    [DEST_DEPT_OVRIDE_FLAG]     NVARCHAR (400)  NULL,
    [DISCONTINUE_MODE]          NVARCHAR (400)  NULL,
    [DISCON_LOC_DTTM]           DATETIME2 (7)   NULL,
    [DISPLAY_NAME]              NVARCHAR (400)  NULL,
    [DSC_COS_MSGSENT_FLAG]      NVARCHAR (400)  NULL,
    [DSC_VRB_MSGSENT_FLAG]      NVARCHAR (400)  NULL,
    [ENCOUNTER_ID]              DECIMAL (18, 4) NULL,
    [FIRST_DISPENSE_CDR]        FLOAT (53)      NULL,
    [FIRST_FINAL_LOC_DTTM]      DATETIME2 (7)   NULL,
    [FIRST_VERIFY_CDR]          FLOAT (53)      NULL,
    [LGQ_ORDERSET_ID]           DECIMAL (18, 4) NULL,
    [MODIFIED_FLAG]             NVARCHAR (400)  NULL,
    [MU_CPOE_FLAG]              NVARCHAR (400)  NULL,
    [ORDERING_PROV_ID]          NVARCHAR (400)  NULL,
    [ORDERING_USER_ID]          NVARCHAR (400)  NULL,
    [ORDER_DESC]                NVARCHAR (400)  NULL,
    [ORDER_DTTM]                DATETIME2 (7)   NULL,
    [ORDER_ID]                  DECIMAL (18, 4) NULL,
    [ORDER_MODE]                NVARCHAR (400)  NULL,
    [ORDER_SOURCE_CODE]         INT             NULL,
    [ORDER_STATUS_CODE]         INT             NULL,
    [ORDER_TYPE_CODE]           INT             NULL,
    [ORD_COS_MSGSENT_FLAG]      NVARCHAR (400)  NULL,
    [ORD_VRB_MSGSENT_FLAG]      NVARCHAR (400)  NULL,
    [ORD_WORKSTATION_ID]        NVARCHAR (400)  NULL,
    [ORIGINAL_SESSIONKEY]       NVARCHAR (400)  NULL,
    [ORIG_AUTH_PROV_ID]         NVARCHAR (400)  NULL,
    [ORIG_ORD_PROV_ID]          NVARCHAR (400)  NULL,
    [PARENT_CE_ORDER_ID]        DECIMAL (18, 4) NULL,
    [PATIENT_ID]                NVARCHAR (400)  NULL,
    [PATIENT_LOC_ID]            DECIMAL (18, 4) NULL,
    [PREFERENCE_LIST_TYPE_CODE] NVARCHAR (400)  NULL,
    [PRL_ORDERSET_ID]           DECIMAL (18, 4) NULL,
    [REORDERED_FLAG]            NVARCHAR (400)  NULL,
    [SESSION_KEY]               NVARCHAR (400)  NULL,
    [SPECIMEN_RECV_DATE]        DATETIME2 (7)   NULL,
    [USER_OVERRIDE_FLAG]        NVARCHAR (400)  NULL,
    [_SURROGATEKEY]             BIGINT          NULL
);


GO

