CREATE TABLE [dbo].[PATIENT_ENCOUNTERS] (
    [ACCOUNT_ID]               DECIMAL (18, 4) NULL,
    [ACCREDITATION_CODE]       INT             NULL,
    [ADM_FOR_SURG_FLAG]        NVARCHAR (400)  NULL,
    [AGE]                      FLOAT (53)      NULL,
    [APPT_BLOCK_CODE]          NVARCHAR (400)  NULL,
    [APPT_CANCEL_DATE]         DATETIME2 (7)   NULL,
    [APPT_CANC_DTTM]           DATETIME2 (7)   NULL,
    [APPT_CANC_USER_ID]        NVARCHAR (400)  NULL,
    [APPT_CANC_UTC_DTTM]       DATETIME2 (7)   NULL,
    [APPT_CONF_INST]           DATETIME2 (7)   NULL,
    [APPT_CONF_PERS]           NVARCHAR (400)  NULL,
    [APPT_CONF_STAT_CODE]      INT             NULL,
    [APPT_CONF_USER_ID]        NVARCHAR (400)  NULL,
    [APPT_ENTRY_USER_ID]       NVARCHAR (400)  NULL,
    [APPT_LENGTH]              INT             NULL,
    [APPT_MADE_DATE]           DATETIME2 (7)   NULL,
    [APPT_PRC_ID]              NVARCHAR (400)  NULL,
    [APPT_QNR_ANS_ID]          NVARCHAR (400)  NULL,
    [APPT_SERIAL_NO]           DECIMAL (18, 4) NULL,
    [APPT_STATUS_CODE]         INT             NULL,
    [APPT_TARGET_DATE]         DATETIME2 (7)   NULL,
    [APPT_TIME]                DATETIME2 (7)   NULL,
    [ARVL_LST_DL_TIME]         DATETIME2 (7)   NULL,
    [ARVL_LST_DL_USR_ID]       NVARCHAR (400)  NULL,
    [AR_EPISODE_ID]            NVARCHAR (400)  NULL,
    [ASGND_INTERP_TYPE_CODE]   INT             NULL,
    [ATTND_PROV_ID]            NVARCHAR (400)  NULL,
    [AVS_FIRST_USER_ID]        NVARCHAR (400)  NULL,
    [AVS_PRINT_TM]             DATETIME2 (7)   NULL,
    [BENEFIT_COMP_ID]          NVARCHAR (400)  NULL,
    [BENEFIT_PACKAGE_ID]       DECIMAL (18, 4) NULL,
    [BEN_ADJ_COPAY_AMT]        DECIMAL (18, 4) NULL,
    [BEN_ADJ_FORMULA_ID]       DECIMAL (18, 4) NULL,
    [BEN_ADJ_METHOD_CODE]      INT             NULL,
    [BEN_ADJ_TABLE_ID]         DECIMAL (18, 4) NULL,
    [BEN_ENG_SP_AMT]           DECIMAL (18, 4) NULL,
    [BMI]                      DECIMAL (18, 4) NULL,
    [BP_DIASTOLIC]             FLOAT (53)      NULL,
    [BP_SYSTOLIC]              FLOAT (53)      NULL,
    [BSA]                      DECIMAL (18, 4) NULL,
    [CALCULATED_ENC_STAT_CODE] INT             NULL,
    [CANCEL_REASON_CMT]        NVARCHAR (400)  NULL,
    [CANCEL_REASON_CODE]       INT             NULL,
    [CERTIFICATION_CODE]       INT             NULL,
    [CHARGE_SLIP_NUMBER]       NVARCHAR (400)  NULL,
    [CHECKIN_TIME]             DATETIME2 (7)   NULL,
    [CHECKIN_USER_ID]          NVARCHAR (400)  NULL,
    [CHECKOUT_TIME]            DATETIME2 (7)   NULL,
    [CHECK_IN_KIOSK_ID]        NVARCHAR (400)  NULL,
    [CHKIN_INDICATOR_CODE]     INT             NULL,
    [CHKIN_INDICATOR_DT]       DATETIME2 (7)   NULL,
    [CLAIM_ID]                 DECIMAL (18, 4) NULL,
    [CM_CT_OWNER_ID]           NVARCHAR (400)  NULL,
    [CONSENT_TYPE_CODE]        INT             NULL,
    [CONTACT_COMMENT]          NVARCHAR (400)  NULL,
    [CONTACT_DATE]             DATETIME2 (7)   NULL,
    [COPAY_COLLECTED]          DECIMAL (18, 4) NULL,
    [COPAY_DUE]                DECIMAL (18, 4) NULL,
    [COPAY_PD_THRU]            INT             NULL,
    [COPAY_PMT_EXPL_CODE]      INT             NULL,
    [COPAY_REF_NUM]            NVARCHAR (400)  NULL,
    [COPAY_SOURCE_CODE]        INT             NULL,
    [COPAY_TYPE_CODE]          INT             NULL,
    [COVERAGE_ID]              DECIMAL (18, 4) NULL,
    [DATA_ENTRY_PERSON]        NVARCHAR (400)  NULL,
    [DEPARTMENT_ID]            DECIMAL (18, 4) NULL,
    [DISCHARGE_DATE_DT]        DATETIME2 (7)   NULL,
    [DOWNTIME_ENC]             DECIMAL (18, 4) NULL,
    [ED_ARRIVAL_KIOSK_ID]      NVARCHAR (400)  NULL,
    [EFFECTIVE_DATE_DT]        DATETIME2 (7)   NULL,
    [EFFECTIVE_DATE_DTTM]      DATETIME2 (7)   NULL,
    [EFFECTIVE_DEPT_ID]        DECIMAL (18, 4) NULL,
    [ENCOUNTER_ID]             DECIMAL (18, 4) NULL,
    [ENC_CLOSED_FLAG]          NVARCHAR (400)  NULL,
    [ENC_CLOSED_USER_ID]       NVARCHAR (400)  NULL,
    [ENC_CLOSE_DATE]           DATETIME2 (7)   NULL,
    [ENC_CLOSE_TIME]           DATETIME2 (7)   NULL,
    [ENC_CREATE_USER_ID]       NVARCHAR (400)  NULL,
    [ENC_INSTANT]              DATETIME2 (7)   NULL,
    [ENC_MED_FRZ_RSN_CODE]     INT             NULL,
    [ENC_TYPE_CODE]            NVARCHAR (400)  NULL,
    [ENC_TYPE_TITLE]           NVARCHAR (400)  NULL,
    [ENTITY_CODE]              INT             NULL,
    [ENTRY_TIME]               DATETIME2 (7)   NULL,
    [ES_ORDER_STATUS_CODE]     INT             NULL,
    [EXTERNAL_VISIT_ID]        NVARCHAR (400)  NULL,
    [FIN_CLASS_CODE]           NVARCHAR (400)  NULL,
    [HEAD_CINEW_UNITMFERENCE]  FLOAT (53)      NULL,
    [HEIGHT]                   NVARCHAR (400)  NULL,
    [HOSPITAL_ACCOUNT_ID]      DECIMAL (18, 4) NULL,
    [HOSP_ADMSN_TIME]          DATETIME2 (7)   NULL,
    [HOSP_ADMSN_TYPE_CODE]     NVARCHAR (400)  NULL,
    [HOSP_DISCHRG_TIME]        DATETIME2 (7)   NULL,
    [HOSP_LICENSE_CODE]        INT             NULL,
    [INPATIENT_DATA_ID]        NVARCHAR (400)  NULL,
    [INTERPRETER_NAME]         NVARCHAR (400)  NULL,
    [INTERPRETER_NEED_FLAG]    NVARCHAR (400)  NULL,
    [INTERPRETER_VEND_CODE]    INT             NULL,
    [INTRP_ASSIGNMENT_CODE]    INT             NULL,
    [IP_EPISODE_ID]            DECIMAL (18, 4) NULL,
    [IS_WALK_IN_FLAG]          NVARCHAR (400)  NULL,
    [LMP_DATE]                 DATETIME2 (7)   NULL,
    [LMP_OTHER_CODE]           INT             NULL,
    [LOS_MODIFIER1_ID]         NVARCHAR (400)  NULL,
    [LOS_MODIFIER2_ID]         NVARCHAR (400)  NULL,
    [LOS_MODIFIER3_ID]         NVARCHAR (400)  NULL,
    [LOS_MODIFIER4_ID]         NVARCHAR (400)  NULL,
    [LOS_PRIME_PROC_ID]        DECIMAL (18, 4) NULL,
    [LOS_PROC_CODE]            NVARCHAR (400)  NULL,
    [NONCVRED_SERVICE_FLAG]    NVARCHAR (400)  NULL,
    [ORDERING_PROV_ID]         NVARCHAR (400)  NULL,
    [ORDERING_PROV_TEXT]       NVARCHAR (400)  NULL,
    [OUTGOING_CALL_FLAG]       NVARCHAR (400)  NULL,
    [PATIENT_ENC_DATE_REAL]    FLOAT (53)      NULL,
    [PATIENT_ID]               NVARCHAR (400)  NULL,
    [PCP_PROV_ID]              NVARCHAR (400)  NULL,
    [PHONE_REM_STAT_CODE]      INT             NULL,
    [PHON_CALL_FLAG]           NVARCHAR (400)  NULL,
    [PHON_NUM_APPT]            NVARCHAR (400)  NULL,
    [PRIMARY_LOC_ID]           DECIMAL (18, 4) NULL,
    [PULSE]                    INT             NULL,
    [REFERRAL_ID]              DECIMAL (18, 4) NULL,
    [REFERRAL_REQ_FLAG]        NVARCHAR (400)  NULL,
    [REFERRAL_SOURCE_ID]       NVARCHAR (400)  NULL,
    [RESPIRATIONS]             INT             NULL,
    [ROUTE_SUM_PRNT_FLAG]      NVARCHAR (400)  NULL,
    [SERVICE_AREA_ID]          DECIMAL (18, 4) NULL,
    [SIGN_IN_TIME]             DATETIME2 (7)   NULL,
    [SIGN_IN_USER_ID]          NVARCHAR (400)  NULL,
    [SURGICAL_SVC_CODE]        NVARCHAR (400)  NULL,
    [TEMPERATURE]              FLOAT (53)      NULL,
    [TOBACCO_USE_VRFY_FLAG]    NVARCHAR (400)  NULL,
    [UPDATE_DATE]              DATETIME2 (7)   NULL,
    [VISIT_EPM_ID]             DECIMAL (18, 4) NULL,
    [VISIT_EPP_ID]             DECIMAL (18, 4) NULL,
    [VISIT_FC]                 NVARCHAR (400)  NULL,
    [VISIT_PROV_ID]            NVARCHAR (400)  NULL,
    [VISIT_PROV_TITLE]         NVARCHAR (400)  NULL,
    [VST_SPECIAL_NEEDS_CODE]   INT             NULL,
    [WC_TPL_VISIT_CMT]         NVARCHAR (400)  NULL,
    [WC_TPL_VISIT_CODE]        INT             NULL,
    [WEIGHT]                   FLOAT (53)      NULL,
    [_SURROGATEKEY]            BIGINT          NULL
);


GO

