CREATE TABLE [dbo].[PATIENTS] (
    [ADD_LINE_1]               NVARCHAR (400)  NULL,
    [ADD_LINE_2]               NVARCHAR (400)  NULL,
    [ADV_DIRECTIVE_DATE]       DATETIME2 (7)   NULL,
    [ADV_DIRECTIVE_FLAG]       NVARCHAR (400)  NULL,
    [ALRGY_UPD_DATE]           DATETIME2 (7)   NULL,
    [ALRGY_UPD_USER_ID]        NVARCHAR (400)  NULL,
    [BIRTH_DATE]               DATETIME2 (7)   NULL,
    [BIRTH_LOC_ID]             DECIMAL (18, 4) NULL,
    [BIRTH_STATUS_CODE]        INT             NULL,
    [BIRTH_WRIST_BAND]         NVARCHAR (400)  NULL,
    [CASE_SPVSR_USER_ID]       NVARCHAR (400)  NULL,
    [CITY]                     NVARCHAR (400)  NULL,
    [CLAIM_ALERT_CODE]         INT             NULL,
    [CLINICAL_PAT_YN]          NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]          NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]          NVARCHAR (400)  NULL,
    [COMM_PREF_LTR_CODE]       INT             NULL,
    [COUNTRY_CODE]             NVARCHAR (400)  NULL,
    [COUNTRY_OF_ORIG_CODE]     NVARCHAR (400)  NULL,
    [COUNTY_CODE]              NVARCHAR (400)  NULL,
    [CREATE_USER_ID]           NVARCHAR (400)  NULL,
    [CUR_CHART_LOC_CODE]       INT             NULL,
    [CUR_PCP_PROV_ID]          NVARCHAR (400)  NULL,
    [CUR_PRIM_LOC_ID]          DECIMAL (18, 4) NULL,
    [DEATH_DATE]               DATETIME2 (7)   NULL,
    [DEF_FIN_CLASS_CODE]       NVARCHAR (400)  NULL,
    [DISTRICT_CODE]            INT             NULL,
    [EDD_CMT]                  NVARCHAR (400)  NULL,
    [EDD_DT]                   DATETIME2 (7)   NULL,
    [EDD_ENTERED_DT]           DATETIME2 (7)   NULL,
    [EMAIL_ADDRESS]            NVARCHAR (400)  NULL,
    [EMPLOYER_ID]              NVARCHAR (400)  NULL,
    [EMPR_ID_CMT]              NVARCHAR (400)  NULL,
    [EMPY_STATUS_CODE]         INT             NULL,
    [EOB_FLAG_FLAG]            NVARCHAR (400)  NULL,
    [ETHNIC_GROUP_CODE]        INT             NULL,
    [FATHER_PATIENT_ID]        NVARCHAR (400)  NULL,
    [FIN_STATUS_CODE]          INT             NULL,
    [GUARDIAN_NAME]            NVARCHAR (400)  NULL,
    [HOME_PHONE]               NVARCHAR (400)  NULL,
    [HOUSE_NUM]                NVARCHAR (400)  NULL,
    [INTERNAL_PATIENT_ID]      NVARCHAR (400)  NULL,
    [INTRPTR_NEEDED_FLAG]      NVARCHAR (400)  NULL,
    [IS_MAIL_BLOCKED_FLAG]     NVARCHAR (400)  NULL,
    [IS_PHONE_REMNDR_FLAG]     NVARCHAR (400)  NULL,
    [LANGUAGE_CODE]            NVARCHAR (400)  NULL,
    [LANG_CARE_CODE]           NVARCHAR (400)  NULL,
    [LANG_WRIT_CODE]           NVARCHAR (400)  NULL,
    [LAST_MYC_ASKED_DATE]      DATETIME2 (7)   NULL,
    [LEGAL_STATUS_CODE]        INT             NULL,
    [MARITAL_STATUS_CODE]      INT             NULL,
    [MEDICAID_NUM]             NVARCHAR (400)  NULL,
    [MEDICARE_NUM]             NVARCHAR (400)  NULL,
    [MEDS_LAST_REV_ENC]        DECIMAL (18, 4) NULL,
    [MEDS_LAST_REV_TM]         DATETIME2 (7)   NULL,
    [MEDS_LST_REV_USR_ID]      NVARCHAR (400)  NULL,
    [MOTHER_PATIENT_ID]        NVARCHAR (400)  NULL,
    [ORGAN_DONOR_FLAG]         NVARCHAR (400)  NULL,
    [PATIENT_FIRST_NAME]       NVARCHAR (400)  NULL,
    [PATIENT_HAS_IOL_FLAG]     NVARCHAR (400)  NULL,
    [PATIENT_ID]               NVARCHAR (400)  NULL,
    [PATIENT_LAST_NAME]        NVARCHAR (400)  NULL,
    [PATIENT_MIDDLE_NAME]      NVARCHAR (400)  NULL,
    [PATIENT_MRN]              NVARCHAR (400)  NULL,
    [PATIENT_NAME]             NVARCHAR (400)  NULL,
    [PATIENT_NAME_SUFFIX_CODE] INT             NULL,
    [PATIENT_STATUS]           NVARCHAR (400)  NULL,
    [PATIENT_STATUS_CODE]      NVARCHAR (400)  NULL,
    [PATIENT_TITLE_CODE]       NVARCHAR (400)  NULL,
    [PCP_DON_CHART_FLAG]       NVARCHAR (400)  NULL,
    [PED_APGAR_ONE]            NVARCHAR (400)  NULL,
    [PED_APGAR_TEN]            NVARCHAR (400)  NULL,
    [PED_APGAR_TWO]            NVARCHAR (400)  NULL,
    [PED_BIRTH_HEAD_CIR]       NVARCHAR (400)  NULL,
    [PED_BIRTH_LABOR]          NVARCHAR (400)  NULL,
    [PED_BIRTH_LEN]            NVARCHAR (400)  NULL,
    [PED_BIRTH_WT]             NVARCHAR (400)  NULL,
    [PED_CESAREAN_FLAG]        NVARCHAR (400)  NULL,
    [PED_COMMENT]              NVARCHAR (400)  NULL,
    [PED_DELIVR_METH_CODE]     NVARCHAR (400)  NULL,
    [PED_DISCHRG_WT]           NVARCHAR (400)  NULL,
    [PED_GEST_AGE]             NVARCHAR (400)  NULL,
    [PED_HOSP_DAYS]            NVARCHAR (400)  NULL,
    [PED_HOSP_LOCATION]        NVARCHAR (400)  NULL,
    [PED_HOSP_NAME]            NVARCHAR (400)  NULL,
    [PED_MULTI_BIRTH_FLAG]     NVARCHAR (400)  NULL,
    [PED_MULT_BIRTH_ORD]       INT             NULL,
    [PED_MULT_BIRTH_TOT]       INT             NULL,
    [PED_NOUR_METH_CODE]       INT             NULL,
    [PERM_CHART_LOC_CODE]      INT             NULL,
    [POWER_OF_ATTRNY_DT]       DATETIME2 (7)   NULL,
    [POWER_OF_ATTRNY_FLAG]     NVARCHAR (400)  NULL,
    [PREF_CLIN_ZIP]            NVARCHAR (400)  NULL,
    [PREF_PCP_LANG_CODE]       NVARCHAR (400)  NULL,
    [PREF_PCP_SEX_CODE]        NVARCHAR (400)  NULL,
    [PREF_PCP_SPEC_CODE]       NVARCHAR (400)  NULL,
    [PRIM_CVG_ID]              DECIMAL (18, 4) NULL,
    [PRIM_EPM_ID]              DECIMAL (18, 4) NULL,
    [PRIM_EPP_ID]              DECIMAL (18, 4) NULL,
    [PRIM_FC]                  NVARCHAR (400)  NULL,
    [PROXY_NAME]               NVARCHAR (400)  NULL,
    [PROXY_PACK_FLAG]          NVARCHAR (400)  NULL,
    [PROXY_PAT_FLAG]           NVARCHAR (400)  NULL,
    [PROXY_PHONE]              NVARCHAR (400)  NULL,
    [RECORD_STATE_CODE]        INT             NULL,
    [REC_CREATE_DATE]          DATETIME2 (7)   NULL,
    [REC_CREATE_PATIENT_ID]    NVARCHAR (400)  NULL,
    [REG_DATE]                 DATETIME2 (7)   NULL,
    [REG_STATUS_CODE]          NVARCHAR (400)  NULL,
    [RELIGION_CODE]            INT             NULL,
    [RESTRICTED_FLAG]          NVARCHAR (400)  NULL,
    [SELF_EC_VERIF_DATE]       DATETIME2 (7)   NULL,
    [SELF_EC_VERIF_ST_FLAG]    NVARCHAR (400)  NULL,
    [SELF_VERIF_DATE]          DATETIME2 (7)   NULL,
    [SELF_VERIF_STATU_FLAG]    NVARCHAR (400)  NULL,
    [SEX]                      NVARCHAR (400)  NULL,
    [SEX_CODE]                 NVARCHAR (400)  NULL,
    [SPECIAL_STATUS_CODE]      INT             NULL,
    [SPECIES_CODE]             NVARCHAR (400)  NULL,
    [SSN]                      NVARCHAR (400)  NULL,
    [STATE_CODE]               NVARCHAR (400)  NULL,
    [TMP_ADDR_END_DT]          DATETIME2 (7)   NULL,
    [TMP_ADDR_LINE_1]          NVARCHAR (400)  NULL,
    [TMP_ADDR_LINE_2]          NVARCHAR (400)  NULL,
    [TMP_ADDR_START_DT]        DATETIME2 (7)   NULL,
    [TMP_CARE_OF_PERSON]       NVARCHAR (400)  NULL,
    [TMP_CITY]                 NVARCHAR (400)  NULL,
    [TMP_COUNTRY_CODE]         NVARCHAR (400)  NULL,
    [TMP_COUNTY_CODE]          NVARCHAR (400)  NULL,
    [TMP_HOME_PHONE]           NVARCHAR (400)  NULL,
    [TMP_STATE_CODE]           NVARCHAR (400)  NULL,
    [TMP_ZIP]                  NVARCHAR (400)  NULL,
    [UPDATE_DATE]              DATETIME2 (7)   NULL,
    [VETERAN_STATUS_CODE]      NVARCHAR (400)  NULL,
    [WORK_PHONE]               NVARCHAR (400)  NULL,
    [ZIP]                      NVARCHAR (400)  NULL,
    [_SURROGATEKEY]            BIGINT          NULL
);


GO

