CREATE TABLE [dbo].[PROCEDURE_ORDERS] (
    [ABNORMAL_FLAG]              NVARCHAR (400)  NULL,
    [ABN_NOTE_ID]                NVARCHAR (400)  NULL,
    [AUTHRZING_PROV_ID]          NVARCHAR (400)  NULL,
    [BILLING_PROV_ID]            NVARCHAR (400)  NULL,
    [CHNG_ORDER_PROC_ID]         DECIMAL (18, 4) NULL,
    [CHRG_DROPPED_TIME]          DATETIME2 (7)   NULL,
    [CM_LOG_OWNER_ID]            NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]            NVARCHAR (400)  NULL,
    [COSIGNED_USER_ID]           NVARCHAR (400)  NULL,
    [COSIGNER_AUTH_TIME]         DATETIME2 (7)   NULL,
    [COSIGNER_USER_ID]           NVARCHAR (400)  NULL,
    [CPT_CODE]                   NVARCHAR (400)  NULL,
    [DEPT_REF_PROV_ID]           DECIMAL (18, 4) NULL,
    [DESCRIPTION]                NVARCHAR (400)  NULL,
    [DISCRETE_INTERVAL]          NVARCHAR (400)  NULL,
    [DISPLAY_NAME]               NVARCHAR (400)  NULL,
    [DOSE]                       INT             NULL,
    [ENCOUNTER_ID]               DECIMAL (18, 4) NULL,
    [FILMS_USED]                 INT             NULL,
    [FILM_SIZE_CODE]             INT             NULL,
    [FUTURE_OR_STAND]            NVARCHAR (400)  NULL,
    [FUT_EXPECT_COMP_DT]         DATETIME2 (7)   NULL,
    [HAS_RELEASED_CHILDREN_FLAG] NVARCHAR (400)  NULL,
    [HV_HOSPITALIST_FLAG]        NVARCHAR (400)  NULL,
    [INSTANTIATED_TIME]          DATETIME2 (7)   NULL,
    [INSTNTOR_USER_ID]           NVARCHAR (400)  NULL,
    [INTERFACE_STAT_CODE]        INT             NULL,
    [INT_STUDY_CODE]             INT             NULL,
    [INT_STUDY_USER_ID]          NVARCHAR (400)  NULL,
    [IS_PENDING_ORD_FLAG]        NVARCHAR (400)  NULL,
    [LABCORP_BILL_TYPE_CODE]     NVARCHAR (400)  NULL,
    [LABCORP_CLIENT_ID]          NVARCHAR (400)  NULL,
    [LABCORP_CONTROL_NUM]        INT             NULL,
    [LAB_STATUS_CODE]            INT             NULL,
    [MODIFIER1_ID]               NVARCHAR (400)  NULL,
    [MODIFIER2_ID]               NVARCHAR (400)  NULL,
    [MODIFIER3_ID]               NVARCHAR (400)  NULL,
    [MODIFIER4_ID]               NVARCHAR (400)  NULL,
    [MRK_RSLT_MSG_IMP_FLAG]      NVARCHAR (400)  NULL,
    [NO_CHG_RSN_CODE]            INT             NULL,
    [NUMBER_OF_REPEATS]          INT             NULL,
    [ORDERING_DATE]              DATETIME2 (7)   NULL,
    [ORDERING_MODE]              NVARCHAR (400)  NULL,
    [ORDER_CLASS_CODE]           NVARCHAR (400)  NULL,
    [ORDER_INST]                 DATETIME2 (7)   NULL,
    [ORDER_PRIORITY_CODE]        INT             NULL,
    [ORDER_PROC_ID]              DECIMAL (18, 4) NULL,
    [ORDER_STATUS_CODE]          INT             NULL,
    [ORDER_TIME]                 DATETIME2 (7)   NULL,
    [ORDER_TYPE_CODE]            INT             NULL,
    [ORD_CREATR_USER_ID]         NVARCHAR (400)  NULL,
    [PANEL_PROC_ID]              DECIMAL (18, 4) NULL,
    [PATIENT_ENC_DATE_REAL]      FLOAT (53)      NULL,
    [PATIENT_ID]                 NVARCHAR (400)  NULL,
    [PROBLEM_LIST_ID]            DECIMAL (18, 4) NULL,
    [PROC_BGN_TIME]              DATETIME2 (7)   NULL,
    [PROC_CODE]                  NVARCHAR (400)  NULL,
    [PROC_DATE]                  DATETIME2 (7)   NULL,
    [PROC_ENDING_TIME]           DATETIME2 (7)   NULL,
    [PROC_END_TIME]              DATETIME2 (7)   NULL,
    [PROC_ID]                    DECIMAL (18, 4) NULL,
    [PROC_LATERALITY_CODE]       INT             NULL,
    [PROC_PAT_CLASS_CODE]        NVARCHAR (400)  NULL,
    [PROC_PERF_DEPT_ID]          DECIMAL (18, 4) NULL,
    [PROC_PERF_PROV_ID]          NVARCHAR (400)  NULL,
    [PROC_POSSIBLE_FLAG]         NVARCHAR (400)  NULL,
    [PROC_START_TIME]            DATETIME2 (7)   NULL,
    [PROV_STATUS]                NVARCHAR (400)  NULL,
    [QUANTITY]                   INT             NULL,
    [RADIOLOGY_STATUS_CODE]      INT             NULL,
    [REASON_FOR_CANC_CODE]       NVARCHAR (400)  NULL,
    [REC_ARCHIVED_FLAG]          NVARCHAR (400)  NULL,
    [REFD_TO_LOC_ID]             DECIMAL (18, 4) NULL,
    [REFD_TO_SPECLTY_CODE]       NVARCHAR (400)  NULL,
    [REFERRING_PROV_ID]          NVARCHAR (400)  NULL,
    [REQUESTED_SPEC_CODE]        NVARCHAR (400)  NULL,
    [RESULT_LAB_ID]              DECIMAL (18, 4) NULL,
    [RESULT_TIME]                DATETIME2 (7)   NULL,
    [RESULT_TYPE]                NVARCHAR (400)  NULL,
    [REVIEW_TIME]                DATETIME2 (7)   NULL,
    [RFL_CLASS_CODE]             NVARCHAR (400)  NULL,
    [RFL_EXPIRE_DT]              DATETIME2 (7)   NULL,
    [RFL_NUM_VIS]                INT             NULL,
    [RFL_PRIORITY]               NVARCHAR (400)  NULL,
    [RFL_TYPE_CODE]              NVARCHAR (400)  NULL,
    [RIS_TRANS_ID]               NVARCHAR (400)  NULL,
    [RSLTS_INTERPRETER]          NVARCHAR (400)  NULL,
    [RSN_FOR_RFL_CODE]           NVARCHAR (400)  NULL,
    [SCHED_START_TM]             DATETIME2 (7)   NULL,
    [SERVICE_AREA_ID]            DECIMAL (18, 4) NULL,
    [SESSION_KEY]                NVARCHAR (400)  NULL,
    [SPECIALTY_DEP_CODE]         NVARCHAR (400)  NULL,
    [SPECIFIED_FIRST_TM]         DATETIME2 (7)   NULL,
    [SPECIMEN_SOURCE_CODE]       INT             NULL,
    [SPECIMEN_TYPE_CODE]         INT             NULL,
    [STANDING_EXP_DATE]          DATETIME2 (7)   NULL,
    [STANDING_OCCURS]            INT             NULL,
    [STAND_INTERVAL]             NVARCHAR (400)  NULL,
    [STAND_ORIG_OCCUR]           INT             NULL,
    [TECHNOLOGIST_ID]            NVARCHAR (400)  NULL,
    [UPDATE_DATE]                DATETIME2 (7)   NULL,
    [_SURROGATEKEY]              BIGINT          NULL
);


GO

