CREATE TABLE [dbo].[PROVIDERS] (
    [ACTIVE_STATUS]             NVARCHAR (400)  NULL,
    [ACTIVE_STATUS_CODE]        INT             NULL,
    [ATTND_PRIM_PAGER]          NVARCHAR (400)  NULL,
    [BASE_COST]                 DECIMAL (18, 4) NULL,
    [BILL_PROV_FLAG]            NVARCHAR (400)  NULL,
    [BILL_UNDER_PROV_ID]        NVARCHAR (400)  NULL,
    [BIRTH_DATE]                DATETIME2 (7)   NULL,
    [CLINICAL_PROV_YN]          NVARCHAR (400)  NULL,
    [CLINICIAN_TITLE]           NVARCHAR (400)  NULL,
    [CLM_POS_REQD_FLAG]         NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]           NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]           NVARCHAR (400)  NULL,
    [COUNTRY_CODE]              NVARCHAR (400)  NULL,
    [COUNTY_CODE]               NVARCHAR (400)  NULL,
    [CTRL_SHEET_PRT_ROU]        NVARCHAR (400)  NULL,
    [DBC_EXT_POS_ID]            DECIMAL (18, 4) NULL,
    [DEA_NUMBER]                NVARCHAR (400)  NULL,
    [DEFAULT_POS_CLM_FLAG]      NVARCHAR (400)  NULL,
    [DEF_DEPARTMENT_ID]         DECIMAL (18, 4) NULL,
    [DEF_DIVISION_CODE]         NVARCHAR (400)  NULL,
    [DEF_PROVIDER_FLAG]         NVARCHAR (400)  NULL,
    [DIRECTORY_INFO]            NVARCHAR (400)  NULL,
    [DOCTORS_DEGREE]            NVARCHAR (400)  NULL,
    [EDI_CLM_ACTIVE_FLAG]       NVARCHAR (400)  NULL,
    [EMAIL]                     NVARCHAR (400)  NULL,
    [EMPLOYED_CRNA_FLAG]        NVARCHAR (400)  NULL,
    [EMP_STATUS]                NVARCHAR (400)  NULL,
    [ENC_PROV_FLAG]             NVARCHAR (400)  NULL,
    [EPRESCRIBING_FLAG]         NVARCHAR (400)  NULL,
    [EP_FLAG_FLAG]              NVARCHAR (400)  NULL,
    [EQUIP_LASTSVC_DATE]        DATETIME2 (7)   NULL,
    [EQUIP_SERVICE_DATE]        DATETIME2 (7)   NULL,
    [EXTERNAL_NAME]             NVARCHAR (400)  NULL,
    [FLASH_CARD_PRT_ROU]        NVARCHAR (400)  NULL,
    [GL_PREFIX]                 NVARCHAR (400)  NULL,
    [HOSPITALIST_FLAG]          NVARCHAR (400)  NULL,
    [INSTRUMENT_TYPE_CODE]      NVARCHAR (400)  NULL,
    [INTERNAL_PROV_ID]          NVARCHAR (400)  NULL,
    [IS_INTERPRETER_FLAG]       NVARCHAR (400)  NULL,
    [IS_PRIV_REVOKED]           NVARCHAR (400)  NULL,
    [IS_RESIDENT]               NVARCHAR (400)  NULL,
    [IS_SUP_PROV_REQ_CODE]      INT             NULL,
    [IS_VERIFIED_FLAG]          NVARCHAR (400)  NULL,
    [LAB_FAX_NUMBER]            NVARCHAR (400)  NULL,
    [LAST_RECOMMENDED_DATE]     DATETIME2 (7)   NULL,
    [MCD_PROF_CD_CODE]          INT             NULL,
    [MEDICAID_PROV_ID]          NVARCHAR (400)  NULL,
    [MEDICARE_PROV_ID]          NVARCHAR (400)  NULL,
    [MEDS_AUTH_PROV_FLAG]       NVARCHAR (400)  NULL,
    [MODALITY_FLAG]             NVARCHAR (400)  NULL,
    [MODALITY_TYPE_CODE]        INT             NULL,
    [NURSE_EMP_ID]              NVARCHAR (400)  NULL,
    [OFFICE_FAX_NUM]            NVARCHAR (400)  NULL,
    [OFFICE_PHONE_NUM]          NVARCHAR (400)  NULL,
    [OO_OFFICE_FROM_DTE]        DATETIME2 (7)   NULL,
    [OO_OFFICE_TO_DTE]          DATETIME2 (7)   NULL,
    [OP_ORD_PROV_FLAG]          NVARCHAR (400)  NULL,
    [ORDS_AUTH_PROV_FLAG]       NVARCHAR (400)  NULL,
    [OR_CHARGE_CODE_ID]         DECIMAL (18, 4) NULL,
    [OR_VLD_DT_OFST]            INT             NULL,
    [PAYEE_NUM_DEFAULT]         NVARCHAR (400)  NULL,
    [PEER_REV_LAST_DATE]        DATETIME2 (7)   NULL,
    [PHARMACIST_FLAG]           NVARCHAR (400)  NULL,
    [PIN_ID]                    NVARCHAR (400)  NULL,
    [PRACTICE_NAME_CODE]        INT             NULL,
    [PROVIDER_TYPE_CODE]        NVARCHAR (400)  NULL,
    [PROV_ABBR]                 NVARCHAR (400)  NULL,
    [PROV_ATTR_ID]              NVARCHAR (400)  NULL,
    [PROV_CLM_PROC_STA_CODE]    INT             NULL,
    [PROV_ID]                   NVARCHAR (400)  NULL,
    [PROV_NAME]                 NVARCHAR (400)  NULL,
    [PROV_PHOTO]                NVARCHAR (400)  NULL,
    [PROV_REC_STATE_CODE]       INT             NULL,
    [PROV_START_DATE]           DATETIME2 (7)   NULL,
    [PROV_TYPE]                 NVARCHAR (400)  NULL,
    [RECORD_TYPE]               INT             NULL,
    [REFERRAL_SOURCE_TYPE]      NVARCHAR (400)  NULL,
    [REFERRAL_SOURCE_TYPE_CODE] NVARCHAR (400)  NULL,
    [REFERRAL_SRCE_TYPE]        NVARCHAR (400)  NULL,
    [REFERRAL_SRCE_TYPE_CODE]   NVARCHAR (400)  NULL,
    [RES_POOL_TYPE_CODE]        INT             NULL,
    [REVENUE_DEPT_ID]           DECIMAL (18, 4) NULL,
    [RPT_GRP_EIGHT]             NVARCHAR (400)  NULL,
    [RPT_GRP_EIGHTEEN_CODE]     NVARCHAR (400)  NULL,
    [RPT_GRP_ELEVEN_CODE]       NVARCHAR (400)  NULL,
    [RPT_GRP_FIFTEEN_CODE]      NVARCHAR (400)  NULL,
    [RPT_GRP_FIVE]              NVARCHAR (400)  NULL,
    [RPT_GRP_FOUR]              NVARCHAR (400)  NULL,
    [RPT_GRP_FOURTEEN_CODE]     NVARCHAR (400)  NULL,
    [RPT_GRP_NINE]              NVARCHAR (400)  NULL,
    [RPT_GRP_NINETEEN_CODE]     NVARCHAR (400)  NULL,
    [RPT_GRP_ONE]               NVARCHAR (400)  NULL,
    [RPT_GRP_SEVEN]             NVARCHAR (400)  NULL,
    [RPT_GRP_SEVNTEEN_CODE]     NVARCHAR (400)  NULL,
    [RPT_GRP_SIX]               NVARCHAR (400)  NULL,
    [RPT_GRP_SIXTEEN_CODE]      NVARCHAR (400)  NULL,
    [RPT_GRP_TEN]               NVARCHAR (400)  NULL,
    [RPT_GRP_THIRTEEN_CODE]     NVARCHAR (400)  NULL,
    [RPT_GRP_THREE]             NVARCHAR (400)  NULL,
    [RPT_GRP_TWELVE_CODE]       NVARCHAR (400)  NULL,
    [RPT_GRP_TWENTY_CODE]       NVARCHAR (400)  NULL,
    [RPT_GRP_TWO]               NVARCHAR (400)  NULL,
    [SER_CLM_ID]                NVARCHAR (400)  NULL,
    [SER_REF_SRCE_ID]           NVARCHAR (400)  NULL,
    [SEX]                       NVARCHAR (400)  NULL,
    [SEX_CODE]                  NVARCHAR (400)  NULL,
    [SSN]                       NVARCHAR (400)  NULL,
    [STAFF_RESOURCE]            NVARCHAR (400)  NULL,
    [STAFF_RESOURCE_CODE]       INT             NULL,
    [SUPERV_POOL_ID]            NVARCHAR (400)  NULL,
    [SUPERV_POOL_NAME]          NVARCHAR (400)  NULL,
    [SUP_PROV_FLAG]             NVARCHAR (400)  NULL,
    [SUP_PROV_ID]               NVARCHAR (400)  NULL,
    [SURG_COST_TBL_ID]          DECIMAL (18, 4) NULL,
    [SURG_EQP_SVCDAT_FLAG]      NVARCHAR (400)  NULL,
    [SURG_REC_POOL_FLAG]        NVARCHAR (400)  NULL,
    [SURG_SCHED_OUT_FLAG]       NVARCHAR (400)  NULL,
    [TAKING_NEW_PAT_FLAG]       NVARCHAR (400)  NULL,
    [TAKING_WALKINS_FLAG]       NVARCHAR (400)  NULL,
    [TEAM_CODE]                 INT             NULL,
    [TEAM_LEADER_ID]            NVARCHAR (400)  NULL,
    [TRANS_INTF_USER_FLAG]      NVARCHAR (400)  NULL,
    [UPIN]                      NVARCHAR (400)  NULL,
    [USER_ID]                   NVARCHAR (400)  NULL,
    [USE_DEPT_VT_LIM_FLAG]      NVARCHAR (400)  NULL,
    [VERIFYING_PERSON_ID]       NVARCHAR (400)  NULL,
    [_SURROGATEKEY]             BIGINT          NULL
);


GO

