CREATE TABLE [dbo].[REF_DISCHARGE_DISPOSITION] (
    [ABBR]            NVARCHAR (400) NULL,
    [DISCH_DISP_CODE] NVARCHAR (400) NULL,
    [INTERNAL_ID]     NVARCHAR (400) NULL,
    [NAME]            NVARCHAR (400) NULL,
    [TITLE]           NVARCHAR (400) NULL
);


GO

