CREATE TABLE [dbo].[V_PHARMACY_DISPENSE] (
    [ACTION_ID]                     DECIMAL (18, 4) NULL,
    [BARCODE_NOT_RECOG_ALT_CNT]     INT             NULL,
    [CONTACT_DATE_REAL]             FLOAT (53)      NULL,
    [DEST_DEPARTMENT_ID]            DECIMAL (18, 4) NULL,
    [DFLT_DISP_CODE_CODE]           INT             NULL,
    [DISP_CHECK_REJECT_COMMENT]     NVARCHAR (400)  NULL,
    [DISP_CHECK_REJECT_REASON]      NVARCHAR (400)  NULL,
    [DISP_CHECK_STAT_CODE]          INT             NULL,
    [DISP_CHK_REJ_REDISP_DATE_REAL] FLOAT (53)      NULL,
    [DISP_CODE]                     NVARCHAR (400)  NULL,
    [DISP_DATE]                     DATETIME2 (7)   NULL,
    [DISP_DTTM]                     DATETIME2 (7)   NULL,
    [DISP_HOUR]                     INT             NULL,
    [DISP_PREP_ATTEMPTED_BOOL]      INT             NULL,
    [DISP_PREP_COMPLETED_BOOL]      INT             NULL,
    [DISP_PREP_DATE]                DATETIME2 (7)   NULL,
    [DISP_PREP_DTTM]                DATETIME2 (7)   NULL,
    [DISP_PREP_HOUR]                INT             NULL,
    [DISP_PREP_NEAR_MISS_BOOL]      INT             NULL,
    [DISP_PREP_NOT_ATTEMPTED_BOOL]  INT             NULL,
    [DISP_PREP_USER_ID]             NVARCHAR (400)  NULL,
    [DISP_RETURNED_FLAG]            NVARCHAR (400)  NULL,
    [DISP_TYPE_CODE]                INT             NULL,
    [DISP_USER_ID]                  NVARCHAR (400)  NULL,
    [EXP_MED_ALT_CNT]               INT             NULL,
    [GEN_DISP_TYPE_CODE]            INT             NULL,
    [INTERFACE_PREP_COMPLETED_BOOL] INT             NULL,
    [LAST_RECEIVE_ACTION_DATE_REAL] FLOAT (53)      NULL,
    [LAST_SENT_ACTION_DATE_REAL]    FLOAT (53)      NULL,
    [LOCATION_ID]                   DECIMAL (18, 4) NULL,
    [LOCATION_NAME]                 NVARCHAR (400)  NULL,
    [MANUAL_ASSOC_INGRED_CNT]       INT             NULL,
    [MEDICATION_ID]                 DECIMAL (18, 4) NULL,
    [MEDICATION_NAME]               NVARCHAR (400)  NULL,
    [NDC_MANUAL_CNT]                INT             NULL,
    [ORDER_MED_ID]                  DECIMAL (18, 4) NULL,
    [PENDING_FLAG]                  NVARCHAR (400)  NULL,
    [PHARMACY_ID]                   DECIMAL (18, 4) NULL,
    [PHARMACY_NAME]                 NVARCHAR (400)  NULL,
    [PHYSICAL_TYPE]                 NVARCHAR (400)  NULL,
    [PHYSICAL_TYPE_CODE]            INT             NULL,
    [WRONG_MED_ALT_CNT]             INT             NULL,
    [WRONG_MED_ALT_OVERRIDDEN_FLAG] NVARCHAR (400)  NULL
);


GO

