CREATE TABLE [dbo].[V_PHARMACY_ORDER] (
    [ADS_OVERRIDE_FLAG]           NVARCHAR (400)  NULL,
    [ADS_OVERRIDE_LINKED_FLAG]    NVARCHAR (400)  NULL,
    [AUTHORIZING_PROV_ID]         NVARCHAR (400)  NULL,
    [BULK_CHARGE_FLAG]            NVARCHAR (400)  NULL,
    [CONDITIONAL_FLAG]            NVARCHAR (400)  NULL,
    [DISCRETE_DOSE]               DECIMAL (18, 4) NULL,
    [DISPENSE_ROUTE_CODE]         INT             NULL,
    [DOSE_UNIT]                   NVARCHAR (400)  NULL,
    [DOSE_UNIT_CODE]              INT             NULL,
    [ENCOUNTER_ID]                DECIMAL (18, 4) NULL,
    [FIRST_ADMIN_DATE_REAL]       FLOAT (53)      NULL,
    [FIRST_ADMIN_DATE_REAL_LINE]  INT             NULL,
    [FIRST_DISPENSE_DATE_REAL]    FLOAT (53)      NULL,
    [FIRST_PEND_VERIFY_DATE_REAL] FLOAT (53)      NULL,
    [FIRST_SCHED_DUE_TIME_DTTM]   DATETIME2 (7)   NULL,
    [FIRST_VERIFY_DATE_REAL]      FLOAT (53)      NULL,
    [FIRST_VERIFY_DATE_REAL_LINE] INT             NULL,
    [FREQ_ID]                     NVARCHAR (400)  NULL,
    [FREQ_NAME]                   NVARCHAR (400)  NULL,
    [INITIATED_DTTM]              DATETIME2 (7)   NULL,
    [IS_RELEASED_FLAG]            NVARCHAR (400)  NULL,
    [IVENT_FLAG]                  NVARCHAR (400)  NULL,
    [LAST_VERIFY_DATE_REAL]       FLOAT (53)      NULL,
    [MEDICATION_ID]               DECIMAL (18, 4) NULL,
    [MEDICATION_NAME]             NVARCHAR (400)  NULL,
    [NF_POST_VERIFY_FLAG]         NVARCHAR (400)  NULL,
    [NF_PRE_VERIFY_FLAG]          NVARCHAR (400)  NULL,
    [NON_CLINICAL_OVERRIDE_FLAG]  NVARCHAR (400)  NULL,
    [ONE_STEP_MED_FLAG]           NVARCHAR (400)  NULL,
    [ON_THE_FLY_FLAG]             NVARCHAR (400)  NULL,
    [ORDERABLE_MED_ID]            DECIMAL (18, 4) NULL,
    [ORDERING_DATE]               DATETIME2 (7)   NULL,
    [ORDERING_DATE_REAL]          FLOAT (53)      NULL,
    [ORDERING_DTTM]               DATETIME2 (7)   NULL,
    [ORDERING_HOUR]               INT             NULL,
    [ORDERING_PROV_ID]            NVARCHAR (400)  NULL,
    [ORDER_DOSE]                  NVARCHAR (400)  NULL,
    [ORDER_END_DTTM]              DATETIME2 (7)   NULL,
    [ORDER_HISTORY_LINK_NM_WID]   NVARCHAR (400)  NULL,
    [ORDER_MED_ID]                DECIMAL (18, 4) NULL,
    [ORDER_PRIORITY]              NVARCHAR (400)  NULL,
    [ORDER_PRIORITY_CODE]         INT             NULL,
    [ORDER_ROUTE]                 NVARCHAR (400)  NULL,
    [ORDER_START_DTTM]            DATETIME2 (7)   NULL,
    [PATIENT_DEPT_ID]             DECIMAL (18, 4) NULL,
    [PATIENT_DEPT_NAME]           NVARCHAR (400)  NULL,
    [PATIENT_ID]                  NVARCHAR (400)  NULL,
    [PATIENT_LOCATION_ID]         DECIMAL (18, 4) NULL,
    [PATIENT_LOCATION_NAME]       NVARCHAR (400)  NULL,
    [PRN_FLAG]                    NVARCHAR (400)  NULL,
    [QUEUE_REASON]                NVARCHAR (400)  NULL,
    [RELEASING_USER_ID]           NVARCHAR (400)  NULL,
    [REPORT_DATE]                 DATETIME2 (7)   NULL,
    [RXQ_REASON_CODE]             INT             NULL,
    [RX_ORDER_NAME]               NVARCHAR (400)  NULL,
    [RX_ORDER_NM_WID]             NVARCHAR (400)  NULL,
    [RX_UNQUEUE_REAS_CODE]        INT             NULL,
    [UNQUEUE_REASON]              NVARCHAR (400)  NULL,
    [VERIFY_QUEUE_ENTRY_DATE]     DATETIME2 (7)   NULL,
    [VERIFY_QUEUE_ENTRY_DTTM]     DATETIME2 (7)   NULL,
    [VERIFY_QUEUE_ENTRY_HOUR]     INT             NULL,
    [VERIFY_QUEUE_LOGIN_DEPT_ID]  DECIMAL (18, 4) NULL,
    [VERIFY_QUEUE_USER_ID]        NVARCHAR (400)  NULL,
    [VERIFY_UNQUEUE_DATE]         DATETIME2 (7)   NULL,
    [VERIFY_UNQUEUE_DTTM]         DATETIME2 (7)   NULL,
    [VERIFY_UNQUEUE_HOUR]         INT             NULL
);


GO

