CREATE TABLE [dbo].[VISIT_REASONS] (
    [ABBREVIATION]         NVARCHAR (400)  NULL,
    [CM_LOG_OWNER_ID]      NVARCHAR (400)  NULL,
    [CM_PHY_OWNER_ID]      NVARCHAR (400)  NULL,
    [DISPLAY_TEXT]         NVARCHAR (400)  NULL,
    [REASON_VISIT_ID]      DECIMAL (18, 4) NULL,
    [REASON_VISIT_NAME]    NVARCHAR (400)  NULL,
    [RECORD_STAT_HRV_CODE] INT             NULL,
    [_SURROGATEKEY]        BIGINT          NULL
);


GO

