CREATE PROCEDURE reporting.USP_DM_Registry_MedDerived
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT DISTINCT MO.PATIENT_ID
  FROM MEDICATION_ORDERS MO
  JOIN MED_CODESET MC ON MC.MED_CODE = MO.MED_NAME
  WHERE MO.MED_NAME IN ('METFORMIN', 'INSULIN GLARGINE')
)
SELECT * FROM Base_Cohort;
END

GO

