CREATE PROCEDURE reporting.USP_Diabetes_Registry
AS
BEGIN
WITH
Reg_Core AS (
  SELECT MO.PATIENT_ID, MO.ORDER_DATE
  FROM MEDICATION_ORDERS MO
  WHERE MO.MED_NAME IN ('METFORMIN', 'INSULIN GLARGINE')
)
SELECT * FROM Reg_Core;
END

GO

