CREATE PROCEDURE reporting.USP_Diabetes_Registry_v1
AS
BEGIN
WITH
Reg_Core_v1 AS (
  SELECT PL.PATIENT_ID, PL.NOTED_DATE
  FROM PROBLEM_LIST PL
  WHERE PL.PROBLEM_CODE = 'DM2'
)
SELECT * FROM Reg_Core_v1;
END

GO

