CREATE PROCEDURE reporting.USP_Controlled_Diabetes_M
AS
BEGIN
WITH
Ctrl_Pop AS (
  SELECT LR.PATIENT_ID, LR.RESULT_DATE
  FROM LAB_RESULTS LR
  WHERE LR.HBA1C_VALUE < 8.0
)
SELECT * FROM Ctrl_Pop;
END

GO

