CREATE PROCEDURE reporting.USP_Diabetic_ExclGest
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT DISTINCT E.PATIENT_ID
  FROM ENCOUNTERS E
  JOIN ENCOUNTER_DIAGNOSIS ED ON ED.ENCOUNTER_ID = E.ENCOUNTER_ID
  WHERE ED.DX_CODE LIKE 'E11%' AND ED.DX_CODE NOT LIKE 'O24.4%'
)
SELECT * FROM Base_Cohort;
END

GO

