CREATE PROCEDURE reporting.USP_Active_Diabetics
AS
BEGIN
WITH
Active_Now AS (
  SELECT DC.PATIENT_ID, DC.DX_DATE
  FROM DIAGNOSIS_CODES DC
  WHERE DC.ICD_CODE LIKE 'E11%'
)
SELECT * FROM Active_Now;
END

GO

