CREATE PROCEDURE reporting.USP_PreOp_Abnormal_Labs
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT OC.PATIENT_ID, OC.CASE_ID
  FROM OR_CASES OC
  WHERE OC.CASE_DATE >= '2026-01-01'
),
Abnormal_Labs AS (
  SELECT BC.PATIENT_ID
  FROM Base_Cohort BC
  JOIN LAB_RESULTS LR ON LR.PATIENT_ID = BC.PATIENT_ID
  WHERE LR.LAB_CODE = 'A1C' AND LR.HBA1C_VALUE >= 8.0
)
SELECT * FROM Abnormal_Labs;
END

GO

