CREATE PROCEDURE reporting.USP_Diabetic_Panel
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT DISTINCT E.PATIENT_ID
  FROM ENCOUNTERS E
  JOIN ENCOUNTER_DIAGNOSIS ED ON ED.ENCOUNTER_ID = E.ENCOUNTER_ID
  JOIN DIAGNOSIS_CODESET DC ON DC.DX_CODE = ED.DX_CODE
  WHERE ED.DX_CODE LIKE 'E11%'
)
SELECT * FROM Base_Cohort;
END

GO

