CREATE PROCEDURE reporting.USP_Ref_Forms_Probe
AS
BEGIN
SELECT LR.PATIENT_ID, LR.HBA1C_VALUE
INTO #A1c_Pool
FROM LAB_RESULTS LR
WHERE LR.LAB_CODE = 'A1C';

SELECT DC.PATIENT_ID, DC.ICD_CODE
INTO #Dx_Events
FROM DIAGNOSIS_CODES DC
WHERE DC.ICD_CODE LIKE 'E11%';

WITH
Direct_Form AS (
  SELECT LAB_RESULTS.LAB_CODE
  FROM LAB_RESULTS
  WHERE LAB_RESULTS.LAB_CODE = 'A1C'
),
Alias_Form AS (
  SELECT LR2.RESULT_DATE
  FROM LAB_RESULTS LR2
  WHERE LR2.RESULT_DATE >= '2026-01-01'
),
TempChase_Form AS (
  SELECT bc.HBA1C_VALUE
  FROM #A1c_Pool bc
  WHERE bc.HBA1C_VALUE >= 6.5
),
Unique_Form AS (
  SELECT HBA1C_VALUE
  FROM LAB_RESULTS
  WHERE LAB_CODE = 'A1C'
),
Ambig_Form AS (
  SELECT PATIENT_ID
  FROM PATIENTS P
  JOIN ENCOUNTERS E ON E.PATIENT_ID = P.PATIENT_ID
  WHERE E.DEPARTMENT = 'ENDOCRINOLOGY'
)
SELECT * FROM TempChase_Form;
END

GO

