CREATE TABLE [reports].[SEVERE_SEPSIS_STAGING] (
    [EncounterID]                      DECIMAL (18, 4) NULL,
    [PatientID]                        NVARCHAR (400)  NULL,
    [SepsisDate]                       DATE            NULL,
    [ABXDays_V42]                      NVARCHAR (400)  NULL,
    [Arrival_Time_V10]                 DATETIME2 (7)   NULL,
    [BCPositive_V35]                   NVARCHAR (400)  NULL,
    [bill]                             NVARCHAR (400)  NULL,
    [Birth_Date_V02]                   DATETIME2 (7)   NULL,
    [Bolus1Time_V20]                   DATETIME2 (7)   NULL,
    [Bolus1Volume_V21]                 NVARCHAR (400)  NULL,
    [Bolus2Time_V22]                   DATETIME2 (7)   NULL,
    [Bolus2Volume_V23]                 NVARCHAR (400)  NULL,
    [Bolus3Time_V24]                   DATETIME2 (7)   NULL,
    [Bolus3Volume_V25]                 NVARCHAR (400)  NULL,
    [Clinically_Derived_Time_Zero_V09] DATETIME2 (7)   NULL,
    [CVLPlacementTime_V44]             DATETIME2 (7)   NULL,
    [DATE_STAMP]                       DATETIME2 (7)   NULL,
    [Disposition_V54]                  NVARCHAR (400)  NULL,
    [DispositionDate_V53]              DATETIME2 (7)   NULL,
    [ECMO_V48]                         NVARCHAR (400)  NULL,
    [ED2GenCareTime_V12]               DATETIME2 (7)   NULL,
    [ED2HemoncTime_V63]                DATETIME2 (7)   NULL,
    [ED2ICUTime_V13]                   DATETIME2 (7)   NULL,
    [ENCOUNTER_ID]                     DECIMAL (18, 4) NULL,
    [FirstABXTime_V26]                 DATETIME2 (7)   NULL,
    [FirstPressorTime_V29]             DATETIME2 (7)   NULL,
    [FirstPressorType_V30]             NVARCHAR (400)  NULL,
    [FirstTimeHypotension_V18]         DATETIME2 (7)   NULL,
    [FunctionaLTimeZero_V68]           DATETIME2 (7)   NULL,
    [GENCARE2ICUTime_V94]              DATETIME2 (7)   NULL,
    [HEMONC2ICUTime_V64]               DATETIME2 (7)   NULL,
    [HighRiskConditions_1_V65]         NVARCHAR (400)  NULL,
    [HighRiskConditions_2_V65]         NVARCHAR (400)  NULL,
    [HighRiskConditions_3_V65]         NVARCHAR (400)  NULL,
    [HighRiskConditions_4_V65]         NVARCHAR (400)  NULL,
    [HighRiskConditions_6_V65]         NVARCHAR (400)  NULL,
    [HighRiskConditions_7_V65]         NVARCHAR (400)  NULL,
    [HighRiskConditions_88_V65]        NVARCHAR (400)  NULL,
    [HighRiskConditions_95_V65]        NVARCHAR (400)  NULL,
    [HighRiskConditions_98_V65]        NVARCHAR (400)  NULL,
    [Huddle_Time_V07]                  DATETIME2 (7)   NULL,
    [ICUDays_V58]                      NVARCHAR (400)  NULL,
    [LacticAcidTime_V46]               DATETIME2 (7)   NULL,
    [LacticAcidValue_V47]              NVARCHAR (400)  NULL,
    [NACHRI_hosp]                      NVARCHAR (400)  NULL,
    [OrderSet_Time_V08]                DATETIME2 (7)   NULL,
    [OrganDysfunction_V41]             NVARCHAR (400)  NULL,
    [OutsideHospital_V11]              NVARCHAR (400)  NULL,
    [Pressor_Days_V57]                 DECIMAL (18, 4) NULL,
    [PressureVentDays_V56]             NVARCHAR (400)  NULL,
    [Pt_Chronically_Vented_V32]        NVARCHAR (400)  NULL,
    [Reviewed]                         NVARCHAR (400)  NULL,
    [Risk_Score_Method_V51]            NVARCHAR (400)  NULL,
    [Risk_Score_V52]                   NVARCHAR (400)  NULL,
    [ScreenTime_V06]                   DATETIME2 (7)   NULL,
    [Sepsis_Episode_ID_V01]            NVARCHAR (400)  NULL,
    [SVO2Time_V45]                     DATETIME2 (7)   NULL,
    [TimeSurgicalSourceControl_V39]    DATETIME2 (7)   NULL,
    [TimeZeroLoc_V66]                  DATETIME2 (7)   NULL,
    [Weight_V16]                       NVARCHAR (400)  NULL
);


GO

