"""Regenerate an estate's gap-check report — the HUMAN deliverable
(the ED-sepsis acceptance law): every named scope's floor, grouped by
file, with the voicing-ledger totals up top. A mechanism, not a
hand-run (Echo Law: round 2's report was ad hoc; Phase C makes the
generator standing).

Usage: python3.11 devtools/gap_check.py [estate]   (default: sepsis)
"""
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from aivia.flows import inbound, produce  # noqa: E402
from aivia.graph import kg1_intake  # noqa: E402
from aivia.graph.read_api import ReadApi  # noqa: E402
from aivia.graph.store import Store  # noqa: E402
from aivia.lenses import decisions  # noqa: E402


def build(base: pathlib.Path) -> ReadApi:
    store = Store()
    reg = json.loads((base / "registration.json").read_text())
    kg1_intake.apply_registration(store, reg)
    snapshots = sorted(base.glob("*_snapshot"))
    estate_dir = base / "estate_snapshot"
    for snap in snapshots:
        if snap == estate_dir:
            continue
        pack = json.loads((snap / "manifest.json").read_text()) \
            .get("source_pack_version", "")
        inbound.receive_extract(store, reg,
                                kg1_intake.load_snapshot(snap),
                                known_packs={pack} if pack else set())
    inbound.receive_estate(store, reg, estate_dir)
    return ReadApi(store)


def render(read: ReadApi) -> str:
    lines = ["# Gap-check report — floors under grammar "
             f"{produce.FLOOR_GRAMMAR_VERSION}",
             "",
             "Every named scope's floor text, for Sunny's gap-check "
             "(the ED-sepsis acceptance law). Regenerated by "
             "devtools/gap_check.py — never hand-edited.", ""]
    totals = {"voiced": 0, "counted": 0}
    sections = []
    for key in sorted(read.trees()):
        tree = read.trees()[key]
        scopes = list(decisions.named_scopes(tree))
        if not scopes:
            continue
        sections.append(f"\n## {tree['name']}\n")
        for scope in scopes:
            floor = produce.compose_floor(read, scope["name_key"])
            ledger = produce.voicing_ledger(read, scope["name_key"])
            totals["voiced"] += ledger["voiced"]
            totals["counted"] += ledger["counted"]
            sections.append(f"### `{scope['name_key']}`\n"
                            f"```\n{floor}\n```\n")
    lines.append(f"**Voicing ledger, corpus-wide:** "
                 f"{totals['voiced']} decisions voiced + "
                 f"{totals['counted']} counted == "
                 f"{totals['voiced'] + totals['counted']} total "
                 "(disjoint; every omission traces to a policy line "
                 "or a census row).")
    # THE GAP TAXONOMY rollup (registry Gap_Classes, ruled
    # 2026-09-06): ruled-silent vs open, owner engine|estate
    cls = {"ruled_silent": 0, "open_engine": 0, "open_estate": 0}
    for n in read.nodes("meaning_twin"):
        for k, v in n.properties["twin"]["census"]["by_class"].items():
            cls[k] += v
    drift = sum(t["resolution_census"].get("unresolved_refs", 0)
                for t in read.trees().values())
    lines += ["",
              "**The gap taxonomy** (ruled-silent = ok forever, by "
              "ruling; open = needs resolution):",
              f"- RULED-SILENT: {cls['ruled_silent']} "
              "(operational statements, degenerate predicates)",
              f"- OPEN, engine debt (ours): {cls['open_engine']} "
              "(unmapped kinds + unbound reference classes — shrinks "
              "with builds)",
              f"- OPEN, estate findings (the customer's): "
              f"{cls['open_estate']} documentation gaps + "
              f"{drift} drift refs (columns nowhere declared — "
              "silently-failing reports, kept counted forever)"]
    return "\n".join(lines + sections)


def main() -> None:
    estate = sys.argv[1] if len(sys.argv) > 1 else "sepsis"
    base = (pathlib.Path(__file__).resolve().parents[1]
            / "AIVIA_Product" / "estates" / estate)
    out = base / "gap_check_report.md"
    out.write_text(render(build(base)) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
