"""Render SHAPES_GAPCHECK.md — the ADR 0055 acceptance artifact.

Runs the shape corpus through the real pipeline (src/shapes/checker)
and writes the cell matrix with per-cell expected vs actual — every
planted sin found, none invented, exclusions with their reasons,
boundary cells disclosed — plus the demo note (the 3 most demoable
cells with the question to ask and the expected on-screen answer).

Usage: python3.11 devtools/shapes_gapcheck.py
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.shapes.checker import check_all, run_corpus  # noqa: E402
from src.shapes.generator import load_palette  # noqa: E402
from src.shapes.matrix import DIMENSIONS, coverage  # noqa: E402

OUT = PROJECT_ROOT / "internal" / "docs" / "SHAPES_GAPCHECK.md"


def main() -> None:
    palette = load_palette(
        PROJECT_ROOT / "data" / "shapes" / "palette_diabetes.json")
    run = run_corpus(palette)
    results = {r.cell_id: r for r in check_all(run)}
    cells = run.manifest["cells"]

    inst = [c for c in cells if c["status"] == "instantiated"]
    excl = [c for c in cells if c["status"] == "excluded"]
    failing = [r for r in results.values() if not r.ok]

    L: "list[str]" = []
    L.append("# Shapes gap-check — ADR 0055 acceptance "
             "(designed shape corpus, diabetic-diagnosis palette)")
    L.append("")
    L.append("Generated by devtools/shapes_gapcheck.py from a full "
             "LOCAL pipeline run (real ScriptDom parse → graph build "
             "→ red-flag sweep) over data/shapes/generated/. The "
             "corpus is deterministic: regeneration is byte-identical "
             "(CI-asserted).")
    L.append("")
    L.append(f"**Verdict: {len(inst)} instantiated cells, "
             f"{len(inst) - len(failing)} pass, {len(failing)} fail; "
             f"{len(excl)} excluded-with-reason; every ratified "
             "dimension value covered.**")
    L.append("")
    L.append("## Corpus totals")
    L.append("")
    L.append(f"- {len(run.files)} SQL files, "
             f"{len(run.parse_rows)} parsed; declared parse "
             f"exceptions: {run.parse_failures or 'none'}")
    L.append(f"- graph: {run.build.node_count} nodes, "
             f"{run.build.edge_count} edges; projection "
             f"{run.build.projection_minted} minted "
             f"({run.build.projection_minted_via_step} via the temp "
             f"chase), drops {run.build.projection_dropped}")
    L.append(f"- sweep: {len(run.sweep.flags_rows)} flags over "
             f"{run.sweep.swept} swept items "
             f"({run.sweep.flagged} flagged, {run.sweep.clean} clean, "
             f"excluded {run.sweep.excluded}) — conservation asserted")
    L.append("")
    L.append("## Dimension coverage (totality — the 0052 pattern)")
    L.append("")
    cov = coverage(run.manifest)
    for dim, values in DIMENSIONS.items():
        pairs = ", ".join(f"{v} → {'/'.join(cov[v])}" for v in values)
        L.append(f"- **{dim}**: {pairs}")
    L.append("")
    L.append("## Cell matrix — expected vs actual")
    L.append("")
    L.append("| cell | dims | status | result |")
    L.append("|---|---|---|---|")
    for c in cells:
        r = results[c["cell_id"]]
        if c["status"] == "excluded":
            verdict = f"EXCLUDED — {c['reason']}"
        elif r.ok:
            verdict = "PASS — expected = actual"
        else:
            verdict = "FAIL — " + "; ".join(r.details)
        L.append(f"| {c['cell_id']} | {c['dims']} | {c['status']} | "
                 f"{verdict} |")
    L.append("")
    L.append("## What each instantiated cell planted (for the "
             "gap-check read)")
    L.append("")
    for c in inst:
        exp = c.get("expect") or {}
        bits = []
        for f in exp.get("flags", []):
            bits.append(f"flag {f['flag_class']}/{f['severity']} on "
                        f"{f['identity'] or 'unnamed duplicate'} "
                        f"({f['distinct_logics']} logic(s))")
        if exp.get("absent_flag_identities"):
            bits.append("clean control: "
                        + ", ".join(exp["absent_flag_identities"]))
        if exp.get("edges"):
            bits.append(f"{len(exp['edges'])} projection edge(s)")
        if exp.get("drop_min"):
            bits.append(f"drop buckets {exp['drop_min']}")
        if exp.get("compare"):
            bits.append(f"compare verdict {exp['compare']['verdict']}")
        if exp.get("t2t_edges"):
            bits.append(f"{len(exp['t2t_edges'])} chain edge(s)")
        if exp.get("disclosure"):
            bits.append(f"DISCLOSED boundary: {exp['disclosure']}")
        if exp.get("note"):
            bits.append(exp["note"])
        L.append(f"- **{c['cell_id']}** ({c['dims']}): "
                 + ("; ".join(bits) or "structural expectations")
                 + f" — files: {', '.join(c['files'])}")
    L.append("")
    L.append("## DEMO NOTE — the 3 most demoable cells")
    L.append("")
    L.append("1. **M1 — the Active Diabetic Patients conflict** "
             "(same business name, two schemas, genuinely different "
             "logic — the classic silent disagreement).")
    L.append("   Ask: *\"Are the two Active Diabetic Patients "
             "definitions the same?\"*")
    L.append("   Expect on screen: compare partition with **2 hash "
             "groups — logic DIFFERS** (W15 stamp), plus the metric "
             "misnomer CONFLICT flag naming both members; caption "
             "must echo \"differs\" (gate-enforced).")
    L.append("2. **M2 — the Diabetes Registry (Legacy v1) cousin** "
             "(the drift beat, estate-wide).")
    L.append("   Ask: *\"What governance red flags exist for the "
             "Diabetes Registry?\"*")
    L.append("   Expect: the cousin_conflict CONFLICT flag row — 2 "
             "members, 2 distinct logics, no official designated; "
             "\"how is Diabetes Registry defined\" stamps "
             "certified-variants-exist.")
    L.append("3. **S4 — the Base_Cohort misnomer** (same CTE name in "
             "two procs, materially different populations — the "
             "Base_Pop story on a plantable corpus).")
    L.append("   Ask: *\"Are all definitions of Base_Cohort the "
             "same?\"*")
    L.append("   Expect: the step-name universe stamp (\"2 procs "
             "have a step NAMED 'Base_Cohort' — a name match is not "
             "logic sameness\") carrying the recorded misnomer flag "
             "(INFO, 2 logics); compare shows the dx-path vs "
             "lab-path diff.")
    L.append("")
    L.append("Each is falsifiable on camera: the sins were PLANTED "
             "with their oracles, so \"it found exactly these\" is a "
             "checkable claim, not a vibe. (Demo-switch mechanism + "
             "tenant load: PARKED for Sunny — see the handoff "
             "RESULTS.)")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT} — {len(inst)} instantiated "
          f"({len(inst) - len(failing)} pass), {len(excl)} excluded")
    if failing:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
