CREATE PROCEDURE reports.USP_Active_Diabetics
AS
BEGIN
WITH
Active_Now AS (
  SELECT MO.PATIENT_ID, MO.ORDER_DATE
  FROM MEDICATION_ORDERS MO
  WHERE MO.MED_NAME IN ('METFORMIN', 'INSULIN GLARGINE')
)
SELECT * FROM Active_Now;
END

GO

