
-- ==== reports/USP_RPTS_IP_SEPSIS.sql ====
/*

MODIFICATION DATE: 05.16.2019

MODIFIED BY: V_DEV001

MODIFICATION: PROCEDURE_ORDERS.PROC_CODE IS DEPRICATED AS OF APRIL 2019. REPLACING IT WITH PROCEDURE IDS.

	--PO.PROC_CODE DEPRICATED AS OF 04.15.2019--REPLACING WITH THE PROC IDS INSTEAD IN THE LINE BELOW

	--AND PO.PROC_CODE IN ('LAB006','LAB007') AND PO.SPECIMEN_SOURCE_CODE=304 



MODIFICATION DATE: 08.08.2019

MODIFIED BY: V_DEV001

MODIFICATION: MAR_ACTION_CODE changed from int to varchar



MODIFICATION DATE:10.01.2019

MODIFIED BY: V_DEV001

MODIFICATION: Added new Sepsis Organ Dysfunction Score Flowsheet ID '9000002644'



MODIFICATION DATE:11.25.2019

MODIFIED BY: V_DEV002

MODIFICATION: Added Sepsis Huddle Note 



MODIFICATION DATE:12.09.2019

MODIFIED BY: V_DEV001

MODIFICATION: Added ED First Positive Score, ED LOS & Took care of the duplicate entries. Duplicate entries were becasue of the time filter we used for OD Scores. Instead of OD Scores being captured between @StartDate and @EndDate, modified to the score time to check Department's IN_DTTM and OUT_DTTM.



MODIFICATION DATE:02.06.2020

MODIFIED BY: V_DEV001

MODIFICATION: Add a flag to check if the PATIENTS is SSS Severe Sepsis PATIENTS



MODIFICATION DATE:10.29.2020

MODIFIED BY: V_DEV001

MODIFICATION: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;



MODIFICATION DATE:2.3.2021

MODIFIED BY: V_DEV002

MODIFICATION: TKT-001 -- add Sepsis Score day/night shift



MODIFICATION DATE:03.01.2021

MODIFIED BY: V_DEV001

MODIFICATION: Change Hudlle time from -30 to 120 TO -30 to 180



MODIFICATION DATE:03.24.2021

MODIFIED BY: V_DEV001

MODIFICATION: TKT-003 -- add PATIENTS's race and ethnic group info



MODIFICATION DATE:11.16.2021

MODIFIED BY: V_DEV001

MODIFICATION: TKT-002 -- add Sepsis CLINICAL_ALERTS Activation and related documentation



MODIFICATION DATE:06.20.2022

MODIFIED BY: V_DEV001

MODIFICATION: Address transfers due to NEW_UNIT

*/

--EXEC [reports].[USP_IP_Sepsis]'MB-3','ME-3'



CREATE   PROCEDURE [reports].[USP_IP_SEPSIS]

@StartDate VARCHAR(20) = NULL,

@EndDate VARCHAR(20) = NULL



AS



SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	--BEGIN TRY

	SET NOCOUNT ON;

	

	DECLARE @dStartDate DATE

	DECLARE @dEndDate DATE

	DECLARE @dTestRun BIT

	

	IF @StartDate IS NULL OR @StartDate = ''

		--SET @dStartDate = [dbo].[fn_parse_date]('mb-95') --('MB-12')--DEFAULTING TO PREVIOUS MONTH

		SET @dStartDate = [dbo].[fn_parse_date]('2018-01-01') --('MB-12')--DEFAULTING TO PREVIOUS MONTH

	ELSE

		SET @dStartDate = [dbo].[fn_parse_date](@StartDate)

	

	IF @EndDate IS NULL OR @EndDate = ''

		--SET @dEndDate = [dbo].[fn_parse_date]('ME-95')--DEFAULTING TO PREVIOUS MONTH

		SET @dEndDate = [dbo].[fn_parse_date]('ME-1')--DEFAULTING TO PREVIOUS MONTH

	ELSE

		SET @dEndDate = [dbo].[fn_parse_date](@EndDate)





IF OBJECT_ID(N'tempdb..#Main') IS NOT NULL DROP TABLE #Main;

SELECT DISTINCT

	HE.ENCOUNTER_ID

	, HE.PATIENT_ID

	, PAT.PATIENT_MRN

	, PAT.PATIENT_NAME

	, REG.NAME AS [Ethnic Group]

	, RPR.NAME AS [Race]

	, HE.INPATIENT_DATA_ID

	, HE.ADT_ARRIVAL_TIME

	, HE.HOSP_ADMSN_TIME

	, HE.HOSP_DISCH_TIME

	, HE.INP_ADM_DATE

	, HE.ED_DEPARTURE_TIME

	, RDD.NAME AS [Disposition]

	, DATEDIFF(MM,PAT.BIRTH_DATE,HE.HOSP_ADMSN_TIME) AS AGE_MONTHS

	, FLOOR(DATEDIFF(DD,PAT.BIRTH_DATE,HE.HOSP_ADMSN_TIME)/365.25) AS AGE_YEARS

	, DATENAME(month, CONVERT(DATE,HE.HOSP_ADMSN_TIME)) + DATENAME(YEAR, CONVERT(DATE, HE.HOSP_ADMSN_TIME)) AS DATE_STAMP

	, DATEDIFF(HH, HE.HOSP_ADMSN_TIME, HE.HOSP_DISCH_TIME) AS LOS_HRS

INTO 

	#Main

FROM dbo.V_HOSPITAL_TRANSACTIONS HTR

	INNER JOIN dbo.HOSPITAL_ENCOUNTERS HE ON HTR.ENCOUNTER_ID = HE.ENCOUNTER_ID

	INNER JOIN dbo.PATIENTS PAT ON PAT.PATIENT_ID = HE.PATIENT_ID

	LEFT OUTER JOIN dbo.REF_DISCHARGE_DISPOSITION RDD ON RDD.DISCH_DISP_CODE = HE.DISCH_DISP_CODE

	LEFT OUTER JOIN dbo.REF_ETHNIC_GROUP REG ON REG.ETHNIC_GROUP_CODE = PAT.ETHNIC_GROUP_CODE

	LEFT OUTER JOIN dbo.PATIENT_DEMOGRAPHICS_RACE RACE ON RACE.PATIENT_ID = PAT.PATIENT_ID AND RACE.LINE=1

	LEFT OUTER JOIN dbo.REF_PATIENT_RACE RPR ON RPR.PATIENT_RACE_CODE = RACE.PATIENT_RACE_CODE

	LEFT OUTER JOIN dbo.REF_ED_DISPOSITION REDI ON REDI.ED_DISPOSITION_CODE = HE.ED_DISPOSITION_CODE

WHERE

	HE.INP_ADM_DATE IS NOT NULL

	AND CONVERT(DATE,HTR.SERVICE_DATE) BETWEEN @dStartDate AND @dEndDate



CREATE NONCLUSTERED INDEX IX_InpDataID  ON #Main (INPATIENT_DATA_ID);

CREATE NONCLUSTERED INDEX IX_PatID  ON #Main (PATIENT_ID);



--CHIEF COMPLIANT

IF OBJECT_ID(N'tempdb..#Base_Pop_ENC_Reason') IS NOT NULL DROP TABLE #Base_Pop_ENC_Reason;

SELECT

	sub.ENCOUNTER_ID,

	string_agg(DIAG.DX_NAME,'% ') AS [AllEncReasons]

INTO #Base_Pop_ENC_Reason

FROM  #Main sub

	INNER JOIN dbo.ENCOUNTER_DIAGNOSES EDX ON EDX.ENCOUNTER_ID = SUB.ENCOUNTER_ID AND EDX.LINE>1

	INNER JOIN dbo.DIAGNOSES DIAG ON DIAG.DX_ID = EDX.DX_ID

group by sub.ENCOUNTER_ID





--SELECT * FROM #Base_Pop_ENC_Reason

IF OBJECT_ID(N'tempdb..#EncounterWeights') IS NOT NULL DROP TABLE #EncounterWeights;

SELECT

	A.ENCOUNTER_ID

	, CAST(ROUND(CONVERT(FLOAT, MEAS_VALUE) * 0.0283495, 2) AS DECIMAL(4, 1)) AS EncWeight

	, ROW_NUMBER() OVER(PARTITION BY A.ENCOUNTER_ID ORDER BY C.RECORDED_TIME ASC) AS TIME_LINE

INTO 

	#EncounterWeights

FROM #Main A

	INNER JOIN dbo.FLOWSHEET_RECORDS B ON A.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS C ON B.FSD_ID = C.FSD_ID AND  C.FLO_MEAS_ID='94'



/*GETTING ENCOUNTERS WITHIN GIVEN DATE RANGES SO WE DON'T HAVE TO QUERY ON WHOLE DATABASE FOR EACH CRITERIA*/

IF OBJECT_ID(N'tempdb..#Base_Pop') IS NOT NULL DROP TABLE #Base_Pop;

SELECT 

	#Main.ENCOUNTER_ID

	, #Main.PATIENT_ID

	, ADT.ADT_DEPARTMENT_ID

	, ADT.ADT_DEPARTMENT_NAME

	, CVS.CODE_DESC AS DEPARTMENT_ROLLUP

	, ADT.IN_DTTM

	, ADT.OUT_DTTM

	, #Main.INPATIENT_DATA_ID

	, #Main.AGE_MONTHS

	, #Main.AGE_YEARS

	, #Main.ADT_ARRIVAL_TIME

	, #Main.ED_DEPARTURE_TIME

INTO 

	#Base_Pop

FROM #Main

INNER JOIN dbo.PATIENTS PAT ON PAT.PATIENT_ID = #Main.PATIENT_ID

cross apply (

			SELECT

				ADTIN.ENCOUNTER_ID,

				ADTIN.EFFECTIVE_TIME AS IN_DTTM,

				COALESCE(ADTOUT.EFFECTIVE_TIME,GETDATE()) AS OUT_DTTM,

				case when (CONVERT(DATE,ADTIN.EFFECTIVE_TIME) between '2022-03-29' and '2022-06-09')/*******************************************************************

																			NEW_UNIT construction 4/4-6/3:

																			NEW_UNIT patients moved to TCU; TCU patients moved to NICU C BED 1-10

																			*******************************************************************/

						and bed.bed_id in ( '20010800423011',

								'20010800423021',

								'20010800423031',

								'20010800423041',

								'20010800423051',

								'20010800423061',

								'20010800423071',

								'20010800423081',

								'20010800423091',

								'20010800423101'

								)

					then 200108013 else ADTIN.DEPARTMENT_ID end AS ADT_DEPARTMENT_ID,

				case when (CONVERT(DATE,ADTIN.EFFECTIVE_TIME) between '2022-03-29' and '2022-06-09')

						and bed.bed_id in ( '20010800423011',

								'20010800423021',

								'20010800423031',

								'20010800423041',

								'20010800423051',

								'20010800423061',

								'20010800423071',

								'20010800423081',

								'20010800423091',

								'20010800423101'

								)

					then 'MAIN 4 TOWER EAST' else DEP.DEPARTMENT_NAME end ADT_DEPARTMENT_NAME

			FROM

				.HOSPITAL_ENCOUNTERS HENC

				INNER JOIN .ADT_EVENTS ADTIN ON ADTIN.ENCOUNTER_ID = HENC.ENCOUNTER_ID

				LEFT OUTER JOIN .ADT_EVENTS ADTOUT ON ADTIN.NEXT_OUT_EVENT_ID = ADTOUT.EVENT_ID

				LEFT OUTER JOIN .DEPARTMENTS DEP ON ADTIN.DEPARTMENT_ID = DEP.DEPARTMENT_ID

				left outer join .BED_CONFIG bed on bed.BED_STAY_ID = adtin.BED_STAY_ID

			WHERE

				HENC.ENCOUNTER_ID = #Main.ENCOUNTER_ID

				and ADTIN.EVENT_TYPE_CODE IN (1, 3) --Only look at "in" events (Admission and Transfer In, LOA Return)

				AND ADTIN.EVENT_SUBTYPE_CODE <> 2 --Exclude deleted/canceled events

)ADT

INNER JOIN reports.CONFIG_VALUE_SET CVS ON CVS.CODE = ADT.adt_DEPARTMENT_ID

			AND CVS.VALUE_SET_ID = 3031 --DEPARTMENT ROLL UP



--POSITIVE ED SEPSIS SCORES & ED LOS

IF OBJECT_ID(N'tempdb..#Base_Pop_Severe_ED_Scores') IS NOT NULL DROP TABLE #Base_Pop_Severe_ED_Scores;

SELECT

	BP.ENCOUNTER_ID

	, CEILING(CONVERT(FLOAT,DATEDIFF(MI, BP.ADT_ARRIVAL_TIME,BP.ED_DEPARTURE_TIME))/60) HoursInED--CHECK WITH STEPHANIE ON 

	, BP.ADT_ARRIVAL_TIME

	, FM.MEAS_VALUE

	, FM.RECORDED_TIME

	, BP.ED_DEPARTURE_TIME

	, ROW_NUMBER() OVER(PARTITION BY BP.ENCOUNTER_ID ORDER BY RECORDED_TIME ASC) AS TIME_LINE

INTO 

	#Base_Pop_Severe_ED_Scores 

FROM #Main BP 

	INNER JOIN dbo.HOSPITAL_ENCOUNTERS HE ON HE.ENCOUNTER_ID = BP.ENCOUNTER_ID --and bp.ENCOUNTER_ID=1016405505 

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = HE.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID and

		FM.FLO_MEAS_ID IN ('9000161709','9000002613')--SEPSIS SCORE--ADDED NEW ED SEPSIS SCORE 9000002613 ON 10.01.2019

		and (FM.RECORDED_TIME <=  BP.ED_DEPARTURE_TIME)



IF OBJECT_ID(N'tempdb..#EDPosScore_EDLOS') IS NOT NULL DROP TABLE #EDPosScore_EDLOS;

SELECT

	ENCOUNTER_ID

	, HoursInED

	, MEAS_VALUE

	, RECORDED_TIME

	, ROW_NUMBER() OVER(PARTITION BY ENCOUNTER_ID ORDER BY RECORDED_TIME ASC) AS FIRST_TIME_LINE

	, ROW_NUMBER() OVER(PARTITION BY ENCOUNTER_ID ORDER BY RECORDED_TIME DESC) AS LAST_TIME_LINE

INTO 

	#EDPosScore_EDLOS

FROM 

	#Base_Pop_Severe_ED_Scores

WHERE

	MEAS_VALUE > 4

--POSITIVE SEPSIS SCORES

IF OBJECT_ID(N'tempdb..#Base_Pop_OD_Scores') IS NOT NULL DROP TABLE #Base_Pop_OD_Scores;

SELECT

	BP.ENCOUNTER_ID

	, BP.ADT_DEPARTMENT_ID

	, BP.ADT_DEPARTMENT_NAME

	, BP.IN_DTTM

	, BP.OUT_DTTM

	, FM.MEAS_VALUE

	, FM.RECORDED_TIME

	, Huddle_Note.[Sepsis PATIENTS Huddle or Sepis CLINICAL_ALERTS Called//Performed with a MD/PNP]

	, Huddle_Note.[Huddle Date]

	, Huddle_Note.[Huddle Time]

	, Huddle_Note.[PATIENTS Assessed by MD/PNP]

	, Huddle_Note.[Physician Name]

	, Huddle_Note.[Additional Orders Received/Placed by MD/PNP]

	, ALERTNOTACTIVATED.[CLINICAL_ALERTS Not Activated Reason]

	, ALERTNOTACTIVATED.[CLINICAL_ALERTS Not Activated Comment]

	, ALERTACTIVATED.[CLINICAL_ALERTS Activated Comment]

	, ROW_NUMBER() OVER(PARTITION BY BP.ENCOUNTER_ID, BP.ADT_DEPARTMENT_ID, BP.IN_DTTM ORDER BY FM.RECORDED_TIME ASC) AS TIME_LINE

INTO 

	#Base_Pop_OD_Scores 

FROM #Base_Pop BP 

	INNER JOIN dbo.HOSPITAL_ENCOUNTERS HE ON HE.ENCOUNTER_ID = BP.ENCOUNTER_ID

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON HE.INPATIENT_DATA_ID = FR.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID

	LEFT OUTER JOIN

		(

			SELECT

				FR.INPATIENT_DATA_ID, IFM_ALERTNOTACTIVATED.FSD_ID, IFM_ALERTNOTACTIVATED.RECORDED_TIME, IFM_ALERTNOTACTIVATED.MEAS_VALUE AS [CLINICAL_ALERTS Not Activated Reason], IFM_ALERTNOTACTIVATED.MEAS_COMMENT as [CLINICAL_ALERTS Not Activated Comment]

			FROM dbo.FLOWSHEET_RECORDS FR

				INNER JOIN dbo.FLOWSHEET_MEASUREMENTS IFM_ALERTNOTACTIVATED ON IFM_ALERTNOTACTIVATED.FSD_ID = FR.FSD_ID

			WHERE

				IFM_ALERTNOTACTIVATED.FLO_MEAS_ID='9000003159'

		)ALERTNOTACTIVATED ON ALERTNOTACTIVATED.INPATIENT_DATA_ID = FR.INPATIENT_DATA_ID

			AND ALERTNOTACTIVATED.FSD_ID = FR.FSD_ID

			AND ALERTNOTACTIVATED.RECORDED_TIME = FM.RECORDED_TIME

		LEFT OUTER JOIN

		(

			SELECT

				ALT.ALT_ID,

				ALT.VISIT_ID,

				HIS.ALT_ACTION_INST,

				COALESCE(HIS.SPEC_OVR_CMNT,' ')+ RSN.NAME [CLINICAL_ALERTS Activated Comment]

			FROM dbo.CLINICAL_ALERTS ALT

				INNER JOIN dbo.ALERT_HISTORY HIS ON HIS.ALT_ID = ALT.ALT_ID

				INNER JOIN dbo.REF_ALERT_OVERRIDE_REASONS RSN ON RSN.ALRT_SP_OVR_RSN_CODE = HIS.SPEC_OVR_RSN_CODE

			WHERE ALT.BPA_LOCATOR_ID=900400001--BASE 2019 HS OD SCORE SEPSIS >2 [900400001]

		)ALERTACTIVATED ON ALERTACTIVATED.VISIT_ID = HE.ENCOUNTER_ID

			AND ALERTACTIVATED.ALT_ACTION_INST = FM.RECORDED_TIME

	--huddle notes within 30 minutes before or 120 minutes after OD Score

	outer apply

		(select a.INPATIENT_DATA_ID

			,a.OD_SCORE_RECORDED_TIME

			,max(case WHEN a.FLO_MEAS_ID = '9000002705' THEN a.MEAS_VALUE end) as "Sepsis PATIENTS Huddle or Sepis CLINICAL_ALERTS Called//Performed with a MD/PNP"

			,max(CASE WHEN a.FLO_MEAS_ID = '9000002732' THEN try_cast(DATEADD(day,try_cast(a.MEAS_VALUE as int),'1840-12-31') as date) end) as "Huddle Date"

			,max(case WHEN a.FLO_MEAS_ID = '9000002733' THEN try_cast(DATEADD(second,try_cast(a.MEAS_VALUE as int),'1840-12-31') as time) end) as "Huddle Time"

			,max(case WHEN a.FLO_MEAS_ID = '9000002706' THEN a.MEAS_VALUE end) as "PATIENTS Assessed by MD/PNP"

			,max(case WHEN a.FLO_MEAS_ID = '9000002734' THEN a.MEAS_VALUE end) as "Physician Name"

			,max(case WHEN a.FLO_MEAS_ID = '9000002707' THEN a.MEAS_VALUE end) as "Additional Orders Received/Placed by MD/PNP"

			from

			(

			select FR.INPATIENT_DATA_ID

			,FM.RECORDED_TIME as OD_SCORE_RECORDED_TIME

			,FLOWSHEET_MEASUREMENTS.FLO_MEAS_ID

			,FLOWSHEET_MEASUREMENTS.RECORDED_TIME

			,FLOWSHEET_MEASUREMENTS.MEAS_VALUE

			,row_number() over (partition by FLOWSHEET_RECORDS.INPATIENT_DATA_ID, FM.RECORDED_TIME, FLOWSHEET_MEASUREMENTS.FLO_MEAS_ID order by FLOWSHEET_MEASUREMENTS.RECORDED_TIME) rownumber

				from  dbo.FLOWSHEET_RECORDS

				INNER JOIN dbo.FLOWSHEET_MEASUREMENTS ON FLOWSHEET_RECORDS.FSD_ID = FLOWSHEET_MEASUREMENTS.FSD_ID

				where FLOWSHEET_RECORDS.INPATIENT_DATA_ID = FR.INPATIENT_DATA_ID

				and datediff(minute,FM.RECORDED_TIME,FLOWSHEET_MEASUREMENTS.RECORDED_TIME) between -30 and 180--WAS -120 UNTIL 03.01.2021 

				and FLOWSHEET_MEASUREMENTS.FLO_MEAS_ID in ('9000002705','9000002732','9000002733','9000002706','9000002734','9000002707')

				and FLOWSHEET_MEASUREMENTS.MEAS_VALUE is not null

			) a

			where a.rownumber = 1

			group by a.INPATIENT_DATA_ID, a.OD_SCORE_RECORDED_TIME

		) Huddle_Note

WHERE 

	FM.FLO_MEAS_ID IN ('9000161711','9000002644') --ORGAN DYSFUNCTION SCORE

	--and FM.RECORDED_TIME BETWEEN @dStartDate AND @dEndDate--BP.IN_DTTM AND BP.OUT_DTTM--this is because a paitient's IN DTTM could be in the current month and out DTTM could be in next month. Per Stakeholder A, we want to look for scores documented in the same time frame.

	AND FM.RECORDED_TIME BETWEEN BP.IN_DTTM AND COALESCE(BP.OUT_DTTM,GETDATE())





IF OBJECT_ID(N'tempdb..#Hypotension') IS NOT NULL DROP TABLE #Hypotension;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, CASE

		WHEN 

			B.AGE_MONTHS < 2 AND Syst.SYSTOLIC < 65

			OR

			(B.AGE_MONTHS >= 2 AND B.AGE_MONTHS < 12) AND Syst.SYSTOLIC < 70

			OR

			(B.AGE_YEARS >= 1 AND B.AGE_YEARS < 2) AND Syst.SYSTOLIC < 80

			OR

			(B.AGE_YEARS >= 2 AND B.AGE_YEARS < 6) AND Syst.SYSTOLIC < 90

			OR

			(B.AGE_YEARS >= 6 AND B.AGE_YEARS < 13) AND Syst.SYSTOLIC < 100

			OR

			B.AGE_YEARS >= 13 AND Syst.SYSTOLIC < 110

		THEN Syst.MEAS_VALUE--FM.RECORDED_TIME

		ELSE NULL

	END AS MEAS_VALUE

	, Syst.RECORDED_TIME

	, Syst.SYSTOLIC

INTO 

	#Hypotension 

FROM

	#Base_Pop B

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	cross apply

	(

		select FM.fsd_id, try_cast(LEFT(FM.MEAS_VALUE, CHARINDEX('/', FM.MEAS_VALUE)-1) as int) AS SYSTOLIC, FM.MEAS_VALUE, FM.RECORDED_TIME

		from 

		dbo.FLOWSHEET_MEASUREMENTS FM 

		where FM.FSD_ID = FR.FSD_ID AND FM.FLO_MEAS_ID = '95' 

		AND FM.MEAS_VALUE IS NOT NULL

		and FM.RECORDED_TIME IS NOT NULL

	)Syst





IF OBJECT_ID(N'tempdb..#ODHYPO') IS NOT NULL DROP TABLE #ODHYPO;

SELECT

	CASE WHEN LASTHYPO.MEAS_VALUE IS NOT NULL THEN LASTHYPO.RECORDED_TIME ELSE NULL END [LAST Hypotension Time],

	LASTHYPO.MEAS_VALUE [LAST Hypotension Value],

	CASE WHEN LASTHYPO.MEAS_VALUE IS NOT NULL AND (LASTHYPO.RECORDED_TIME BETWEEN A.IN_DTTM AND A.OUT_DTTM) THEN 'Y' ELSE 'N' END AS [LAST Hypotension taken in Dept Y/N],

	A.*,

	CASE WHEN FIRSTHYPO.MEAS_VALUE IS NOT NULL THEN FIRSTHYPO.RECORDED_TIME ELSE NULL END [FIRST Hypotension Time],

	FIRSTHYPO.MEAS_VALUE [FIRST Hypotension Value],

	CASE WHEN FIRSTHYPO.MEAS_VALUE IS NOT NULL AND (FIRSTHYPO.RECORDED_TIME BETWEEN A.IN_DTTM AND A.OUT_DTTM) THEN 'Y' ELSE 'N' END AS [FIRST Hypotension taken in Dept Y/N]

INTO #ODHYPO

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 HYPO.RECORDED_TIME, HYPO.MEAS_VALUE FROM #Hypotension HYPO

		WHERE HYPO.ENCOUNTER_ID = A.ENCOUNTER_ID AND HYPO.RECORDED_TIME<A.RECORDED_TIME

		ORDER BY HYPO.RECORDED_TIME DESC

	)LASTHYPO

	OUTER APPLY

	(

		SELECT TOP 1 HYPO.RECORDED_TIME, HYPO.MEAS_VALUE FROM #Hypotension HYPO

		WHERE HYPO.ENCOUNTER_ID = A.ENCOUNTER_ID AND HYPO.RECORDED_TIME>=A.RECORDED_TIME

		ORDER BY HYPO.RECORDED_TIME ASC

	)FIRSTHYPO



------------------------------------------------------END OF HYPO------------------------------------------------------------------

------------------------------------------------------ABX------------------------------------------------------------------

-- All encounters from #Base_pop where ABX was administered

IF OBJECT_ID(N'tempdb..#BasePopABX') IS NOT NULL DROP TABLE #BasePopABX;

SELECT

	MO.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, MEDS.NAME

	, MA.TAKEN_TIME AS ABX_ADMIN_TIME

	, MA.SIG AS BOLUS_VOLUME

INTO

	#BasePopABX

FROM #Base_Pop B

	INNER JOIN dbo.MEDICATION_ORDERS MO	ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID AND MEDS.THERA_CLASS_CODE = 11 --Antibiotics

	INNER JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID

WHERE

	MA.TAKEN_TIME IS NOT NULL	--ADMINISTERED ABX ONLY

	AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

							, '7'			--RESTARTED

							, '102'		--GIVEN BY OTHER

							, '105'		--NEW CARTRIDGE

							, '113'		--GIVEN DURING DOWNTIME

							, '114'		--STARTED DURING DOWNTIME

							, '115'		--MEDICATION APPLIED

							, '122'		--CONTINUED FROM OR

							, '124'		--SELF ADMINISTERED VIA PUMP

							, '132'		--CONTINUED FROM PREVIOUS ORDER

							, '143'		--REDOSE

							, '1604'		--INFUSION GREATER THAN 15 MIN

							, '1605'		--INFUSION LESS THAN 15 MIN

							, '1607'		--NEW CARTRIDGE

							, '6'			--NEW BAG

							)

--VALUES BELOW ADDED TO THE CODE ON STEPHANIE'S REQUEST DURING VALIDATION.

	AND MEDS.ROUTE NOT IN ('intratympanic'

						, 'intraocular'

						, 'Apply externally'

						, 'ophthalmic'

						, 'oral'

						, 'Topical'

						, 'nasal'

						, 'intramuscular'

						, 'otic'

						, 'intravitreal'

						, 'vaginal'

						, 'inhalation'

						, 'intravenous'

						)							



IF OBJECT_ID(N'tempdb..#ODABX') IS NOT NULL DROP TABLE #ODABX;

SELECT

	LASTABX.ABX_ADMIN_TIME LASTABX_TIME,

	LASTABX.NAME LASTABX_NAME,

	LASTABX.BOLUS_VOLUME AS [LAST ABX Volume],

	LASTABX.[Last ABX to OD Score Time],

	CASE WHEN LASTABX.ABX_ADMIN_TIME BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST ABX Given in Dept Y/N],

	A.*,

	FIRSTABX.ABX_ADMIN_TIME FIRSTABX_TIME,

	FIRSTABX.NAME FIRSTABX_NAME,

	FIRSTABX.BOLUS_VOLUME AS [FIRST ABX Volume],

	FIRSTABX.[OD Score to First ABX Time],

	CASE WHEN FIRSTABX.ABX_ADMIN_TIME BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST ABX Given in Dept Y/N]

INTO #ODABX

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 ABX.ABX_ADMIN_TIME, ABX.ADT_DEPARTMENT_ID, ABX.IN_DTTM, ABX.OUT_DTTM, ABX.NAME, ABX.ENCOUNTER_ID, ABX.ADT_DEPARTMENT_NAME, ABX.BOLUS_VOLUME, DATEDIFF(MI,ABX_ADMIN_TIME,A.RECORDED_TIME) AS [Last ABX to OD Score Time] FROM #BasePopABX ABX

		WHERE ABX.ENCOUNTER_ID = A.ENCOUNTER_ID AND ABX.ABX_ADMIN_TIME<A.RECORDED_TIME

		ORDER BY ABX.ABX_ADMIN_TIME DESC

	)LASTABX

	OUTER APPLY

	(

		SELECT TOP 1 ABX.ABX_ADMIN_TIME, ABX.ADT_DEPARTMENT_ID, ABX.IN_DTTM, ABX.OUT_DTTM, ABX.NAME, ABX.ENCOUNTER_ID, ABX.ADT_DEPARTMENT_NAME, ABX.BOLUS_VOLUME, DATEDIFF(MI,A.RECORDED_TIME,ABX_ADMIN_TIME) AS [OD Score to First ABX Time] FROM #BasePopABX ABX

		WHERE ABX.ENCOUNTER_ID = A.ENCOUNTER_ID AND ABX.ABX_ADMIN_TIME>=A.RECORDED_TIME

		ORDER BY ABX.ABX_ADMIN_TIME ASC

	)FIRSTABX

------------------------------------------------------END OF ABX------------------------------------------------------------------



------------------------------------------------------ORDER SET------------------------------------------------------------------

-- All encounters from #Base_pop where Bolus was administered

IF OBJECT_ID(N'tempdb..#SSOrderSet') IS NOT NULL DROP TABLE #SSOrderSet;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, MO.ORDER_DTTM

	, MO.PRL_ORDERSET_ID

INTO

	#SSOrderSet 

FROM #Base_Pop B

INNER JOIN dbo.ORDER_TRACKING_METRICS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

WHERE

	MO.PRL_ORDERSET_ID IN (400001)-- (40400100, 40400058, 40400196, 40400153, 4058600002, 400001) --Severe Sepsis, Short Stay – Sepsis, H/O – Sepsis CLINICAL_ALERTS, ID – Staph Aureus Sepsis, H/O Sepsis CLINICAL_ALERTS in Clinic, Sepsis Pathway





IF OBJECT_ID(N'tempdb..#ODORDSET') IS NOT NULL DROP TABLE #ODORDSET;

SELECT

	LASTOS.ORDER_DTTM [LAST OrderSet Time],

	LASTOS.PRL_ORDERSET_ID [LAST OrderSet ID],

	CASE WHEN LASTOS.ORDER_DTTM BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST OrderSet in Dept Y/N],

	A.*,

	FIRSTOS.ORDER_DTTM [FIRST OrderSet Time],

	FIRSTOS.PRL_ORDERSET_ID [FIRST OrderSet ID],

	CASE WHEN FIRSTOS.ORDER_DTTM BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST OrderSet in Dept Y/N]

INTO #ODORDSET

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 SOS.ORDER_DTTM, SOS.PRL_ORDERSET_ID FROM #SSOrderSet SOS

		WHERE SOS.ENCOUNTER_ID = A.ENCOUNTER_ID AND SOS.ORDER_DTTM<A.RECORDED_TIME

		ORDER BY SOS.ORDER_DTTM DESC

	)LASTOS

	OUTER APPLY

	(

		SELECT TOP 1 SOS.ORDER_DTTM, SOS.PRL_ORDERSET_ID FROM #SSOrderSet SOS

		WHERE SOS.ENCOUNTER_ID = A.ENCOUNTER_ID AND SOS.ORDER_DTTM>=A.RECORDED_TIME

		ORDER BY SOS.ORDER_DTTM ASC

	)FIRSTOS

------------------------------------------------------END OF ORDER SET------------------------------------------------------------------



------------------------------------------------------BOLUS------------------------------------------------------------------



IF OBJECT_ID(N'tempdb..#BasePopBolus') IS NOT NULL DROP TABLE #BasePopBolus;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	,B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, MA.TAKEN_TIME AS BOLUS_ADMIN_TIME

	, MEDS.NAME AS Medication

	, MA.SIG AS BOLUS_VOLUME

INTO

	#BasePopBolus 

FROM #Base_Pop B

	INNER JOIN dbo.MEDICATION_ORDERS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID

	INNER JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID

WHERE

	MA.TAKEN_TIME IS NOT NULL --ADMINISTERED BOLUS ONLY

	AND (MO.MEDICATION_ID IN (700001  --SODIUM CHLORIDE 0.99 % IV BOLUS

							, 7000739 --LACTATED RINGERS IV BOLUS

							, 700003    --ALBUMIN, HUMAN 95 % INTRAVENOUS SOLUTION

							, 7006331 --ELECTROLYE-A IV Bolus (PLASMALYTE)

							, 700002	--SODIUM CHLORIDE 0.99 % INJECTION SYRINGE

							)

		OR (MO.MEDICATION_ID = 700004)

	AND MO.HV_DISCR_FREQ_ID = '300902') -- FREQUENCY = ONCE 

	AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

							, '7'			--RESTARTED

							, '102'		--GIVEN BY OTHER

							, '105'		--NEW CARTRIDGE

							, '113'		--GIVEN DURING DOWNTIME

							, '114'		--STARTED DURING DOWNTIME

							, '115'		--MEDICATION APPLIED

							, '122'		--CONTINUED FROM OR

							, '124'		--SELF ADMINISTERED VIA PUMP

							, '132'		--CONTINUED FROM PREVIOUS ORDER

							, '143'		--REDOSE

							, '1604'		--INFUSION GREATER THAN 15 MIN

							, '1605'		--INFUSION LESS THAN 15 MIN

							, '1607'		--NEW CARTRIDGE

							, '6'			--NEW BAG

							)

	AND CONVERT(NUMERIC, MA.SIG ) > 95.0



IF OBJECT_ID(N'tempdb..#OdboL') IS NOT NULL DROP TABLE #OdboL;

SELECT

	LASTBOL.BOLUS_ADMIN_TIME [LAST Bolus Time],

	LASTBOL.Medication [LAST Bolus],

	LASTBOL.BOLUS_VOLUME AS [LAST Bolus Volume],

	LASTBOL.[Last Bolus to Screen Time],

	CASE WHEN LASTBOL.BOLUS_ADMIN_TIME BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST Bolus Given in Dept Y/N],

	A.*,

	FIRSTBOL.BOLUS_ADMIN_TIME [FIRST Bolus Time],

	FIRSTBOL.Medication [FIRST Bolus],

	FIRSTBOL.BOLUS_VOLUME AS [FIRST Bolus Volume],

	FIRSTBOL.[Screen Time to First Bolus],

	CASE WHEN FIRSTBOL.BOLUS_ADMIN_TIME BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST Bolus Given in Dept Y/N]

INTO #OdboL

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 BOL.BOLUS_ADMIN_TIME, BOL.BOLUS_VOLUME, BOL.Medication, DATEDIFF(MI, BOLUS_ADMIN_TIME,A.RECORDED_TIME) AS [Last Bolus to Screen Time] FROM #BasePopBolus BOL

		WHERE BOL.ENCOUNTER_ID = A.ENCOUNTER_ID AND BOL.BOLUS_ADMIN_TIME<A.RECORDED_TIME

		ORDER BY BOL.BOLUS_ADMIN_TIME DESC

	)LASTBOL

	OUTER APPLY

	(

		SELECT TOP 1 BOL.BOLUS_ADMIN_TIME, BOL.BOLUS_VOLUME, BOL.Medication, DATEDIFF(MI, A.RECORDED_TIME,BOLUS_ADMIN_TIME) AS [Screen Time to First Bolus] FROM #BasePopBolus BOL

		WHERE BOL.ENCOUNTER_ID = A.ENCOUNTER_ID AND BOL.BOLUS_ADMIN_TIME>=A.RECORDED_TIME

		ORDER BY BOL.BOLUS_ADMIN_TIME ASC

	)FIRSTBOL



------------------------------------------------------END OF BOLUS------------------------------------------------------------------

------------------------------------------------------CVL TIMES------------------------------------------------------------------



/*CVL TIME - TEST ENCOUNTER 5550010001*/

IF OBJECT_ID(N'tempdb..#ALLCVLTime') IS NOT NULL DROP TABLE #ALLCVLTime;

SELECT DISTINCT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, LNA.PLACEMENT_INSTANT

INTO 

	#ALLCVLTime

FROM #Base_Pop B

	INNER JOIN dbo.LINE_DEVICE_AIRWAY LNA ON LNA.ENCOUNTER_ID = B.ENCOUNTER_ID 

	INNER JOIN reports.CONFIG_VALUE_SET CVS ON CVS.CODE = LNA.FLO_MEAS_ID

			AND CVS.VALUE_SET_ID = 3022 --CVL CODES



IF OBJECT_ID(N'tempdb..#ODCVL') IS NOT NULL DROP TABLE #ODCVL;

SELECT

	LASTCVL.PLACEMENT_INSTANT [LAST CVL Time],

	CASE WHEN LASTCVL.PLACEMENT_INSTANT BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST CVL in Dept Y/N],

	A.*,

	FIRSTCVL.PLACEMENT_INSTANT [FIRST CVL Time],

	CASE WHEN FIRSTCVL.PLACEMENT_INSTANT BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST CVL in Dept Y/N]

INTO #ODCVL

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 CVL.PLACEMENT_INSTANT FROM #ALLCVLTime CVL

		WHERE CVL.ENCOUNTER_ID = A.ENCOUNTER_ID AND CVL.PLACEMENT_INSTANT<A.RECORDED_TIME

		ORDER BY CVL.PLACEMENT_INSTANT DESC

	)LASTCVL

	OUTER APPLY

	(

		SELECT TOP 1 CVL.PLACEMENT_INSTANT FROM #ALLCVLTime CVL

		WHERE CVL.ENCOUNTER_ID = A.ENCOUNTER_ID AND CVL.PLACEMENT_INSTANT>=A.RECORDED_TIME

		ORDER BY CVL.PLACEMENT_INSTANT ASC

	)FIRSTCVL



------------------------------------------------------END OF CVL TIMES------------------------------------------------------------------



------------------------------------------------------PRESSORS TIMES------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#Pressors') IS NOT NULL DROP TABLE #Pressors;

SELECT DISTINCT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, MA.TAKEN_TIME

	, GMR.GROUPER_ID

	, MEDS.NAME AS MEDICATION

INTO

	#Pressors 

FROM #Base_Pop B

	LEFT JOIN dbo.MEDICATION_ORDERS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

	LEFT JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID

	LEFT JOIN dbo.GROUPER_MED_RECORDS GMR ON GMR.EXP_MEDS_LIST_ID = MEDS.MEDICATION_ID

	LEFT JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID

	LEFT JOIN dbo.HOSPITAL_ENCOUNTERS HE ON HE.ENCOUNTER_ID = B.ENCOUNTER_ID

WHERE

	GMR.GROUPER_ID IN ('8000100'    -- HS RX EPINEPHRINE SEPSIS

							, '8000101' -- HS RX DOPAMINE SEPSIS

							, '8000102' -- HS RX DOBUTAMINE SEPSIS

							, '8000103' -- HS RX MILRINONE SEPSIS

							, '8000104' -- HS RX NOREPINEPHRINE SEPSIS

						)

	AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

							, '7'			--RESTARTED

							, '102'		--GIVEN BY OTHER

							, '105'		--NEW CARTRIDGE

							, '113'		--GIVEN DURING DOWNTIME

							, '114'		--STARTED DURING DOWNTIME

							, '115'		--MEDICATION APPLIED

							, '122'		--CONTINUED FROM OR

							, '124'		--SELF ADMINISTERED VIA PUMP

							, '132'		--CONTINUED FROM PREVIOUS ORDER

							, '143'		--REDOSE

							, '1604'		--INFUSION GREATER THAN 15 MIN

							, '1605'		--INFUSION LESS THAN 15 MIN

							, '1607'		--NEW CARTRIDGE

							, '6'			--NEW BAG

							)

	AND MA.ROUTE_CODE = 11 --INTRAVENOUS





IF OBJECT_ID(N'tempdb..#ODPressorSummary') IS NOT NULL DROP TABLE #ODPressorSummary;

SELECT

ENCOUNTER_ID,

CASE WHEN GROUPER_ID = '8000100'   THEN 'EPINEPHRINE' -- HS RX EPINEPHRINE SEPSIS

	WHEN GROUPER_ID =  '8000101' THEN 'DOPAMINE'

	WHEN GROUPER_ID = '8000102'   THEN 'DOBUTAMINE'

	WHEN GROUPER_ID = '8000103'   THEN 'MILRINONE'

	WHEN GROUPER_ID = '8000104'   THEN 'NOREPINEPHRINE'

	END PRESSOR,

	COUNT(TAKEN_TIME) AS MYC

INTO #ODPressorSummary

FROM #Pressors

GROUP BY ENCOUNTER_ID, GROUPER_ID



IF OBJECT_ID ('TEMPDB..#ODPressorPivot') IS NOT NULL DROP TABLE #ODPressorPivot



SELECT

	ENCOUNTER_ID, PVT.[EPINEPHRINE] AS [EPINEPHRINE], PVT.[DOPAMINE] AS [DOPAMINE], PVT.[DOBUTAMINE] AS [DOBUTAMINE],

	PVT.[MILRINONE] AS [MILRINONE], PVT.[NOREPINEPHRINE] AS [NOREPINEPHRINE]

INTO #ODPressorPivot

FROM #ODPressorSummary

	PIVOT( MAX(myc)

	FOR PRESSOR IN ([EPINEPHRINE],[DOPAMINE],[DOBUTAMINE],[MILRINONE],[NOREPINEPHRINE])) AS PVT

--select * from #ODPressorPivot

------------------------------------------------------END OF PRESSORS TIMES------------------------------------------------------------------

------------------------------------------------------SVO2 TIMES------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#SVO2') IS NOT NULL DROP TABLE #SVO2;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, PO.ORDER_TIME AS SVO2OrderTime

	, LAB_ORDER_RESULTS.RESULT_TIME

	, LAB_ORDER_RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, LAB_ORDER_RESULTS.ORD_VALUE

	, LAB_ORDER_RESULTS.ORDER_PROC_ID

INTO 

	#SVO2

FROM #Base_Pop B

	INNER JOIN dbo.LAB_ORDER_RESULTS ON B.ENCOUNTER_ID = LAB_ORDER_RESULTS.ENCOUNTER_ID

	INNER JOIN dbo.PROCEDURE_ORDERS PO ON PO.ORDER_PROC_ID = LAB_ORDER_RESULTS.ORDER_PROC_ID

WHERE

	LAB_ORDER_RESULTS.COMPONENT_ID IN (5000001861, 5000000478)



IF OBJECT_ID(N'tempdb..#ODSVO2') IS NOT NULL DROP TABLE #ODSVO2;

SELECT

	LASTSVO2.SVO2OrderTime [LAST SVO2 Time],

	CASE WHEN LASTSVO2.SVO2OrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST SVO2 in Dept Y/N],

	A.*,

	FIRSTSVO2.SVO2OrderTime [FIRST SVO2 Time],

	CASE WHEN FIRSTSVO2.SVO2OrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST SVO2 in Dept Y/N]

INTO #ODSVO2

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 SVO2.SVO2OrderTime FROM #SVO2 SVO2

		WHERE SVO2.ENCOUNTER_ID = A.ENCOUNTER_ID AND SVO2.SVO2OrderTime<A.RECORDED_TIME

		ORDER BY SVO2.SVO2OrderTime DESC

	)LASTSVO2

	OUTER APPLY

	(

		SELECT TOP 1 SVO2.SVO2OrderTime FROM #SVO2 SVO2

		WHERE SVO2.ENCOUNTER_ID = A.ENCOUNTER_ID AND SVO2.SVO2OrderTime>=A.RECORDED_TIME

		ORDER BY SVO2.SVO2OrderTime ASC

	)FIRSTSVO2

------------------------------------------------------END OF SVO2 TIMES------------------------------------------------------------------



------------------------------------------------------LACTIC ACID TIMES------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#LacticAcid') IS NOT NULL DROP TABLE #LacticAcid;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, PO.ORDER_PROC_ID

	, PO.ORDER_TIME AS MBOrderTime

	, LAB_ORDER_RESULTS.RESULT_TIME

	, LAB_ORDER_RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, LAB_ORDER_RESULTS.ORD_VALUE

INTO 

	#LacticAcid

FROM #Base_Pop B

	INNER JOIN dbo.LAB_ORDER_RESULTS ON LAB_ORDER_RESULTS.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN dbo.PROCEDURE_ORDERS PO ON PO.ORDER_PROC_ID = LAB_ORDER_RESULTS.ORDER_PROC_ID

WHERE

	LAB_ORDER_RESULTS.COMPONENT_ID IN (5000000446, 5000000447, 5000000449)



IF OBJECT_ID(N'tempdb..#ODLA') IS NOT NULL DROP TABLE #ODLA;

SELECT

	LASTLA.MBOrderTime [LAST LacticAcid Order Time],

	LASTLA.ORD_VALUE AS [LAST LacticAcid Result],

	CASE WHEN LASTLA.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST LacticAcid in Dept Y/N],

	A.*,

	FIRSTLA.MBOrderTime [FIRST LacticAcid Order Time],

	LASTLA.ORD_VALUE AS [FIRST LacticAcid Result],

	CASE WHEN FIRSTLA.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST LacticAcid in Dept Y/N]

INTO #ODLA

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 LA.MBOrderTime, LA.ORD_VALUE FROM #LacticAcid LA

		WHERE LA.ENCOUNTER_ID = A.ENCOUNTER_ID AND LA.MBOrderTime<A.RECORDED_TIME

		ORDER BY LA.MBOrderTime DESC

	)LASTLA

	OUTER APPLY

	(

		SELECT TOP 1 LA.MBOrderTime, LA.ORD_VALUE FROM #LacticAcid LA

		WHERE LA.ENCOUNTER_ID = A.ENCOUNTER_ID AND LA.MBOrderTime>=A.RECORDED_TIME

		ORDER BY LA.MBOrderTime ASC

	)FIRSTLA

--SELECT * FROM #ODLA

------------------------------------------------------END OF LACTIC ACID TIMES------------------------------------------------------------------



------------------------------------------------------PROCALCITONIN TIMES------------------------------------------------------------------

/*PROCALCITONIN*/

IF OBJECT_ID(N'tempdb..#Procalcitonin') IS NOT NULL DROP TABLE #Procalcitonin;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, PO.ORDER_TIME AS MBOrderTime

	, LAB_ORDER_RESULTS.RESULT_TIME

	, LAB_ORDER_RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, LAB_ORDER_RESULTS.ORD_VALUE

	, LAB_ORDER_RESULTS.ORDER_PROC_ID



INTO 

	#Procalcitonin

FROM #Base_Pop B

	INNER JOIN dbo.LAB_ORDER_RESULTS ON LAB_ORDER_RESULTS.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN dbo.PROCEDURE_ORDERS PO ON PO.ORDER_PROC_ID = LAB_ORDER_RESULTS.ORDER_PROC_ID

WHERE

	LAB_ORDER_RESULTS.COMPONENT_ID = 500001 --COULD USE PROC CODE ALSO.... LAB014

IF OBJECT_ID(N'tempdb..#ODPROCAL') IS NOT NULL DROP TABLE #ODPROCAL;

SELECT

	LASTPRO.MBOrderTime [LAST Procalcitonin Order Time],

	LASTPRO.ORD_VALUE AS [LAST Procalcitonin Result],

	CASE WHEN LASTPRO.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST Procalcitonin in Dept Y/N],

	A.*,

	FIRSTPRO.MBOrderTime [FIRST Procalcitonin Order Time],

	FIRSTPRO.ORD_VALUE AS [FIRST Procalcitonin Result],

	CASE WHEN FIRSTPRO.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST Procalcitonin in Dept Y/N]

INTO #ODPROCAL

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 PROCAL.MBOrderTime, PROCAL.ORD_VALUE FROM #Procalcitonin PROCAL

		WHERE PROCAL.ENCOUNTER_ID = A.ENCOUNTER_ID AND PROCAL.MBOrderTime<A.RECORDED_TIME

		ORDER BY PROCAL.MBOrderTime DESC

	)LASTPRO

	OUTER APPLY

	(

		SELECT TOP 1 PROCAL.MBOrderTime, PROCAL.ORD_VALUE FROM #Procalcitonin PROCAL

		WHERE PROCAL.ENCOUNTER_ID = A.ENCOUNTER_ID AND PROCAL.MBOrderTime>=A.RECORDED_TIME

		ORDER BY PROCAL.MBOrderTime ASC

	)FIRSTPRO

------------------------------------------------------END OF PROCALCITONIN TIMES------------------------------------------------------------------



------------------------------------------------------BLOOD CULTURE TIMES------------------------------------------------------------------

/*Blood Culture*/

IF OBJECT_ID(N'tempdb..#BloodCultureValue') IS NOT NULL DROP TABLE #BloodCultureValue;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, PO.ORDER_PROC_ID

	, PCAT.PROC_CODE AS [Blood Culture Procedure Ordered]

	, PO.ORDER_TIME AS MBOrderTime

	, RESULTS.RESULT_TIME

	, RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, RESULTS.ORD_VALUE

INTO 

	#BloodCultureValue 

FROM #Base_Pop B

	INNER JOIN dbo.LAB_ORDER_RESULTS RESULTS ON B.ENCOUNTER_ID = RESULTS.ENCOUNTER_ID

	INNER JOIN dbo.PROCEDURE_ORDERS PO  ON RESULTS.ORDER_PROC_ID = PO.ORDER_PROC_ID 

				AND PO.PROC_ID IN (600003,600004,600011,600012)

	INNER JOIN dbo.PROCEDURES_CATALOG PCAT ON PCAT.PROC_ID = PO.PROC_ID



IF OBJECT_ID(N'tempdb..#ODBC') IS NOT NULL DROP TABLE #ODBC;

SELECT

	LASTBC.MBOrderTime [LAST Blood Culture Order Time],

	LASTBC.[Blood Culture Procedure Ordered] AS [LAST Blood Culture Procedure Ordered],

	LASTBC.ORD_VALUE [LAST Blood Culture Result],

	CASE WHEN LASTBC.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST Blood Culture in Dept Y/N],

	A.*,

	FIRSTBC.MBOrderTime [FIRST Blood Culture Order Time],

	FIRSTBC.[Blood Culture Procedure Ordered] AS [FIRST Blood Culture Procedure Ordered],

	FIRSTBC.ORD_VALUE [FIRST Blood Culture Result],

	CASE WHEN FIRSTBC.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST Blood Culture in Dept Y/N]

INTO #ODBC

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 BC.[Blood Culture Procedure Ordered], BC.MBOrderTime, BC.ORD_VALUE FROM #BloodCultureValue BC

		WHERE BC.ENCOUNTER_ID = A.ENCOUNTER_ID AND BC.MBOrderTime<A.RECORDED_TIME

		ORDER BY BC.MBOrderTime DESC

	)LASTBC

	OUTER APPLY

	(

		SELECT TOP 1 BC.[Blood Culture Procedure Ordered], BC.MBOrderTime, BC.ORD_VALUE FROM #BloodCultureValue BC

		WHERE BC.ENCOUNTER_ID = A.ENCOUNTER_ID AND BC.MBOrderTime>=A.RECORDED_TIME

		ORDER BY BC.MBOrderTime ASC

	)FIRSTBC

--SELECT * FROM #ODBC



------------------------------------------------------END OF BLOOD CULTURE TIMES------------------------------------------------------------------



------------------------------------------------------CSF TIMES------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#CSF') IS NOT NULL DROP TABLE #CSF;

SELECT

	B.ENCOUNTER_ID

	, B.ADT_DEPARTMENT_ID

	, B.ADT_DEPARTMENT_NAME

	, B.IN_DTTM

	, B.OUT_DTTM

	, PO.ORDER_PROC_ID

	, PCAT.PROC_CODE as [CSF Procedure Ordered]

	, PO.ORDER_TIME AS MBOrderTime

	, RESULTS.RESULT_TIME

	, RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, RESULTS.ORD_VALUE

INTO 

	#CSF 

FROM #Base_Pop B

	INNER JOIN dbo.LAB_ORDER_RESULTS RESULTS ON B.ENCOUNTER_ID = RESULTS.ENCOUNTER_ID

	INNER JOIN dbo.PROCEDURE_ORDERS PO  ON RESULTS.ORDER_PROC_ID = PO.ORDER_PROC_ID

				--AND PO.PROC_CODE IN ('LAB006','LAB007') AND PO.SPECIMEN_SOURCE_CODE=304 --PER STEPHANIE, USE THOSE LAB CODES WITH SPECIMEN SOURCE AS LUMBAR PUNCTURE--('LAB005','LAB013','LAB004')

				AND PROC_ID IN (600005,600006) AND PO.SPECIMEN_SOURCE_CODE=304

	INNER JOIN dbo.PROCEDURES_CATALOG PCAT ON PCAT.PROC_ID = PO.PROC_ID





--SELECT * FROM #CSF

IF OBJECT_ID(N'tempdb..#ODCSF') IS NOT NULL DROP TABLE #ODCSF;

SELECT

	LASTCSF.MBOrderTime [LAST CSF Order Time],

	LASTCSF.[CSF Procedure Ordered] AS [LAST CSF Ordered],

	CASE WHEN LASTCSF.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST CSF in Dept Y/N],

	A.*,

	FIRSTCSF.MBOrderTime [FIRST CSF Order Time],

	FIRSTCSF.[CSF Procedure Ordered] AS [FIRST CSF Ordered],

	CASE WHEN FIRSTCSF.MBOrderTime BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST CSF in Dept Y/N]

INTO #ODCSF

FROM #Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 CSF.[CSF Procedure Ordered], CSF.MBOrderTime FROM #CSF CSF

		WHERE CSF.ENCOUNTER_ID = A.ENCOUNTER_ID AND CSF.MBOrderTime<A.RECORDED_TIME

		ORDER BY CSF.MBOrderTime DESC

	)LASTCSF

	OUTER APPLY

	(

		SELECT TOP 1 CSF.[CSF Procedure Ordered], CSF.MBOrderTime FROM #CSF CSF

		WHERE CSF.ENCOUNTER_ID = A.ENCOUNTER_ID AND CSF.MBOrderTime>=A.RECORDED_TIME

		ORDER BY CSF.MBOrderTime ASC

	)FIRSTCSF



------------------------------------------------------END OF CSF TIMES------------------------------------------------------------------



------------------------------------------------------ETT TIMES------------------------------------------------------------------

/*ETT*/

IF OBJECT_ID(N'tempdb..#ETT') IS NOT NULL DROP TABLE #ETT;

SELECT

	B.ENCOUNTER_ID,

	B.ADT_DEPARTMENT_ID,

	B.ADT_DEPARTMENT_NAME,

	B.IN_DTTM,

	B.OUT_DTTM,

	LNA.IP_LDA_ID,

	LNA.PLACEMENT_INSTANT

INTO #ETT

FROM #Base_Pop B

	INNER JOIN dbo.LINE_DEVICE_AIRWAY LNA ON LNA.ENCOUNTER_ID = B.ENCOUNTER_ID AND LNA.FLO_MEAS_ID='900112' AND LNA.PLACEMENT_INSTANT IS NOT NULL





IF OBJECT_ID(N'tempdb..#ODETT') IS NOT NULL DROP TABLE #ODETT;

SELECT

	LASTETT.PLACEMENT_INSTANT [LAST Intubation Time],

	CASE WHEN LASTETT.PLACEMENT_INSTANT BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST ETT in Dept Y/N],

	A.*,

	FIRSTETT.PLACEMENT_INSTANT [FIRST Intubation Time],

	CASE WHEN FIRSTETT.PLACEMENT_INSTANT BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST ETT in Dept Y/N]

INTO #ODETT

FROM

	#Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 ETT.PLACEMENT_INSTANT FROM #ETT ETT

		WHERE ETT.ENCOUNTER_ID = A.ENCOUNTER_ID AND ETT.PLACEMENT_INSTANT<A.RECORDED_TIME

		ORDER BY ETT.PLACEMENT_INSTANT DESC

	)LASTETT

	OUTER APPLY

	(

		SELECT TOP 1 ETT.PLACEMENT_INSTANT FROM #ETT ETT

		WHERE ETT.ENCOUNTER_ID = A.ENCOUNTER_ID AND ETT.PLACEMENT_INSTANT>=A.RECORDED_TIME

		ORDER BY ETT.PLACEMENT_INSTANT ASC

	)FIRSTETT





------------------------------------------------------END OF ETT TIMES------------------------------------------------------------------



------------------------------------------------------PIV TIMES------------------------------------------------------------------

/*PIV*/

IF OBJECT_ID(N'tempdb..#PIV') IS NOT NULL DROP TABLE #PIV;

SELECT

	B.ENCOUNTER_ID,

	B.ADT_DEPARTMENT_ID,

	B.ADT_DEPARTMENT_NAME,

	B.IN_DTTM,

	B.OUT_DTTM,

	LNA.IP_LDA_ID,

	LNA.PLACEMENT_INSTANT

INTO #PIV

FROM #Base_Pop B

	INNER JOIN dbo.LINE_DEVICE_AIRWAY LNA ON LNA.ENCOUNTER_ID = B.ENCOUNTER_ID AND LNA.FLO_MEAS_ID='900111' AND LNA.PLACEMENT_INSTANT IS NOT NULL



IF OBJECT_ID(N'tempdb..#ODPIV') IS NOT NULL DROP TABLE #ODPIV;

SELECT

	LASTPIV.PLACEMENT_INSTANT [LAST PIV Before Screen],

	CASE WHEN LASTPIV.PLACEMENT_INSTANT BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [LAST PIV in Dept Y/N],

	A.*,

	FIRSTPIV.PLACEMENT_INSTANT [FIRST PIV After Screen],

	CASE WHEN FIRSTPIV.PLACEMENT_INSTANT BETWEEN A.IN_DTTM AND A.OUT_DTTM THEN 'Y' ELSE 'N' END AS [FIRST PIV in Dept Y/N]

INTO #ODPIV

FROM

	#Base_Pop_OD_Scores A

	OUTER APPLY

	(

		SELECT TOP 1 PIV.PLACEMENT_INSTANT FROM #PIV PIV

		WHERE PIV.ENCOUNTER_ID = A.ENCOUNTER_ID AND PIV.PLACEMENT_INSTANT<A.RECORDED_TIME

		ORDER BY PIV.PLACEMENT_INSTANT DESC

	)LASTPIV

	OUTER APPLY

	(

		SELECT TOP 1 PIV.PLACEMENT_INSTANT FROM #PIV PIV

		WHERE PIV.ENCOUNTER_ID = A.ENCOUNTER_ID AND PIV.PLACEMENT_INSTANT>=A.RECORDED_TIME

		ORDER BY PIV.PLACEMENT_INSTANT ASC

	)FIRSTPIV



------------------------------------------------------END OF PIV TIMES------------------------------------------------------------------



------------------------------------------------------ PROPHYLAXIS ------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#PROPHYLAXIS') IS NOT NULL DROP TABLE #PROPHYLAXIS;

SELECT

	B.ENCOUNTER_ID,

	CASE WHEN COUNT(FM.RECORDED_TIME)>0 THEN 'Y' ELSE 'N' END AS PROPHYLAXIS_FLAG

INTO #PROPHYLAXIS

FROM #Base_Pop B

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID AND FM.RECORDED_TIME IS NOT NULL

		AND FM.FLO_MEAS_ID IN ('9000613042','9000613043','9000613044','9000613045','9000613047','9000613048','9000613050')

		--9000613042	R HS IP VTE AMBULATION ACTION

		--9000613043	R HS IP VTE SCD ACTION

		--9000613044	R HS IP VTE BOOTS ACTION

		--9000613045	R HS IP VTE HEMATOLOGY ACTION

		--9000613047	R HS IP VTE COUMADIN ACTION

		--9000613048	R HS IP VTE HEPARIN ACTION

	--9000613050	R HS IP VTE COMPLICATION ACTIONS

GROUP BY B.ENCOUNTER_ID



------------------------------------------------------END OF PROPHYLAXIS------------------------------------------------------------------



------------------------------------------------------ CVVH ------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#CVVH') IS NOT NULL DROP TABLE #CVVH;

SELECT

	B.ENCOUNTER_ID,

	CASE WHEN COUNT(FM.RECORDED_TIME)>0 THEN 'Y' ELSE 'N' END AS CVVH_FLAG

INTO #CVVH

FROM #Base_Pop B

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID 

		AND FM.FLT_ID='9000001359'--ANY FLOWSHEET FROM THIS TEMPLATE IS A CANDIDATE

	--9000001359	T HS IP INPATIENT CVVH	Inpatient CVVH	



GROUP BY B.ENCOUNTER_ID



------------------------------------------------------END OF CVVH------------------------------------------------------------------

------------------------------------------------------ CEREBRAL OX MONITORING ------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#OX') IS NOT NULL DROP TABLE #OX;

SELECT

	B.ENCOUNTER_ID,

	CASE WHEN COUNT(FM.RECORDED_TIME)>0 THEN 'Y' ELSE 'N' END AS OX_FLAG

INTO #OX

FROM #Base_Pop B

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID 

		AND FM.FLO_MEAS_ID IN ('900201','900202','900203','9000001977')

	--FLO   900201		R AN NEAR-INFRARED SPECTROSCOPY LEFT CEREBRAL	(Cerebral Oximetry)

	--FLO   900202		R AN NEAR-INFRARED SPECTROSCOPY RIGHT CEREBRAL	(Cerebral Oximetry)

	--FLO   900203		R AN NEAR-INFRARED SPECTROSCOPY RENAL			(Cerebral Oximetry)

	--FLO   9000001977  R HS IP NEAR-INFRARED SPECTROSCOPY CEREBRAL		(Cerebral Oximetry)

GROUP BY B.ENCOUNTER_ID



------------------------------------------------------END OF CEREBRAL OX MONITORING------------------------------------------------------------------

------------------------------------------------------ ECMO ------------------------------------------------------------------

IF OBJECT_ID(N'tempdb..#ECMO') IS NOT NULL DROP TABLE #ECMO;

SELECT

	B.ENCOUNTER_ID,

	CASE WHEN COUNT(FM.RECORDED_TIME)>0 THEN 'Y' ELSE 'N' END AS ECMO_FLAG

INTO #ECMO

FROM #Base_Pop B

	INNER JOIN dbo.FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID 

		AND FM.FLO_MEAS_ID ='9000101014'

	--9000101014	R ECMO ON/OFF

GROUP BY B.ENCOUNTER_ID



------------------------------------------------------END OF ECMO------------------------------------------------------------------



IF OBJECT_ID(N'tempdb..#FINAL') IS NOT NULL DROP TABLE #FINAL;

SELECT

	Main.PATIENT_NAME,

	Main.PATIENT_MRN,

	Main.[Ethnic Group],

	Main.[Race],

	Main.ENCOUNTER_ID,

	Main.AGE_MONTHS,

	Main.AGE_YEARS,

	Main.INP_ADM_DATE,

	Main.HOSP_DISCH_TIME,

	Main.Disposition,

	Main.LOS_HRS,

	ENC_RSN.AllEncReasons AS [Encounter Diagnoses],

	HYPO.[LAST Hypotension Time],

	HYPO.[LAST Hypotension Value],

	HYPO.[LAST Hypotension taken in Dept Y/N],

	HYPO.[FIRST Hypotension Time],

	HYPO.[FIRST Hypotension Value],

	HYPO.[FIRST Hypotension taken in Dept Y/N],

	WT.EncWeight,

	EDLOS.MEAS_VALUE [First Positive Score in ED],

	EDLOS.RECORDED_TIME AS [First Positive Score Time in ED],

	EDLOS.HoursInED AS [ED LOS (Hrs)],

	BP.ADT_DEPARTMENT_NAME,

	BP.DEPARTMENT_ROLLUP,

	BP.IN_DTTM [In Department Time],

	BP.OUT_DTTM [Out Department Time],

	SCORES.MEAS_VALUE AS OD_SCORE,

	SCORES.RECORDED_TIME as [Score Time],

	CASE WHEN SCORES.RECORDED_TIME IS NOT NULL

			THEN CASE WHEN DATEPART(HOUR,SCORES.RECORDED_TIME) >= 7 and DATEPART(HOUR,SCORES.RECORDED_TIME) < 19 then 'AM (Day Shift)'

						ELSE 'PM (Night Shift)'

					END

	END AS [OD Score AM/PM],

	SCORES.[Sepsis PATIENTS Huddle or Sepis CLINICAL_ALERTS Called//Performed with a MD/PNP],

	SCORES.[Huddle Date],

	SCORES.[Huddle Time],

	SCORES.[PATIENTS Assessed by MD/PNP],

	SCORES.[Physician Name],

	SCORES.[Additional Orders Received/Placed by MD/PNP],

	ABX.LASTABX_TIME [LAST ABX Time],

	ABX.LASTABX_NAME [LAST ABX Name],

	ABX.[LAST ABX Volume],

	ABX.[Last ABX to OD Score Time],

	ABX.[LAST ABX Given in Dept Y/N],

	ABX.FIRSTABX_TIME [FIRST ABX Time],

	ABX.FIRSTABX_NAME [FIRST ABX Name],

	ABX.[FIRST ABX Volume],

	ABX.[OD Score to First ABX Time],

	ABX.[FIRST ABX Given in Dept Y/N],

	CASE WHEN (ABX.LASTABX_TIME IS NOT NULL OR ABX.FIRSTABX_TIME IS NOT NULL) THEN 'Y' ELSE 'N' END AS ABX_FLAG,

	BOL.[LAST Bolus Time],

	BOL.[LAST Bolus],

	BOL.[LAST Bolus Volume],

	BOL.[Last Bolus to Screen Time],

	BOL.[LAST Bolus Given in Dept Y/N],

	BOL.[FIRST Bolus Time],

	BOL.[FIRST Bolus],

	BOL.[FIRST Bolus Volume],

	BOL.[Screen Time to First Bolus],

	BOL.[FIRST Bolus Given in Dept Y/N],

	CASE WHEN (BOL.[LAST Bolus Time] IS NOT NULL OR BOL.[FIRST Bolus Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS BOLUS_FLAG,

	LA.[LAST LacticAcid Order Time],

	LA.[LAST LacticAcid Result],

	LA.[LAST LacticAcid in Dept Y/N],

	LA.[FIRST LacticAcid Order Time],

	LA.[FIRST LacticAcid Result],

	LA.[FIRST LacticAcid in Dept Y/N],

	CASE WHEN (LA.[LAST LacticAcid Order Time] IS NOT NULL OR LA.[FIRST LacticAcid Order Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS LACTICACID_FLAG,

	ORDS.[LAST OrderSet Time],

	ORDS.[LAST OrderSet ID],

	ORDS.[LAST OrderSet in Dept Y/N],

	ORDS.[FIRST OrderSet Time],

	ORDS.[FIRST OrderSet ID],

	ORDS.[FIRST OrderSet in Dept Y/N],

	CVL.[LAST CVL Time],

	CVL.[LAST CVL in Dept Y/N],

	CVL.[FIRST CVL Time],

	CVL.[FIRST CVL in Dept Y/N],

	CASE WHEN (CVL.[LAST CVL Time] IS NOT NULL OR CVL.[FIRST CVL Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS CVL_FLAG,

	SVO2.[LAST SVO2 Time],

	SVO2.[LAST SVO2 in Dept Y/N],

	SVO2.[FIRST SVO2 Time],

	SVO2.[FIRST SVO2 in Dept Y/N],

	CASE WHEN (SVO2.[LAST SVO2 Time] IS NOT NULL OR SVO2.[FIRST SVO2 Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS SVO2_FLAG,

	PROCAL.[LAST Procalcitonin Order Time],

	PROCAL.[LAST Procalcitonin Result],

	PROCAL.[LAST Procalcitonin in Dept Y/N],

	PROCAL.[FIRST Procalcitonin Order Time],

	PROCAL.[FIRST Procalcitonin Result],

	PROCAL.[FIRST Procalcitonin in Dept Y/N],

	CASE WHEN (PROCAL.[LAST Procalcitonin Order Time] IS NOT NULL OR PROCAL.[FIRST Procalcitonin Order Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS PROCALCITONIN_FLAG,

	BC.[LAST Blood Culture Order Time],

	BC.[LAST Blood Culture Procedure Ordered],

	BC.[LAST Blood Culture Result],

	BC.[LAST Blood Culture in Dept Y/N],

	BC.[FIRST Blood Culture Order Time],

	BC.[FIRST Blood Culture Procedure Ordered],

	BC.[FIRST Blood Culture Result],

	BC.[FIRST Blood Culture in Dept Y/N],

	CASE WHEN (BC.[LAST Blood Culture Order Time] IS NOT NULL OR BC.[FIRST Blood Culture Order Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS BLOODCULTURE_FLAG,

	CSF.[LAST CSF Order Time],

	CSF.[LAST CSF Ordered],

	CSF.[LAST CSF in Dept Y/N],

	CSF.[FIRST CSF Order Time],

	CSF.[FIRST CSF Ordered],

	CSF.[FIRST CSF in Dept Y/N],

	CASE WHEN (CSF.[LAST CSF Order Time] IS NOT NULL OR CSF.[FIRST CSF Order Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS CSF_FLAG,

	PIV.[LAST PIV Before Screen],

	PIV.[LAST PIV in Dept Y/N],

	PIV.[FIRST PIV After Screen],

	PIV.[FIRST PIV in Dept Y/N],

	CASE WHEN (PIV.[LAST PIV Before Screen] IS NOT NULL OR PIV.[FIRST PIV After Screen] IS NOT NULL) THEN 'Y' ELSE 'N' END AS PIV_FLAG,

	ETT.[LAST Intubation Time],

	ETT.[LAST ETT in Dept Y/N],

	ETT.[FIRST Intubation Time],

	ETT.[FIRST ETT in Dept Y/N],

	CASE WHEN (ETT.[LAST Intubation Time] IS NOT NULL OR ETT.[FIRST Intubation Time] IS NOT NULL) THEN 'Y' ELSE 'N' END AS ETT_FLAG,

	CASE WHEN PRESSOR.DOBUTAMINE IS NULL THEN 'N' ELSE 'Y' END DOBUTAMINE,

	CASE WHEN PRESSOR.DOPAMINE IS NULL THEN 'N' ELSE 'Y' END DOPAMINE,

	CASE WHEN PRESSOR.EPINEPHRINE IS NULL THEN 'N' ELSE 'Y' END EPINEPHRINE,

	CASE WHEN PRESSOR.MILRINONE IS NULL THEN 'N' ELSE 'Y' END MILRINONE,

	CASE WHEN PRESSOR.NOREPINEPHRINE IS NULL THEN 'N' ELSE 'Y' END NOREPINEPHRINE,

	CASE WHEN (

				PRESSOR.DOBUTAMINE IS NOT NULL OR

				PRESSOR.DOPAMINE IS NOT NULL OR

				PRESSOR.EPINEPHRINE IS NOT NULL OR

				PRESSOR.MILRINONE IS NOT NULL OR

				PRESSOR.NOREPINEPHRINE IS NOT NULL) THEN 'Y' ELSE 'N' END AS PRESSOR_FLAG,

	COALESCE(PROPHY.PROPHYLAXIS_FLAG,'N') AS DVTPROPHYLAXIS_FLAG,

	COALESCE(CVVH.CVVH_FLAG,'N') AS CVVH_FLAG,

	COALESCE(OX.OX_FLAG,'N') AS OX_FLAG,

	COALESCE(ECMO.ECMO_FLAG,'N') AS ECMO_FLAG,

	CASE WHEN SSS.ENCOUNTER_ID IS NULL THEN 'N' ELSE 'Y' END SEVERE_SEPSIS_STAGING,

	SCORES.[CLINICAL_ALERTS Not Activated Reason],

	SCORES.[CLINICAL_ALERTS Not Activated Comment],

	SCORES.[CLINICAL_ALERTS Activated Comment],

	GETDATE() AS [Refresh Time]

INTO #FINAL

FROM #Main Main

	INNER JOIN #Base_Pop BP ON BP.ENCOUNTER_ID = Main.ENCOUNTER_ID

	INNER JOIN #Base_Pop_OD_Scores SCORES ON SCORES.ENCOUNTER_ID = BP.ENCOUNTER_ID AND SCORES.ADT_DEPARTMENT_ID = BP.ADT_DEPARTMENT_ID AND SCORES.IN_DTTM = BP.IN_DTTM

	LEFT OUTER JOIN #Base_Pop_ENC_Reason ENC_RSN ON ENC_RSN.ENCOUNTER_ID = Main.ENCOUNTER_ID

	LEFT OUTER JOIN #EncounterWeights WT ON WT.ENCOUNTER_ID = Main.ENCOUNTER_ID AND WT.TIME_LINE=1

	LEFT OUTER JOIN #ODHYPO HYPO ON HYPO.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND HYPO.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND HYPO.IN_DTTM = SCORES.IN_DTTM AND HYPO.TIME_LINE=1

	LEFT OUTER JOIN #ODABX ABX ON ABX.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND ABX.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND ABX.IN_DTTM = SCORES.IN_DTTM AND ABX.TIME_LINE=1

	LEFT OUTER JOIN #OdboL BOL ON BOL.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND BOL.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND BOL.IN_DTTM = SCORES.IN_DTTM AND BOL.TIME_LINE=1

	LEFT OUTER JOIN #ODLA LA ON LA.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND LA.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND LA.IN_DTTM = SCORES.IN_DTTM AND LA.TIME_LINE=1

	LEFT OUTER JOIN #ODORDSET ORDS ON ORDS.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND ORDS.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND ORDS.IN_DTTM = SCORES.IN_DTTM AND ORDS.TIME_LINE=1

	LEFT OUTER JOIN #ODCVL CVL ON CVL.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND CVL.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND CVL.IN_DTTM = SCORES.IN_DTTM AND CVL.TIME_LINE=1

	LEFT OUTER JOIN #ODPressorPivot PRESSOR ON PRESSOR.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND SCORES.TIME_LINE=1--CHECK THIS AGAIN

	LEFT OUTER JOIN #ODSVO2 SVO2 ON SVO2.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND SVO2.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND SVO2.IN_DTTM = SCORES.IN_DTTM AND SVO2.TIME_LINE=1

	LEFT OUTER JOIN #ODPROCAL PROCAL ON PROCAL.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND PROCAL.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND PROCAL.IN_DTTM = SCORES.IN_DTTM AND PROCAL.TIME_LINE=1

	LEFT OUTER JOIN #ODBC BC ON BC.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND BC.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND BC.IN_DTTM = SCORES.IN_DTTM AND BC.TIME_LINE=1

	LEFT OUTER JOIN #ODCSF CSF ON CSF.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND CSF.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND CSF.IN_DTTM = SCORES.IN_DTTM AND CSF.TIME_LINE=1

	LEFT OUTER JOIN #ODPIV PIV ON PIV.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND PIV.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND PIV.IN_DTTM = SCORES.IN_DTTM AND PIV.TIME_LINE=1

	LEFT OUTER JOIN #ODETT ETT ON ETT.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND ETT.ADT_DEPARTMENT_ID = SCORES.ADT_DEPARTMENT_ID AND ETT.IN_DTTM = SCORES.IN_DTTM AND ETT.TIME_LINE=1

	LEFT OUTER JOIN #PROPHYLAXIS PROPHY ON PROPHY.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND SCORES.TIME_LINE=1

	LEFT OUTER JOIN #CVVH CVVH ON CVVH.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND SCORES.TIME_LINE=1

	LEFT OUTER JOIN #OX OX ON OX.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND SCORES.TIME_LINE=1

	LEFT OUTER JOIN #ECMO ECMO ON ECMO.ENCOUNTER_ID = SCORES.ENCOUNTER_ID AND SCORES.TIME_LINE=1

	LEFT OUTER JOIN #EDPosScore_EDLOS EDLOS ON EDLOS.ENCOUNTER_ID = MAIN.ENCOUNTER_ID AND EDLOS.FIRST_TIME_LINE=1

	LEFT OUTER JOIN [reports].[SEVERE_SEPSIS_STAGING] SSS ON SSS.ENCOUNTER_ID = Main.ENCOUNTER_ID





DROP INDEX  IX_InpDataID  ON #Main , IX_PatID  ON #Main;



SELECT * FROM #FINAL order by ENCOUNTER_ID

GO

