
-- ==== reports/USP_RPTS_IP_SEPSIS_COMPLIANCE.sql ====
/*

/*********************************************************************************

	TITLE:		 Sepsis Compliance

	PURPOSE:	 Sepsis Scoring compliance report by unit

	AUTHOR:		 V_DEV001



	REVISION HISTORY:

				11.16.2021 V_DEV001 - Original version

				05.22.2022 V_DEV001 - Location  update for Expansion Phase III



*********************************************************************************

	USAGE:

		EXEC [reports].[USP_IP_SEPSIS_COMPLIANCE] '09/01/2021','09/30/2021',0

*********************************************************************************/

*/

CREATE   PROCEDURE [reports].[USP_IP_SEPSIS_COMPLIANCE](

@i_vRelativeStartDate DATE = NULL

	, @i_vRelativeEndDate DATE = NULL

	--, @i_vRelative15OREOM bit = null 

)

AS

SET NOCOUNT ON;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;	

BEGIN



	--BEGIN TRY

	SET NOCOUNT ON;

	

	DECLARE @dStartDate DATE

	DECLARE @dEndDate DATE

	DECLARE @dTestRun BIT

	

	IF @i_vRelativeStartDate IS NULL OR @i_vRelativeStartDate = ''

		SET @dStartDate = dbo.fn_parse_date('MB-3')

						

	ELSE

		SET @dStartDate = [dbo].[fn_parse_date](@i_vRelativeStartDate)



	IF @i_vRelativeEndDate IS NULL OR @i_vRelativeEndDate = ''

		SET @dEndDate = [dbo].[fn_parse_date]('ME-1')

	ELSE

		SET @dEndDate = [dbo].[fn_parse_date](@i_vRelativeEndDate)	

	/*

	IF @i_vRelative15OREOM IS NULL OR @i_vRelative15OREOM = ''

		set @dTestRun = 0

		else 	set @dTestRun = 1

	*/



IF OBJECT_ID(N'tempdb..#Main') IS NOT NULL DROP TABLE #Main;

SELECT

	PAT.PATIENT_MRN AS MRN

	, PAT.PATIENT_NAME AS [PATIENTS]

	, HE.ENCOUNTER_ID

	, HE.INP_ADM_DATE AS [IP Admit Time]

	, HE.INPATIENT_DATA_ID

	, PLH.ADT_DEPARTMENT_ID

	, PLH.ADT_DEPARTMENT_NAME

	, loc.LOC_NAME [Location]

	, PLH.IN_DTTM

	, PLH.OUT_DTTM

	, DT.CALENDAR_DT

	, DT.MONTH_END_DT

	, DT.DAY_OF_MONTH

	, HE.HOSP_DISCH_TIME

INTO 

	#Main

FROM 

dbo.V_PATIENT_LOCATION_HISTORY PLH

	INNER JOIN dbo.HOSPITAL_ENCOUNTERS HE ON HE.ENCOUNTER_ID = PLH.ENCOUNTER_NUM

	INNER JOIN dbo.PATIENTS PAT ON PAT.PATIENT_ID = HE.PATIENT_ID

	INNER JOIN dbo.CALENDAR_DATES DT ON (DT.CALENDAR_DT BETWEEN CONVERT(DATE,PLH.IN_DTTM) AND CONVERT(DATE,PLH.OUT_DTTM))

	left outer join dbo.DEPARTMENTS dep on dep.DEPARTMENT_ID = PLH.ADT_DEPARTMENT_ID

	left outer join dbo.LOCATIONS loc on loc.loc_id = dep.REV_LOC_ID

WHERE

	PLH.ADT_DEPARTMENT_ID IS NOT NULL AND

	HE.INP_ADM_DATE IS NOT NULL

	AND (CONVERT(DATE,DT.CALENDAR_DT) BETWEEN @dStartDate AND @dEndDate)



IF OBJECT_ID(N'tempdb..#Base_Pop_OD_Scores') IS NOT NULL DROP TABLE #Base_Pop_OD_Scores;

SELECT

	PD.[PATIENTS]

	, PD.[MRN]

	, PD.ENCOUNTER_ID

	, PD.[IP Admit Time]

	, COALESCE(CVS.CODE_DESC,'Rollup Not Available') AS DEPARTMENT_ROLLUP

	, PD.ADT_DEPARTMENT_ID

	, PD.ADT_DEPARTMENT_NAME

	, PD.[Location]

	, PD.IN_DTTM

	, PD.OUT_DTTM

	, SEPSIS.MEAS_VALUE

	, SEPSIS.RECORDED_TIME AS [OD Score Time]

	, ALERTNOTACTIVATED.[CLINICAL_ALERTS Not Activated Reason]

	, ALERTNOTACTIVATED.[CLINICAL_ALERTS Not Activated Comment]

	, ALERTACTIVATED.[CLINICAL_ALERTS Activated Comment]

	, DATEADD(MI,420,DATEADD(DD, 0, DATEDIFF(DD, 0, PD.CALENDAR_DT))) AS SHIFT1_START

	, DATEADD(MI,1139,DATEADD(DD, 0, DATEDIFF(DD, 0, PD.CALENDAR_DT))) AS SHIFT1_END

	, DATEADD(MI,419,DATEADD(DD, 1, DATEDIFF(DD, 0, PD.CALENDAR_DT))) AS SHIFT2_END

	, CASE WHEN CAST (SEPSIS.RECORDED_TIME AS TIME) BETWEEN CAST ('00:01:00.0000000' AS TIME) AND CAST ('06:59:00.0000000' AS TIME) THEN 

		DATEADD(DD,-1,CONVERT(DATE,SEPSIS.RECORDED_TIME)) ELSE CALENDAR_DT  END AS CALENDAR_DT

	, SepsisAlert.*

	, ROW_NUMBER() OVER(PARTITION BY PD.ENCOUNTER_ID ORDER BY SEPSIS.RECORDED_TIME ASC) AS TIME_LINE

	, ROW_NUMBER() OVER(PARTITION BY PD.ENCOUNTER_ID, PD.IN_DTTM,PD.OUT_DTTM ORDER BY SEPSIS.RECORDED_TIME ASC) AS DEPT_TIME_LINE

	, PD.HOSP_DISCH_TIME AS [Discharge Time]

	, PD.DAY_OF_MONTH

	, PD.MONTH_END_DT

INTO 

	#Base_Pop_OD_Scores 

FROM #Main PD

	LEFT OUTER JOIN

	(

		SELECT

			FR.INPATIENT_DATA_ID, FR.FSD_ID, FM.MEAS_VALUE, FM.RECORDED_TIME

		FROM dbo.FLOWSHEET_RECORDS FR

			INNER JOIN dbo.FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID

		WHERE FM.FLO_MEAS_ID IN ('9000161711','9000002644') --ORGAN DYSFUNCTION SCORE

	)SEPSIS ON SEPSIS.INPATIENT_DATA_ID = PD.INPATIENT_DATA_ID

			AND (SEPSIS.RECORDED_TIME BETWEEN PD.IN_DTTM AND PD.OUT_DTTM)

			AND CONVERT(DATE,SEPSIS.RECORDED_TIME) = PD.CALENDAR_DT

	LEFT OUTER JOIN reports.CONFIG_VALUE_SET CVS ON CVS.CODE = PD.ADT_DEPARTMENT_ID

				AND CVS.VALUE_SET_ID = 3031 --DEPARTMENT ROLL UP

	OUTER APPLY

	(

		SELECT

			TOP 1  EMP.NAME AS [Note Author], CNOTE.CRT_INST_LOCAL_DTTM AS [Note Created Time]

		FROM dbo.CLINICAL_NOTES CNOTE

			LEFT JOIN dbo.NOTE_TEMPLATE_TEXT_IDS ETX ON ETX.NOTE_ID = CNOTE.NOTE_ID

			LEFT JOIN dbo.NOTE_TEMPLATE_LIST_IDS LIS ON LIS.NOTE_ID = CNOTE.NOTE_ID

			INNER JOIN dbo.NOTE_ENCOUNTER_INFO HNOENC ON HNOENC.NOTE_ID = CNOTE.NOTE_ID

			INNER JOIN dbo.EMPLOYEES EMP ON EMP.USER_ID = HNOENC.AUTHOR_USER_ID

		WHERE

			CNOTE.ENCOUNTER_ID = PD.ENCOUNTER_ID

			AND (CNOTE.CRT_INST_LOCAL_DTTM BETWEEN SEPSIS.RECORDED_TIME AND DATEADD(MI, 180, SEPSIS.RECORDED_TIME))--within one hour from OD SCORE

			AND (ETX.SMARTTEXTS_ID='40440015' OR LIS.SMARTLISTS_ID='46214') --HS IP SEPSIS HUDDLE NOTE or Sepsis Eval SmartList

		ORDER BY CNOTE.CRT_INST_LOCAL_DTTM 

	)SepsisAlert

	LEFT OUTER JOIN

	(

		SELECT

			FR.INPATIENT_DATA_ID, IFM_ALERTNOTACTIVATED.FSD_ID, IFM_ALERTNOTACTIVATED.RECORDED_TIME, IFM_ALERTNOTACTIVATED.MEAS_VALUE AS [CLINICAL_ALERTS Not Activated Reason], IFM_ALERTNOTACTIVATED.MEAS_COMMENT as [CLINICAL_ALERTS Not Activated Comment]

		FROM dbo.FLOWSHEET_RECORDS FR

			INNER JOIN dbo.FLOWSHEET_MEASUREMENTS IFM_ALERTNOTACTIVATED ON IFM_ALERTNOTACTIVATED.FSD_ID = FR.FSD_ID

		WHERE

			IFM_ALERTNOTACTIVATED.FLO_MEAS_ID='9000003159'

	)ALERTNOTACTIVATED ON ALERTNOTACTIVATED.INPATIENT_DATA_ID = SEPSIS.INPATIENT_DATA_ID

		AND ALERTNOTACTIVATED.FSD_ID = SEPSIS.FSD_ID

		AND ALERTNOTACTIVATED.RECORDED_TIME = SEPSIS.RECORDED_TIME

	LEFT OUTER JOIN

	(

		SELECT

			ALT.ALT_ID,

			ALT.VISIT_ID,

			HIS.ALT_ACTION_INST,

			--COALESCE(HIS.SPEC_OVR_CMNT,' ')+ RSN.NAME [CLINICAL_ALERTS Activated Comment]

			HIS.SPEC_OVR_CMNT [CLINICAL_ALERTS Activated Comment]

		FROM dbo.CLINICAL_ALERTS ALT

			INNER JOIN dbo.ALERT_HISTORY HIS ON HIS.ALT_ID = ALT.ALT_ID

			INNER JOIN dbo.REF_ALERT_OVERRIDE_REASONS RSN ON RSN.ALRT_SP_OVR_RSN_CODE = HIS.SPEC_OVR_RSN_CODE

		WHERE ALT.BPA_LOCATOR_ID=900400001--BASE 2019 HS OD SCORE SEPSIS >2 [900400001]

	)ALERTACTIVATED ON ALERTACTIVATED.VISIT_ID = PD.ENCOUNTER_ID

		AND ALERTACTIVATED.ALT_ACTION_INST = SEPSIS.RECORDED_TIME



IF OBJECT_ID(N'tempdb..#SepsisSummary') IS NOT NULL DROP TABLE #SepsisSummary;

SELECT

	ENCOUNTER_ID,

	ADT_DEPARTMENT_ID,

	DEPARTMENT_ROLLUP,

	IN_DTTM,

	OUT_DTTM,

	ScoreDay,

	CASE WHEN (

			CASE WHEN SUM([Shift 1 Score])>=1 THEN 1 ELSE 0 END + 

			CASE WHEN sum([Shift 2 Score])>=1 THEN 1 ELSE 0 END )>1 THEN 'y' ELSE 'n'

	END AS SCORECOMPLIANT_FLAG

INTO #SepsisSummary

FROM

(

	SELECT

		[PATIENTS]

		,[MRN]

		,ENCOUNTER_ID

		,[IP Admit Time]

		,DEPARTMENT_ROLLUP

		,ADT_DEPARTMENT_ID

		,ADT_DEPARTMENT_NAME

		,IN_DTTM

		,OUT_DTTM

		,MEAS_VALUE

		,[OD Score Time]

		,CONVERT(DATE,CALENDAR_DT) as ScoreDay

		,CASE

			WHEN [OD Score Time] IS NULL THEN 0	

			WHEN --CHECK IF IP ADMIT DATE IS THE FIRST DAY OF SCORE

				CONVERT(DATE,[OD Score Time]) = CONVERT(DATE,[IP Admit Time])

				AND [IP Admit Time]  >= SHIFT1_END THEN 1

			WHEN --CHECK IF IP ADMIT DATE IS THE FIRST DAY OF SCORE

				CONVERT(DATE,[OD Score Time]) = CONVERT(DATE,IN_DTTM)

				AND IN_DTTM  >= SHIFT1_END THEN 1

			WHEN

				[OD Score Time] BETWEEN SHIFT1_START AND SHIFT1_END THEN 1

			ELSE 0

			END AS [Shift 1 Score]

		,CASE

			WHEN [OD Score Time] IS NULL THEN 0	

			WHEN --CHECK IF IP ADMIT DATE IS THE FIRST DAY OF SCORE

				CONVERT(DATE,[OD Score Time]) = CONVERT(DATE, [Discharge Time])

				AND [Discharge Time] <= SHIFT1_END THEN 1

			WHEN --CHECK IF IP ADMIT DATE IS THE FIRST DAY OF SCORE

				CONVERT(DATE,[OD Score Time]) = CONVERT(DATE, OUT_DTTM)

				AND OUT_DTTM <= SHIFT1_END THEN 1

			WHEN [OD Score Time] > SHIFT1_END AND [OD Score Time] <=SHIFT2_END THEN 1

			ELSE 0

			END AS [Shift 2 Score]

		,[Note Author]

		,[Note Created Time]

		,TIME_LINE

		,DEPT_TIME_LINE

		,[Discharge Time]

		,DAY_OF_MONTH

		,MONTH_END_DT

	FROM #Base_Pop_OD_Scores

) A

GROUP BY ENCOUNTER_ID, DEPARTMENT_ROLLUP, ADT_DEPARTMENT_ID, IN_DTTM, OUT_DTTM, ScoreDay--,DAY_OF_MONTH,MONTH_END_DT

ORDER BY ENCOUNTER_ID, ScoreDay



SELECT

	BASE.PATIENTS,

	BASE.MRN,

	BASE.ENCOUNTER_ID AS [ENC_ID],

	BASE.[IP Admit Time],

	CASE WHEN BASE.DEPARTMENT_ROLLUP IS NULL THEN 'Rollup Not Available' ELSE BASE.DEPARTMENT_ROLLUP END AS DEPARTMENT_ROLLUP,

	BASE.ADT_DEPARTMENT_NAME AS [Department],

	BASE.Location,

	BASE.IN_DTTM AS [Department In Time],

	BASE.OUT_DTTM AS [Department Out Time],

	BASE.CALENDAR_DT AS ScoreDay,

	TRY_CAST(BASE.MEAS_VALUE AS INT) AS [OD Score],

	BASE.[OD Score Time],

	BASE.[CLINICAL_ALERTS Not Activated Reason],

	BASE.[CLINICAL_ALERTS Not Activated Comment],

	BASE.[CLINICAL_ALERTS Activated Comment],

	BASE.[Note Author],

	BASE.[Note Created Time],

	CASE WHEN BASE.DEPT_TIME_LINE=1 AND SUMMARY.ENCOUNTER_ID IS NOT NULL THEN 'N' 

	WHEN BASE.DEPT_TIME_LINE=1 AND SUMMARY.ENCOUNTER_ID IS NULL THEN 'Y' 

	ELSE NULL END AS SCORECOMPLIANT_FLAG,

	[Discharge Time],

	BASE.DEPT_TIME_LINE,

	BASE.TIME_LINE,

	case when BASE.DAY_OF_MONTH = 15 OR BASE.MONTH_END_DT = CONVERT(DATE,BASE.[OD Score Time]) then 'True' else 'False' end as [15th or EOM]

FROM #Base_Pop_OD_Scores BASE

	LEFT OUTER JOIN--CHECK IF THERE IS AT LEAST ONE 'N' FOR A GIVEN CALENDAR DATE

	(

		SELECT

			SUMMARY.ENCOUNTER_ID, SUMMARY.IN_DTTM,SUMMARY.ScoreDay

			,ROW_NUMBER()OVER(PARTITION BY SUMMARY.ENCOUNTER_ID,SUMMARY.IN_DTTM ORDER BY SUMMARY.ScoreDay) AS MYLINE

		FROM #SepsisSummary SUMMARY

		WHERE

			 SUMMARY.SCORECOMPLIANT_FLAG='N'

	)SUMMARY ON SUMMARY.ENCOUNTER_ID = BASE.ENCOUNTER_ID

			AND SUMMARY.IN_DTTM = BASE.IN_DTTM

			AND BASE.DEPT_TIME_LINE=1

			AND SUMMARY.MYLINE=1

WHERE

	BASE.DEPARTMENT_ROLLUP not in ('Rollup Not Available','ER')

	/*AND	(

			(@dTestRun = 1 and

				(

					BASE.DAY_OF_MONTH = 15

					OR BASE.MONTH_END_DT = CONVERT(DATE,BASE.[OD Score Time])

				)

			) 

			

			or  @dTestRun = 0

		)*/

ORDER BY BASE.ENCOUNTER_ID,BASE.CALENDAR_DT, [OD Score Time]

END

GO

