-- Supplemental stubs: corpus-referenced tables the lineage seed
-- missed (write-targets, suppressed extractions). Generated by
-- scripts/build_demo_stub_supplement.py. Idempotent; GO-separated
-- so one failure can NEVER silently kill the rest of the batch.

IF OBJECT_ID('dbo.clinical_note_text') IS NULL
CREATE TABLE [dbo].[clinical_note_text] (
    [NOTE_ID] DECIMAL(18,4) NULL,
    [NOTE_TEXT] NVARCHAR(400) NULL
);
GO

IF OBJECT_ID('dbo.diagnoses_current_icd10') IS NULL
CREATE TABLE [dbo].[diagnoses_current_icd10] (
    [CODE] NVARCHAR(400) NULL,
    [DX_ID] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('dbo.dm_icu_stay') IS NULL
CREATE TABLE [dbo].[dm_icu_stay] (
    [ENCOUNTER_ID] DECIMAL(18,4) NULL,
    [ICU_STAY_END_DT] DATETIME2 NULL,
    [ICU_STAY_START_DT] DATETIME2 NULL,
    [PATIENT_ID] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('dbo.hospital_acct_px_list') IS NULL
CREATE TABLE [dbo].[hospital_acct_px_list] (
    [FINAL_ICD_PX_ID] DECIMAL(18,4) NULL,
    [HOSPITAL_ACCOUNT_ID] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('dbo.icd_procedure_codes') IS NULL
CREATE TABLE [dbo].[icd_procedure_codes] (
    [ICD_PX_ID] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('dbo.med_mix_components') IS NULL
CREATE TABLE [dbo].[med_mix_components] (
    [DRUG_ID] DECIMAL(18,4) NULL,
    [LINE] DECIMAL(18,4) NULL,
    [MEDICATION_ID] DECIMAL(18,4) NULL,
    [TYPE_CODE] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('dbo.patient_or_adm_link') IS NULL
CREATE TABLE [dbo].[patient_or_adm_link] (
    [LOG_ID] DECIMAL(18,4) NULL,
    [OR_LINK_VISIT_ID] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('dbo.v_log_based') IS NULL
CREATE TABLE [dbo].[v_log_based] (
    [IN_OR_DTTM] DATETIME2 NULL,
    [LOG_ID] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('reporting.ip_sepsisdetails') IS NULL
CREATE TABLE [reporting].[ip_sepsisdetails] (
    [ABXName] NVARCHAR(400) NULL,
    [ABXTime] DATETIME2 NULL,
    [ABXVolume] NVARCHAR(400) NULL,
    [BPPercentile] NVARCHAR(400) NULL,
    [BloodCultureOrderTime] DATETIME2 NULL,
    [BloodCultureProcedureOrdered] NVARCHAR(400) NULL,
    [BloodCultureResult] NVARCHAR(400) NULL,
    [Bolus] DATETIME2 NULL,
    [BolusTime] DATETIME2 NULL,
    [BolusVolume] NVARCHAR(400) NULL,
    [CALENDAR_DT] DATETIME2 NULL,
    [CSFOrderTime] DATETIME2 NULL,
    [CSFOrdered] NVARCHAR(400) NULL,
    [CSFValue] NVARCHAR(400) NULL,
    [CVVHYN] NVARCHAR(400) NULL,
    [DobutamineYN] NVARCHAR(400) NULL,
    [DopamineYN] NVARCHAR(400) NULL,
    [ECMOYN] NVARCHAR(400) NULL,
    [EDLosHours] NVARCHAR(400) NULL,
    [ENCORDER] NVARCHAR(400) NULL,
    [ENCOVERALLORDER] NVARCHAR(400) NULL,
    [EncounterWeight] NVARCHAR(400) NULL,
    [EpinephrineYN] NVARCHAR(400) NULL,
    [FirstPositiveScoreInED] NVARCHAR(400) NULL,
    [FirstPositiveScoreTimeInED] DATETIME2 NULL,
    [HypotensionTime] DATETIME2 NULL,
    [HypotensionValue] NVARCHAR(400) NULL,
    [IPSOSevereSepsisYN] NVARCHAR(400) NULL,
    [IntubationTime] DATETIME2 NULL,
    [LacticAcidOrderTime] DATETIME2 NULL,
    [LacticAcidResult] NVARCHAR(400) NULL,
    [MilrinoneYN] NVARCHAR(400) NULL,
    [NorepinephrineYN] NVARCHAR(400) NULL,
    [OXYN] NVARCHAR(400) NULL,
    [OrderSetID] NVARCHAR(400) NULL,
    [OrderSetTime] DATETIME2 NULL,
    [PATENCENCID] NVARCHAR(400) NULL,
    [PIVPlacementTime] DATETIME2 NULL,
    [PositiveODScore] NVARCHAR(400) NULL,
    [PressorYN] NVARCHAR(400) NULL,
    [ProcalcitoninOrderTime] DATETIME2 NULL,
    [ProcalcitoninResult] NVARCHAR(400) NULL,
    [RefreshDate] DATETIME2 NULL,
    [SepsisDate] DATETIME2 NULL,
    [UniqueRow] NVARCHAR(400) NULL,
    [UnitOrder] NVARCHAR(400) NULL
);
GO

IF OBJECT_ID('reporting.ip_sepsisencounters') IS NULL
CREATE TABLE [reporting].[ip_sepsisencounters] (
    [ADTArrivalTime] DATETIME2 NULL,
    [ADTDepartmentID] NVARCHAR(400) NULL,
    [ADTDepartmentName] NVARCHAR(400) NULL,
    [AgeMonths] NVARCHAR(400) NULL,
    [AgeYears] NVARCHAR(400) NULL,
    [AllEncDx] NVARCHAR(400) NULL,
    [AllEncReasons] NVARCHAR(400) NULL,
    [BirthDate] DATETIME2 NULL,
    [Disposition] NVARCHAR(400) NULL,
    [EDDepartureTime] DATETIME2 NULL,
    [ENCOUNTER_ID] DECIMAL(18,4) NULL,
    [EthnicGroup] NVARCHAR(400) NULL,
    [HospAdmsnTime] DATETIME2 NULL,
    [HospDischTime] DATETIME2 NULL,
    [INPATIENT_DATA_ID] DECIMAL(18,4) NULL,
    [InDepartmentTime] DATETIME2 NULL,
    [InpAdmDate] DATETIME2 NULL,
    [InpatientDataID] NVARCHAR(400) NULL,
    [Location] NVARCHAR(400) NULL,
    [LosHours] NVARCHAR(400) NULL,
    [OutDepartmentTime] DATETIME2 NULL,
    [PATENCENCID] NVARCHAR(400) NULL,
    [PATIENTMRN] NVARCHAR(400) NULL,
    [PatientID] NVARCHAR(400) NULL,
    [PatientName] NVARCHAR(400) NULL,
    [Race] NVARCHAR(400) NULL,
    [RefreshDate] DATETIME2 NULL,
    [UniqueRow] NVARCHAR(400) NULL
);
GO

IF OBJECT_ID('reporting.ip_sepsisencounterswlocations') IS NULL
CREATE TABLE [reporting].[ip_sepsisencounterswlocations] (
    [ADTArrivalTime] DATETIME2 NULL,
    [ADTDepartmentID] NVARCHAR(400) NULL,
    [ADTDepartmentName] NVARCHAR(400) NULL,
    [ADT_ARRIVAL_TIME] DATETIME2 NULL,
    [ADT_DEPARTMENT_ID] DECIMAL(18,4) NULL,
    [ADT_DEPARTMENT_NAME] NVARCHAR(400) NULL,
    [AGE_MONTHS] NVARCHAR(400) NULL,
    [AGE_YEARS] NVARCHAR(400) NULL,
    [AgeMonths] NVARCHAR(400) NULL,
    [AgeYears] NVARCHAR(400) NULL,
    [AllEncDx] NVARCHAR(400) NULL,
    [AllEncReasons] NVARCHAR(400) NULL,
    [BIRTH_DATE] DATETIME2 NULL,
    [BirthDate] DATETIME2 NULL,
    [DEPARTMENT_ROLLUP] NVARCHAR(400) NULL,
    [DepartmentRollup] NVARCHAR(400) NULL,
    [Disposition] NVARCHAR(400) NULL,
    [EDDepartureTime] DATETIME2 NULL,
    [ED_DEPARTURE_TIME] DATETIME2 NULL,
    [ENCORDER] NVARCHAR(400) NULL,
    [ENCOUNTER_ID] DECIMAL(18,4) NULL,
    [ENC_ID] DECIMAL(18,4) NULL,
    [Ethnic] NVARCHAR(400) NULL,
    [EthnicGroup] NVARCHAR(400) NULL,
    [HOSP_ADMSN_TIME] DATETIME2 NULL,
    [HOSP_DISCH_TIME] DATETIME2 NULL,
    [HospAdmsnTime] DATETIME2 NULL,
    [HospDischTime] DATETIME2 NULL,
    [INPATIENT_DATA_ID] DECIMAL(18,4) NULL,
    [INP_ADM_DATE] DATETIME2 NULL,
    [In] NVARCHAR(400) NULL,
    [InDepartmentTime] DATETIME2 NULL,
    [In_DTTM] DATETIME2 NULL,
    [InpAdmDate] DATETIME2 NULL,
    [InpatientDataID] NVARCHAR(400) NULL,
    [LOCATION_ABBR] NVARCHAR(400) NULL,
    [LOC_ID] DECIMAL(18,4) NULL,
    [LOC_NAME] NVARCHAR(400) NULL,
    [LOS_HRS] NVARCHAR(400) NULL,
    [Location] NVARCHAR(400) NULL,
    [LosHours] NVARCHAR(400) NULL,
    [Out] NVARCHAR(400) NULL,
    [OutDepartmentTime] DATETIME2 NULL,
    [Out_DTTM] DATETIME2 NULL,
    [PATENCENCID] NVARCHAR(400) NULL,
    [PATIENTMRN] NVARCHAR(400) NULL,
    [PATIENT_ID] DECIMAL(18,4) NULL,
    [PATIENT_MRN] NVARCHAR(400) NULL,
    [PATIENT_NAME] NVARCHAR(400) NULL,
    [POS_TYPE] NVARCHAR(400) NULL,
    [PatientID] NVARCHAR(400) NULL,
    [PatientName] NVARCHAR(400) NULL,
    [Race] NVARCHAR(400) NULL,
    [RefreshDate] DATETIME2 NULL,
    [Sepsis] DATETIME2 NULL,
    [Service] NVARCHAR(400) NULL,
    [Shift] DATETIME2 NULL,
    [Unique] NVARCHAR(400) NULL,
    [UniqueRow] NVARCHAR(400) NULL,
    [Unit] NVARCHAR(400) NULL,
    [loc_id] DECIMAL(18,4) NULL
);
GO

IF OBJECT_ID('reporting.ip_sepsispatientdates') IS NULL
CREATE TABLE [reporting].[ip_sepsispatientdates] (
    [ADTDepartmentID] NVARCHAR(400) NULL,
    [ADTDepartmentName] NVARCHAR(400) NULL,
    [AgeOnDateMonths] DATETIME2 NULL,
    [AgeOnDateYears] DATETIME2 NULL,
    [DepartmentRollup] NVARCHAR(400) NULL,
    [ENCORDER] NVARCHAR(400) NULL,
    [ENCOVERALLORDER] NVARCHAR(400) NULL,
    [InDepartmentTime] DATETIME2 NULL,
    [InpatientDataID] NVARCHAR(400) NULL,
    [OutDepartmentTime] DATETIME2 NULL,
    [PATENCENCID] NVARCHAR(400) NULL,
    [PatientID] NVARCHAR(400) NULL,
    [RefreshDate] DATETIME2 NULL,
    [SepsisPatientDate] DATETIME2 NULL,
    [UniqueRow] NVARCHAR(400) NULL,
    [UnitOrder] NVARCHAR(400) NULL
);
GO

IF OBJECT_ID('reporting.ip_sepsisscreeningaudit') IS NULL
CREATE TABLE [reporting].[ip_sepsisscreeningaudit] (
    [AddOrdersReceivedPlacedByMDPNP] NVARCHAR(400) NULL,
    [AlertActivatedComment] NVARCHAR(400) NULL,
    [AlertNotActivatedComment] NVARCHAR(400) NULL,
    [AlertNotActivatedReason] NVARCHAR(400) NULL,
    [BP] DATETIME2 NULL,
    [BPBoysPercentile] NVARCHAR(400) NULL,
    [BPGirlsPercentile] NVARCHAR(400) NULL,
    [CapillaryRefill] NVARCHAR(400) NULL,
    [CirculatoryDysfunction] NVARCHAR(400) NULL,
    [ExternalCreatinine] NVARCHAR(400) NULL,
    [ExternalLactateResult] NVARCHAR(400) NULL,
    [ExternalPlatelets] NVARCHAR(400) NULL,
    [FifteenthOrEOM] NVARCHAR(400) NULL,
    [HematologicDysfunction] NVARCHAR(400) NULL,
    [HuddleDate] DATETIME2 NULL,
    [HuddleTime] DATETIME2 NULL,
    [InfectiousSymptoms] NVARCHAR(400) NULL,
    [LBrachialPulse] NVARCHAR(400) NULL,
    [LPedalPulse] NVARCHAR(400) NULL,
    [LPosteriorTibialPulse] NVARCHAR(400) NULL,
    [LRadialPulse] NVARCHAR(400) NULL,
    [NeurologicalDysfunction] NVARCHAR(400) NULL,
    [NoteAuthor] NVARCHAR(400) NULL,
    [NoteCreatedTime] DATETIME2 NULL,
    [Notification] NVARCHAR(400) NULL,
    [ODScore] NVARCHAR(400) NULL,
    [ODScoreIs2] NVARCHAR(400) NULL,
    [PATENCENCID] NVARCHAR(400) NULL,
    [PatientAssessedByMDPNP] NVARCHAR(400) NULL,
    [PerfusionWDL] NVARCHAR(400) NULL,
    [PhysicianName] NVARCHAR(400) NULL,
    [PosODScore] NVARCHAR(400) NULL,
    [Predisposition] NVARCHAR(400) NULL,
    [Pulse] NVARCHAR(400) NULL,
    [RBrachialPulse] NVARCHAR(400) NULL,
    [RPedalPulse] NVARCHAR(400) NULL,
    [RPosteriorTibialPulse] NVARCHAR(400) NULL,
    [RRadialPulse] NVARCHAR(400) NULL,
    [RefreshDate] DATETIME2 NULL,
    [RenalDysfunction] NVARCHAR(400) NULL,
    [Resp] NVARCHAR(400) NULL,
    [RespiratoryDysfunction] NVARCHAR(400) NULL,
    [ScoreDate] DATETIME2 NULL,
    [ScoreTime] DATETIME2 NULL,
    [SepsisPatientHuddleorAlertWithMDPNP] NVARCHAR(400) NULL,
    [ShiftColorDisplay] NVARCHAR(400) NULL,
    [SkinColor] NVARCHAR(400) NULL,
    [SkinConditionTemp] NVARCHAR(400) NULL,
    [UniqueRow] NVARCHAR(400) NULL
);
GO

IF OBJECT_ID('reporting.ip_sepsisshiftcompliance') IS NULL
CREATE TABLE [reporting].[ip_sepsisshiftcompliance] (
    [AMDenom] NVARCHAR(400) NULL,
    [AlertActivatedComment] NVARCHAR(400) NULL,
    [AlertNotActivatedComment] NVARCHAR(400) NULL,
    [AlertNotActivatedReason] NVARCHAR(400) NULL,
    [Denominator] NVARCHAR(400) NULL,
    [ENCORDER] NVARCHAR(400) NULL,
    [ENCOVERALLORDER] NVARCHAR(400) NULL,
    [FY] NVARCHAR(400) NULL,
    [FYDate] DATETIME2 NULL,
    [FYMonthName] NVARCHAR(400) NULL,
    [FYMonthNumber] NVARCHAR(400) NULL,
    [FYMonthShortName] NVARCHAR(400) NULL,
    [FYYear] NVARCHAR(400) NULL,
    [FifteenthOrEOM] NVARCHAR(400) NULL,
    [NoteAuthor] NVARCHAR(400) NULL,
    [NoteCreatedTime] DATETIME2 NULL,
    [ODScore] NVARCHAR(400) NULL,
    [PATENCENCID] NVARCHAR(400) NULL,
    [PMDenom] NVARCHAR(400) NULL,
    [PositiveODScore] NVARCHAR(400) NULL,
    [RefreshDate] DATETIME2 NULL,
    [ScoreTime] DATETIME2 NULL,
    [Shift1Color] NVARCHAR(400) NULL,
    [Shift1Compliance] NVARCHAR(400) NULL,
    [Shift1ComplianceYN] NVARCHAR(400) NULL,
    [Shift1NonCompliance] NVARCHAR(400) NULL,
    [Shift2Color] NVARCHAR(400) NULL,
    [Shift2Compliance] NVARCHAR(400) NULL,
    [Shift2ComplianceYN] NVARCHAR(400) NULL,
    [Shift2NonCompliance] NVARCHAR(400) NULL,
    [ShiftAMPM] NVARCHAR(400) NULL,
    [ShiftCNs] NVARCHAR(400) NULL,
    [ShiftColor] NVARCHAR(400) NULL,
    [ShiftColorDisplay] NVARCHAR(400) NULL,
    [ShiftCompliance] NVARCHAR(400) NULL,
    [ShiftComplianceFlag] NVARCHAR(400) NULL,
    [ShiftDate] DATETIME2 NULL,
    [ShiftEnd] NVARCHAR(400) NULL,
    [ShiftNonCompliance] NVARCHAR(400) NULL,
    [ShiftRNs] NVARCHAR(400) NULL,
    [ShiftStart] NVARCHAR(400) NULL,
    [UniqueRow] NVARCHAR(400) NULL,
    [UnitOrder] NVARCHAR(400) NULL
);
GO

-- VERIFICATION: expect an EMPTY result. Each row = a
-- referenced table still missing from this database.
SELECT v.full_name AS missing_table FROM (VALUES
    ('dbo.adt_events'),
    ('dbo.alert_actions'),
    ('dbo.alert_history'),
    ('dbo.calendar_dates'),
    ('dbo.clinical_alerts'),
    ('dbo.clinical_note_text'),
    ('dbo.clinical_notes'),
    ('dbo.config_grouper_categories'),
    ('dbo.departments'),
    ('dbo.diagnoses'),
    ('dbo.diagnoses_current_icd10'),
    ('dbo.dm_icu_stay'),
    ('dbo.ed_encounters_dm'),
    ('dbo.ed_encounters_fact'),
    ('dbo.ed_event_info'),
    ('dbo.ed_event_templates'),
    ('dbo.ed_patient_info'),
    ('dbo.employees'),
    ('dbo.encounter_diagnoses'),
    ('dbo.encounter_visit_reasons'),
    ('dbo.flowsheet_measurements'),
    ('dbo.flowsheet_records'),
    ('dbo.grouper_compiled_list'),
    ('dbo.grouper_groups'),
    ('dbo.grouper_med_records'),
    ('dbo.grouper_terminology'),
    ('dbo.hospital_accounts'),
    ('dbo.hospital_accounts_ext'),
    ('dbo.hospital_acct_diagnoses'),
    ('dbo.hospital_acct_px_list'),
    ('dbo.hospital_encounters'),
    ('dbo.hospital_transactions'),
    ('dbo.icd_procedure_codes'),
    ('dbo.lab_components'),
    ('dbo.lab_order_results'),
    ('dbo.line_device_airway'),
    ('dbo.locations'),
    ('dbo.med_admin_records'),
    ('dbo.med_details_ext'),
    ('dbo.med_mix_components'),
    ('dbo.medication_orders'),
    ('dbo.medication_orders_ext'),
    ('dbo.medications'),
    ('dbo.note_encounter_info'),
    ('dbo.note_template_list_ids'),
    ('dbo.note_template_text_ids'),
    ('dbo.order_dispense_info'),
    ('dbo.order_tracking_metrics'),
    ('dbo.organisms'),
    ('dbo.patient_demographics_race'),
    ('dbo.patient_encounters'),
    ('dbo.patient_or_adm_link'),
    ('dbo.patients'),
    ('dbo.procedure_orders'),
    ('dbo.procedure_orders_ext'),
    ('dbo.procedures_catalog'),
    ('dbo.providers'),
    ('dbo.ref_alert_actions'),
    ('dbo.ref_alert_override_reasons'),
    ('dbo.ref_alert_status'),
    ('dbo.ref_discharge_disposition'),
    ('dbo.ref_ed_disposition'),
    ('dbo.ref_ethnic_group'),
    ('dbo.ref_generic_med'),
    ('dbo.ref_patient_race'),
    ('dbo.ref_shown_place'),
    ('dbo.rx_verify_trace'),
    ('dbo.treatment_teams'),
    ('dbo.v_hospital_transactions'),
    ('dbo.v_log_based'),
    ('dbo.v_patient_location_history'),
    ('dbo.v_pharmacy_dispense'),
    ('dbo.v_pharmacy_dispense_action'),
    ('dbo.v_pharmacy_order'),
    ('dbo.visit_reasons'),
    ('reporting.ip_sepsis'),
    ('reporting.ip_sepsisdetails'),
    ('reporting.ip_sepsisencounters'),
    ('reporting.ip_sepsisencounterswlocations'),
    ('reporting.ip_sepsispatientdates'),
    ('reporting.ip_sepsisscreeningaudit'),
    ('reporting.ip_sepsisshiftcompliance'),
    ('reports.config_value_set'),
    ('reports.fy_date_dimension'),
    ('reports.non_severe_sepsis_staging'),
    ('reports.severe_sepsis_staging')
) v(full_name) WHERE OBJECT_ID(v.full_name) IS NULL;
GO
