"""Generate empty stub tables for the demo source database.

The demo model's EXEC partitions must LOAD in Power BI Desktop, which
means the procs must execute — so every base table they reference must
exist (empty is fine; 0 rows in, 0 rows out). Tables and their exact
(schema, table) spellings come from the recorded parse lineage; column
definitions come from the customer dictionary. Tables referenced but
absent from the dictionary are reported loudly, not guessed.

Output: data/demo/seed_demo_tables.sql (run AFTER seed_demo_source.sql).

Usage:
    python scripts/build_demo_stub_tables.py
"""

from __future__ import annotations

import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

FIXTURES = REPO / "tests" / "fixtures" / "recorded"
DICT_COLUMNS = REPO / "data" / "synthetic" / "dict_columns.csv"
OUT = REPO / "data" / "demo" / "seed_demo_tables.sql"

TYPE_MAP = {
    "VARCHAR": "NVARCHAR(400)",
    "NVARCHAR": "NVARCHAR(400)",
    "CHAR": "NVARCHAR(50)",
    "NUMERIC": "DECIMAL(18,4)",
    "DECIMAL": "DECIMAL(18,4)",
    "INTEGER": "INT",
    "INT": "INT",
    "BIGINT": "BIGINT",
    "SMALLINT": "SMALLINT",
    "FLOAT": "FLOAT",
    "REAL": "FLOAT",
    "DATETIME": "DATETIME2",
    "DATETIME2": "DATETIME2",
    "DATE": "DATE",
    "TIME": "TIME",
    "BIT": "BIT",
    "MONEY": "DECIMAL(19,4)",
}


def referenced_tables() -> "tuple[set[tuple[str, str]], dict[str, set[str]]]":
    """(schema, table) pairs referenced in the recorded parses, plus the
    column names the SQL itself references per table (fallback columns
    for tables absent from the dictionary)."""
    parse_results = json.loads((FIXTURES / "parse_results.json").read_text())
    pairs: "set[tuple[str, str]]" = set()
    ref_columns: "dict[str, set[str]]" = defaultdict(set)

    def add(ref):
        if not isinstance(ref, dict):
            return
        table = (ref.get("table") or "").strip("[]# ")
        if not table or table.startswith(("#", "@")):
            return
        schema = (ref.get("schema") or "dbo").strip("[] ") or "dbo"
        pairs.add((schema, table))

    def add_col(ref):
        if not isinstance(ref, dict):
            return
        table = (ref.get("table") or "").strip("[]# ").upper()
        column = (ref.get("column") or "").strip("[] ")
        if table and column and not column.startswith(("@", "#")):
            ref_columns[table].add(column)

    for pr in parse_results:
        for ref in json.loads(pr.get("final_select_tables") or "[]"):
            add(ref if isinstance(ref, dict) else {"table": ref})
        for ref in json.loads(pr.get("final_select_columns") or "[]"):
            add_col(ref)
        for cte in json.loads(pr.get("ctes_json") or "[]"):
            for ref in cte.get("table_refs", []):
                add(ref if isinstance(ref, dict) else {"table": ref})
            for ref in cte.get("column_refs", []):
                add_col(ref)
    return pairs, ref_columns


def main() -> None:
    dict_cols: "dict[str, list[tuple[str, str]]]" = defaultdict(list)
    for row in csv.DictReader(open(DICT_COLUMNS, encoding="utf-8")):
        dict_cols[row["TABLE_NAME"].upper()].append(
            (row["COLUMN_NAME"], row.get("DATA_TYPE", "").upper()))

    pairs, ref_columns = referenced_tables()
    lines = [
        "-- Empty stub tables for the demo source database.",
        "-- Generated by scripts/build_demo_stub_tables.py from the recorded",
        "-- parse lineage + the customer dictionary. Run AFTER",
        "-- seed_demo_source.sql. Empty tables: procs execute, return 0 rows.",
        "",
    ]
    missing = []
    created = 0
    for schema, table in sorted(pairs):
        cols = dict_cols.get(table.upper())
        if not cols:
            # Fallback: the columns the SQL itself references, typed
            # permissively — enough for EXEC to run over empty tables.
            fallback = sorted(ref_columns.get(table.upper(), set()))
            if not fallback:
                missing.append(f"{schema}.{table}")
                continue
            cols = [(c, "VARCHAR") for c in fallback]
        lines.append(f"IF OBJECT_ID('{schema}.{table}') IS NULL")
        col_defs = ",\n    ".join(
            f"[{name}] {TYPE_MAP.get(dtype, 'NVARCHAR(400)')} NULL"
            for name, dtype in cols
        )
        lines.append(f"CREATE TABLE [{schema}].[{table}] (\n    {col_defs}\n);")
        lines.append("GO")
        lines.append("")
        created += 1

    OUT.write_text("\n".join(lines))
    print(f"{created} stub tables written to {OUT}")
    if missing:
        print(f"[!] {len(missing)} referenced tables NOT in the dictionary "
              f"(procs touching them may fail at EXEC):")
        for m in sorted(missing):
            print(f"    {m}")


if __name__ == "__main__":
    main()
