"""Column patch for demo stubs: every column the corpus references on a
stubbed table that the stub doesn't carry (the dictionary is the stub's
source, and dictionaries lag code — 'Invalid column name VALUE_SET_ABBR',
2026-08-18).

Scans BOTH seed files' CREATE TABLE column lists, harvests alias-scoped
and INSERT-list column references per table from the noise-stripped
corpus, and emits idempotent ALTER TABLE ... ADD statements (COL_LENGTH
guard, GO-separated) plus a verification tail: expect an EMPTY result;
each row names a still-missing (table, column).

Output: data/demo/seed_demo_columns_patch.sql
Usage:  python scripts/build_demo_stub_column_patch.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

from build_demo_stub_supplement import (  # noqa: E402
    alias_columns,
    infer_type,
    strip_noise,
)

CORPUS = REPO / "data" / "demo" / "seed_demo_source.sql"
SEEDS = [REPO / "data" / "demo" / "seed_demo_tables.sql",
         REPO / "data" / "demo" / "seed_demo_tables_supplement.sql"]
OUT = REPO / "data" / "demo" / "seed_demo_columns_patch.sql"


def stub_columns(seed_sql: str) -> "dict[str, set[str]]":
    """table_key -> lowercase column set, from CREATE TABLE blocks."""
    out: "dict[str, set[str]]" = {}
    for m in re.finditer(
        r"CREATE\s+TABLE\s+\[?(\w+)\]?\s*\.\s*\[?(\w+)\]?\s*\((.*?)\);",
        seed_sql, re.IGNORECASE | re.DOTALL,
    ):
        key = f"{m.group(1)}.{m.group(2)}".lower()
        cols = {c.lower() for c in re.findall(r"\[(\w+)\]", m.group(3))}
        out.setdefault(key, set()).update(cols)
    return out


def main() -> None:
    corpus_raw = CORPUS.read_text()
    corpus = strip_noise(corpus_raw)
    stubs: "dict[str, set[str]]" = {}
    for seed in SEEDS:
        for key, cols in stub_columns(seed.read_text()).items():
            stubs.setdefault(key, set()).update(cols)

    patches: "list[tuple[str, str, str]]" = []  # (table_key, col, type)
    for key, existing in sorted(stubs.items()):
        referenced = alias_columns(corpus, key)
        for col in sorted(referenced, key=str.lower):
            if col.lower() not in existing:
                patches.append((key, col, infer_type(corpus, col)))
                existing.add(col.lower())

    lines = [
        "-- Column patch: corpus-referenced columns missing from the",
        "-- dictionary-derived stubs. Generated by",
        "-- scripts/build_demo_stub_column_patch.py. Idempotent;",
        "-- GO-separated; verification tail expects an EMPTY result.",
        "",
    ]
    for key, col, sqltype in patches:
        schema, name = key.split(".")
        lines.append(f"IF COL_LENGTH('{schema}.{name}', '{col}') IS NULL")
        lines.append(f"ALTER TABLE [{schema}].[{name}] ADD [{col}] {sqltype} NULL;")
        lines.append("GO")
        lines.append("")

    lines.append("-- VERIFICATION: expect an EMPTY result. Each row is a")
    lines.append("-- referenced column still missing from its stub table.")
    lines.append("SELECT v.tbl AS table_name, v.col AS missing_column FROM (VALUES")
    lines.append(",\n".join(f"    ('{k}', '{c}')" for k, c, _ in patches))
    lines.append(") v(tbl, col) WHERE COL_LENGTH(v.tbl, v.col) IS NULL;")
    lines.append("GO")

    OUT.write_text("\n".join(lines) + "\n")
    by_table: "dict[str, int]" = {}
    for k, _, _ in patches:
        by_table[k] = by_table.get(k, 0) + 1
    print(f"columns patched: {len(patches)} across {len(by_table)} tables")
    for k, n in sorted(by_table.items(), key=lambda kv: -kv[1])[:15]:
        print(f"   {k}: {n}")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
