





/**********************************************************************************************************

Author: <Unknown>

Create date:  <Unknown>

Description:  

Report Name: BI-Health System --> Quality --> ED Sepsis

==========================================================================================================

Revision Detail 



Date			Who						Description 

----------------------------------------------------------------------------------------------------------

2019.05.16		V_DEV001				[PROCEDURE_ORDERS].PROC_CODE is deprecated as of april 2019; Replacing it with PROC_ID.

2019.07.19		V_DEV001				MAR_ACTION_CODE changed data type from INT to VARCHAR.

2019.10.01		V_DEV001				Added new Sepsis Score Flowsheet ID '9000002613'

2019.11.07		V_DEV001				Added Quick Set/ OrdersetS OSQ: 

											- ED Sepsis Panel - OSQ 400002

											- Sepsis Antimicrobials Unknown Source - OSQ 400007

											- Neo Fever Panel - OSQ 400003

											- Oncology with Fever Panel - OSQ 400004

2019.11.08		V_DEV001				Updated calculation to include Triage Stop Time instead of Triage Start Time

2019.12.11		V_DEV001				Added First ABX Order and its related Pharmacy times

2020.04.10		V_DEV001				Added First and Last Blood Pressure information and ED Border Flag

2020.09.21		V_DEV001				Added Compliance for (FPS + ABX/ Bolus/ Rescreen):

											- Rescreen One Hour before Transfer/ Discharge

											- ED 2 PICU/ ED 2 Floor and then ICU

											- ED IP Bed assignment to IP Transfer Metric

											- ABX given only in ED setting

2020.10.29		V_DEV001				Set TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

2020.11.17		V_DEV001				Set end date to T-1

2021.02.03		V_DEV001				Added first sepsis score day/night shift

2021.03.24		V_DEV001				Added PATIENTS's race and ethnic group info

2023.06.15		V_DEV003				Added age in days for 21 days or less age filter, and modified months age to include FLOOR



2025.08.06		V_DEV004				Added #SepsisAlertCancelled columns

2025.08.26		V_DEV004				Added Urine Culture Results, Organism name to Blood/CSF, and corrected Blood/CSF code

2025.10.06		V_DEV004				Added BP percentile Flowsheets [9001140203, 9001140205] (per TKT-009)

2025.12.07		V_DEV004				Added [Septic Shock] and [Blood Culture First Order Time] columns

==========================================================================================================

USAGE: 

	exec [reports].[USP_ED_Sepsis] 'MB-1', 'ME-1' 

**********************************************************************************************************/ 





CREATE       PROCEDURE [reports].[USP_ED_Sepsis] (

	@StartDate VARCHAR(20) = NULL,

	@EndDate VARCHAR(20) = NULL

)



AS



SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SET NOCOUNT ON;

	

DECLARE @dStartDate DATE;

DECLARE @dEndDate DATE;



	

IF @StartDate IS NULL OR @StartDate = ''

	SET @dStartDate = [dbo].[fn_parse_date]('MB-12')

ELSE

	SET @dStartDate = [dbo].[fn_parse_date](@StartDate)

	

IF @EndDate IS NULL OR @EndDate = ''

	SET @dEndDate = [dbo].[fn_parse_date]('T-1')

ELSE

	SET @dEndDate = [dbo].[fn_parse_date](@EndDate)





--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

--SET NOCOUNT ON;



--DECLARE @dStartDate DATE = '2025-11-01';

--DECLARE @dEndDate DATE = '2025-11-30';





/* ************** */

/* Base ED Visits */

/* ************** */

DROP TABLE IF EXISTS #Base_Pop;



SELECT DISTINCT

	HE.ENCOUNTER_ID

	, HE.PATIENT_ID

	, PAT.PATIENT_MRN

	, PAT.PATIENT_NAME

	, REG.NAME AS [Ethnic Group]

	, RPR.NAME AS [Race]

	, EEF.AGE_AT_ARRIVAL_MONTHS

	, EEF.AGE_AT_ARRIVAL_YEARS

	, HE.INPATIENT_DATA_ID

	, HE.ADT_ARRIVAL_TIME

	, EED.TRIAGE_START_DTTM

	, EED.TRIAGE_END_DTTM

	, HE.HOSP_ADMSN_TIME

	, HE.HOSP_DISCH_TIME

	, HE.INP_ADM_DATE

	, HE.ED_DEPARTURE_TIME

	, HE.ED_DISPOSITION_CODE

	, REDI.NAME AS [Disposition]

	, LOC.LOCATION_ABBR [Location]

	, FLOOR(DATEDIFF(day,PAT.BIRTH_DATE,HE.ADT_ARRIVAL_TIME)) AS AGE_IN_DAYS ---ADDED V_DEV003 6/15/2023 TKT-007 

	, FLOOR(DATEDIFF(MM,PAT.BIRTH_DATE,COALESCE(HE.ADT_ARRIVAL_TIME,HE.ADT_ARRIVAL_TIME)) ) AS AGE_MONTHS  ---ADDED V_DEV003 6/15/2023 TKT-007  (AGE IN MONTHS IS SHOWING AS 1 WHEN ITS ONLY 2 WEEKS, ETC.)

	, FLOOR(DATEDIFF(DD,PAT.BIRTH_DATE,HE.ADT_ARRIVAL_TIME)/365.25) AS AGE_YEARS

	, DATENAME(month, CONVERT(DATE,HE.ADT_ARRIVAL_TIME)) + DATENAME(YEAR, CONVERT(DATE, HE.ADT_ARRIVAL_TIME)) AS DATE_STAMP



INTO #Base_Pop



FROM [dbo].ED_ENCOUNTERS_FACT EEF



	INNER JOIN [dbo].HOSPITAL_ENCOUNTERS HE ON EEF.ENCOUNTER_ID = HE.ENCOUNTER_ID

	INNER JOIN [dbo].ED_ENCOUNTERS_DM EED ON EED.ENCOUNTER_ID = EEF.ENCOUNTER_ID

	INNER JOIN [dbo].PATIENTS PAT ON PAT.PATIENT_ID = HE.PATIENT_ID

	LEFT OUTER JOIN [dbo].REF_ED_DISPOSITION REDI ON REDI.ED_DISPOSITION_CODE = HE.ED_DISPOSITION_CODE

	LEFT OUTER JOIN [dbo].REF_ETHNIC_GROUP REG ON REG.ETHNIC_GROUP_CODE = PAT.ETHNIC_GROUP_CODE

	LEFT OUTER JOIN [dbo].PATIENT_DEMOGRAPHICS_RACE RACE ON RACE.PATIENT_ID = PAT.PATIENT_ID AND RACE.LINE=1

	LEFT OUTER JOIN [dbo].REF_PATIENT_RACE RPR ON RPR.PATIENT_RACE_CODE = RACE.PATIENT_RACE_CODE

	LEFT OUTER JOIN [dbo].DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = HE.DEPARTMENT_ID

	LEFT OUTER JOIN [dbo].LOCATIONS LOC ON LOC.LOC_ID = DEP.REV_LOC_ID



WHERE 1=1

	AND EEF.ADT_ARRIVAL_DATE BETWEEN @dStartDate AND @dEndDate

;



CREATE CLUSTERED INDEX INX_BASE_POP_ENC ON #Base_Pop ([ENCOUNTER_ID]);





/* ******************** */

/* Treatment Plan Begin */

/* ******************** */



-- All encounters from #Base_pop where ABX was administered

DROP TABLE IF EXISTS #BasePopABX;



WITH ABX AS

(

SELECT

		MO.ENCOUNTER_ID

		, MO.ORDER_MED_ID

		, MA.TAKEN_TIME AS ABX_ADMIN_TIME

		, MEDS.[NAME]



	FROM #Base_Pop B -- ONLY THOSE PATIENTS WITH A POSITIVE SCORE

		INNER JOIN dbo.MEDICATION_ORDERS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

		INNER JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID --AND MEDS.THERA_CLASS_CODE = 11 --Antibiotics

		INNER JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID



	WHERE 1=1

		AND MA.TAKEN_TIME IS NOT NULL	--ADMINISTERED ABX ONLY

		AND MA.TAKEN_TIME < B.ED_DEPARTURE_TIME--09.23.2020; MAKE SURE THE Antibiotics WERE GIVEN IN ED

		AND MO.MED_ROUTE_CODE=11--IV ONLY

		AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

								, '7'			--RESTARTED

								, '102'		--GIVEN BY OTHER

								, '105'		--NEW CARTRIDGE

								, '113'		--GIVEN DURING DOWNTIME

								, '114'		--STARTED DURING DOWNTIME

								, '115'		--MEDICATION APPLIED

								, '122'		--CONTINUED FROM OR

								, '124'		--SELF ADMINISTERED VIA PUMP

								, '132'		--CONTINUED FROM PREVIOUS ORDER

								, '143'		--REDOSE

								, '1604'		--INFUSION GREATER THAN 15 MIN

								, '1605'		--INFUSION LESS THAN 15 MIN

								, '1607'		--NEW CARTRIDGE

								, '6'			--NEW BAG

								, '99'			--RATE CHANGE

								)

		AND MO.MEDICATION_ID IN 

			(



				select 

						medlist.MEDICATION_ID

					from

						(

							SELECT 

								RXM.MEDICATION_ID,

								RXM.NAME,

								cntl.VALUE_SET_DISPLAY as AGENT,

								case when CHARINDEX('^',cntl.VALUE_SET_ABBR)>0 then SUBSTRING(cntl.VALUE_SET_ABBR,0,CHARINDEX('^',cntl.VALUE_SET_ABBR)) else cntl.VALUE_SET_ABBR end as AGENT_GROUP,

								case when cntl.VALUE_SET_ABBR like '%^Y' then 1 else 0 end as DOT_MONITORING,

								gen.TITLE,

								ROW_NUMBER() over(partition by RXM.MEDICATION_ID order by cntl.VALUE_SET_ABBR,cntl.VALUE_SET_DISPLAY asc) as AGENT_ORDER



							FROM

								dbo.MEDICATIONS RXM

								OUTER APPLY(

									--Get the main medication's simple generic if its a mixture

									SELECT TOP 1 

										mix.DRUG_ID,

										comp.SIMPLE_GENERIC_CODE 

									FROM dbo.MED_MIX_COMPONENTS mix

										INNER JOIN dbo.MEDICATIONS comp on mix.DRUG_ID=comp.MEDICATION_ID

									WHERE 1=1

										AND mix.TYPE_CODE=3		--3 - Medications 

										AND mix.MEDICATION_ID=RXM.MEDICATION_ID

									ORDER BY

										mix.LINE

								) mixture

								INNER JOIN dbo.REF_GENERIC_MED gen on gen.SIMPLE_GENERIC_CODE=coalesce(RXM.SIMPLE_GENERIC_CODE,mixture.SIMPLE_GENERIC_CODE)

								INNER JOIN reports.CONFIG_VALUE_SET cntl on cntl.VALUE_SET_ID=3016 and cntl.CODE=gen.SIMPLE_GENERIC_CODE -- and cntl.VALUE_SET_ABBR='Antibacterial'

						) medlist

					where

						medlist.AGENT_ORDER=1						

			)



	UNION



	SELECT DISTINCT

		MO.ENCOUNTER_ID

		, MO.ORDER_MED_ID

		, MA.TAKEN_TIME AS ABX_ADMIN_TIME

		, MEDS.NAME



	FROM #Base_Pop B -- ONLY THOSE PATIENTS WITH A POSITIVE SCORE



		INNER JOIN dbo.MEDICATION_ORDERS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

		INNER JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID AND MEDS.THERA_CLASS_CODE = 11 --Antibiotics

		INNER JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID



	WHERE 1=1

		AND MA.TAKEN_TIME IS NOT NULL	--ADMINISTERED ABX ONLY

		AND MA.TAKEN_TIME < B.ED_DEPARTURE_TIME--09.23.2020; MAKE SURE THE Antibiotics WERE GIVEN IN ED

		AND MO.MED_ROUTE_CODE=11--IV ONLY

		AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

								, '7'			--RESTARTED

								, '102'		--GIVEN BY OTHER

								, '105'		--NEW CARTRIDGE

								, '113'		--GIVEN DURING DOWNTIME

								, '114'		--STARTED DURING DOWNTIME

								, '115'		--MEDICATION APPLIED

								, '122'		--CONTINUED FROM OR

								, '124'		--SELF ADMINISTERED VIA PUMP

								, '132'		--CONTINUED FROM PREVIOUS ORDER

								, '143'		--REDOSE

								, '1604'		--INFUSION GREATER THAN 15 MIN

								, '1605'		--INFUSION LESS THAN 15 MIN

								, '1607'		--NEW CARTRIDGE

								, '6'			--NEW BAG

								, '99'			--RATE CHANGE

								)

)



SELECT

	ABX.ENCOUNTER_ID

	,ABX.ORDER_MED_ID

	,ABX.NAME

	,ABX.ABX_ADMIN_TIME

	,ROW_NUMBER() OVER(PARTITION BY ABX.ENCOUNTER_ID ORDER BY ABX.ABX_ADMIN_TIME) TIME_LINE



INTO #BasePopABX

FROM ABX						

;





/* *************** */

/* Chief Complaint */

/* *************** */

DROP TABLE IF EXISTS #Base_Pop_ENC_Reason;



SELECT DISTINCT   CAT.ENCOUNTER_ID,

        STUFF((	SELECT ';' + CONVERT(VARCHAR,VR.REASON_VISIT_NAME)-- AS [text()]

                FROM #Base_Pop SUB

					INNER JOIN [dbo].ENCOUNTER_VISIT_REASONS RSN ON RSN.ENCOUNTER_ID = SUB.ENCOUNTER_ID AND RSN.LINE>1

					INNER JOIN [dbo].VISIT_REASONS VR ON VR.REASON_VISIT_ID = RSN.ENC_REASON_ID

				WHERE

                    SUB.ENCOUNTER_ID = CAT.ENCOUNTER_ID

				ORDER BY LINE

                    FOR XML PATH('')

               ), 1, 1, '' )

            AS [AllEncReasons]

INTO #Base_Pop_ENC_Reason

FROM  #Base_Pop CAT

;





/* ************* */

/* Order Set OSQ */

/* ************* */

DROP TABLE IF EXISTS #SSOrderSetOSQ_PRL;



	SELECT

		B.ENCOUNTER_ID

		, MO.ORDER_DTTM

		, MO2.ORD_OSQ_ID AS PRL_ORDERSET_ID

	INTO #SSOrderSetOSQ_PRL

	FROM #Base_Pop B

		INNER JOIN dbo.ORDER_TRACKING_METRICS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

		INNER JOIN [dbo].MEDICATION_ORDERS_EXT MO2 ON MO2.ORDER_ID = MO.ORDER_ID AND MO2.ORD_OSQ_ID IN (400002,400007,400003,400004)

	WHERE MO.ORDER_DTTM BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME



UNION



	SELECT

		B.ENCOUNTER_ID

		, MO.ORDER_DTTM

		, MO2.ORD_OSQ_ID AS PRL_ORDERSET_ID

	FROM #Base_Pop B

		INNER JOIN dbo.ORDER_TRACKING_METRICS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

		INNER JOIN [dbo].PROCEDURE_ORDERS_EXT MO2 ON MO2.ORDER_ID = MO.ORDER_ID AND MO2.ORD_OSQ_ID IN (400002,400007,400003,400004)

	WHERE

		MO.ORDER_DTTM BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME



UNION



	SELECT

		B.ENCOUNTER_ID

		, MO.ORDER_DTTM

		, MO.PRL_ORDERSET_ID

	FROM #Base_Pop B

		INNER JOIN dbo.ORDER_TRACKING_METRICS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

	WHERE

		MO.PRL_ORDERSET_ID IN (400001)-- (40400100, 40400058, 40400196, 40400153, 4058600002, 400001) --Severe Sepsis, Short Stay – Sepsis, H/O – Sepsis CLINICAL_ALERTS, ID – Staph Aureus Sepsis, H/O Sepsis CLINICAL_ALERTS in Clinic, Sepsis Pathway

		AND MO.ORDER_DTTM BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME

;





/* ******************* */

/* Order Set           */

/* ******************* */

DROP TABLE IF EXISTS #SSOrderSet;



SELECT

	ENCOUNTER_ID

	, ORDER_DTTM

	, ROW_NUMBER() OVER(PARTITION BY ENCOUNTER_ID ORDER BY ORDER_DTTM ASC) AS TIME_LINE

	, PRL_ORDERSET_ID

INTO #SSOrderSet 

FROM #SSOrderSetOSQ_PRL

;





/* ******************* */

/* Bolus               */

/* ******************* */

DROP TABLE IF EXISTS #BasePopBolus;



SELECT

	B.ENCOUNTER_ID

	, MA.TAKEN_TIME AS BOLUS_ADMIN_TIME

	, CASE	WHEN MO.MEDICATION_ID IN (700001, 700002) THEN 'SODIUM CHLORIDE 0.99%'

			ELSE MEDS.[NAME]

	  END AS Medication

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY MA.TAKEN_TIME ASC) TIME_LINE

	, MA.SIG AS BOLUS_VOLUME



INTO #BasePopBolus 

FROM #Base_Pop B

	INNER JOIN dbo.MEDICATION_ORDERS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID

	INNER JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID



WHERE 1=1

	AND MA.TAKEN_TIME IS NOT NULL --ADMINISTERED BOLUS ONLY

	AND MA.TAKEN_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME

	AND (MO.MEDICATION_ID IN (700001  --SODIUM CHLORIDE 0.99 % IV BOLUS

							, 7000739 --LACTATED RINGERS IV BOLUS

							, 700003    --ALBUMIN, HUMAN 95 % INTRAVENOUS SOLUTION

							, 7006331 --ELECTROLYE-A IV Bolus (PLASMALYTE)

							, 700002	--SODIUM CHLORIDE 0.99 % INJECTION SYRINGE--ADDED ON 04.02.2019

							)

		OR (MO.MEDICATION_ID = 700004)

	AND MO.HV_DISCR_FREQ_ID = '300902') -- FREQUENCY = ONCE 

	AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

							, '7'			--RESTARTED

							, '102'		--GIVEN BY OTHER

							, '105'		--NEW CARTRIDGE

							, '113'		--GIVEN DURING DOWNTIME

							, '114'		--STARTED DURING DOWNTIME

							, '115'		--MEDICATION APPLIED

							, '122'		--CONTINUED FROM OR

							, '124'		--SELF ADMINISTERED VIA PUMP

							, '132'		--CONTINUED FROM PREVIOUS ORDER

							, '143'		--REDOSE

							, '1604'		--INFUSION GREATER THAN 15 MIN

							, '1605'		--INFUSION LESS THAN 15 MIN

							, '1607'		--NEW CARTRIDGE

							, '6'			--NEW BAG

							)

	AND CONVERT(NUMERIC, MA.SIG ) > 95.0

GROUP BY

	B.ENCOUNTER_ID

	, MA.TAKEN_TIME

	, MA.SIG

	, MO.MEDICATION_ID

	, MEDS.NAME

	--select * from #BasePopBolus WHERE TIME_LINE=1

	/*PATIENTS Weight*/

;





/* ******************* */

/* Encounter Weight    */

/* ******************* */

DROP TABLE IF EXISTS #EncounterWeights;



SELECT

	A.ENCOUNTER_ID

	, CAST(ROUND(CONVERT(FLOAT, MEAS_VALUE) * 0.0283495, 2) AS DECIMAL(4, 1)) AS EncWeight

	, ROW_NUMBER() OVER(PARTITION BY A.ENCOUNTER_ID ORDER BY C.RECORDED_TIME ASC) AS TIME_LINE

INTO #EncounterWeights

FROM #Base_Pop A

	INNER JOIN [dbo].FLOWSHEET_RECORDS B ON A.INPATIENT_DATA_ID = B.INPATIENT_DATA_ID

	INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS C ON B.FSD_ID = C.FSD_ID AND  C.FLO_MEAS_ID='94'

;





/* ******************* */

/* Hypotension         */

/* ******************* */

DROP TABLE IF EXISTS #Hypotension;



SELECT

	C.ENCOUNTER_ID

	, FM.RECORDED_TIME

	, C.AGE_MONTHS

	, C.AGE_YEARS

	, LEFT(FM.MEAS_VALUE, CHARINDEX('/', FM.MEAS_VALUE)-1) AS SYSTOLIC

	, FM.MEAS_VALUE

	, ROW_NUMBER() OVER(PARTITION BY C.ENCOUNTER_ID ORDER BY FM.RECORDED_TIME ASC) AS TIME_LINE

INTO #Hypotension 

FROM #Base_Pop C 

	INNER JOIN [dbo].FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = C.INPATIENT_DATA_ID

	INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID

WHERE 1=1

	AND FM.FLO_MEAS_ID = '95'

	AND FM.RECORDED_TIME IS NOT NULL 

	AND FM.RECORDED_TIME BETWEEN C.ADT_ARRIVAL_TIME AND C.ED_DEPARTURE_TIME

	AND FM.MEAS_VALUE IS NOT NULL

;







/* ********************** */

/* Sepsis CLINICAL_ALERTS Cancelled */

/* ********************** */

DROP TABLE IF EXISTS #SepsisAlertCancelled;



SELECT 

	C.ENCOUNTER_ID

	, FM.RECORDED_TIME	AS SEPSIS_ALERT_CANC_TIME

	, C.AGE_MONTHS

	, C.AGE_YEARS

	, 'Y'				AS SEPSIS_ALERT_CANC_FLAG

	, FM.MEAS_COMMENT	AS SEPSIS_ALERT_CANC_BY		-- Free text

	, ROW_NUMBER() OVER(PARTITION BY C.ENCOUNTER_ID ORDER BY FM.RECORDED_TIME ASC) AS TIME_LINE

INTO #SepsisAlertCancelled 

FROM #Base_Pop C 

	INNER JOIN [dbo].FLOWSHEET_RECORDS FR ON FR.INPATIENT_DATA_ID = C.INPATIENT_DATA_ID

	INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID

WHERE 1=1

	AND FM.FLO_MEAS_ID = '9001125002'	-- R HS ED SEPSIS CLINICAL_ALERTS CANCELLED

	AND FM.RECORDED_TIME IS NOT NULL 

	AND FM.RECORDED_TIME BETWEEN C.ADT_ARRIVAL_TIME AND C.ED_DEPARTURE_TIME

	AND FM.MEAS_VALUE IS NOT NULL

;







/* ******************* */

/* CVL Time            */

/* ******************* */

DROP TABLE IF EXISTS #ALLCVLTime;



SELECT DISTINCT

	C.ENCOUNTER_ID

	, LNA.PLACEMENT_INSTANT

	, ROW_NUMBER() OVER(PARTITION BY C.ENCOUNTER_ID ORDER BY LNA.PLACEMENT_INSTANT) TIME_LINE

INTO #ALLCVLTime

FROM #Base_Pop C

	INNER JOIN [dbo].LINE_DEVICE_AIRWAY LNA ON LNA.ENCOUNTER_ID = C.ENCOUNTER_ID 

	INNER JOIN reports.CONFIG_VALUE_SET CVS ON CVS.CODE = LNA.FLO_MEAS_ID

		AND CVS.VALUE_SET_ID = 3022 --CVL CODES

WHERE LNA.PLACEMENT_INSTANT BETWEEN C.ADT_ARRIVAL_TIME AND C.ED_DEPARTURE_TIME

;





/* ******************* */

/* Presssors           */

/* ******************* */

DROP TABLE IF EXISTS #Pressors;



SELECT DISTINCT

	B.ENCOUNTER_ID

	, MA.TAKEN_TIME

	, MEDS.NAME AS MEDICATION

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY MA.TAKEN_TIME) AS TIME_LINE

INTO #Pressors 

FROM #Base_Pop B

	LEFT JOIN dbo.MEDICATION_ORDERS MO ON MO.ENCOUNTER_ID = B.ENCOUNTER_ID

	LEFT JOIN dbo.MEDICATIONS MEDS ON MEDS.MEDICATION_ID = MO.MEDICATION_ID

	LEFT JOIN dbo.GROUPER_MED_RECORDS GMR ON GMR.EXP_MEDS_LIST_ID = MEDS.MEDICATION_ID

	LEFT JOIN dbo.MED_ADMIN_RECORDS MA ON MA.ORDER_MED_ID = MO.ORDER_MED_ID

	LEFT JOIN dbo.HOSPITAL_ENCOUNTERS HE ON HE.ENCOUNTER_ID = B.ENCOUNTER_ID

WHERE 1=1

	AND GMR.GROUPER_ID IN ('8000100'    -- HS RX EPINEPHRINE SEPSIS

							, '8000101' -- HS RX DOPAMINE SEPSIS

							, '8000102' -- HS RX DOBUTAMINE SEPSIS

							, '8000103' -- HS RX MILRINONE SEPSIS

							, '8000104' -- HS RX NOREPINEPHRINE SEPSIS

						)

	AND MA.MAR_ACTION_CODE IN ('1'			--GIVEN

							, '7'			--RESTARTED

							, '102'		--GIVEN BY OTHER

							, '105'		--NEW CARTRIDGE

							, '113'		--GIVEN DURING DOWNTIME

							, '114'		--STARTED DURING DOWNTIME

							, '115'		--MEDICATION APPLIED

							, '122'		--CONTINUED FROM OR

							, '124'		--SELF ADMINISTERED VIA PUMP

							, '132'		--CONTINUED FROM PREVIOUS ORDER

							, '143'		--REDOSE

							, '1604'		--INFUSION GREATER THAN 15 MIN

							, '1605'		--INFUSION LESS THAN 15 MIN

							, '1607'		--NEW CARTRIDGE

							, '6'			--NEW BAG

							)

	AND MA.ROUTE_CODE = 11 --INTRAVENOUS

	AND (MA.TAKEN_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

;







/* ******************* */

/* SV02                */

/* ******************* */

DROP TABLE IF EXISTS #SVO2;



SELECT

	B.ENCOUNTER_ID

	, PO.ORDER_TIME AS MBOrderTime

	, LAB_ORDER_RESULTS.RESULT_TIME

	, LAB_ORDER_RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, LAB_ORDER_RESULTS.ORD_VALUE

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY PO.ORDER_TIME ASC) AS TIME_LINE

	, LAB_ORDER_RESULTS.ORDER_PROC_ID

INTO #SVO2

FROM #Base_Pop B

	INNER JOIN [dbo].LAB_ORDER_RESULTS ON B.ENCOUNTER_ID = LAB_ORDER_RESULTS.ENCOUNTER_ID

	INNER JOIN [dbo].PROCEDURE_ORDERS PO ON PO.ORDER_PROC_ID = LAB_ORDER_RESULTS.ORDER_PROC_ID

WHERE 1=1

	AND LAB_ORDER_RESULTS.COMPONENT_ID IN (5000001861, 5000000478)

	AND (PO.ORDER_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

;







/* ******************* */

/* Lactic Acid         */

/* ******************* */

DROP TABLE IF EXISTS #LacticAcid;



SELECT

	B.ENCOUNTER_ID

	, PO.ORDER_PROC_ID

	, PO.ORDER_TIME AS MBOrderTime

	, LAB_ORDER_RESULTS.RESULT_TIME

	, LAB_ORDER_RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, LAB_ORDER_RESULTS.ORD_VALUE

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY PO.ORDER_TIME ASC) AS TIME_LINE

INTO #LacticAcid

FROM #Base_Pop B

	INNER JOIN [dbo].LAB_ORDER_RESULTS ON LAB_ORDER_RESULTS.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN [dbo].PROCEDURE_ORDERS PO ON PO.ORDER_PROC_ID = LAB_ORDER_RESULTS.ORDER_PROC_ID

WHERE

	LAB_ORDER_RESULTS.COMPONENT_ID IN (5000000446, 5000000447, 5000000449)

	AND (PO.ORDER_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

;







/* ******************* */

/* Procalcitonin       */

/* ******************* */

DROP TABLE IF EXISTS #Procalcitonin;



SELECT

	B.ENCOUNTER_ID

	, PO.ORDER_TIME AS MBOrderTime

	, LAB_ORDER_RESULTS.RESULT_TIME

	, LAB_ORDER_RESULTS.COMP_OBS_INST_TM AS CollectionTime

	, LAB_ORDER_RESULTS.ORD_VALUE

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY PO.ORDER_TIME ASC) AS TIME_LINE

	, LAB_ORDER_RESULTS.ORDER_PROC_ID

INTO #Procalcitonin

FROM #Base_Pop B

	INNER JOIN [dbo].LAB_ORDER_RESULTS ON LAB_ORDER_RESULTS.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN [dbo].PROCEDURE_ORDERS PO ON PO.ORDER_PROC_ID = LAB_ORDER_RESULTS.ORDER_PROC_ID

WHERE 1=1

	AND LAB_ORDER_RESULTS.COMPONENT_ID = 500001	-- 'LAB014'

	AND (PO.ORDER_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

;





/* ******************* */

/* Blood Culture       */

/* ******************* */

DROP TABLE IF EXISTS #BloodCultureValue;



WITH BloodCultureResults AS

(

	SELECT

		B.ENCOUNTER_ID

		, PO.ORDER_PROC_ID

		, PO.ORDER_TIME

		, RESULTS.RESULT_TIME

		, RESULTS.COMP_OBS_INST_TM

		, RESULTS.ORD_VALUE

		, CASE WHEN RESULTS.RESULT_FLAG_CODE IN (2, 218) THEN 1 ELSE 0 END AS CRITICAL_VALUE_01		-- Abnormal or Critical

		, RESULTS.LRR_BASED_ORGAN_ID

		, [ORGANISMS].EXTERNAL_NAME



	FROM #Base_Pop B



		INNER JOIN [dbo].LAB_ORDER_RESULTS RESULTS ON B.ENCOUNTER_ID = RESULTS.ENCOUNTER_ID

		INNER JOIN [dbo].PROCEDURE_ORDERS	 PO		 ON RESULTS.ORDER_PROC_ID = PO.ORDER_PROC_ID 

														AND PO.PROC_ID IN (600003,600004,600011,600012)	-- 'LAB001', 'NUR001', 'LAB012', 'LAB011'



		LEFT JOIN [dbo].ORGANISMS ON [RESULTS].LRR_BASED_ORGAN_ID = [ORGANISMS].ORGANISM_ID



	WHERE (PO.ORDER_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

)



, PositiveCultures AS

(

	SELECT

		ENCOUNTER_ID



		, MIN(ORDER_TIME)		AS [MBOrderTime]

		, MIN(COMP_OBS_INST_TM)	AS [CollectionTime]



		, COALESCE(STRING_AGG(EXTERNAL_NAME, '; ') WITHIN GROUP(ORDER BY LRR_BASED_ORGAN_ID), 'Critical Value') AS [OrganismList]



	FROM BloodCultureResults

	GROUP BY ENCOUNTER_ID

	HAVING MAX(CRITICAL_VALUE_01) = 1

)



, NegativeCultures AS

(

	SELECT

		ENCOUNTER_ID



		, MIN(ORDER_TIME)		AS [MBOrderTime]

		, MIN(COMP_OBS_INST_TM)	AS [CollectionTime]



		, 'Negative' AS [OrganismList]



	FROM BloodCultureResults

	GROUP BY ENCOUNTER_ID

	HAVING MAX(CRITICAL_VALUE_01) = 0

)



SELECT * 

INTO #BloodCultureValue

FROM PositiveCultures

UNION

SELECT * FROM NegativeCultures

;







/* ******************* */

/* Urine Culture       */

/* ******************* */

DROP TABLE IF EXISTS #UrineCultureValue;



WITH UrineCultureResults AS 

(

	SELECT

		B.ENCOUNTER_ID

		, PO.ORDER_PROC_ID

		, PO.ORDER_TIME

		, RESULTS.RESULT_TIME

		, RESULTS.COMP_OBS_INST_TM

		, RESULTS.ORD_VALUE

		, RESULTS.RESULT_FLAG_CODE

		, CASE WHEN RESULTS.RESULT_FLAG_CODE IN (2, 218) THEN 1 ELSE 0 END AS CRITICAL_VALUE_01		-- Abnormal or Critical

		, RESULTS.LRR_BASED_ORGAN_ID

		, [ORGANISMS].EXTERNAL_NAME



	FROM #Base_Pop B



		INNER JOIN [dbo].LAB_ORDER_RESULTS RESULTS ON B.ENCOUNTER_ID = RESULTS.ENCOUNTER_ID

		INNER JOIN [dbo].PROCEDURE_ORDERS	 PO		 ON RESULTS.ORDER_PROC_ID = PO.ORDER_PROC_ID 

														AND PO.PROC_ID IN (600001, 600007, 600008, 600009, 600010)	-- 'LAB002', 'LAB008', 'LAB009', 'LAB010', 'POC001'



		LEFT JOIN [dbo].ORGANISMS ON [RESULTS].LRR_BASED_ORGAN_ID = [ORGANISMS].ORGANISM_ID



	WHERE (PO.ORDER_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)



)



, PositiveCultures AS

(

	SELECT

		ENCOUNTER_ID



		, MIN(ORDER_TIME)		AS [MBOrderTime]

		, MIN(COMP_OBS_INST_TM)	AS [CollectionTime]



		, COALESCE(STRING_AGG(EXTERNAL_NAME, '; ') WITHIN GROUP(ORDER BY LRR_BASED_ORGAN_ID), 'Critical Value') AS [OrganismList]



	FROM UrineCultureResults

	GROUP BY ENCOUNTER_ID

	HAVING MAX(CRITICAL_VALUE_01) = 1

)



, NegativeCultures AS

(

	SELECT

		ENCOUNTER_ID



		, MIN(ORDER_TIME)		AS [MBOrderTime]

		, MIN(COMP_OBS_INST_TM)	AS [CollectionTime]



		, 'Negative' AS [OrganismList]		-- 'No Growth' or contamination with normal flora



	FROM UrineCultureResults

	GROUP BY ENCOUNTER_ID

	HAVING MAX(CRITICAL_VALUE_01) = 0

)



SELECT * 

INTO #UrineCultureValue

FROM PositiveCultures

UNION

SELECT * FROM NegativeCultures

;







/* ******************* */

/* CSF Culture         */

/* ******************* */

DROP TABLE IF EXISTS #CsfCultureValue;



WITH CsfCultureResults AS 

(

	SELECT

		B.ENCOUNTER_ID

		, PO.ORDER_PROC_ID

		, PO.ORDER_TIME

		, RESULTS.RESULT_TIME

		, RESULTS.COMP_OBS_INST_TM

		, RESULTS.ORD_VALUE

		, RESULTS.RESULT_FLAG_CODE

		, CASE WHEN RESULTS.RESULT_FLAG_CODE IN (2, 218) THEN 1 ELSE 0 END AS CRITICAL_VALUE_01		-- Abnormal or Critical

		, RESULTS.LRR_BASED_ORGAN_ID

		, [ORGANISMS].EXTERNAL_NAME



	FROM #Base_Pop B

		INNER JOIN [dbo].LAB_ORDER_RESULTS RESULTS ON B.ENCOUNTER_ID = RESULTS.ENCOUNTER_ID

		INNER JOIN [dbo].PROCEDURE_ORDERS	 PO		 ON RESULTS.ORDER_PROC_ID = PO.ORDER_PROC_ID

														AND PO.PROC_ID IN (600005,600006, 600002)		-- 'LAB006', 'LAB007', 'LAB003'

														AND PO.SPECIMEN_SOURCE_CODE=304				-- Lumber puncture



		LEFT JOIN [dbo].ORGANISMS ON [RESULTS].LRR_BASED_ORGAN_ID = [ORGANISMS].ORGANISM_ID



	WHERE (PO.ORDER_TIME BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

)



, PositiveCultures AS

(

	SELECT

		ENCOUNTER_ID



		, MIN(ORDER_TIME)		AS [MBOrderTime]

		, MIN(COMP_OBS_INST_TM)	AS [CollectionTime]



		, COALESCE(STRING_AGG(EXTERNAL_NAME, '; ') WITHIN GROUP(ORDER BY LRR_BASED_ORGAN_ID), 'Critical Value') AS [OrganismList]



	FROM CsfCultureResults

	GROUP BY ENCOUNTER_ID

	HAVING MAX(CRITICAL_VALUE_01) = 1

)



, NegativeCultures AS

(

	SELECT

		ENCOUNTER_ID



		, MIN(ORDER_TIME)		AS [MBOrderTime]

		, MIN(COMP_OBS_INST_TM)	AS [CollectionTime]



		, 'Negative' AS [OrganismList]



	FROM CsfCultureResults

	GROUP BY ENCOUNTER_ID

	HAVING MAX(CRITICAL_VALUE_01) = 0

)



SELECT * 

INTO #CsfCultureValue

FROM PositiveCultures

UNION

SELECT * FROM NegativeCultures

;





/* ******************* */

/* ETT                 */

/* ******************* */

DROP TABLE IF EXISTS #ETT;

SELECT

	B.ENCOUNTER_ID,

	LNA.IP_LDA_ID,

	LNA.PLACEMENT_INSTANT,

	ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY LNA.PLACEMENT_INSTANT) TIME_LINE

INTO #ETT

FROM #Base_Pop B

	INNER JOIN [dbo].LINE_DEVICE_AIRWAY LNA ON LNA.ENCOUNTER_ID = B.ENCOUNTER_ID

WHERE 1=1

	AND LNA.FLO_MEAS_ID='900112'

	AND LNA.PLACEMENT_INSTANT IS NOT NULL

	AND (LNA.PLACEMENT_INSTANT BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

;







/* ******************* */

/* IV Placement        */

/* ******************* */

DROP TABLE IF EXISTS #IV;



SELECT

	B.ENCOUNTER_ID,

	LNA.IP_LDA_ID,

	LNA.PLACEMENT_INSTANT,

	ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY LNA.PLACEMENT_INSTANT) TIME_LINE

INTO #IV

FROM #Base_Pop B

	INNER JOIN [dbo].LINE_DEVICE_AIRWAY LNA ON LNA.ENCOUNTER_ID = B.ENCOUNTER_ID

WHERE 1=1

	AND LNA.FLO_MEAS_ID='900111'

	AND LNA.PLACEMENT_INSTANT IS NOT NULL

	AND (LNA.PLACEMENT_INSTANT BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME)

;







/* ******************* */

/* Hem/Oncology        */

/* ******************* */

DROP TABLE IF EXISTS #ED2HEMONC;



SELECT

	B.ENCOUNTER_ID

	, DEP.DEPARTMENT_NAME

	, ADT_ED.EFFECTIVE_TIME AS ED2HemoncTime

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY ADT_ED.EFFECTIVE_TIME ASC) AS TIME_LINE

INTO #ED2HEMONC

FROM #Base_Pop B

	INNER JOIN [dbo].ADT_EVENTS ADT_ED 

			ON ADT_ED.ENCOUNTER_ID =  B.ENCOUNTER_ID

				AND ADT_ED.DEPARTMENT_ID IN (200108022) 

				AND ADT_ED.EVENT_TYPE_CODE = 4 --TRANSFER OUT

				AND ADT_ED.EVENT_SUBTYPE_CODE <> 2 --CANCELED

	INNER JOIN [dbo].ADT_EVENTS ADT_GENCARE 

			ON ADT_ED.XFER_IN_EVENT_ID = ADT_GENCARE.EVENT_ID

				AND ADT_GENCARE.DEPARTMENT_ID IN (200108001, 200108115, 20120106, 20101124, 20108007) 

				AND ADT_GENCARE.EVENT_TYPE_CODE = 3 --TRANSFER IN

				AND ADT_GENCARE.EVENT_SUBTYPE_CODE <> 2 --CANCELED

	INNER JOIN [dbo].DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = ADT_GENCARE.DEPARTMENT_ID

;







/* ******************* */

/* ICU                 */

/* ******************* */

DROP TABLE IF EXISTS #ED2ICU;



SELECT

	B.ENCOUNTER_ID

	, DEP.DEPARTMENT_NAME

	, ADT_ED.EFFECTIVE_TIME AS ED2ICUTime

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY ADT_ED.EFFECTIVE_TIME ASC) AS TIME_LINE

INTO #ED2ICU

FROM #Base_Pop B

	INNER JOIN [dbo].ADT_EVENTS ADT_ED ON ADT_ED.ENCOUNTER_ID =  B.ENCOUNTER_ID

				AND ADT_ED.DEPARTMENT_ID IN (200108022) 

				AND ADT_ED.EVENT_TYPE_CODE = 4 --TRANSFER OUT

				AND ADT_ED.EVENT_SUBTYPE_CODE <> 2 --CANCELED

	INNER JOIN [dbo].ADT_EVENTS ADT_GENCARE ON ADT_ED.XFER_IN_EVENT_ID = ADT_GENCARE.EVENT_ID

				AND ADT_GENCARE.DEPARTMENT_ID IN (20101116			--EAST ICU

														, 20101124			--EAST CARDIAC ICU

														, 20101126			--EAST NEURO ICU

														, 20101127			--EAST PEDIATRIC ICU

														, 20101128			--EAST SURGICAL ICU

														, 20101165			--EAST REMOTE ICU

														, 20120106			--WEST CARDIAC ICU

														, 20120121			--WEST ICU							

														, 200108001			--MAIN 2 PAVILION PICU

														, 200108070			--MAIN 3 CICU

														, 200108115			--MAIN 2 PICU NEURO

														, 200108147			--MAIN PHARMACY ICU

														) 

				AND ADT_GENCARE.EVENT_TYPE_CODE = 3 --TRANSFER IN

				AND ADT_GENCARE.EVENT_SUBTYPE_CODE <> 2 --CANCELED

	INNER JOIN [dbo].DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = ADT_GENCARE.DEPARTMENT_ID

;







/* ******************* */

/* Gen Care            */

/* ******************* */

DROP TABLE IF EXISTS #ED2GEN;



SELECT

	B.ENCOUNTER_ID

	, DEP.DEPARTMENT_NAME

	, ADT_ED.EFFECTIVE_TIME AS ED2GENTime

	, ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY ADT_ED.EFFECTIVE_TIME ASC) AS TIME_LINE

	, GEN2ICU.EFFECTIVE_TIME AS [Gen Back To ICU Time]

	, GEN2ICU.DEPARTMENT_NAME AS [Gen Back To ICU Department]

INTO #ED2GEN

FROM #Base_Pop B

	INNER JOIN [dbo].ADT_EVENTS ADT_ED 

			ON ADT_ED.ENCOUNTER_ID =  B.ENCOUNTER_ID

				AND ADT_ED.DEPARTMENT_ID IN (200108022) 

				AND ADT_ED.EVENT_TYPE_CODE = 4 --TRANSFER OUT

				AND ADT_ED.EVENT_SUBTYPE_CODE <> 2 --CANCELED

	INNER JOIN [dbo].ADT_EVENTS ADT_GENCARE 

			ON ADT_ED.XFER_IN_EVENT_ID = ADT_GENCARE.EVENT_ID

				AND ADT_GENCARE.DEPARTMENT_ID IN (200108021, 200108020, 200108018, 200108017, 200108110, 200108012, 200108011, 200108010, 200108009, 200108008) 

				AND ADT_GENCARE.EVENT_TYPE_CODE = 3 --TRANSFER IN

				AND ADT_GENCARE.EVENT_SUBTYPE_CODE <> 2 --CANCELED

	INNER JOIN [dbo].DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = ADT_GENCARE.DEPARTMENT_ID	

	OUTER APPLY--09.09.2020 V_DEV001 added this to check for PATIENTS who went from ED --> Gen Care and then back to ICU within 24 hours

	(

		SELECT TOP 1 ICU.EFFECTIVE_TIME, DEP.DEPARTMENT_NAME

		FROM [dbo].ADT_EVENTS ICU

		INNER JOIN [dbo].DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = ICU.DEPARTMENT_ID

		WHERE ICU.ENCOUNTER_ID = ADT_GENCARE.ENCOUNTER_ID

			AND (ICU.EFFECTIVE_TIME BETWEEN ADT_GENCARE.EFFECTIVE_TIME AND DATEADD(HH,24,ADT_GENCARE.EFFECTIVE_TIME) )

			AND ICU.DEPARTMENT_ID IN (20101116			--EAST ICU

									, 20101124			--EAST CARDIAC ICU

									, 20101126			--EAST NEURO ICU

									, 20101127			--EAST PEDIATRIC ICU

									, 20101128			--EAST SURGICAL ICU

									, 20101165			--EAST REMOTE ICU

									, 20120106			--WEST CARDIAC ICU

									, 20120121			--WEST ICU							

									, 200108001			--MAIN 2 PAVILION PICU

									, 200108070			--MAIN 3 CICU

									, 200108115			--MAIN 2 PICU NEURO

									, 200108147			--MAIN PHARMACY ICU

									) 

			AND ICU.EVENT_TYPE_CODE = 3 --TRANSFER IN

			AND ICU.EVENT_SUBTYPE_CODE <> 2 --CANCELED

		ORDER BY ICU.EFFECTIVE_TIME ASC

	) GEN2ICU

;





/* ******************* */

/* BPA                 */

/* ******************* */

DROP TABLE IF EXISTS #BPA;



SELECT

	B.ENCOUNTER_ID,

	ALT.ALT_ID,

	AH.ALT_ACTION_INST,

	RAS.NAME AS ALERT_STATUS,

	RSP.NAME AS ALERT_SHOWN_PLACE,

	RAA.NAME AS ACTION_TAKE,

	ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY AH.ALT_ACTION_INST) AS TIME_LINE,

	RAOR.NAME AS OVERRIDDEN,

	ah.SPEC_OVR_CMNT,

	EMP.NAME

INTO #BPA

FROM #Base_Pop B

	INNER JOIN [dbo].CLINICAL_ALERTS ALT ON ALT.VISIT_ID = B.ENCOUNTER_ID AND ALT.BPA_LOCATOR_ID = '900130001'

	INNER JOIN [dbo].ALERT_HISTORY AH ON AH.ALT_ID = ALT.ALT_ID

	LEFT OUTER JOIN [dbo].ALERT_ACTIONS AA ON AA.ALT_ENCOUNTER_ID = AH.ALT_ENCOUNTER_ID AND AA.LINE=1

	LEFT OUTER JOIN [dbo].REF_ALERT_ACTIONS RAA ON RAA.ALT_ACTION_TAKEN_CODE = AA.ACTION_TAKEN_CODE

	LEFT OUTER JOIN [dbo].REF_ALERT_OVERRIDE_REASONS RAOR ON RAOR.ALRT_SP_OVR_RSN_CODE = AH.SPEC_OVR_RSN_CODE

	LEFT OUTER JOIN [dbo].REF_ALERT_STATUS RAS ON RAS.ALT_STATUS_CODE = AH.ALT_STATUS_CODE

	LEFT OUTER JOIN [dbo].REF_SHOWN_PLACE RSP ON RSP.SHOWN_PLACE_CODE = AH.SHOWN_PLACE_CODE

	LEFT OUTER JOIN [dbo].EMPLOYEES EMP ON EMP.USER_ID = AH.USER_ID

WHERE AH.ALT_ACTION_INST BETWEEN B.ADT_ARRIVAL_TIME AND B.ED_DEPARTURE_TIME

;







/* ******************* */

/* Severe Sepsis       */

/* ******************* */

DROP TABLE IF EXISTS #Base_Pop_Severe_ED_Scores;



SELECT

	BP.ENCOUNTER_ID

	, FM.MEAS_VALUE

	, FM.RECORDED_TIME

	, ROW_NUMBER() OVER(PARTITION BY BP.ENCOUNTER_ID ORDER BY RECORDED_TIME ASC) AS TIME_LINE

INTO #Base_Pop_Severe_ED_Scores 

FROM #Base_Pop BP 

	INNER JOIN [dbo].HOSPITAL_ENCOUNTERS HE ON HE.ENCOUNTER_ID = BP.ENCOUNTER_ID

	INNER JOIN [dbo].FLOWSHEET_RECORDS FR ON HE.INPATIENT_DATA_ID = FR.INPATIENT_DATA_ID

	INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS FM ON FM.FSD_ID = FR.FSD_ID

WHERE 1=1

	AND FM.FLO_MEAS_ID IN ('9000161709','9000002613')--SEPSIS SCORE--ADDED NEW ED SEPSIS SCORE 9000002613 ON 10.01.2019

	and FM.RECORDED_TIME BETWEEN BP.ADT_ARRIVAL_TIME AND BP.ED_DEPARTURE_TIME

;





/* ******************* */

/* Positive Sepsis     */

/* ******************* */

DROP TABLE IF EXISTS #ED_PositiveScores;



SELECT

	ENCOUNTER_ID

	, MEAS_VALUE

	, RECORDED_TIME

	, ROW_NUMBER() OVER(PARTITION BY ENCOUNTER_ID ORDER BY RECORDED_TIME ASC) AS FIRST_TIME_LINE

	, ROW_NUMBER() OVER(PARTITION BY ENCOUNTER_ID ORDER BY RECORDED_TIME DESC) AS LAST_TIME_LINE

INTO #ED_PositiveScores

FROM #Base_Pop_Severe_ED_Scores

WHERE MEAS_VALUE > 4

;





/* ************************ */

/* Severe + Positive Sepsis */

/* ************************ */

DROP TABLE IF EXISTS #Base_Pop_SepsisScores_ConCat;



SELECT DISTINCT CAT.ENCOUNTER_ID,

        STUFF(( SELECT ',' + CONVERT(VARCHAR,SUB.MEAS_VALUE)-- AS [text()]

                FROM #Base_Pop_Severe_ED_Scores SUB

				WHERE SUB.ENCOUNTER_ID = CAT.ENCOUNTER_ID

				ORDER BY RECORDED_TIME

                FOR XML PATH('')

                ), 1, 1, '' )

        AS [AllSepsis_Scores]

INTO #Base_Pop_SepsisScores_ConCat

FROM  #Base_Pop_Severe_ED_Scores CAT





/* ******************************************* */

/* Time from First Positive Score -> First Abx */

/* ******************************************* */

DROP TABLE IF EXISTS #FirstPositiveOD_To_ABXAdminTime;



SELECT

	[subQ].ENCOUNTER_ID

	,[subQ].MEDICATION

	,[subQ].ABX_ADMIN_TIME

	,[subQ].RECORDED_TIME,

	DATEDIFF(MI, [subQ].RECORDED_TIME, [subQ].ABX_ADMIN_TIME) AS POSOD2ABX



INTO #FirstPositiveOD_To_ABXAdminTime



FROM 

	(

		SELECT 

			[#BasePopABX].ENCOUNTER_ID

			, [#BasePopABX].[NAME] AS MEDICATION

			, [#BasePopABX].ABX_ADMIN_TIME

			, [#ED_PositiveScores].MEAS_VALUE

			, [#ED_PositiveScores].RECORDED_TIME

			, ROW_NUMBER() OVER(PARTITION BY [#BasePopABX].ENCOUNTER_ID ORDER BY [#BasePopABX].ABX_ADMIN_TIME ASC) MYLINE

		FROM #BasePopABX

		INNER JOIN #ED_PositiveScores ON [#BasePopABX].ENCOUNTER_ID = [#ED_PositiveScores].ENCOUNTER_ID

			AND [#ED_PositiveScores].RECORDED_TIME < [#BasePopABX].ABX_ADMIN_TIME

			AND [#ED_PositiveScores].FIRST_TIME_LINE=1

	) subQ

WHERE [subQ].MYLINE=1

;





/* ******************************** */

/* First Abx Order and Time Details */

/* ******************************** */

DROP TABLE IF EXISTS #FirstABXAdminTimeDetails;



SELECT

	A.ENCOUNTER_ID

	, ORD.ORDER_MED_ID "Order ID"

	, ORD.ORDERING_DTTM "Order date and time"

	, ORT.RXQ_INSTANT [In VERIFY Queue Time]

	, ORT.RX_VERIFY_INSTANT [Verified in Queue Time]

	, ORT.[Queue Verified by]

	, VERIFY.ACTION_INSTANT " Order VERIFY date and time"

	, DISPENSE.ACTION_INSTANT "Order Dispense date and time"

	, ACTION.ACTION_DTTM "Rx Dispense Sent Time"



INTO #FirstABXAdminTimeDetails



FROM #BasePopABX A

	INNER JOIN [dbo].V_PHARMACY_ORDER ORD on ORD.ORDER_MED_ID = A.ORDER_MED_ID AND A.TIME_LINE=1--LOOK FOR FIRST ANTIBIOTIC ADMINISTRATION ONLY

	INNER JOIN

		(

			SELECT

				ODI.ORDER_MED_ID, ODI.ACTION_INSTANT,ODI.CONTACT_DATE_REAL, ROW_NUMBER()OVER(PARTITION BY ODI.ORDER_MED_ID ORDER BY ACTION_INSTANT ASC) AS MYLINE

			FROM

			[dbo].ORDER_DISPENSE_INFO  ODI WHERE ODI.ORD_CNTCT_TYPE_CODE = 4--VERIFY

		)VERIFY on ord.ORDER_MED_ID = VERIFY.ORDER_MED_ID AND VERIFY.MYLINE=1

	INNER JOIN

		(

			SELECT

				ODI.ORDER_MED_ID, ODI.ACTION_INSTANT,ODI.VERIFY_CONTDATREAL,ODI.CONTACT_DATE_REAL,ODI.CONTACT_DATE, ROW_NUMBER()OVER(PARTITION BY ODI.ORDER_MED_ID ORDER BY ACTION_INSTANT ASC) AS MYLINE

			FROM

			[dbo].ORDER_DISPENSE_INFO  ODI WHERE ODI.ORD_CNTCT_TYPE_CODE = 95--DISPENSE

		)DISPENSE ON ord.ORDER_MED_ID = DISPENSE.ORDER_MED_ID AND DISPENSE.MYLINE=1

			AND VERIFY.CONTACT_DATE_REAL = DISPENSE.VERIFY_CONTDATREAL

			AND DISPENSE.ACTION_INSTANT<A.ABX_ADMIN_TIME--MAKE SURE WE ARE LOOKING AT THE RIGHT MEDICATION ADMINT TIME. A MEDICATION ORDER COULD HAVE MULTIPLE DISPENSES

	LEFT OUTER JOIN [dbo].V_PHARMACY_DISPENSE disp on DISPENSE.ORDER_MED_ID = disp.ORDER_MED_ID and DISPENSE.CONTACT_DATE_REAL = disp.CONTACT_DATE_REAL

	LEFT OUTER JOIN 

		(

			SELECT PDA.ACTION_ID, PDA.ACTION_DTTM, ROW_NUMBER()OVER(PARTITION BY PDA.ACTION_ID ORDER BY PDA.ACTION_DTTM ASC) AS MYLINE FROM 

			[dbo].V_PHARMACY_DISPENSE_ACTION PDA WHERE PDA.ACTION_TYPE_CODE=270

		)action on disp.ACTION_ID = action.ACTION_ID AND ACTION.MYLINE=1

	LEFT OUTER JOIN 

		(

			SELECT ORT1.ORDER_MED_ID,ORT1.RXQ_INSTANT, ORT1.RX_VERIFY_INSTANT, ORT1.RX_VER_USER_ID, EMP.NAME AS [Queue Verified by],

				ROW_NUMBER()OVER(PARTITION BY ORT1.ORDER_MED_ID ORDER BY LINE DESC) MYLINE

			FROM [dbo].RX_VERIFY_TRACE ORT1

			LEFT OUTER JOIN [dbo].EMPLOYEES EMP ON EMP.USER_ID = ORT1.RX_VER_USER_ID

		)ORT ON ORT.ORDER_MED_ID = ord.ORDER_MED_ID AND ORT.MYLINE=1

;



/* ********** */

/* Bed Events */

/* ********** */

DROP TABLE IF EXISTS #BedEvents;



SELECT

	B.ENCOUNTER_ID, C.RECORD_NAME AS [EVENT], EEI.EVENT_TYPE AS [EVENT ID],EEI.EVENT_TIME,

	ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID ORDER BY EEI.EVENT_TIME ) AS TIME_LINE,

	ROW_NUMBER() OVER(PARTITION BY B.ENCOUNTER_ID, EEI.EVENT_TYPe ORDER BY EEI.EVENT_TIME ) AS REQ_LINE--JUST IN CASE IF THERE IS MORE THAN ONE EVENT OF THE SAME EVENT_TYPE.

INTO #BedEvents

FROM #Base_Pop B

	INNER JOIN [dbo].ED_PATIENT_INFO EPI ON EPI.ENCOUNTER_ID = B.ENCOUNTER_ID

	INNER JOIN [dbo].ED_EVENT_INFO EEI ON EEI.EVENT_ID = EPI.EVENT_ID AND EEI.EVENT_TYPE IN ('2600000347','2600000346')

	INNER JOIN [dbo].ED_EVENT_TEMPLATES C ON EEI.EVENT_TYPE = C.RECORD_ID

;



/* ************ */

/* Readmissions */

/* ************ */

DROP TABLE IF EXISTS #Base_Pop_ED_Readmit_All;



SELECT DISTINCT BP.ENCOUNTER_ID

INTO #Base_Pop_ED_Readmit_All

FROM #Base_Pop BP

	INNER JOIN [dbo].ED_ENCOUNTERS_DM EED ON EED.PATIENT_ID = BP.PATIENT_ID AND (EED.ARRIVAL_DTTM BETWEEN BP.ED_DEPARTURE_TIME AND DATEADD(HH,24,BP.ED_DEPARTURE_TIME))

;



/* *********************************** */

/* Readmissions (positive sepsis only) */

/* *********************************** */

DROP TABLE IF EXISTS #Base_Pop_ED_Readmit;



SELECT DISTINCT BP.ENCOUNTER_ID

INTO #Base_Pop_ED_Readmit

FROM #ED_PositiveScores EPS

	INNER JOIN #Base_Pop BP ON EPS.ENCOUNTER_ID = BP.ENCOUNTER_ID AND EPS.FIRST_TIME_LINE=1

	INNER JOIN [dbo].ED_ENCOUNTERS_DM EED ON EED.PATIENT_ID = BP.PATIENT_ID AND (EED.ARRIVAL_DTTM BETWEEN BP.ED_DEPARTURE_TIME AND DATEADD(HH,24,BP.ED_DEPARTURE_TIME))

;





/* *********** */

/* Final Query */

/* *********** */

SELECT

	[BasePop].PATIENT_MRN		AS MRN

	,[BasePop].PATIENT_NAME			AS PATIENTS

	,[BasePop].[Ethnic Group]

	,[BasePop].[Race]

	,[BasePop].ENCOUNTER_ID	AS ENC_ID

	,[BasePop].AGE_MONTHS		AS [Age at ED Arrival (Months)]

	,[BasePop].AGE_YEARS		AS [Age at ED Arrival (Years)]

	,[BasePop].AGE_IN_DAYS		AS [Age In Days]



	,CASE WHEN [BasePop].AGE_IN_DAYS <= 21 THEN 1 ELSE 0 END						AS [Age in Days Count]

	,CASE WHEN [BasePop].AGE_IN_DAYS <= 21 THEN '<= 21 Days' ELSE '> 21 Days' END	AS [Age in Days Indicator]



	,[BasePop].[Location]

	,[BasePop].DATE_STAMP

	,[BasePop].ADT_ARRIVAL_TIME		AS [ED Arrival Time]

	,[BasePop].TRIAGE_START_DTTM	AS [Traige Start Time]

	,[BasePop].TRIAGE_END_DTTM		AS [Traige Stop Time]



	,CONVERT(DATE, [BasePop].ADT_ARRIVAL_TIME)		AS [ED Arrival Date]	-- for PBI DateTable



	,VR.REASON_VISIT_NAME			AS [Chief Complaint]

	,RSN.AllEncReasons				AS [Other Visit Reasons]

	,[BasePop].ED_DEPARTURE_TIME	AS [ED Departure Time]

	,[BasePop].HOSP_ADMSN_TIME		AS [HOSP Admit Time]

	,[BasePop].HOSP_DISCH_TIME		AS [HOSP Discharge Time]

	,[BasePop].Disposition			AS [ED Disposition]



	,FIRST_ADMIT_DEPARTMENT.ADT_DEPARTMENT_NAME AS [First IP Department]



	,CASE WHEN SepsisScreened.ENCOUNTER_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS [Sepsis Screened]



	,CASE	WHEN [#ED_PositiveScores].RECORDED_TIME IS NOT NULL

			THEN CASE	WHEN DATEPART(HOUR,[#ED_PositiveScores].RECORDED_TIME) >= 7 and DATEPART(HOUR,[#ED_PositiveScores].RECORDED_TIME) < 19 

						THEN 'AM (Day Shift)'

						ELSE 'PM (Night Shift)'

			END

	  END AS [First Positive Score AM/PM]



	,[#ED_PositiveScores].RECORDED_TIME		AS [First Positive Score Time]

	,[#ED_PositiveScores].MEAS_VALUE		AS [First Positive Score]

	,ALLSCORES.AllSepsis_Scores				AS [All Sepsis Scores]



	,ABXTimes.[Order date and time]

	,ABXTimes.[In VERIFY Queue Time]

	,ABXTimes.[Verified in Queue Time]

	,ABXTimes.[Queue Verified by]

	,ABXTimes.[Order Dispense date and time]

	,ABXTimes.[Rx Dispense Sent Time]



	/* Antibiotic (1st) */

	, ABX1.ABX_ADMIN_TIME	AS [First ABX Admin Time]

	, ABX1.[NAME]			AS [First ABX Name]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, ABX1.ABX_ADMIN_TIME)				AS [Arrival To First ABX Admin Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, ABX1.ABX_ADMIN_TIME)				AS [Triage To First ABX Admin Time]

	, DATEDIFF(MI, [#ED_PositiveScores]. RECORDED_TIME,ABX1.ABX_ADMIN_TIME)		AS [First Positive Screen To First ABX Time]



	/* Antibiotic (2nd) */

	, ABX2.ABX_ADMIN_TIME	AS [Second ABX Admin Time]

	, ABX2.[NAME]			AS [Second ABX Name]



	, DATEDIFF(MI, ABX1.ABX_ADMIN_TIME, ABX2.ABX_ADMIN_TIME)					AS [First ABX To Second ABX Admin Time]

	, DATEDIFF(MI, [#ED_PositiveScores].RECORDED_TIME, ABX2.ABX_ADMIN_TIME)		AS [First Positive Screen To Second ABX Time]

	

	/* OrderSet */

	, [#SSOrderSet].ORDER_DTTM AS [Order Set Time]

	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [#SSOrderSet].ORDER_DTTM)	AS [Arrival To Order Set Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [#SSOrderSet].ORDER_DTTM)	AS [Triage To Order Set Time]



	/* Bolus (1st) */

	, BPB1.BOLUS_ADMIN_TIME AS [Bolus 1 Admin Time]

	, BPB1.BOLUS_VOLUME		AS [Bolus 1 Volume]

	, CASE	WHEN BPB1.Medication = 'ALBUMIN, HUMAN 95 % INTRAVENOUS SOLUTION' THEN 'Albumin 95%' ELSE BPB1.Medication END	AS [Bolus 1 Administered]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, BPB1.BOLUS_ADMIN_TIME) AS [Arrival To First Bolus Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, BPB1.BOLUS_ADMIN_TIME) AS [Triage To First Bolus Time]

	, DATEDIFF(MI, [#ED_PositiveScores].RECORDED_TIME, BPB1.BOLUS_ADMIN_TIME) AS [First Positive Screen To First Bolus Time]

	

	/* Bolus (2nd) */

	, BPB2.BOLUS_ADMIN_TIME AS [Bolus 2 Admin Time]

	, BPB2.BOLUS_VOLUME		AS [Bolus 2 Volume]

	, CASE	WHEN BPB2.Medication = 'ALBUMIN, HUMAN 95 % INTRAVENOUS SOLUTION' THEN 'Albumin 95%' ELSE BPB2.Medication	END AS [Bolus 2 Administered]



	, DATEDIFF(MI, [#ED_PositiveScores].RECORDED_TIME, BPB2.BOLUS_ADMIN_TIME)	AS [First Positive Screen To Second Bolus Time]

	, DATEDIFF(MI, BPB1.BOLUS_ADMIN_TIME, BPB2.BOLUS_ADMIN_TIME)				AS [First Bolus To Second Bolus Time]

	

	/* Bolus (3rd) */

	, BPB3.BOLUS_ADMIN_TIME AS [Bolus 3 Admin Time]

	, BPB3.BOLUS_VOLUME		AS [Bolus 3 Volume]

	, CASE	WHEN BPB3.Medication = 'ALBUMIN, HUMAN 95 % INTRAVENOUS SOLUTION' THEN 'Albumin 95%' ELSE BPB3.Medication	END AS [Bolus 3 Administered]



	, DATEDIFF(MI, [#ED_PositiveScores].RECORDED_TIME, BPB3.BOLUS_ADMIN_TIME)	AS [First Positive Screen To Third Bolus Time]

	, DATEDIFF(MI, BPB2.BOLUS_ADMIN_TIME, BPB3.BOLUS_ADMIN_TIME)				AS [Second Bolus To Third Bolus Time]



	, EW.EncWeight AS [PATIENTS Weight]



	/* Hypotension */

	, [#Hypotension].RECORDED_TIME	AS [First Hypotension Recorded Time]

	, [#Hypotension].MEAS_VALUE		AS [First Hypotension Value]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [#Hypotension].RECORDED_TIME)	AS [Arrival To First Hypotension Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [#Hypotension].RECORDED_TIME)	AS [Triage To First Hypotension Time]



	/* CVL Placement */

	, CVL.PLACEMENT_INSTANT AS [CVL Placement Time]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, CVL.PLACEMENT_INSTANT)	AS [Arrival To CLV Placement Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, CVL.PLACEMENT_INSTANT)	AS [Triage To CLV Placement Time]



	/* Presssors */

	, [#Pressors].TAKEN_TIME AS [Vasopressor Admin Time]

	, [#Pressors].MEDICATION AS [Vasopressor Administered]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [#Pressors].TAKEN_TIME)					AS [Arrival To Vasopressor Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [#Pressors].TAKEN_TIME)					AS [Triage To Vasopressor Time]

	, DATEDIFF(MI,[#ED_PositiveScores].RECORDED_TIME, [#Pressors].TAKEN_TIME)	AS [First Positive Screen To Vasopressor Time]



	/* SVO2 */

	, [#SVO2].MBOrderTime		AS [SVO2 Order Time]

	, [#SVO2].CollectionTime	AS [SVO2 Order Collection Time]

	, [#SVO2].ORD_VALUE			AS [SVO2 Lab Result]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [#SVO2].MBOrderTime)	AS [Arrival To SVO2 Order Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [#SVO2].MBOrderTime)		AS [Triage To SVO2 Order Time]



	/* Lactic Acid */

	, [#LacticAcid].MBOrderTime		AS [Lactic Acid Order Time]

	, [#LacticAcid].CollectionTime	AS [Lactic Acid Order Collection Time]

	, [#LacticAcid].ORD_VALUE		AS [Lactic Acid Lab Result]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [#LacticAcid].MBOrderTime)	AS [Arrival To Lactic Acid Order Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [#LacticAcid].MBOrderTime)		AS [Triage To Lactic Acid Order Time]



	/* Procalcitonin */

	, [#Procalcitonin].MBOrderTime		AS [Procalcitonin Order Time]

	, [#Procalcitonin].CollectionTime	AS [Procalcitonin Order Collection Time]

	, [#Procalcitonin].ORD_VALUE		AS [Procalcitonin Lab Result]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [#Procalcitonin].MBOrderTime) AS [Arrival To PRO Order Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [#Procalcitonin].MBOrderTime)	AS [Triage To PRO Order Time]



	/* Blood Culture */

	, [BC].MBOrderTime		AS [Blood Culture Order Time]

	, [BC].CollectionTime	AS [Blood Culture Order Collection Time]

	, [BC].OrganismList		AS [Blood Culture Lab Result]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [BC].MBOrderTime)	AS [Arrival To Blood Culture Order Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [BC].MBOrderTime)		AS [Triage To Blood Culture Order Time]



	/* Urine Culture */

	, [UC].MBOrderTime		AS [Urine Culture Order Time]

	, [UC].CollectionTime	AS [Urine Culture Order Collection Time]

	, [UC].OrganismList		AS [Urine Culture Lab Result]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [UC].MBOrderTime)	AS [Arrival To Urine Culture Order Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [UC].MBOrderTime)		AS [Triage To Urine Culture Order Time]



	/* CSF Culture */

	, [CSF].MBOrderTime			AS [CSF Order Time]

	, [CSF].CollectionTime		AS [CSF Order Collection Time]

	, [CSF].OrganismList		AS [CSF Lab Result]



	, DATEDIFF(MI, [BasePop].ADT_ARRIVAL_TIME, [CSF].MBOrderTime)	AS [Arrival To CSF Order Time]

	, DATEDIFF(MI, [BasePop].TRIAGE_END_DTTM, [CSF].MBOrderTime)	AS [Triage To CSF Order Time]



	, [#ETT].PLACEMENT_INSTANT AS [First ETT Placement Time]

	, [#IV].PLACEMENT_INSTANT AS [First PIV Placement Time]

	, DATEDIFF(MI,[#ED_PositiveScores].RECORDED_TIME, [#IV].PLACEMENT_INSTANT) AS [First Positive Screen To First PIV Placement]

	, BE1.EVENT_TIME AS [ED IP Bed Requested Time]

	, BE2.EVENT_TIME AS [ED IP Bed Assigned Time]

	, DATEDIFF(MI,BE1.EVENT_TIME,BE2.EVENT_TIME) AS [Bed Request to Bed Assigned Time]

	, DATEDIFF(MI,BE1.EVENT_TIME, ICU.ED2ICUTime) AS [IP Bed Request to PICU Transfer Time]

	, [#ED2HEMONC].ED2HemoncTime

	, ICU.ED2ICUTime

	, GEN.ED2GENTime



	/* BPA */

	, [#BPA].ALT_ACTION_INST	AS [First BPA CLINICAL_ALERTS/Action Time]

	, [#BPA].ACTION_TAKE		AS [Action Taken]

	, [#BPA].OVERRIDDEN			AS [BPA Overridden]

	, [#BPA].SPEC_OVR_CMNT		AS [BPA Overridden Comment]

	, [#BPA].[NAME]				AS [BPA Action User]



	, [#SepsisAlertCancelled].SEPSIS_ALERT_CANC_TIME

	, [#SepsisAlertCancelled].SEPSIS_ALERT_CANC_BY

	, CASE WHEN [#BPA].ALT_ACTION_INST IS NOT NULL THEN ISNULL([#SepsisAlertCancelled].SEPSIS_ALERT_CANC_FLAG, 'N') END AS [SEPSIS_ALERT_CANC_FLAG]



	/* Blood pressure */

	, LAST_BP.RECORDED_TIME AS [Last Blood Pressure Time]

	, LAST_BP.MEAS_VALUE AS [Last Blood Pressure Value]

	, DATEDIFF(MI,LAST_BP.RECORDED_TIME, [#ED_PositiveScores].RECORDED_TIME) AS [Last BP to First Positive Score Time]

	, FIRST_BP.RECORDED_TIME AS [First Blood Pressure Time]

	, FIRST_BP.MEAS_VALUE AS [First Blood Pressure Value]

	, DATEDIFF(MI, [#ED_PositiveScores].RECORDED_TIME, FIRST_BP.RECORDED_TIME) AS [First Positive Score Time to First BP]



	, [LAST_BP_PERCENTILE].RECORDED_TIME	AS [Last BP Percentile Time]

	, [LAST_BP_PERCENTILE].MEAS_VALUE		AS [Last BP Percentile Value]

	, [FIRST_BP_PERCENTILE].RECORDED_TIME	AS [First BP Percentile Time]

	, [FIRST_BP_PERCENTILE].MEAS_VALUE		AS [First BP Percentile Value]



	, CASE WHEN ED_BORDER.ENCOUNTER_ID IS NOT NULL THEN 'Y' ELSE 'N' END	AS [ED Border PATIENTS]

	, CASE WHEN READMIT.ENCOUNTER_ID IS NOT NULL THEN 'Y' ELSE 'N' END	AS [Sepsis Pos ED Readmit in 24Hrs]

	, CASE WHEN READMITALL.ENCOUNTER_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS [ED Readmit in 24Hrs]

	, CASE WHEN SEVERE.ENCOUNTER_ID IS NOT NULL THEN 'Y' ELSE 'N' END		AS [SSS Severe Sepsis Criteria Met]

	, CASE WHEN NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 'Y' ELSE 'N' END	AS [SSS Non Severe Sepsis Criteria Met]

 

	/* Positive sepsis screen */

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NOT NULL THEN 1 ELSE 0 END	AS [Positive Sepsis and OrderSet Placed]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NULL THEN 1 ELSE 0 END		AS [Positive Sepsis and OrderSet NOT Placed]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NOT NULL THEN 1 ELSE 0 END		AS [Positive Sepsis and Abx Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NULL THEN 1 ELSE 0 END			AS [Positive Sepsis and Abx NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NOT NULL THEN 1 ELSE 0 END		AS [Positive Sepsis and Bolus Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NULL THEN 1 ELSE 0 END			AS [Positive Sepsis and Bolus NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BC.MBOrderTime IS NOT NULL THEN 1 ELSE 0 END				AS [Positive Sepsis and Blood Culture Ordered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BC.MBOrderTime IS NULL THEN 1 ELSE 0 END					AS [Positive Sepsis and Blood Culture NOT Ordered]



	/* Negative sepsis screen */

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NOT NULL THEN 1 ELSE 0 END	AS [Negative Sepsis and OrderSet Placed]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NULL THEN 1 ELSE 0 END		AS [Negative Sepsis and OrderSet NOT Placed]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NOT NULL THEN 1 ELSE 0 END			AS [Negative Sepsis and Abx Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NULL THEN 1 ELSE 0 END				AS [Negative Sepsis and Abx NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NOT NULL THEN 1 ELSE 0 END		AS [Negative Sepsis and Bolus Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NULL THEN 1 ELSE 0 END			AS [Negative Sepsis and Bolus NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BC.MBOrderTime IS NOT NULL THEN 1 ELSE 0 END				AS [Negative Sepsis and Blood Culture Ordered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BC.MBOrderTime IS NULL THEN 1 ELSE 0 END					AS [Negative Sepsis and Blood Culture NOT Ordered]



	/* SSS severe (+) and Sepsis (+) */

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS SEVERE and Positive Sepsis and OrderSet Placed]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS SEVERE and Positive Sepsis and OrderSet NOT Placed]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS SEVERE and Positive Sepsis and Abx Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END				AS [SSS SEVERE and Positive Sepsis and Abx NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS SEVERE and Positive Sepsis and Bolus Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS SEVERE and Positive Sepsis and Bolus NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BC.MBOrderTime IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END				AS [SSS SEVERE and Positive Sepsis and Blood Culture Ordered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BC.MBOrderTime IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END					AS [SSS SEVERE and Positive Sepsis and Blood Culture NOT Ordered]



	/* SSS non-severe (+) and Sepsis (+) */

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END	AS [SSS NON SEVERE and Positive Sepsis and OrderSet Placed]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS NON SEVERE and Positive Sepsis and OrderSet NOT Placed]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS NON SEVERE and Positive Sepsis and Abx Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS NON SEVERE and Positive Sepsis and Abx NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS NON SEVERE and Positive Sepsis and Bolus Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS NON SEVERE and Positive Sepsis and Bolus NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BC.MBOrderTime IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS NON SEVERE and Positive Sepsis and Blood Culture Ordered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NOT NULL AND BC.MBOrderTime IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END				AS [SSS NON SEVERE and Positive Sepsis and Blood Culture NOT Ordered]



	/* SSS severe (+) and Sepsis (neg) */

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END	AS [SSS SEVERE and Negative Sepsis and OrderSet Placed]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS SEVERE and Negative Sepsis and OrderSet NOT Placed]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS SEVERE and Negative Sepsis and Abx Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS SEVERE and Negative Sepsis and Abx NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS SEVERE and Negative Sepsis and Bolus Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS SEVERE and Negative Sepsis and Bolus NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BC.MBOrderTime IS NOT NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS SEVERE and Negative Sepsis and Blood Culture Ordered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BC.MBOrderTime IS NULL AND SEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END				AS [SSS SEVERE and Negative Sepsis and Blood Culture NOT Ordered]



	/* SSS non-severe (+) and Sepsis (neg) */

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END	AS [SSS NON SEVERE and Negative Sepsis and OrderSet Placed]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND [#SSOrderSet].ORDER_DTTM IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS NON SEVERE and Negative Sepsis and OrderSet NOT Placed]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS NON SEVERE and Negative Sepsis and Abx Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND ABX1.ABX_ADMIN_TIME IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS NON SEVERE and Negative Sepsis and Abx NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END		AS [SSS NON SEVERE and Negative Sepsis and Bolus Administered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BPB1.BOLUS_ADMIN_TIME IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END			AS [SSS NON SEVERE and Negative Sepsis and Bolus NOT Administered]



	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BC.MBOrderTime IS NOT NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END				AS [SSS NON SEVERE and Negative Sepsis and Blood Culture Ordered]

	,CASE WHEN [#ED_PositiveScores].MEAS_VALUE IS NULL AND ALLSCORES.AllSepsis_Scores IS NOT NULL AND BC.MBOrderTime IS NULL AND NONSEVERE.ENCOUNTER_ID IS NOT NULL THEN 1 ELSE 0 END					AS [SSS NON SEVERE and Negative Sepsis and Blood Culture NOT Ordered]



	,RESCREEN.RECORDED_TIME AS [ReScreen After FPS]



	,CASE	WHEN DATEDIFF(MI,[#ED_PositiveScores].RECORDED_TIME,ABX1.ABX_ADMIN_TIME) <=60

				AND DATEDIFF(MI,[#ED_PositiveScores].RECORDED_TIME,BPB1.BOLUS_ADMIN_TIME) <=20

				AND RESCREEN.RECORDED_TIME IS NOT NULL

			THEN 1 

			ELSE 0 

	  END AS [FPS Bolus ABX ReScreen Compliance]



	,REPEATSCREEN.RECORDED_TIME AS [Repeat Screen before ED Departure]

	,GEN.[Gen Back To ICU Time]

	,GEN.[Gen Back To ICU Department]



	/* Added 2025.11.24 V_DEV004 */

	-- Septic Shock criteria; Logic from [reports].USP_Severe_Sepsis for consistency

	, CASE

		WHEN DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [ABX1].ABX_ADMIN_TIME) <= 6*60

			AND DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [BPB1].BOLUS_ADMIN_TIME) <= 6*60

			AND ( DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [BPB2].BOLUS_ADMIN_TIME) <= 6*60

					OR

				  DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [#Pressors].TAKEN_TIME) <= 6*60

				)

			AND DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [bcx_order01].[Blood Culture First Order Time]) <= 72*60

			AND ( [BPB3].BOLUS_ADMIN_TIME IS NOT NULL

					OR

				  [#Pressors].TAKEN_TIME IS NOT NULL

				)



		THEN 'Septic Shock'

		

		WHEN DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [ABX1].ABX_ADMIN_TIME) <= 6*60

			AND DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [BPB1].BOLUS_ADMIN_TIME) <= 6*60

			AND ( DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [BPB2].BOLUS_ADMIN_TIME) <= 6*60

					OR

				  DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [#Pressors].TAKEN_TIME) <= 6*60

				)

			AND DATEDIFF(MINUTE, [BasePop].ADT_ARRIVAL_TIME, [bcx_order01].[Blood Culture First Order Time]) <= 72*60



		THEN 'Potential Septic Shock' 

		--ELSE 99	-- "Un-treated"

	  END AS [Septic Shock]



FROM #Base_Pop BasePop



	LEFT OUTER JOIN [dbo].ENCOUNTER_VISIT_REASONS	CHIEF_CMPLNT	ON CHIEF_CMPLNT.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID AND CHIEF_CMPLNT.LINE=1

	LEFT OUTER JOIN [dbo].VISIT_REASONS	VR			ON VR.REASON_VISIT_ID = CHIEF_CMPLNT.ENC_REASON_ID



	LEFT OUTER JOIN [reports].[SEVERE_SEPSIS_STAGING]		SEVERE		ON SEVERE.DATE_STAMP = [BasePop].DATE_STAMP AND SEVERE.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

	LEFT OUTER JOIN [reports].[NON_SEVERE_SEPSIS_STAGING]	NONSEVERE	ON NONSEVERE.DATE_STAMP = [BasePop].DATE_STAMP AND NONSEVERE.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID



	LEFT OUTER JOIN #Base_Pop_SepsisScores_ConCat	ALLSCORES		ON ALLSCORES.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

	LEFT OUTER JOIN #Base_Pop_Severe_ED_Scores		SepsisScreened	ON SepsisScreened.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID and SepsisScreened.TIME_LINE=1



	LEFT OUTER JOIN #ED_PositiveScores							ON [#ED_PositiveScores].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID AND [#ED_PositiveScores].FIRST_TIME_LINE=1

	LEFT OUTER JOIN #BasePopABX						abx1		ON [BasePop].ENCOUNTER_ID = ABX1.ENCOUNTER_ID AND ABX1.TIME_LINE=1

	LEFT OUTER JOIN #BasePopABX						abx2		ON [BasePop].ENCOUNTER_ID = ABX2.ENCOUNTER_ID AND ABX2.TIME_LINE=2

	LEFT OUTER JOIN #SSOrderSet									ON [BasePop].ENCOUNTER_ID = [#SSOrderSet].ENCOUNTER_ID AND [#SSOrderSet].TIME_LINE=1

	LEFT OUTER JOIN #BasePopBolus					BPB1		ON [BasePop].ENCOUNTER_ID = BPB1.ENCOUNTER_ID AND BPB1.TIME_LINE=1

	LEFT OUTER JOIN #BasePopBolus					BPB2		ON [BasePop].ENCOUNTER_ID = BPB2.ENCOUNTER_ID AND BPB2.TIME_LINE=2

	LEFT OUTER JOIN #BasePopBolus					BPB3		ON [BasePop].ENCOUNTER_ID = BPB3.ENCOUNTER_ID AND BPB3.TIME_LINE=3

	LEFT OUTER JOIN #EncounterWeights				EW			ON [BasePop].ENCOUNTER_ID = EW.ENCOUNTER_ID AND EW.TIME_LINE=1

	LEFT OUTER JOIN #Hypotension								ON [BasePop].ENCOUNTER_ID = [#Hypotension].ENCOUNTER_ID AND [#Hypotension].TIME_LINE=1

	LEFT OUTER JOIN #ALLCVLTime						CVL			ON [BasePop].ENCOUNTER_ID = CVL.ENCOUNTER_ID AND CVL.TIME_LINE=1

	LEFT OUTER JOIN #Pressors									ON [BasePop].ENCOUNTER_ID = [#Pressors].ENCOUNTER_ID AND [#Pressors].TIME_LINE=1

	LEFT OUTER JOIN #SVO2										ON [BasePop].ENCOUNTER_ID = [#SVO2].ENCOUNTER_ID AND [#SVO2].TIME_LINE=1

	LEFT OUTER JOIN #LacticAcid									ON [BasePop].ENCOUNTER_ID = [#LacticAcid].ENCOUNTER_ID AND [#LacticAcid].TIME_LINE=1

	LEFT OUTER JOIN #Procalcitonin								ON [BasePop].ENCOUNTER_ID = [#Procalcitonin].ENCOUNTER_ID AND [#Procalcitonin].TIME_LINE=1

	LEFT OUTER JOIN #BloodCultureValue				BC			ON [BasePop].ENCOUNTER_ID = [BC].ENCOUNTER_ID

	LEFT OUTER JOIN #UrineCultureValue				UC			ON [BasePop].ENCOUNTER_ID = [UC].ENCOUNTER_ID

	LEFT OUTER JOIN #CsfCultureValue				CSF			ON [BasePop].ENCOUNTER_ID = [CSF].ENCOUNTER_ID

	LEFT OUTER JOIN #ETT										ON [BasePop].ENCOUNTER_ID = [#ETT].ENCOUNTER_ID AND [#ETT].TIME_LINE=1

	LEFT OUTER JOIN #IV											ON [BasePop].ENCOUNTER_ID = [#IV].ENCOUNTER_ID AND [#IV].TIME_LINE=1

	LEFT OUTER JOIN #ED2HEMONC									ON [BasePop].ENCOUNTER_ID = [#ED2HEMONC].ENCOUNTER_ID AND [#ED2HEMONC].TIME_LINE=1

	LEFT OUTER JOIN #ED2ICU							ICU			ON [BasePop].ENCOUNTER_ID = [ICU].ENCOUNTER_ID AND [ICU].TIME_LINE=1

	LEFT OUTER JOIN #ED2GEN							GEN			ON [BasePop].ENCOUNTER_ID = [GEN].ENCOUNTER_ID AND [GEN].TIME_LINE=1

	LEFT OUTER JOIN #BPA										ON [BasePop].ENCOUNTER_ID = [#BPA].ENCOUNTER_ID AND [#BPA].TIME_LINE=1



	LEFT OUTER JOIN #BedEvents						BE1			ON [BE1].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID AND [BE1].REQ_LINE=1 AND [BE1].TIME_LINE=1--BED REQUESTED

	LEFT OUTER JOIN #BedEvents						BE2			ON [BE2].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID AND [BE2].REQ_LINE=1 AND [BE2].TIME_LINE=2--BED ASSIGNED

	LEFT OUTER JOIN #Base_Pop_ED_Readmit_All		READMITALL	ON [READMITALL].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

	LEFT OUTER JOIN #Base_Pop_ED_Readmit			READMIT		ON [READMIT].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

	LEFT OUTER JOIN #Base_Pop_ENC_Reason			RSN			ON [RSN].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID



	LEFT OUTER JOIN #FirstPositiveOD_To_ABXAdminTime OD2ABX		ON OD2ABX.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

	LEFT OUTER JOIN #FirstABXAdminTimeDetails		ABXTimes	ON ABXTimes.ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

	LEFT OUTER JOIN #SepsisAlertCancelled						ON [BasePop].ENCOUNTER_ID = [#SepsisAlertCancelled].ENCOUNTER_ID AND [#SepsisAlertCancelled].TIME_LINE=1



	LEFT OUTER JOIN (

		SELECT ENCOUNTER_ID, min(MBOrderTime) AS [Blood Culture First Order Time]

		FROM #BloodCultureValue

		GROUP BY ENCOUNTER_ID

	) bcx_order01 ON [BasePop].ENCOUNTER_ID = [bcx_order01].ENCOUNTER_ID



	OUTER APPLY

	(

		SELECT TOP 1 [#Base_Pop_Severe_ED_Scores].RECORDED_TIME

		FROM #Base_Pop_Severe_ED_Scores

		WHERE 1=1

			AND [#Base_Pop_Severe_ED_Scores].ENCOUNTER_ID = [#ED_PositiveScores].ENCOUNTER_ID

			AND [#ED_PositiveScores].FIRST_TIME_LINE = 1

			AND ([#Base_Pop_Severe_ED_Scores].RECORDED_TIME > [#ED_PositiveScores].RECORDED_TIME AND [#Base_Pop_Severe_ED_Scores].RECORDED_TIME <= DATEADD(MI, 90, [#ED_PositiveScores].RECORDED_TIME))

		ORDER BY [#ED_PositiveScores].RECORDED_TIME DESC

	) RESCREEN



	OUTER APPLY

	(

		SELECT TOP 1 [#Base_Pop_Severe_ED_Scores].RECORDED_TIME

		FROM #Base_Pop_Severe_ED_Scores

		WHERE 1=1

			AND [#Base_Pop_Severe_ED_Scores].ENCOUNTER_ID = [BasePop].ENCOUNTER_ID

			AND ([#Base_Pop_Severe_ED_Scores].RECORDED_TIME >  DATEADD(MI, -60, [BasePop].ED_DEPARTURE_TIME) AND [#Base_Pop_Severe_ED_Scores].RECORDED_TIME < [BasePop].ED_DEPARTURE_TIME)

		ORDER BY [#Base_Pop_Severe_ED_Scores].RECORDED_TIME DESC

	) REPEATSCREEN



	OUTER APPLY

	(

		SELECT TOP 1 [V_PATIENT_LOCATION_HISTORY].ADT_DEPARTMENT_NAME

		FROM [dbo].V_PATIENT_LOCATION_HISTORY

		WHERE 1=1

			AND [V_PATIENT_LOCATION_HISTORY].ADT_DEPARTMENT_ID IS NOT NULL

			AND [V_PATIENT_LOCATION_HISTORY].ENCOUNTER_NUM = [BasePop].ENCOUNTER_ID 

			AND [V_PATIENT_LOCATION_HISTORY].IN_DTTM >= [BasePop].ED_DEPARTURE_TIME

		ORDER BY [V_PATIENT_LOCATION_HISTORY].IN_DTTM ASC

	) FIRST_ADMIT_DEPARTMENT



	/* Previous blood pressure (up to 30 minutes prior to positive screen) */

	OUTER APPLY

	(

		SELECT TOP 1 

			[FLOWSHEET_MEASUREMENTS].RECORDED_TIME

			, [FLOWSHEET_MEASUREMENTS].MEAS_VALUE

			, [FLOWSHEET_MEASUREMENTS].FLO_MEAS_ID

		FROM [dbo].HOSPITAL_ENCOUNTERS

			INNER JOIN [dbo].FLOWSHEET_RECORDS	ON [HOSPITAL_ENCOUNTERS].INPATIENT_DATA_ID = [FLOWSHEET_RECORDS].INPATIENT_DATA_ID

			INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS	ON [FLOWSHEET_RECORDS].FSD_ID = [FLOWSHEET_MEASUREMENTS].FSD_ID	



		WHERE 1=1

			AND [HOSPITAL_ENCOUNTERS].ENCOUNTER_ID = [#ED_PositiveScores].ENCOUNTER_ID

			AND [FLOWSHEET_MEASUREMENTS].FLO_MEAS_ID = '95'	-- Blood Pressure

			AND [FLOWSHEET_MEASUREMENTS].RECORDED_TIME BETWEEN DATEADD(MI, -30, [#ED_PositiveScores].RECORDED_TIME) AND [#ED_PositiveScores].RECORDED_TIME

		ORDER BY [FLOWSHEET_MEASUREMENTS].RECORDED_TIME DESC	

	) LAST_BP



	/* Previous blood pressure percentile (up to 30 minutes prior to positive screen) */

	OUTER APPLY

	(

		SELECT TOP 1 

			[FLOWSHEET_MEASUREMENTS].RECORDED_TIME

			, [FLOWSHEET_MEASUREMENTS].MEAS_VALUE

		FROM [dbo].HOSPITAL_ENCOUNTERS

			INNER JOIN [dbo].FLOWSHEET_RECORDS	ON [HOSPITAL_ENCOUNTERS].INPATIENT_DATA_ID = [FLOWSHEET_RECORDS].INPATIENT_DATA_ID

			INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS	ON [FLOWSHEET_RECORDS].FSD_ID = [FLOWSHEET_MEASUREMENTS].FSD_ID	

		WHERE 1=1

			AND [HOSPITAL_ENCOUNTERS].ENCOUNTER_ID = [#ED_PositiveScores].ENCOUNTER_ID

			AND [FLOWSHEET_MEASUREMENTS].FLO_MEAS_ID IN (

				'9001140203'	-- R EDX GIRLS SYSTOLIC BP PERCENTILE

				,'9001140205'	-- R EDX BOYS SYSTOLIC BP PERCENTILE 

				)

			AND [FLOWSHEET_MEASUREMENTS].RECORDED_TIME BETWEEN DATEADD(MI, -30, [#ED_PositiveScores].RECORDED_TIME) AND [#ED_PositiveScores].RECORDED_TIME

		ORDER BY [FLOWSHEET_MEASUREMENTS].RECORDED_TIME DESC	

	) LAST_BP_PERCENTILE



	/* First blood pressure (up to 30 minutes after positive screen) */

	OUTER APPLY

	(

		SELECT TOP 1 

			[FLOWSHEET_MEASUREMENTS].RECORDED_TIME

			, [FLOWSHEET_MEASUREMENTS].MEAS_VALUE

		FROM [dbo].HOSPITAL_ENCOUNTERS

			INNER JOIN [dbo].FLOWSHEET_RECORDS	ON [HOSPITAL_ENCOUNTERS].INPATIENT_DATA_ID = [FLOWSHEET_RECORDS].INPATIENT_DATA_ID

			INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS	ON [FLOWSHEET_RECORDS].FSD_ID = [FLOWSHEET_MEASUREMENTS].FSD_ID	

		WHERE 1=1

			AND [HOSPITAL_ENCOUNTERS].ENCOUNTER_ID = [#ED_PositiveScores].ENCOUNTER_ID

			AND [FLOWSHEET_MEASUREMENTS].FLO_MEAS_ID = '95'	-- Blood Pressure

			AND [FLOWSHEET_MEASUREMENTS].RECORDED_TIME BETWEEN [#ED_PositiveScores].RECORDED_TIME AND DATEADD(MI, 30, [#ED_PositiveScores].RECORDED_TIME)

		ORDER BY [FLOWSHEET_MEASUREMENTS].RECORDED_TIME DESC			

	) FIRST_BP



	/* First blood pressure (up to 30 minutes after positive screen) */

	OUTER APPLY

	(

		SELECT TOP 1 

			[FLOWSHEET_MEASUREMENTS].RECORDED_TIME

			, [FLOWSHEET_MEASUREMENTS].MEAS_VALUE

		FROM [dbo].HOSPITAL_ENCOUNTERS

			INNER JOIN [dbo].FLOWSHEET_RECORDS	ON [HOSPITAL_ENCOUNTERS].INPATIENT_DATA_ID = [FLOWSHEET_RECORDS].INPATIENT_DATA_ID

			INNER JOIN [dbo].FLOWSHEET_MEASUREMENTS	ON [FLOWSHEET_RECORDS].FSD_ID = [FLOWSHEET_MEASUREMENTS].FSD_ID	

		WHERE 1=1

			AND [HOSPITAL_ENCOUNTERS].ENCOUNTER_ID = [#ED_PositiveScores].ENCOUNTER_ID

			AND [FLOWSHEET_MEASUREMENTS].FLO_MEAS_ID IN (

				'9001140203'	-- R EDX GIRLS SYSTOLIC BP PERCENTILE

				,'9001140205'	-- R EDX BOYS SYSTOLIC BP PERCENTILE 

				)

			AND [FLOWSHEET_MEASUREMENTS].RECORDED_TIME BETWEEN [#ED_PositiveScores].RECORDED_TIME AND DATEADD(MI, 30, [#ED_PositiveScores].RECORDED_TIME)

		ORDER BY [FLOWSHEET_MEASUREMENTS].RECORDED_TIME DESC			

	) FIRST_BP_PERCENTILE



	/* ED boarder PATIENTS */

	LEFT OUTER JOIN

	(

		SELECT DISTINCT [HOSPITAL_ENCOUNTERS].ENCOUNTER_ID

		FROM [dbo].HOSPITAL_ENCOUNTERS

			INNER JOIN [dbo].ED_PATIENT_INFO		 ON [ED_PATIENT_INFO].ENCOUNTER_ID = [HOSPITAL_ENCOUNTERS].ENCOUNTER_ID

			INNER JOIN [dbo].ED_EVENT_INFO	 ON [ED_EVENT_INFO].EVENT_ID = [ED_PATIENT_INFO].EVENT_ID 

															AND [ED_EVENT_INFO].EVENT_TYPE IN ('2600000007')--ED BOARDER PATIENTS

	) ED_BORDER ON [BasePop].ENCOUNTER_ID = ED_BORDER.ENCOUNTER_ID

;



