"""SPEC_REGISTRY — the axiom ledger as data (ADR 0067, turn 1).

The eighth peer registry: one record per SPEC.md axiom. Single-writer
effects: trace_registry derives SPEC_AXIOMS and SPEC_TO_AXM from here
(two hand-maintained structures retired); per-axiom checks are data.

Field discipline (the single-home rule, ADR 0067):
- parents: the framework axioms (docs/AI_VIA_AXIOMS.md) this applies —
  THE home (the crosswalk doc narrates, this decides).
- checks: the file paths SPEC.md's Binding: line names. Where SPEC
  names no file, checks is empty and `reason` quotes the prose binding
  — faithful to the document, never an invented attribution. The count
  of file-less bindings is thereby measurable debt.
- law formulas and per-axiom STATUS stay in SPEC.md, their one home,
  until a later ratchet turn retires that prose into ADRs. Copying
  them here now would mint a second truth.

Grounding ADRs are DERIVED (trace_registry axioms fields), not stored.
Closure checks: tests/test_spec_registry.py (totality both ways
against SPEC.md, check-path existence, parent validity, checks-or-
reason totality).
"""

from __future__ import annotations

GROUPS = {
    "A": "Identity", "B": "Soundness", "C": "Completeness",
    "D": "Derived structure", "E": "Ask-time determinism",
    "F": "The round trip", "G": "Mechanism uniqueness",
    "H": "Escalation", "L": "The ledger", "P": "The one-mind turn",
    "Q": "Graph topology", "R": "Ask-time interpretation + run boundary",
    "T": "The double-sided function",
}

SPEC_REGISTRY = {
    "A1": {"title": "folding is idempotent", "parents": ["D2"],
           "parent_note": "one folding rule, one definition",
           "checks": ["tests/parser/test_identity.py"]},
    "A2": {"title": "metric_id is a key", "parents": ["D3"],
           "parent_note": "identity -> exactly one owner per metric",
           "checks": ["tests/test_invariants.py",
                      "tests/test_table_contracts.py"]},
    "A3": {"title": "fold-collisions are rejected loudly",
           "parents": ["D2"],
           "parent_note": "one folding rule, one definition", "checks": ["tests/test_invariants.py"]},
    "B1": {"title": "witness totality (anti-fabrication)",
           "parents": ["B1"],
           "parent_note": "witness totality IS 'no claim without a witness'",
           "checks": ["tests/test_invariants.py",
                      "tests/test_tree_contract.py"],
           "reason": "PARTIAL by construction in builders; not yet a "
                     "uniform declared invariant on every edge table"},
    "B2": {"title": "description provenance is total and closed",
           "parents": ["B1", "J4"],
           "parent_note": "provenance closed -> every description judged",
           "checks": ["tests/test_tree_contract.py"]},
    "C1": {"title": "the frontier is enumerated", "parents": ["D1"],
           "parent_note": "the enumerated frontier -> nothing unreachable",
           "checks": ["tests/test_extraction_registry.py"]},
    "C2": {"title": "conservation per extractor", "parents": ["R1"],
           "parent_note": "handled + fallout = total (conservation)",
           "checks": ["tests/test_tree_contract.py",
                      "tests/mquery/test_mquery.py"]},
    "C3": {"title": "images land in the graph", "parents": ["R1"],
           "parent_note": "handled + fallout = total (conservation)",
           "checks": ["tests/test_invariants.py"]},
    "C4": {"title": "leaf grounding (termination)",
           "parents": ["R1", "D1"],
           "parent_note": "leaf grounding: termination + reachability",
           "checks": ["tests/governance/test_leaf_grounding.py"]},
    "D1": {"title": "materialized closures equal the fixpoint",
           "parents": ["D4"],
           "parent_note": "closure = shape-defined derivation",
           "checks": ["tests/test_recorded_pipeline.py"],
           "reason": "oracles ENFORCED; the general closure-vs-live "
                     "diff is UNBOUND (ADR 0037 stated gap)"},
    "D2": {"title": "count oracles", "parents": ["J1"],
           "parent_note": "count oracles = founder-defined correctness",
           "checks": ["tests/test_recorded_pipeline.py"]},
    "D3": {"title": "projections are functions of the record",
           "parents": ["D3"],
           "parent_note": "projections have one owning record", "checks": [],
           "reason": "by construction in the builders; no general "
                     "recompute-and-diff check yet (SPEC stated gap)"},
    "E1": {"title": "the path space is finite and enumerable",
           "parents": ["S3"],
           "parent_note": "the path space is data-shaped, hence enumerable", "checks": ["tests/test_spec_gates.py"]},
    "E2": {"title": "replay determinism for retrieval",
           "parents": ["J2"],
           "parent_note": "replay determinism = the computable type",
           "checks": ["tests/orchestrator/test_core.py"]},
    "E3": {"title": "the decision typing rule", "parents": ["M5", "J2"],
           "parent_note": "the decision-typing rule, verbatim",
           "checks": ["tests/test_methodology.py"]},
    "E4": {"title": "pick containment", "parents": ["M5"],
           "parent_note": "intent decisions bind to the human", "checks": [],
           "reason": "structural pick validation in the orchestrator "
                     "(prose binding, no file named; 0046 re-binds)"},
    "E5": {"title": "filter grounding", "parents": ["B1"],
           "parent_note": "filter values need witnesses",
           "checks": ["tests/test_spec_gates.py"]},
    "E6": {"title": "presentation honesty", "parents": ["B2", "B3"],
           "parent_note": "boundary honesty + bounded quantified claims",
           "checks": ["tests/orchestrator/test_core.py",
                      "tests/orchestrator/test_caption_gate.py"]},
    "F": {"title": "the round trip (0044 as equations)",
          "parents": ["J4"],
           "parent_note": "the round trip is the description's oracle", "checks": ["tests/test_tree_contract.py"]},
    "G1": {"title": "one owner per capability", "parents": ["D2"],
           "parent_note": "one owner per capability, mechanized",
           "checks": ["tests/test_capability_registry.py"]},
    "G2": {"title": "sanctioned powers only (Uses \\ S = empty)",
           "parents": ["D2"],
           "parent_note": "one owner per capability, mechanized",
           "checks": ["tests/test_capability_registry.py",
                      "tests/test_native_parser_law.py",
                      "tests/test_notebook_contract.py"]},
    "G3": {"title": "no undeclared power", "parents": ["D2"],
           "parent_note": "one owner per capability, mechanized",
           "checks": ["tests/test_capability_registry.py"]},
    "H1": {"title": "fallout resolution is total and closed",
           "parents": ["R3"],
           "parent_note": "novelty escalates",
           "checks": ["tests/test_escalation_contract.py"]},
    "H2": {"title": "novelty always escalates", "parents": ["R3"],
           "parent_note": "novelty escalates",
           "checks": ["tests/test_escalation_contract.py"]},
    "L1": {"title": "append-only is declared AND obeyed",
           "parents": ["R4"],
           "parent_note": "the ledger may only grow",
           "checks": ["tests/test_ledger_contract.py",
                      "tests/test_table_contracts.py"]},
    "L2": {"title": "aggregates are derived, never stored",
           "parents": ["R4", "D3"],
           "parent_note": "aggregates derived, never stored",
           "checks": ["tests/test_ledger_contract.py"]},
    "L3": {"title": "every declaration has a firing mechanism",
           "parents": ["R2"],
           "parent_note": "every declaration has a firing mechanism", "checks": ["tests/test_spec_gates.py"],
           "reason": "ENFORCED by citation (0059 Q3 precedent): the "
                     "registry closure checks, funnel, reachability"},
    "P1": {"title": "one conversation decides a turn", "parents": ["M2"],
           "parent_note": "one mind, full evidence",
           "checks": ["tests/orchestrator/test_turn_engine.py"]},
    "P2": {"title": "full tool results persist in one history",
           "parents": ["M2"],
           "parent_note": "one mind, full evidence",
           "checks": ["tests/orchestrator/test_turn_engine.py"]},
    "P3": {"title": "thinking room", "parents": ["M3"],
           "parent_note": "thinking room",
           "checks": ["tests/orchestrator/test_turn_engine.py"]},
    "P4": {"title": "no question-family casebook", "parents": ["M4"],
           "parent_note": "no question-shaped control flow",
           "checks": ["tests/orchestrator/test_turn_engine.py",
                      "tests/test_methodology.py"]},
    "P5": {"title": "honesty at the boundary only", "parents": ["B2"],
           "parent_note": "honesty at the boundary, never the interior",
           "checks": ["tests/orchestrator/test_turn_engine.py"]},
    "P6": {"title": "failure is observation", "parents": ["M1"],
           "parent_note": "failure as observation = loop-shape capability",
           "checks": ["tests/orchestrator/test_turn_engine.py"]},
    "Q1": {"title": "accounted connectivity", "parents": ["D1"],
           "parent_note": "accounted connectivity -> nothing unreachable",
           "checks": ["tests/graph/test_topology.py"]},
    "Q2": {"title": "edge soundness", "parents": ["B1"],
           "parent_note": "every edge provenance-mapped",
           "checks": ["tests/graph/test_topology.py"]},
    "Q3": {"title": "relative completeness", "parents": ["B3"],
           "parent_note": "completeness claims are conservation equations",
           "checks": [],
           "reason": "ENFORCED by citation — the existing conservation "
                     "asserts predate the axiom (ADR 0059)"},
    "R1": {"title": "parse, never generate", "parents": ["M4", "M5"],
           "parent_note": "parse-never-generate: free composition + typing",
           "checks": ["tests/orchestrator/test_parse_plan.py"]},
    "R2": {"title": "no question types", "parents": ["M4"],
           "parent_note": "no question types",
           "checks": ["tests/test_methodology.py"]},
    "R3": {"title": "interpretation confirms before it executes",
           "parents": ["B4"],
           "parent_note": "irreversible acts confirm - applied to "
                          "interpretation",
           "checks": ["tests/webapp/test_app.py"]},
    "R4": {"title": "no dead ends", "parents": ["R3"],
           "parent_note": "no dead ends -> novelty escalates",
           "checks": ["tests/webapp/test_app.py"]},
    "R5": {"title": "certain answers", "parents": ["B3"],
           "parent_note": "certain answers = bounded claims under ambiguity", "checks": [],
           "reason": "the no-nag boundary in the loop; no general "
                     "multi-reading intersection check (SPEC: PARTIAL)"},
    "R6": {"title": "rows never enter model context", "parents": ["B2"],
           "parent_note": "rows never enter model context",
           "checks": ["tests/test_run_layer.py"]},
    "R7": {"title": "confirmed SQL only; read-only by construction",
           "parents": ["B4"],
           "parent_note": "confirmed-only execution", "checks": ["tests/test_run_layer.py"]},
    "R8": {"title": "sampling is machine-labelled", "parents": ["B3"],
           "parent_note": "machine-labelled sampling",
           "checks": ["tests/test_run_layer.py"]},
    "T0": {"title": "the round-trip law", "parents": ["J4"],
           "parent_note": "the round-trip law: kappa(rho(tau(t))) = kappa(t)",
           "checks": [],
           "reason": "instantiated as T1-T3, each with its own judge; "
                     "no single check by design (ADR 0065)"},
    "T1": {"title": "descriptions round-trip (spec:F as family member)",
           "parents": ["J4"],
           "parent_note": "descriptions - blind verifier + kappa-diff", "checks": ["tests/test_tree_contract.py"]},
    "T2": {"title": "SQL stitching round-trips", "parents": ["J4", "B1"],
           "parent_note": "SQL stitching - parseability round-trips; kappa-diff is the stated gap",
           "checks": ["tests/test_run_layer.py"],
           "reason": "parseability round-trips; the kappa-equality "
                     "diff is the stated gap, live when stitching ships"},
    "T3": {"title": "definition creation round-trips",
           "parents": ["M5", "J2"],
           "parent_note": "definition creation - the human is the judge (L3 stratum)", "checks": [],
           "reason": "JUDGED, not tested — the human is the judge by "
                     "construction (SPEC 14d, L3 stratum)"},
}
