# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "f7c297eb-4659-4600-ab89-0e860638fb6c",
# META       "default_lakehouse_name": "sql_query_lh",
# META       "default_lakehouse_workspace_id": "1f55e1c1-b660-4715-9b56-4140edce3940",
# META       "known_lakehouses": [
# META         {
# META           "id": "f7c297eb-4659-4600-ab89-0e860638fb6c"
# META         }
# META       ]
# META     },
# META     "environment": {
# META       "environmentId": "0776fc8d-1451-838d-47e6-f5c7a0bd174b",
# META       "workspaceId": "00000000-0000-0000-0000-000000000000"
# META     }
# META   }
# META }

# CELL ********************

"""Fabric Notebook: Publish Descriptions to Collibra (pure publisher)

Reads from: ops_agent_descriptions (written by 07b), graph_nodes/edges
Writes to:  Collibra (REST API) + gov_publish_log

Publishing was split from generation (2026-08-18): this notebook
matches _PBI metrics to Collibra report assets (lineage-exact names
first, heuristic fallback) and updates their Description attribute.
It NEVER generates — run 07b_generate_agent_descriptions first.
"""

# %% Cell 0: Setup
import json
import sys

# If the wheel is installed via Fabric Environment, src is already importable.
# Fallback to sys.path for dev mode or non-wheel deployments.
try:
    import src
except ImportError:
    sys.path.insert(0, "/lakehouse/default/Files/sql-query-agent")
    import src
print(f"v{src.__version__}")

from src.config import load_config

config = load_config("/lakehouse/default/Files/sql-query-agent/org_config.yaml")

# %% Cell 1: Load graph from Delta
from src.steps.gates import precondition_gate

precondition_gate("08_publish_collibra", table_exists=spark.catalog.tableExists,
                  count=lambda t: spark.table(t).count())

from src.models import EdgeType, GraphEdge, GraphNode, NodeLayer

nodes_df = spark.table(config.lakehouse.graph_nodes)
edges_df = spark.table(config.lakehouse.graph_edges)

nodes = {}
for row in nodes_df.collect():
    r = row.asDict()
    props = json.loads(r["properties"]) if r["properties"] else {}
    nodes[r["node_id"]] = GraphNode(
        node_id=r["node_id"],
        layer=NodeLayer(r["layer"]),
        name=r["name"],
        description=r["description"] or "",
        properties=props,
    )

edges = []
for row in edges_df.collect():
    r = row.asDict()
    props = json.loads(r["properties"]) if r["properties"] else {}
    edges.append(GraphEdge(
        source_id=r["source_id"],
        target_id=r["target_id"],
        edge_type=EdgeType(r["edge_type"]),
        properties=props,
    ))

print(f"Loaded {len(nodes)} nodes, {len(edges)} edges from Delta")

# %% Cell 2: Load agent descriptions (generated by 07b — this notebook only publishes)
from src.adapters.collibra_lineage_match import extract_match_key
from src.steps.agent_descriptions import STATUS_OK

if not spark.catalog.tableExists("ops_agent_descriptions"):
    raise SystemExit(
        "ops_agent_descriptions is missing — run 07b_generate_agent_descriptions "
        "first. Publishing was split from generation (2026-08-18): this "
        "notebook consumes descriptions, it never generates them."
    )

desc_lookup = {}
rejected = 0
for row in spark.table("ops_agent_descriptions").collect():
    r = row.asDict()
    if r.get("status", STATUS_OK) == STATUS_OK:
        desc_lookup[r["metric_name"]] = r["description"]
    else:
        rejected += 1

print(f"Loaded {len(desc_lookup)} publishable descriptions"
      + (f" ({rejected} rejected rows excluded — retry via 07b)" if rejected else ""))
if not desc_lookup:
    raise SystemExit("No publishable descriptions — run 07b first.")

# %% Cell 4: Connect to Collibra and match to PBI reports
from src.adapters.collibra import CollibraAdapter, CollibraConfig
from src.adapters.collibra_lineage import CollibraClient
from src.adapters.collibra_lineage_match import CollibraLineageMatcher

collibra_cfg = config.adapters.collibra

adapter = CollibraAdapter(CollibraConfig(
    base_url=collibra_cfg.base_url,
    username=collibra_cfg.username,
    password=collibra_cfg.password,
    api_key=collibra_cfg.api_key,
    domain_id=collibra_cfg.domain_id,
    community_id=collibra_cfg.community_id,
    asset_type_id=collibra_cfg.asset_type_id,
    description_attr_type_id=collibra_cfg.description_attr_type_id,
))

base = collibra_cfg.base_url.replace("/rest/2.0", "")
client = CollibraClient(base, collibra_cfg.username, collibra_cfg.password)

print("Testing connection...")
if adapter.test_connection():
    print("[+] Connected to Collibra!")
else:
    print("[X] Connection failed. Check base_url and credentials in org_config.yaml")
    raise SystemExit("Cannot proceed without Collibra connection — a publish "
                     "run against a dead adapter reports counts that look like work.")

# Match _PBI metrics to Collibra reports
objects = [{"object_name": name, "object_type": "SQL_STORED_PROCEDURE"} for name in desc_lookup]
matcher = CollibraLineageMatcher(client, min_score=0.5)
match_result = matcher.match_objects(objects)
print(f"\n{match_result}")

# %% Cell 5: Review matches before publishing
print(f"{'='*80}")
print(f"MATCHED — will update descriptions ({len(match_result.matched)})")
print(f"{'='*80}")

for m in match_result.matched:
    desc = desc_lookup.get(m.object_name, "")
    print(f"\n  Proc/View: {m.object_name}")
    print(f"  Collibra:  {m.report_name}")
    print(f"  Score:     {m.score:.2f}")
    print(f"  Description: {desc[:150]}..." if len(desc) > 150 else f"  Description: {desc}")

if match_result.unmatched_objects:
    print(f"\n{'='*80}")
    print(f"UNMATCHED — no Collibra report found ({len(match_result.unmatched_objects)})")
    print(f"{'='*80}")
    for name in match_result.unmatched_objects:
        print(f"  {name}  (key: '{extract_match_key(name)}')")

# %% Cell 6: Publish descriptions to Collibra
# Review cell 5 output first!
# To publish only specific reports, add names to PUBLISH_ONLY.
# Leave empty [] to publish all matched reports.

PUBLISH_ONLY = []  # e.g., ["Executive Dashboard", "Another Report"]

publish_results = []
for m in match_result.matched:
    if PUBLISH_ONLY and not any(name.lower() in m.report_name.lower() for name in PUBLISH_ONLY):
        continue

    desc = desc_lookup.get(m.object_name, "")
    if not desc:
        print(f"  SKIP {m.object_name} — no description generated")
        continue

    result = adapter.update_description(
        asset_name=m.report_name,
        description=desc,
    )
    publish_results.append((m.object_name, m.report_name, result))
    status = result.status.value
    print(f"  {status}: {m.object_name} → {result.message}")

# %% Cell 6b: Durable publish log (gov_publish_log — admin telemetry)
from datetime import datetime, timezone

from src.governance.publish_log import publish_log_rows
from src.schemas import PUBLISH_LOG, to_spark_schema

_now = datetime.now(timezone.utc)
log_rows = publish_log_rows(
    [r for _, _, r in publish_results], target="collibra", kind="asset",
    run_id=_now.strftime("%Y%m%dT%H%M%SZ"),
    published_at=_now.isoformat(),
)
if log_rows:
    spark.createDataFrame(log_rows, schema=to_spark_schema(PUBLISH_LOG)) \
        .write.format("delta").mode("append").saveAsTable("gov_publish_log")
print(f"[+] gov_publish_log: {len(log_rows)} rows appended")

# %% Cell 7: Summary
succeeded = sum(1 for _, _, r in publish_results if r.status.value == "success")
failed = sum(1 for _, _, r in publish_results if r.status.value == "failed")
skipped = len(match_result.matched) - len(publish_results)

print(f"\n{'='*80}")
print("PUBLISH SUMMARY")
print(f"{'='*80}")
print(f"  Total canonical metrics: {len([n for n in nodes.values() if n.layer == NodeLayer.CANONICAL])}")
print(f"  Publishable descriptions: {len(desc_lookup)}")
print(f"  Agent descriptions:      {len(desc_lookup)}")
print(f"  Matched to Collibra:     {len(match_result.matched)}")
print(f"  Published:               {succeeded}")
print(f"  Failed:                  {failed}")
print(f"  Skipped (no desc):       {skipped}")
print(f"  Unmatched:               {len(match_result.unmatched_objects)}")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
