CREATE PROCEDURE reports.USP_High_ED_Utilizers
AS
BEGIN
WITH
Utilizers AS (
  SELECT HE.HOSP_ENC_ID, HE.PATIENT_ID, HE.ADMIT_DATE
  FROM HOSPITAL_ENCOUNTERS HE
  WHERE HE.ENCOUNTER_TYPE = 'ED'
)
SELECT * FROM Utilizers;
END
