CREATE TABLE [reporting].[ip_sepsisshiftcompliance] (
    [AMDenom]                  NVARCHAR (400) NULL,
    [AlertActivatedComment]    NVARCHAR (400) NULL,
    [AlertNotActivatedComment] NVARCHAR (400) NULL,
    [AlertNotActivatedReason]  NVARCHAR (400) NULL,
    [Denominator]              NVARCHAR (400) NULL,
    [ENCORDER]                 NVARCHAR (400) NULL,
    [ENCOVERALLORDER]          NVARCHAR (400) NULL,
    [FY]                       NVARCHAR (400) NULL,
    [FYDate]                   DATETIME2 (7)  NULL,
    [FYMonthName]              NVARCHAR (400) NULL,
    [FYMonthNumber]            NVARCHAR (400) NULL,
    [FYMonthShortName]         NVARCHAR (400) NULL,
    [FYYear]                   NVARCHAR (400) NULL,
    [FifteenthOrEOM]           NVARCHAR (400) NULL,
    [NoteAuthor]               NVARCHAR (400) NULL,
    [NoteCreatedTime]          DATETIME2 (7)  NULL,
    [ODScore]                  NVARCHAR (400) NULL,
    [PATENCENCID]              NVARCHAR (400) NULL,
    [PMDenom]                  NVARCHAR (400) NULL,
    [PositiveODScore]          NVARCHAR (400) NULL,
    [RefreshDate]              DATETIME2 (7)  NULL,
    [ScoreTime]                DATETIME2 (7)  NULL,
    [Shift1Color]              NVARCHAR (400) NULL,
    [Shift1Compliance]         NVARCHAR (400) NULL,
    [Shift1ComplianceYN]       NVARCHAR (400) NULL,
    [Shift1NonCompliance]      NVARCHAR (400) NULL,
    [Shift2Color]              NVARCHAR (400) NULL,
    [Shift2Compliance]         NVARCHAR (400) NULL,
    [Shift2ComplianceYN]       NVARCHAR (400) NULL,
    [Shift2NonCompliance]      NVARCHAR (400) NULL,
    [ShiftAMPM]                NVARCHAR (400) NULL,
    [ShiftCNs]                 NVARCHAR (400) NULL,
    [ShiftColor]               NVARCHAR (400) NULL,
    [ShiftColorDisplay]        NVARCHAR (400) NULL,
    [ShiftCompliance]          NVARCHAR (400) NULL,
    [ShiftComplianceFlag]      NVARCHAR (400) NULL,
    [ShiftDate]                DATETIME2 (7)  NULL,
    [ShiftEnd]                 NVARCHAR (400) NULL,
    [ShiftNonCompliance]       NVARCHAR (400) NULL,
    [ShiftRNs]                 NVARCHAR (400) NULL,
    [ShiftStart]               NVARCHAR (400) NULL,
    [UniqueRow]                NVARCHAR (400) NULL,
    [UnitOrder]                NVARCHAR (400) NULL
);


GO

