CREATE TABLE [reporting].[ip_sepsisdetails] (
    [ABXName]                      NVARCHAR (400) NULL,
    [ABXTime]                      DATETIME2 (7)  NULL,
    [ABXVolume]                    NVARCHAR (400) NULL,
    [BPPercentile]                 NVARCHAR (400) NULL,
    [BloodCultureOrderTime]        DATETIME2 (7)  NULL,
    [BloodCultureProcedureOrdered] NVARCHAR (400) NULL,
    [BloodCultureResult]           NVARCHAR (400) NULL,
    [Bolus]                        DATETIME2 (7)  NULL,
    [BolusTime]                    DATETIME2 (7)  NULL,
    [BolusVolume]                  NVARCHAR (400) NULL,
    [CALENDAR_DT]                  DATETIME2 (7)  NULL,
    [CSFOrderTime]                 DATETIME2 (7)  NULL,
    [CSFOrdered]                   NVARCHAR (400) NULL,
    [CSFValue]                     NVARCHAR (400) NULL,
    [CVVHYN]                       NVARCHAR (400) NULL,
    [DobutamineYN]                 NVARCHAR (400) NULL,
    [DopamineYN]                   NVARCHAR (400) NULL,
    [ECMOYN]                       NVARCHAR (400) NULL,
    [EDLosHours]                   NVARCHAR (400) NULL,
    [ENCORDER]                     NVARCHAR (400) NULL,
    [ENCOVERALLORDER]              NVARCHAR (400) NULL,
    [EncounterWeight]              NVARCHAR (400) NULL,
    [EpinephrineYN]                NVARCHAR (400) NULL,
    [FirstPositiveScoreInED]       NVARCHAR (400) NULL,
    [FirstPositiveScoreTimeInED]   DATETIME2 (7)  NULL,
    [HypotensionTime]              DATETIME2 (7)  NULL,
    [HypotensionValue]             NVARCHAR (400) NULL,
    [IPSOSevereSepsisYN]           NVARCHAR (400) NULL,
    [IntubationTime]               DATETIME2 (7)  NULL,
    [LacticAcidOrderTime]          DATETIME2 (7)  NULL,
    [LacticAcidResult]             NVARCHAR (400) NULL,
    [MilrinoneYN]                  NVARCHAR (400) NULL,
    [NorepinephrineYN]             NVARCHAR (400) NULL,
    [OXYN]                         NVARCHAR (400) NULL,
    [OrderSetID]                   NVARCHAR (400) NULL,
    [OrderSetTime]                 DATETIME2 (7)  NULL,
    [PATENCENCID]                  NVARCHAR (400) NULL,
    [PIVPlacementTime]             DATETIME2 (7)  NULL,
    [PositiveODScore]              NVARCHAR (400) NULL,
    [PressorYN]                    NVARCHAR (400) NULL,
    [ProcalcitoninOrderTime]       DATETIME2 (7)  NULL,
    [ProcalcitoninResult]          NVARCHAR (400) NULL,
    [RefreshDate]                  DATETIME2 (7)  NULL,
    [SepsisDate]                   DATETIME2 (7)  NULL,
    [UniqueRow]                    NVARCHAR (400) NULL,
    [UnitOrder]                    NVARCHAR (400) NULL
);


GO

