CREATE TABLE [reporting].[ip_sepsisencounterswlocations] (
    [ADTArrivalTime]      DATETIME2 (7)   NULL,
    [ADTDepartmentID]     NVARCHAR (400)  NULL,
    [ADTDepartmentName]   NVARCHAR (400)  NULL,
    [ADT_ARRIVAL_TIME]    DATETIME2 (7)   NULL,
    [ADT_DEPARTMENT_ID]   DECIMAL (18, 4) NULL,
    [ADT_DEPARTMENT_NAME] NVARCHAR (400)  NULL,
    [AGE_MONTHS]          NVARCHAR (400)  NULL,
    [AGE_YEARS]           NVARCHAR (400)  NULL,
    [AgeMonths]           NVARCHAR (400)  NULL,
    [AgeYears]            NVARCHAR (400)  NULL,
    [AllEncDx]            NVARCHAR (400)  NULL,
    [AllEncReasons]       NVARCHAR (400)  NULL,
    [BIRTH_DATE]          DATETIME2 (7)   NULL,
    [BirthDate]           DATETIME2 (7)   NULL,
    [DEPARTMENT_ROLLUP]   NVARCHAR (400)  NULL,
    [DepartmentRollup]    NVARCHAR (400)  NULL,
    [Disposition]         NVARCHAR (400)  NULL,
    [EDDepartureTime]     DATETIME2 (7)   NULL,
    [ED_DEPARTURE_TIME]   DATETIME2 (7)   NULL,
    [ENCORDER]            NVARCHAR (400)  NULL,
    [ENCOUNTER_ID]        DECIMAL (18, 4) NULL,
    [ENC_ID]              DECIMAL (18, 4) NULL,
    [Ethnic]              NVARCHAR (400)  NULL,
    [EthnicGroup]         NVARCHAR (400)  NULL,
    [HOSP_ADMSN_TIME]     DATETIME2 (7)   NULL,
    [HOSP_DISCH_TIME]     DATETIME2 (7)   NULL,
    [HospAdmsnTime]       DATETIME2 (7)   NULL,
    [HospDischTime]       DATETIME2 (7)   NULL,
    [INPATIENT_DATA_ID]   DECIMAL (18, 4) NULL,
    [INP_ADM_DATE]        DATETIME2 (7)   NULL,
    [In]                  NVARCHAR (400)  NULL,
    [InDepartmentTime]    DATETIME2 (7)   NULL,
    [In_DTTM]             DATETIME2 (7)   NULL,
    [InpAdmDate]          DATETIME2 (7)   NULL,
    [InpatientDataID]     NVARCHAR (400)  NULL,
    [LOCATION_ABBR]       NVARCHAR (400)  NULL,
    [LOC_ID]              DECIMAL (18, 4) NULL,
    [LOC_NAME]            NVARCHAR (400)  NULL,
    [LOS_HRS]             NVARCHAR (400)  NULL,
    [Location]            NVARCHAR (400)  NULL,
    [LosHours]            NVARCHAR (400)  NULL,
    [Out]                 NVARCHAR (400)  NULL,
    [OutDepartmentTime]   DATETIME2 (7)   NULL,
    [Out_DTTM]            DATETIME2 (7)   NULL,
    [PATENCENCID]         NVARCHAR (400)  NULL,
    [PATIENTMRN]          NVARCHAR (400)  NULL,
    [PATIENT_ID]          DECIMAL (18, 4) NULL,
    [PATIENT_MRN]         NVARCHAR (400)  NULL,
    [PATIENT_NAME]        NVARCHAR (400)  NULL,
    [POS_TYPE]            NVARCHAR (400)  NULL,
    [PatientID]           NVARCHAR (400)  NULL,
    [PatientName]         NVARCHAR (400)  NULL,
    [Race]                NVARCHAR (400)  NULL,
    [RefreshDate]         DATETIME2 (7)   NULL,
    [Sepsis]              DATETIME2 (7)   NULL,
    [Service]             NVARCHAR (400)  NULL,
    [Shift]               DATETIME2 (7)   NULL,
    [Unique]              NVARCHAR (400)  NULL,
    [UniqueRow]           NVARCHAR (400)  NULL,
    [Unit]                NVARCHAR (400)  NULL
);


GO

