CREATE TABLE [reporting].[ip_sepsisscreeningaudit] (
    [AddOrdersReceivedPlacedByMDPNP]      NVARCHAR (400) NULL,
    [AlertActivatedComment]               NVARCHAR (400) NULL,
    [AlertNotActivatedComment]            NVARCHAR (400) NULL,
    [AlertNotActivatedReason]             NVARCHAR (400) NULL,
    [BP]                                  DATETIME2 (7)  NULL,
    [BPBoysPercentile]                    NVARCHAR (400) NULL,
    [BPGirlsPercentile]                   NVARCHAR (400) NULL,
    [CapillaryRefill]                     NVARCHAR (400) NULL,
    [CirculatoryDysfunction]              NVARCHAR (400) NULL,
    [ExternalCreatinine]                  NVARCHAR (400) NULL,
    [ExternalLactateResult]               NVARCHAR (400) NULL,
    [ExternalPlatelets]                   NVARCHAR (400) NULL,
    [FifteenthOrEOM]                      NVARCHAR (400) NULL,
    [HematologicDysfunction]              NVARCHAR (400) NULL,
    [HuddleDate]                          DATETIME2 (7)  NULL,
    [HuddleTime]                          DATETIME2 (7)  NULL,
    [InfectiousSymptoms]                  NVARCHAR (400) NULL,
    [LBrachialPulse]                      NVARCHAR (400) NULL,
    [LPedalPulse]                         NVARCHAR (400) NULL,
    [LPosteriorTibialPulse]               NVARCHAR (400) NULL,
    [LRadialPulse]                        NVARCHAR (400) NULL,
    [NeurologicalDysfunction]             NVARCHAR (400) NULL,
    [NoteAuthor]                          NVARCHAR (400) NULL,
    [NoteCreatedTime]                     DATETIME2 (7)  NULL,
    [Notification]                        NVARCHAR (400) NULL,
    [ODScore]                             NVARCHAR (400) NULL,
    [ODScoreIs2]                          NVARCHAR (400) NULL,
    [PATENCENCID]                         NVARCHAR (400) NULL,
    [PatientAssessedByMDPNP]              NVARCHAR (400) NULL,
    [PerfusionWDL]                        NVARCHAR (400) NULL,
    [PhysicianName]                       NVARCHAR (400) NULL,
    [PosODScore]                          NVARCHAR (400) NULL,
    [Predisposition]                      NVARCHAR (400) NULL,
    [Pulse]                               NVARCHAR (400) NULL,
    [RBrachialPulse]                      NVARCHAR (400) NULL,
    [RPedalPulse]                         NVARCHAR (400) NULL,
    [RPosteriorTibialPulse]               NVARCHAR (400) NULL,
    [RRadialPulse]                        NVARCHAR (400) NULL,
    [RefreshDate]                         DATETIME2 (7)  NULL,
    [RenalDysfunction]                    NVARCHAR (400) NULL,
    [Resp]                                NVARCHAR (400) NULL,
    [RespiratoryDysfunction]              NVARCHAR (400) NULL,
    [ScoreDate]                           DATETIME2 (7)  NULL,
    [ScoreTime]                           DATETIME2 (7)  NULL,
    [SepsisPatientHuddleorAlertWithMDPNP] NVARCHAR (400) NULL,
    [ShiftColorDisplay]                   NVARCHAR (400) NULL,
    [SkinColor]                           NVARCHAR (400) NULL,
    [SkinConditionTemp]                   NVARCHAR (400) NULL,
    [UniqueRow]                           NVARCHAR (400) NULL
);


GO

