CREATE PROCEDURE reporting.USP_Care_Cascade
AS
BEGIN
WITH
Cascade_A AS (
  SELECT DC.PATIENT_ID, DC.DX_DATE
  FROM DIAGNOSIS_CODES DC
  WHERE DC.ICD_CODE LIKE 'E11%'
),
Cascade_B AS (
  SELECT CA.PATIENT_ID
  FROM Cascade_A CA
  WHERE CA.PATIENT_ID > 0
),
Cascade_C AS (
  SELECT CB.PATIENT_ID
  FROM Cascade_B CB
  WHERE CB.PATIENT_ID > 0
)
SELECT * FROM Cascade_C;
END
