CREATE PROCEDURE reporting.USP_Outreach_Funnel
AS
BEGIN
WITH
Reach_Base AS (
  SELECT PL.PATIENT_ID, PL.NOTED_DATE
  FROM PROBLEM_LIST PL
  WHERE PL.PROBLEM_CODE = 'DM2'
),
Arm_Dx AS (
  SELECT RB.PATIENT_ID
  FROM Reach_Base RB
  JOIN DIAGNOSIS_CODES DC ON DC.PATIENT_ID = RB.PATIENT_ID
  WHERE DC.ICD_CODE LIKE 'E11%'
),
Arm_Lab AS (
  SELECT RB.PATIENT_ID
  FROM Reach_Base RB
  JOIN LAB_RESULTS LR ON LR.PATIENT_ID = RB.PATIENT_ID
  WHERE LR.HBA1C_VALUE >= 6.5
),
Funnel_Join AS (
  SELECT AD.PATIENT_ID
  FROM Arm_Dx AD
  JOIN Arm_Lab AL ON AL.PATIENT_ID = AD.PATIENT_ID
)
SELECT * FROM Funnel_Join;
END
