CREATE PROCEDURE reporting.USP_DM_Patient_List
AS
BEGIN
WITH
Panel_All AS (
  SELECT PL.PATIENT_ID, PL.NOTED_DATE
  FROM PROBLEM_LIST PL
  WHERE PL.PROBLEM_CODE = 'DM2'
)
SELECT * FROM Panel_All;
END
