CREATE PROCEDURE reporting.USP_Diabetic_Patients_DX
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT DC.PATIENT_ID, DC.DX_DATE
  FROM DIAGNOSIS_CODES DC
  WHERE DC.ICD_CODE LIKE 'E11%'
),
Enc_Recent AS (
  SELECT MO.PATIENT_ID, MO.ORDER_DATE
  FROM MEDICATION_ORDERS MO
  WHERE MO.MED_NAME IN ('METFORMIN', 'INSULIN GLARGINE')
),
Lab_Draws AS (
  SELECT LR.PATIENT_ID, LR.RESULT_DATE
  FROM LAB_RESULTS LR
  WHERE LR.HBA1C_VALUE >= 6.5
),
A1c_High AS (
  SELECT LR.PATIENT_ID, LR.RESULT_DATE
  FROM LAB_RESULTS LR
  WHERE LR.HBA1C_VALUE >= 6.5
),
Med_Orders_Cur AS (
  SELECT MO.PATIENT_ID, MO.ORDER_DATE
  FROM MEDICATION_ORDERS MO
  WHERE MO.MED_NAME IN ('METFORMIN', 'INSULIN GLARGINE')
)
SELECT * FROM Base_Cohort;
END
