CREATE PROCEDURE reporting.USP_Panel_NoShows
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT DISTINCT E.PATIENT_ID
  FROM ENCOUNTERS E
  JOIN ENCOUNTER_DIAGNOSIS ED ON ED.ENCOUNTER_ID = E.ENCOUNTER_ID
  JOIN DIAGNOSIS_CODESET DC ON DC.DX_CODE = ED.DX_CODE
  WHERE ED.DX_CODE LIKE 'E11%'
),
Missed_Appts AS (
  SELECT BC.PATIENT_ID
  FROM Base_Cohort BC
  JOIN APPOINTMENTS A ON A.PATIENT_ID = BC.PATIENT_ID
  WHERE A.APPT_STATUS IN ('cancelled', 'no-show')
)
SELECT * FROM Missed_Appts;
END
