CREATE PROCEDURE reporting.USP_High_ED_Utilizers
AS
BEGIN
WITH
Utilizers AS (
  SELECT DISTINCT HE.PATIENT_ID
  FROM HOSPITAL_ENCOUNTERS HE
  WHERE HE.ENCOUNTER_TYPE = 'ED'
)
SELECT * FROM Utilizers;
END
