CREATE PROCEDURE reporting.USP_Diabetic_Billing
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT DISTINCT PB.PATIENT_ID
  FROM PROFESSIONAL_BILLING PB
  JOIN CPT_CODES CC ON CC.CPT_ROW_ID = PB.CPT_ROW_ID
  JOIN CPT_CODESET CS ON CS.CPT_CODE = CC.CPT_CODE
  WHERE CC.CPT_CODE IN ('82947', '83036')
)
SELECT * FROM Base_Cohort;
END
