CREATE PROCEDURE reporting.USP_Panel_Rollup
AS
BEGIN
WITH Rollup_R AS (
  SELECT P.PATIENT_ID, 0 AS DEPTH
  FROM PATIENTS P
  WHERE P.ACTIVE_FLAG = 1
  UNION ALL
  SELECT R.PATIENT_ID, R.DEPTH + 1
  FROM Rollup_R R
  WHERE R.DEPTH < 3
)
SELECT * FROM Rollup_R;
END
