CREATE PROCEDURE reporting.USP_DM_Registry_Composite
AS
BEGIN
WITH
Dx_Path AS (
  SELECT DC2.PATIENT_ID
  FROM DIAGNOSIS_CODES DC2
  WHERE DC2.ICD_CODE LIKE 'E11%'
),
Lab_Path AS (
  SELECT LR.PATIENT_ID
  FROM LAB_RESULTS LR
  WHERE LR.HBA1C_VALUE >= 6.5
),
Med_Path AS (
  SELECT MO.PATIENT_ID
  FROM MEDICATION_ORDERS MO
  WHERE MO.MED_NAME IN ('METFORMIN', 'INSULIN GLARGINE')
),
Composite AS (
  SELECT P.PATIENT_ID
  FROM PATIENTS P
  WHERE (CASE WHEN EXISTS (SELECT 1 FROM Dx_Path D WHERE D.PATIENT_ID = P.PATIENT_ID) THEN 1 ELSE 0 END
       + CASE WHEN EXISTS (SELECT 1 FROM Lab_Path L WHERE L.PATIENT_ID = P.PATIENT_ID) THEN 1 ELSE 0 END
       + CASE WHEN EXISTS (SELECT 1 FROM Med_Path M WHERE M.PATIENT_ID = P.PATIENT_ID) THEN 1 ELSE 0 END) >= 2
)
SELECT * FROM Composite;
END
