CREATE PROCEDURE reporting.USP_Panel_Refresh
AS
BEGIN
SELECT MO.PATIENT_ID, MO.MED_NAME
INTO #Dx_Events
FROM MEDICATION_ORDERS MO
WHERE MO.MED_NAME = 'METFORMIN';

WITH Refresh_Pop AS (
  SELECT DE.PATIENT_ID
  FROM #Dx_Events DE
  WHERE DE.PATIENT_ID > 0
)
SELECT * FROM Refresh_Pop;
END
