CREATE PROCEDURE reporting.USP_High_ED_NoPCP
AS
BEGIN
WITH
Base_Cohort AS (
  SELECT HE.PATIENT_ID, HE.HOSP_ENC_ID
  FROM HOSPITAL_ENCOUNTERS HE
  WHERE HE.ENCOUNTER_TYPE = 'ED'
),
High_Util AS (
  SELECT BC.PATIENT_ID
  FROM Base_Cohort BC
  GROUP BY BC.PATIENT_ID
  HAVING COUNT(BC.HOSP_ENC_ID) >= 4
),
No_PCP AS (
  SELECT HU.PATIENT_ID
  FROM High_Util HU
  WHERE NOT EXISTS (SELECT 1 FROM PATIENT_PCP_ASSIGNMENT PA
    WHERE PA.PATIENT_ID = HU.PATIENT_ID)
)
SELECT * FROM No_PCP;
END
